/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import Mathlib.Algebra.Algebra.TransferInstance
public import Mathlib.Analysis.InnerProductSpace.l2Space
public import Mathlib.Analysis.LocallyConvex.WithSeminorms
public import Mathlib.Data.Stream.Init
public import Mathlib.LinearAlgebra.Dual.Lemmas
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination
public import Mathlib.Topology.Algebra.InfiniteSum.NatInt

/-!
# The σ-weak operator topology

This file defines a type copy `E →σw[𝕜] F` of `E →L[𝕜] F`, for inner product spaces `E`, `F`,
endowed with the **σ-weak** (ultraweak) operator topology: the coarsest topology making
`A ↦ ∑ₙ ⟪ξₙ, A ηₙ⟫` continuous for all square-summable sequences `ξ ∈ ℓ²(ℕ, F)`, `η ∈ ℓ²(ℕ, E)`
(Takesaki, *Theory of Operator Algebras I*, §II.2; Bratteli–Robinson, *Operator Algebras and
Quantum Statistical Mechanics 1*, §2.4.1). It is finer than the weak operator topology (take `ξ`,
`η` supported at one index) and coarser than the norm topology.

The construction mirrors Mathlib's `ContinuousLinearMapWOT`: the topology is induced by the linear
map `A ↦ (fun (ξ, η) => ⟪ξ, A η⟫_{ℓ²})`, and is generated by the seminorms `‖∑ₙ ⟪ξₙ, A ηₙ⟫‖`.

The main result is the description of σ-weakly continuous functionals: on any subspace
`S ⊆ E →σw[𝕜] F`, a continuous linear functional has the form `A ↦ ∑ₙ ⟪ξₙ, A ηₙ⟫`
(`ContinuousLinearMapSigmaWeak.exists_lp_pair_of_continuous`). Two general-purpose ingredients
are proved on the way and would go to separate Mathlib files upstream:

* `LinearMap.exists_finset_sum_eq_of_continuous` — a linear functional continuous for a topology
  generated by the seminorms `‖Lᵢ ·‖` is a finite linear combination of the `Lᵢ`;
* `lp.interleave` — the interleaving (Mathlib's `Stream'.interleave`) of two square-summable
  sequences, with `HasSum.interleave` and `Stream'.zip_interleave`.

## Main definitions

* `ContinuousLinearMapSigmaWeak 𝕜 E F`, notation `E →σw[𝕜] F` — the type copy.
* `ContinuousLinearMapSigmaWeak.inducingFn` — the map inducing the topology.
* `ContinuousLinearMapSigmaWeak.seminormFamily` — the seminorms `‖∑ₙ ⟪ξₙ, A ηₙ⟫‖`.

## Main results

* `ContinuousLinearMapSigmaWeak.continuous_tsum_inner_apply` — `A ↦ ∑ₙ ⟪ξₙ, A ηₙ⟫` is continuous.
* `ContinuousLinearMapSigmaWeak.withSeminorms` — the topology is generated by `seminormFamily`.
* `ContinuousLinearMapSigmaWeak.exists_lp_pair_of_continuous` — σ-weakly continuous functionals on
  a subspace are of the form `A ↦ ∑ₙ ⟪ξₙ, A ηₙ⟫`.
-/

@[expose] public noncomputable section

open Topology
open scoped InnerProductSpace

/-! ### Interleaving sequences -/

/-- Interleaving commutes with zipping: zipping two interleaved streams interleaves the zips. -/
theorem Stream'.zip_interleave {α β δ : Type*} (f : α → β → δ) (s₁ s₂ : Stream' α)
    (t₁ t₂ : Stream' β) : Stream'.zip f (s₁ ⋈ s₂) (t₁ ⋈ t₂) = Stream'.zip f s₁ t₁ ⋈ Stream'.zip f s₂ t₂ := by
  ext n
  obtain ⟨k, rfl | rfl⟩ := Nat.even_or_odd' n
  · simp only [Stream'.get_zip, Stream'.get_interleave_left]
  · simp only [Stream'.get_zip, Stream'.get_interleave_right]

/-- The sum of an interleaved sequence is the sum of the two sums. -/
theorem HasSum.interleave {M : Type*} [AddCommMonoid M] [TopologicalSpace M] [ContinuousAdd M]
    {f g : ℕ → M} {a b : M} (hf : HasSum f a) (hg : HasSum g b) : HasSum (f ⋈ g) (a + b) := by
  have h₁ : (fun k => (f ⋈ g) (2 * k)) = f := funext fun k => Stream'.get_interleave_left k f g
  have h₂ : (fun k => (f ⋈ g) (2 * k + 1)) = g := funext fun k => Stream'.get_interleave_right k f g
  exact HasSum.even_add_odd (by rw [h₁]; exact hf) (by rw [h₂]; exact hg)

/-- Interleaving preserves `ℓᵖ`-membership. -/
theorem Memℓp.interleave {E : Type*} [NormedAddCommGroup E] {p : ENNReal} (hp : 0 < p.toReal)
    {f g : ℕ → E} (hf : Memℓp f p) (hg : Memℓp g p) : Memℓp (f ⋈ g) p := by
  have h₁ : (fun k => (f ⋈ g) (2 * k)) = f := funext fun k => Stream'.get_interleave_left k f g
  have h₂ : (fun k => (f ⋈ g) (2 * k + 1)) = g := funext fun k => Stream'.get_interleave_right k f g
  rw [← h₁] at hf
  rw [← h₂] at hg
  exact (memℓp_gen_iff hp).2 (((memℓp_gen_iff hp).1 hf).even_add_odd ((memℓp_gen_iff hp).1 hg))

namespace lp

variable {E : Type*} [NormedAddCommGroup E]

/-- The interleaving of two square-summable sequences. -/
def interleave (ξ η : lp (fun _ : ℕ => E) 2) : lp (fun _ : ℕ => E) 2 :=
  ⟨(ξ : ℕ → E) ⋈ (η : ℕ → E), ξ.2.interleave (by norm_num) η.2⟩

/-- The underlying sequence of `lp.interleave ξ η`. -/
@[simp] lemma coeFn_interleave (ξ η : lp (fun _ : ℕ => E) 2) :
    ⇑(interleave ξ η) = (ξ : ℕ → E) ⋈ (η : ℕ → E) :=
  rfl

end lp

/-! ### Functionals continuous for a family of seminorms -/

/-- A linear functional that is continuous for a topology generated by the seminorms `‖Lᵢ ·‖` is a
finite linear combination of the `Lᵢ`. -/
theorem LinearMap.exists_finset_sum_eq_of_continuous {𝕜 E ι : Type*} [NontriviallyNormedField 𝕜]
    [AddCommGroup E] [Module 𝕜 E] [TopologicalSpace E] {L : ι → E →ₗ[𝕜] 𝕜}
    (hL : WithSeminorms fun i => (normSeminorm 𝕜 𝕜).comp (L i)) {φ : E →ₗ[𝕜] 𝕜}
    (hφ : Continuous φ) : ∃ (s : Finset ι) (c : s → 𝕜), ∀ x, φ x = ∑ i, c i * L i x := by
  obtain ⟨s, C, -, hC⟩ := Seminorm.bound_of_continuous hL ((normSeminorm 𝕜 𝕜).comp φ)
    (continuous_norm.comp hφ)
  have hker : ⨅ i : s, LinearMap.ker (L i) ≤ LinearMap.ker φ := by
    intro x hx
    simp only [Submodule.mem_iInf, LinearMap.mem_ker] at hx
    rw [LinearMap.mem_ker, ← norm_le_zero_iff]
    have h₂ : (s.sup fun i => (normSeminorm 𝕜 𝕜).comp (L i)) x ≤ 0 :=
      Seminorm.finset_sup_apply_le le_rfl fun i hi => by simp [hx ⟨i, hi⟩]
    have h₁ : ‖φ x‖ ≤ (C : ℝ) * (s.sup fun i => (normSeminorm 𝕜 𝕜).comp (L i)) x := hC x
    exact h₁.trans (mul_nonpos_of_nonneg_of_nonpos C.2 h₂)
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun 𝕜).mp
    (mem_span_of_iInf_ker_le_ker (L := fun i : s => L i) hker)
  exact ⟨s, c, fun x => by rw [← hc]; simp⟩

/-! ### The type copy -/

/-- The type copy of `E →L[𝕜] F` endowed with the σ-weak operator topology, denoted
`E →σw[𝕜] F`. -/
structure ContinuousLinearMapSigmaWeak (𝕜 E F : Type*) [RCLike 𝕜] [NormedAddCommGroup E]
    [InnerProductSpace 𝕜 E] [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] where
  /-- Construct an element of `E →σw[𝕜] F` from a continuous linear map. -/
  ofCLM ::
  /-- The continuous linear map underlying an element of `E →σw[𝕜] F`. -/
  toCLM : E →L[𝕜] F

@[inherit_doc]
notation:25 E " →σw[" 𝕜 "] " F => ContinuousLinearMapSigmaWeak 𝕜 E F

/-- `(A ηₙ)ₙ` is square-summable along with `(ηₙ)ₙ`, for a bounded operator `A`. -/
lemma lp.memℓp_apply_clm {𝕜 ι E F : Type*} [RCLike 𝕜] [NormedAddCommGroup E] [NormedSpace 𝕜 E]
    [NormedAddCommGroup F] [NormedSpace 𝕜 F] (η : lp (fun _ : ι => E) 2) (A : E →L[𝕜] F) :
    Memℓp (fun i => A (η i)) 2 :=
  (((‖A‖ : 𝕜) • η : lp (fun _ : ι => E) 2).2).mono' fun i => by
    rw [lp.coeFn_smul, Pi.smul_apply, norm_smul, RCLike.norm_ofReal, abs_norm]
    exact A.le_opNorm _

namespace ContinuousLinearMapSigmaWeak

variable {𝕜 E F : Type*} [RCLike 𝕜] [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
  [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]

section Basic

/-- The equivalence between `E →σw[𝕜] F` and `E →L[𝕜] F`. -/
@[simps]
def equiv : (E →σw[𝕜] F) ≃ (E →L[𝕜] F) where
  toFun := toCLM
  invFun := ofCLM
  left_inv _ := rfl
  right_inv _ := rfl

/-- The additive group structure, transferred from `E →L[𝕜] F`. -/
instance instAddCommGroup : AddCommGroup (E →σw[𝕜] F) :=
  equiv.addCommGroup

/-- The additive equivalence between `E →σw[𝕜] F` and `E →L[𝕜] F`. -/
@[implicit_reducible, simps!]
def addEquiv : (E →σw[𝕜] F) ≃+ (E →L[𝕜] F) where
  __ := equiv
  map_add' _ _ := rfl

/-- The module structure, transferred from `E →L[𝕜] F`. -/
instance instModule : Module 𝕜 (E →σw[𝕜] F) :=
  addEquiv.module 𝕜

/-- The linear equivalence between `E →σw[𝕜] F` and `E →L[𝕜] F`. -/
@[simps!]
def linearEquiv : (E →σw[𝕜] F) ≃ₗ[𝕜] (E →L[𝕜] F) where
  __ := equiv
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- Elements of `E →σw[𝕜] F` act as functions `E → F`. -/
instance instFunLike : FunLike (E →σw[𝕜] F) E F where
  coe f := toCLM f
  coe_injective := DFunLike.coe_injective.comp equiv.injective

/-- The coercion to functions through `toCLM`. -/
@[simp] lemma coe_toCLM (A : E →σw[𝕜] F) : ⇑(toCLM A) = A := rfl
/-- The coercion to functions through `ofCLM`. -/
@[simp] lemma coe_ofCLM (A : E →L[𝕜] F) : ⇑(ofCLM A : E →σw[𝕜] F) = A := rfl
/-- `toCLM` inverts `ofCLM`. -/
@[simp] lemma toCLM_ofCLM (A : E →L[𝕜] F) : toCLM (ofCLM A : E →σw[𝕜] F) = A := rfl
/-- `ofCLM` inverts `toCLM`. -/
@[simp] lemma ofCLM_toCLM (A : E →σw[𝕜] F) : ofCLM (toCLM A) = A := rfl
/-- `toCLM` is additive. -/
@[simp] lemma toCLM_add (A B : E →σw[𝕜] F) : toCLM (A + B) = toCLM A + toCLM B := rfl
/-- `toCLM` commutes with scalar multiplication. -/
@[simp] lemma toCLM_smul (c : 𝕜) (A : E →σw[𝕜] F) : toCLM (c • A) = c • toCLM A := rfl

end Basic

/-! ### The topology -/

section Topology

/-- `(A ηₙ)ₙ ∈ ℓ²(ℕ, F)` for `η ∈ ℓ²(ℕ, E)`. -/
def applyLp (A : E →L[𝕜] F) (η : lp (fun _ : ℕ => E) 2) : lp (fun _ : ℕ => F) 2 :=
  ⟨fun n => A (η n), lp.memℓp_apply_clm η A⟩

/-- The underlying sequence of `applyLp A η`. -/
@[simp] lemma coeFn_applyLp (A : E →L[𝕜] F) (η : lp (fun _ : ℕ => E) 2) :
    ⇑(applyLp A η) = fun n => A (η n) :=
  rfl

variable (𝕜 E F) in
/-- The map inducing the σ-weak topology: `A ↦ fun (ξ, η) => ∑ₙ ⟪ξₙ, A ηₙ⟫`. -/
def inducingFn : (E →σw[𝕜] F) →ₗ[𝕜] (lp (fun _ : ℕ => F) 2 × lp (fun _ : ℕ => E) 2 → 𝕜) where
  toFun A p := ⟪p.1, applyLp (toCLM A) p.2⟫_𝕜
  map_add' A B := by
    ext p
    rw [Pi.add_apply, ← inner_add_right]
    congr 1
  map_smul' c A := by
    ext p
    rw [Pi.smul_apply, RingHom.id_apply, smul_eq_mul, ← inner_smul_right]
    congr 1

/-- `inducingFn A (ξ, η) = ∑ₙ ⟪ξₙ, A ηₙ⟫`. -/
lemma hasSum_inner_apply (ξ : lp (fun _ : ℕ => F) 2) (η : lp (fun _ : ℕ => E) 2)
    (A : E →σw[𝕜] F) : HasSum (fun n => ⟪ξ n, A (η n)⟫_𝕜) (inducingFn 𝕜 E F A (ξ, η)) :=
  lp.hasSum_inner ξ (applyLp (toCLM A) η)

/-- `inducingFn A (ξ, η) = ∑' n, ⟪ξₙ, A ηₙ⟫`. -/
lemma inducingFn_apply (ξ : lp (fun _ : ℕ => F) 2) (η : lp (fun _ : ℕ => E) 2)
    (A : E →σw[𝕜] F) : inducingFn 𝕜 E F A (ξ, η) = ∑' n, ⟪ξ n, A (η n)⟫_𝕜 :=
  (hasSum_inner_apply ξ η A).tsum_eq.symm

/-- The σ-weak operator topology: the coarsest topology such that `A ↦ ∑ₙ ⟪ξₙ, A ηₙ⟫` is
continuous for all `ξ ∈ ℓ²(ℕ, F)`, `η ∈ ℓ²(ℕ, E)`. -/
instance instTopologicalSpace : TopologicalSpace (E →σw[𝕜] F) :=
  .induced (inducingFn 𝕜 E F) Pi.topologicalSpace

/-- The inducing map is continuous. -/
lemma continuous_inducingFn : Continuous (inducingFn 𝕜 E F) :=
  continuous_induced_dom

/-- The σ-weak topology is induced by `inducingFn`. -/
lemma isInducing_inducingFn : IsInducing (inducingFn 𝕜 E F) := ⟨rfl⟩

/-- `A ↦ ∑ₙ ⟪ξₙ, A ηₙ⟫` is σ-weakly continuous. -/
lemma continuous_tsum_inner_apply (ξ : lp (fun _ : ℕ => F) 2) (η : lp (fun _ : ℕ => E) 2) :
    Continuous fun A : E →σw[𝕜] F => ∑' n, ⟪ξ n, A (η n)⟫_𝕜 := by
  simp_rw [← inducingFn_apply]
  exact continuous_pi_iff.mp continuous_inducingFn (ξ, η)

/-- A map into `E →σw[𝕜] F` is continuous if every `a ↦ ∑ₙ ⟪ξₙ, g a ηₙ⟫` is. -/
lemma continuous_of_tsum_inner_apply_continuous {α : Type*} [TopologicalSpace α]
    {g : α → E →σw[𝕜] F}
    (h : ∀ (ξ : lp (fun _ : ℕ => F) 2) (η : lp (fun _ : ℕ => E) 2),
      Continuous fun a => ∑' n, ⟪ξ n, g a (η n)⟫_𝕜) :
    Continuous g :=
  continuous_induced_rng.2 (continuous_pi_iff.mpr fun ⟨ξ, η⟩ => by
    simpa only [Function.comp_def, inducingFn_apply] using h ξ η)

/-- `E →σw[𝕜] F` is a topological additive group. -/
instance instIsTopologicalAddGroup : IsTopologicalAddGroup (E →σw[𝕜] F) where
  toContinuousAdd := .induced (inducingFn 𝕜 E F)
  toContinuousNeg := .induced (inducingFn 𝕜 E F)

/-- Scalar multiplication is σ-weakly continuous. -/
instance instContinuousSMul : ContinuousSMul 𝕜 (E →σw[𝕜] F) :=
  .induced (inducingFn 𝕜 E F)

end Topology

/-! ### The σ-weak topology is generated by seminorms -/

section Seminorms

/-- The coordinate functional `A ↦ ∑ₙ ⟪ξₙ, A ηₙ⟫`. -/
def coord (p : lp (fun _ : ℕ => F) 2 × lp (fun _ : ℕ => E) 2) : (E →σw[𝕜] F) →ₗ[𝕜] 𝕜 :=
  (LinearMap.proj p).comp (inducingFn 𝕜 E F)

/-- `coord (ξ, η) A = ⟪ξ, (A ηₙ)ₙ⟫_{ℓ²}`. -/
lemma coord_apply (p : lp (fun _ : ℕ => F) 2 × lp (fun _ : ℕ => E) 2) (A : E →σw[𝕜] F) :
    coord p A = ⟪p.1, applyLp (toCLM A) p.2⟫_𝕜 :=
  rfl

variable (𝕜 E F) in
/-- The seminorms `‖∑ₙ ⟪ξₙ, A ηₙ⟫‖` generating the σ-weak topology. -/
def seminormFamily :
    SeminormFamily 𝕜 (E →σw[𝕜] F) (lp (fun _ : ℕ => F) 2 × lp (fun _ : ℕ => E) 2) :=
  fun p => (normSeminorm 𝕜 𝕜).comp (coord p)

/-- The σ-weak topology is generated by `seminormFamily`. -/
lemma withSeminorms : WithSeminorms (seminormFamily 𝕜 E F) :=
  let e : lp (fun _ : ℕ => F) 2 × lp (fun _ : ℕ => E) 2 ≃
      (Σ _ : lp (fun _ : ℕ => F) 2 × lp (fun _ : ℕ => E) 2, Unit) := .symm <| .sigmaUnique _ _
  isInducing_inducingFn.withSeminorms <| withSeminorms_pi (fun _ ↦ norm_withSeminorms 𝕜 𝕜)
    |>.congr_equiv e

end Seminorms

/-! ### σ-weakly continuous functionals -/

section Functionals

/-- A finite combination `∑ᵢ cᵢ ⟪ξ⁽ⁱ⁾, A η⁽ⁱ⁾⟫_{ℓ²}` is a single `⟪ξ', A η'⟫_{ℓ²}`, by interleaving. -/
lemma exists_lp_pair_finset_sum {ι : Type*} (t : Finset ι) (c : ι → 𝕜)
    (p : ι → lp (fun _ : ℕ => F) 2 × lp (fun _ : ℕ => E) 2) :
    ∃ (ξ : lp (fun _ : ℕ => F) 2) (η : lp (fun _ : ℕ => E) 2), ∀ A : E →L[𝕜] F,
      HasSum (fun n => ⟪ξ n, A (η n)⟫_𝕜) (∑ i ∈ t, c i * ⟪(p i).1, applyLp A (p i).2⟫_𝕜) := by
  classical
  induction t using Finset.induction_on with
  | empty => exact ⟨0, 0, fun A => by simp⟩
  | insert a t ha ih =>
    obtain ⟨ξ, η, h⟩ := ih
    refine ⟨lp.interleave ((starRingEnd 𝕜 (c a)) • (p a).1) ξ, lp.interleave (p a).2 η,
      fun A => ?_⟩
    rw [Finset.sum_insert ha]
    have h₁ : HasSum (fun n => ⟪((starRingEnd 𝕜 (c a)) • (p a).1) n, A ((p a).2 n)⟫_𝕜)
        (c a * ⟪(p a).1, applyLp A (p a).2⟫_𝕜) := by
      simpa only [lp.coeFn_smul, Pi.smul_apply, inner_smul_left, starRingEnd_self_apply,
        coeFn_applyLp] using
        (lp.hasSum_inner (p a).1 (applyLp A (p a).2)).mul_left (c a)
    have hzip := Stream'.zip_interleave (fun x y => ⟪x, A y⟫_𝕜)
      (⇑((starRingEnd 𝕜 (c a)) • (p a).1) : ℕ → F) (ξ : ℕ → F) ((p a).2 : ℕ → E) (η : ℕ → E)
    exact (congrArg (HasSum · _) hzip).mpr (h₁.interleave (h A))

/-- **σ-weakly continuous functionals.** On a subspace `S ⊆ E →σw[𝕜] F`, every σ-weakly
continuous linear functional is `A ↦ ∑ₙ ⟪ξₙ, A ηₙ⟫` for some `ξ ∈ ℓ²(ℕ, F)`, `η ∈ ℓ²(ℕ, E)`. -/
theorem exists_lp_pair_of_continuous {S : Submodule 𝕜 (E →σw[𝕜] F)} {φ : S →ₗ[𝕜] 𝕜}
    (hφ : Continuous φ) :
    ∃ (ξ : lp (fun _ : ℕ => F) 2) (η : lp (fun _ : ℕ => E) 2), ∀ x : S,
      HasSum (fun n => ⟪ξ n, (x : E →σw[𝕜] F) (η n)⟫_𝕜) (φ x) := by
  have hS : WithSeminorms fun p => (normSeminorm 𝕜 𝕜).comp ((coord p).comp S.subtype) :=
    IsInducing.subtypeVal.withSeminorms (f := S.subtype) withSeminorms
  obtain ⟨s, c, hc⟩ := LinearMap.exists_finset_sum_eq_of_continuous hS hφ
  obtain ⟨ξ, η, h⟩ := exists_lp_pair_finset_sum Finset.univ c (fun i : s => i.1)
  refine ⟨ξ, η, fun x => ?_⟩
  rw [hc x]
  exact h (toCLM (x : E →σw[𝕜] F))

end Functionals

end ContinuousLinearMapSigmaWeak
