/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import Mathlib.Analysis.Calculus.Deriv.Star
public import Mathlib.Analysis.Complex.LocallyUniformLimit
public import QuantumSystem.Analysis.SpectralTheory.AnalyticContinuation
public import QuantumSystem.Analysis.SpectralTheory.Power
public import QuantumSystem.Analysis.SpectralTheory.UnboundedIntegral
public import QuantumSystem.Analysis.SpectralTheory.PolarDecomposition
public import QuantumSystem.ForMathlib.Analysis.Complex.Strip
public import QuantumSystem.ForMathlib.Analysis.Complex.WeakHolomorphic

/-!
# Interpolation between the imaginary powers of two positive operators

Let `A` on `H₁` and `B` on `H₂` be self-adjoint operators and let `V`, `V'` be bounded operators
with `B^{1/2} V ⊇ V' A^{1/2}`. The square roots and imaginary powers only see the positive parts:
`A^{1/2} = ∫ √λ dE_A(λ)` and `A^{it}` vanish on `E_A((-∞, 0]) H₁` (`IsSelfAdjoint.sqrt`), so the
statement concerns positive operators, and is stated for self-adjoint ones without loss. Then
`t ↦ B^{-it} V A^{it}` extends to a family `F z` of bounded operators on the strip
`0 ≤ im z ≤ 1/2`, holomorphic in the operator norm in the interior, `*`-strongly continuous up to
the boundary, with the three lines bound
`‖F z‖ ≤ ‖V‖^{1 - 2 im z} ‖V'‖^{2 im z}` and `F (t + i/2) = B^{-it} V' A^{it}`
(`IsSelfAdjoint.exists_stripContinuation`); here `A^{it} = ∫_{(0,∞)} λ^{it} dE_A(λ)` are the
imaginary powers (`IsSelfAdjoint.imaginaryPower`), partial isometries vanishing on
`E_A((-∞, 0]) H₁` (on `ker A` for a positive `A`), and the unitary group generated by `log A` when
`A` is positive and injective. This is the analytic core of Borchers'
Theorem A
(`QuantumSystem.Analysis.InnerProductSpace.StandardSubspace.Borchers`), where `A`, `B` are modular operators
and `V' = J₂ V J₁`.

## Proof

The imaginary powers are cut off to the spectral windows `[1/(n+1), n+1] ⊆ (0, ∞)`, whose spectral
projections increase strongly to `E((0, ∞))`; the kernels of `A` and `B` play no role, since every
cut-off operator vanishes on them: with `1_n` the indicator
of the window, the operators `F_n(z) = ∫ 1_n λ^{-iz} dE_B ∘ V ∘ ∫ 1_n λ^{iz} dE_A` are bounded and
entire in `z`, bounded by `‖V‖` on `im z = 0` and, by the intertwining, equal to
`∫ 1_n λ^{-it} dE_B ∘ V' ∘ ∫ 1_n λ^{it} dE_A` on `im z = 1/2`; the three lines theorem bounds them
by `‖V‖^{1 - 2 im z} ‖V'‖^{2 im z}` on the strip. The windows are compatible,
`F_n = E_B(window n) F_m E_A(window n)` for `n ≤ m`, so on the range of a window
`‖F_m x - F_n x‖² = ‖F_m x‖² - ‖F_n x‖²`, and the uniform bound makes `F_n` converge strongly. Its
matrix coefficients between window vectors are eventually those of a fixed `F_n`, hence entire, and
the general ones are uniform limits of these on the strip; norm holomorphy follows from weak
holomorphy and the bound (`Complex.differentiableOn_continuousLinearMap_of_inner`).

Strong continuity up to the boundary: for a window vector `x' = E_A(window N) x` and `N ≤ n ≤ m`,
`(F_m - F_n)(t) x' = ∫ 1_m λ^{-it} dE_B (1 - E_B(window n)) V A^{it} x'` on the real line, and
likewise with `V'` on `im z = 1/2`. The maximum principle for the entire function
`e^{-(z - c)²} (F_m - F_n)(z) x'` bounds it on the strip by its boundary values; there the Gaussian
factor is small far from `c`, and near `c` the window projections converge uniformly on the compact
set `{V A^{it} x' | |t - c| ≤ R}`. So `F_n(z) x'` converges locally uniformly on the closed strip,
`z ↦ F(z) x'` is norm continuous, and so is `z ↦ F(z) x` by density and the uniform bound. The
adjoint is `F(z)† = G(z̄ + i/2)` for the continuation `G` of `t ↦ A^{-it} V'† B^{it}`, which exists
because the intertwining passes to the adjoints, `A^{1/2} V'† ⊇ V† B^{1/2}`: the matrix
coefficients of both sides are bounded and holomorphic and agree on the real line
(`Complex.eqOn_zero_of_eqOn_zero_im_eq_lower`).

## Main results

* `IsSelfAdjoint.exists_stripContinuation` — the interpolation theorem.
* `IsSelfAdjoint.exists_stripContinuation_polarIsometry` — **Borchers' Theorem A for semilinear
  operators**: for closed `σ`-semilinear `T₁`, `T₂` with polar decompositions `Tᵢ = Jᵢ Δᵢ^{1/2}`
  and a bounded `V` with `V T₁ ⊆ T₂ V`, `t ↦ Δ₂^{-it} V Δ₁^{it}` continues to the strip with
  boundary value `Δ₂^{-it} J₂† V J₁ Δ₁^{it}` on `im z = 1/2`.
* `IsSelfAdjoint.exists_stripContinuation_of_le` — **Theorem A with contractions**: the same for
  arbitrary self-adjoint `A`, `B` and `σ`-semilinear contractions `U₁`, `U₂` with
  `T₁ ⊇ U₁ A^{1/2}`, `B^{1/2} ⊇ U₂ T₂`: boundary value `B^{-it} U₂ V U₁ A^{it}`.

## References

* H.-J. Borchers, *On the use of modular groups in quantum field theory*, Ann. Inst. H. Poincaré
  Phys. Théor. 63 (1995), 331–382, Theorem A
* H. Araki, T. Masuda, *Positive cones and Lp-spaces for von Neumann algebras*,
  Publ. RIMS 18 (1982) — the relative modular operators with supports.

## TODO

* Interpolation for a general exponent: `B^α V ⊇ V' A^α` continues `t ↦ B^{-it} V A^{it}` to
  `0 ≤ im z ≤ α` (Heinz–Kato type inequalities).
-/

@[expose] public section

open Set Filter Topology MeasureTheory Complex Metric
open scoped InnerProductSpace ComplexConjugate LinearPMap InnerProduct

namespace MeasureTheory.ProjectionValuedMeasure

/-! ### Spectral windows -/

/-- The spectral window `[1/(n+1), n+1] ⊆ (0, ∞)`. -/
private def window (n : ℕ) : Set ℝ := Icc ((n + 1 : ℝ)⁻¹) (n + 1)

/-- The windows are measurable. -/
private lemma measurableSet_window (n : ℕ) : MeasurableSet (window n) := measurableSet_Icc

/-- The windows lie in `(0, ∞)`. -/
private lemma pos_of_mem_window {n : ℕ} {t : ℝ} (ht : t ∈ window n) : 0 < t :=
  lt_of_lt_of_le (inv_pos.mpr (by positivity)) ht.1

/-- The windows increase. -/
private lemma window_mono {n m : ℕ} (h : n ≤ m) : window n ⊆ window m := by
  have h' : (n + 1 : ℝ) ≤ m + 1 := by exact_mod_cast Nat.succ_le_succ h
  exact Icc_subset_Icc (inv_anti₀ (by positivity) h') h'

/-- On the window `n`, `|log λ| ≤ log (n + 1)`. -/
private lemma abs_log_le_of_mem_window {n : ℕ} {t : ℝ} (ht : t ∈ window n) :
    |Real.log t| ≤ Real.log (n + 1) := by
  rw [abs_le]
  constructor
  · have := Real.log_le_log (inv_pos.mpr (by positivity)) ht.1
    rw [Real.log_inv] at this
    linarith
  · exact Real.log_le_log (pos_of_mem_window ht) ht.2

/-- Every `λ > 0` lies in all windows from some index on. -/
private lemma eventually_mem_window {t : ℝ} (ht : 0 < t) : ∀ᶠ n : ℕ in atTop, t ∈ window n := by
  obtain ⟨N, hN⟩ := exists_nat_gt (max t t⁻¹)
  filter_upwards [eventually_ge_atTop N] with n hn
  have hn' : (N : ℝ) ≤ n := by exact_mod_cast hn
  constructor
  · rw [inv_le_comm₀ (by positivity) ht]
    linarith [le_max_right t t⁻¹]
  · linarith [le_max_left t t⁻¹]

/-- The cut-off power `λ ↦ 1_{[1/(n+1), n+1]}(λ) λ^w`, with `λ^w = e^{w log λ}`. -/
private noncomputable def cutPow (n : ℕ) (w : ℂ) : ℝ → ℂ :=
  (window n).indicator fun t => cexp (w * Real.log t)

/-- The cut-off powers are measurable. -/
private lemma measurable_cutPow (n : ℕ) (w : ℂ) : Measurable (cutPow n w) :=
  (by fun_prop : Measurable fun t : ℝ => cexp (w * Real.log t)).indicator (measurableSet_window n)

/-- `|1_n(λ) λ^w| ≤ (n + 1)^{|re w|}`. -/
private lemma norm_cutPow_le (n : ℕ) (w : ℂ) (t : ℝ) :
    ‖cutPow n w t‖ ≤ Real.exp (|w.re| * Real.log (n + 1)) := by
  by_cases ht : t ∈ window n
  · rw [cutPow, indicator_of_mem ht, norm_exp, re_mul_ofReal]
    refine Real.exp_le_exp.mpr ((le_abs_self _).trans ?_)
    rw [abs_mul]
    exact mul_le_mul_of_nonneg_left (abs_log_le_of_mem_window ht) (abs_nonneg _)
  · rw [cutPow, indicator_of_notMem ht, norm_zero]
    positivity

/-- The cut-off powers are bounded by `1` for imaginary `w`. -/
private lemma norm_cutPow_le_of_re_eq_zero (n : ℕ) {w : ℂ} (hw : w.re = 0) (t : ℝ) : ‖cutPow n w t‖ ≤ 1 :=
  (norm_cutPow_le n w t).trans (by simp [hw])

/-- The cut-off powers are bounded by `n + 1` for `|re w| ≤ 1`. -/
private lemma norm_cutPow_le_of_abs_re_le_one (n : ℕ) {w : ℂ} (hw : |w.re| ≤ 1) (t : ℝ) :
    ‖cutPow n w t‖ ≤ n + 1 := by
  refine (norm_cutPow_le n w t).trans ?_
  calc Real.exp (|w.re| * Real.log (n + 1)) ≤ Real.exp (1 * Real.log (n + 1)) :=
        Real.exp_le_exp.mpr (mul_le_mul_of_nonneg_right hw (Real.log_nonneg (by linarith)))
    _ = n + 1 := by rw [one_mul, Real.exp_log (by positivity)]

/-- Cutting off a cut-off power to a smaller window. -/
private lemma indicator_one_mul_cutPow {n m : ℕ} (h : n ≤ m) (w : ℂ) :
    (window n).indicator 1 * cutPow m w = cutPow n w := by
  funext t
  by_cases ht : t ∈ window n
  · simp [cutPow, ht, window_mono h ht]
  · simp [cutPow, ht]

/-- Cutting off a cut-off power to a smaller window, on the right. -/
private lemma cutPow_mul_indicator_one {n m : ℕ} (h : n ≤ m) (w : ℂ) :
    cutPow m w * (window n).indicator 1 = cutPow n w := by
  rw [mul_comm, indicator_one_mul_cutPow h]

/-- The cut-off powers converge to `1_{(0, ∞)} λ^w`. -/
private lemma tendsto_cutPow (w : ℂ) (t : ℝ) :
    Tendsto (fun n => cutPow n w t) atTop (𝓝 ((Ioi 0).indicator (fun t => cexp (w * Real.log t)) t)) := by
  by_cases ht : 0 < t
  · rw [indicator_of_mem (show t ∈ Ioi 0 from ht)]
    refine tendsto_const_nhds.congr' ?_
    filter_upwards [eventually_mem_window ht] with n hn
    rw [cutPow, indicator_of_mem hn]
  · rw [indicator_of_notMem (show t ∉ Ioi 0 from ht)]
    exact tendsto_const_nhds.congr' (Eventually.of_forall fun n =>
      (indicator_of_notMem (fun h => ht (pos_of_mem_window h)) _).symm)

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  (E : ProjectionValuedMeasure ℝ H)

/-- `z ↦ ∫ 1_{[1/(n+1), n+1]}(λ) λ^{cz} dE(λ)` is entire in the operator norm. -/
private lemma differentiable_integral_cutPow (n : ℕ) (c : ℂ) :
    Differentiable ℂ fun z => E.integral (cutPow n (c * z)) := by
  intro z₀
  set R := ‖z₀‖ + 1 with hRdef
  have hz₀ : z₀ ∈ ball (0 : ℂ) R := mem_ball_zero_iff.mpr (by rw [hRdef]; linarith)
  set M := Real.exp (‖c‖ * R * Real.log (n + 1))
  have hU : IsOpen (ball (0 : ℂ) R) := isOpen_ball
  have hb : ∀ z ∈ ball (0 : ℂ) R, ∀ t, ‖cutPow n (c * z) t‖ ≤ M := fun z hz t => by
    refine (norm_cutPow_le n _ t).trans (Real.exp_le_exp.mpr
      (mul_le_mul_of_nonneg_right ?_ (Real.log_nonneg (by linarith))))
    rw [mem_ball_zero_iff] at hz
    calc |(c * z).re| ≤ ‖c * z‖ := abs_re_le_norm _
      _ = ‖c‖ * ‖z‖ := norm_mul _ _
      _ ≤ ‖c‖ * R := mul_le_mul_of_nonneg_left hz.le (norm_nonneg _)
  have hd : DifferentiableOn ℂ (fun z => E.integral (cutPow n (c * z))) (ball 0 R) := by
    refine Complex.differentiableOn_continuousLinearMap_of_inner hU fun ξ η => ?_
    · have hv : DifferentiableOn ℂ (fun z => E.integralApply (cutPow n (c * z)) ξ) (ball 0 R) :=
        E.differentiableOn_integralApply hU (fun z _ => measurable_cutPow n _)
          (F' := fun z => (window n).indicator fun t => cexp (c * z * Real.log t) * (c * Real.log t))
          (fun z _ => (by fun_prop : Measurable fun t : ℝ =>
            cexp (c * z * Real.log t) * (c * Real.log t)).indicator (measurableSet_window n))
          (fun t z _ => ?_) (memLp_const M) (Eventually.of_forall fun t z hz => hb z hz t)
      · refine ((innerSL ℂ η).differentiable.comp_differentiableOn hv).congr fun z hz => ?_
        simp [E.integral_apply (measurable_cutPow n _) ⟨M, hb z hz⟩]
      · by_cases ht : t ∈ window n
        · simp only [cutPow, indicator_of_mem ht]
          simpa [mul_assoc] using
            (((hasDerivAt_id z).const_mul c).mul_const (Real.log t : ℂ)).cexp
        · simp only [cutPow, indicator_of_notMem ht]
          exact hasDerivAt_const _ _
  exact (hd z₀ hz₀).differentiableAt (hU.mem_nhds hz₀)

/-- The cut-off imaginary powers, partial isometries with initial and final space `E(window n)`,
converge strongly: `∫ 1_n λ^w dE → ∫ 1_{(0,∞)} λ^w dE` for `re w = 0`. -/
private lemma tendsto_integral_cutPow {w : ℂ} (hw : w.re = 0) (y : H) :
    Tendsto (fun n => E.integral (cutPow n w) y) atTop
      (𝓝 (E.integral ((Ioi 0).indicator fun t => cexp (w * Real.log t)) y)) := by
  have hm : Measurable fun t : ℝ => cexp (w * Real.log t) := by fun_prop
  have hbi : ∀ t : ℝ, ‖(Ioi 0).indicator (fun t => cexp (w * Real.log t)) t‖ ≤ 1 := fun t => by
    by_cases ht : t ∈ Ioi (0 : ℝ)
    · rw [indicator_of_mem ht, norm_exp, re_mul_ofReal, hw, zero_mul, Real.exp_zero]
    · rw [indicator_of_notMem ht, norm_zero]
      exact zero_le_one
  exact E.tendsto_integral_apply (fun n => measurable_cutPow n w)
    (hm.indicator measurableSet_Ioi) (fun n t => norm_cutPow_le_of_re_eq_zero n hw t) hbi
    (tendsto_cutPow w) y

/-- The spectral projections of the windows converge strongly to `E((0, ∞))`. -/
private lemma tendsto_apply_window (y : H) :
    Tendsto (fun n => E (window n) y) atTop (𝓝 (E (Ioi 0) y)) := by
  have h := E.tendsto_integral_cutPow (w := 0) rfl y
  simp only [zero_mul, Complex.exp_zero] at h
  rw [show ((Ioi (0 : ℝ)).indicator fun _ : ℝ => (1 : ℂ)) = (Ioi 0).indicator 1 from rfl,
    E.integral_indicator_one measurableSet_Ioi] at h
  refine h.congr fun n => ?_
  rw [← E.integral_indicator_one (measurableSet_window n)]
  congr 2
  funext t
  by_cases ht : t ∈ window n <;> simp [cutPow, ht]

/-- The windows lie in `(0, ∞)`: `E(window n) E((0, ∞)) = E(window n)`. -/
private lemma apply_window_apply_Ioi (n : ℕ) (y : H) : E (window n) (E (Ioi 0) y) = E (window n) y := by
  rw [← mul_apply_eq_comp, ← E.apply_inter (measurableSet_window n) measurableSet_Ioi,
    inter_eq_left.mpr (show window n ⊆ Ioi 0 from fun _ ht => pos_of_mem_window ht)]

/-- The windows lie in `(0, ∞)`: `E((0, ∞)) E(window n) = E(window n)`. -/
private lemma apply_Ioi_apply_window (n : ℕ) (y : H) : E (Ioi 0) (E (window n) y) = E (window n) y :=
  E.apply_apply_of_subset (measurableSet_window n) measurableSet_Ioi (fun _ ht => pos_of_mem_window ht) y

/-- `E((0, ∞)) - E(window n) = E((0, ∞) \ window n)`. -/
private lemma apply_Ioi_sub_apply_window (n : ℕ) (y : H) :
    E (Ioi 0) y - E (window n) y = E (Ioi 0 \ window n) y := by
  have h := E.apply_union (disjoint_sdiff_right (s := window n) (t := Ioi (0 : ℝ)))
    (measurableSet_window n) (measurableSet_Ioi.diff (measurableSet_window n))
  rw [union_sdiff_cancel (show window n ⊆ Ioi 0 from fun _ ht => pos_of_mem_window ht)] at h
  rw [h, add_apply, add_sub_cancel_left]

/-- The cut-off powers vanish off `(0, ∞)`: `∫ 1_n λ^w dE ∘ E((0, ∞)) = ∫ 1_n λ^w dE`. -/
private lemma integral_cutPow_apply_Ioi (n : ℕ) (w : ℂ) (y : H) :
    E.integral (cutPow n w) (E (Ioi 0) y) = E.integral (cutPow n w) y := by
  have hmul : cutPow n w * (Ioi 0).indicator 1 = cutPow n w := by
    funext t
    by_cases ht : t ∈ window n
    · simp [cutPow, ht, pos_of_mem_window ht]
    · simp [cutPow, ht]
  rw [← E.integral_indicator_one measurableSet_Ioi, ← ContinuousLinearMap.comp_apply, ← ContinuousLinearMap.mul_def,
    ← E.integral_mul (measurable_cutPow n w) ⟨_, norm_cutPow_le n w⟩
      (measurable_one.indicator measurableSet_Ioi)
      ⟨1, fun t => by by_cases ht : t ∈ Ioi (0 : ℝ) <;> simp [ht]⟩, hmul]

/-- The cut-off powers take values in `E((0, ∞)) H`. -/
private lemma apply_Ioi_integral_cutPow (n : ℕ) (w : ℂ) (y : H) :
    E (Ioi 0) (E.integral (cutPow n w) y) = E.integral (cutPow n w) y := by
  have hmul : (Ioi 0).indicator 1 * cutPow n w = cutPow n w := by
    funext t
    by_cases ht : t ∈ window n
    · simp [cutPow, ht, pos_of_mem_window ht]
    · simp [cutPow, ht]
  rw [← E.integral_indicator_one measurableSet_Ioi, ← ContinuousLinearMap.comp_apply, ← ContinuousLinearMap.mul_def,
    ← E.integral_mul (measurable_one.indicator measurableSet_Ioi)
      ⟨1, fun t => by by_cases ht : t ∈ Ioi (0 : ℝ) <;> simp [ht]⟩ (measurable_cutPow n w)
      ⟨_, norm_cutPow_le n w⟩, hmul]

/-- `∫ 1_m λ^w dE ∘ E(window n) = ∫ 1_n λ^w dE` for `n ≤ m`. -/
private lemma integral_cutPow_comp_apply {n m : ℕ} (h : n ≤ m) (w : ℂ) :
    E.integral (cutPow m w) ∘L E (window n) = E.integral (cutPow n w) := by
  rw [← E.integral_indicator_one (measurableSet_window n), ← ContinuousLinearMap.mul_def,
    ← E.integral_mul (measurable_cutPow m w) ⟨_, norm_cutPow_le m w⟩
      (measurable_one.indicator (measurableSet_window n))
      ⟨1, fun t => by by_cases ht : t ∈ window n <;> simp [ht]⟩, cutPow_mul_indicator_one h]

/-- `E(window n) ∘ ∫ 1_m λ^w dE = ∫ 1_n λ^w dE` for `n ≤ m`. -/
private lemma apply_comp_integral_cutPow {n m : ℕ} (h : n ≤ m) (w : ℂ) :
    E (window n) ∘L E.integral (cutPow m w) = E.integral (cutPow n w) := by
  rw [← E.integral_indicator_one (measurableSet_window n), ← ContinuousLinearMap.mul_def,
    ← E.integral_mul (measurable_one.indicator (measurableSet_window n))
      ⟨1, fun t => by by_cases ht : t ∈ window n <;> simp [ht]⟩ (measurable_cutPow m w)
      ⟨_, norm_cutPow_le m w⟩, indicator_one_mul_cutPow h]

/-! ### The interpolation theorem -/

section Interpolation

variable {H₁ H₂ : Type*} [NormedAddCommGroup H₁] [InnerProductSpace ℂ H₁] [CompleteSpace H₁]
  [NormedAddCommGroup H₂] [InnerProductSpace ℂ H₂] [CompleteSpace H₂]
  (E₁ : ProjectionValuedMeasure ℝ H₁) (E₂ : ProjectionValuedMeasure ℝ H₂)

/-- The family `B^{-iz} V A^{iz}` with `A`, `B` cut off to the spectral window `n`; it is entire
in `z`. -/
private noncomputable def windowConj (V : H₁ →L[ℂ] H₂) (n : ℕ) (z : ℂ) : H₁ →L[ℂ] H₂ :=
  E₂.integral (cutPow n (-I * z)) ∘L V ∘L E₁.integral (cutPow n (I * z))

private lemma differentiable_windowConj (V : H₁ →L[ℂ] H₂) (n : ℕ) :
    Differentiable ℂ (windowConj E₁ E₂ V n) :=
  (E₂.differentiable_integral_cutPow n (-I)).clm_comp
    ((differentiable_const V).clm_comp (E₁.differentiable_integral_cutPow n I))

/-- `‖∫ 1_n λ^w dE‖ ≤ n + 1` for `|re w| ≤ 1`, so for `w = ± i z` with `|im z| ≤ 1`. -/
private lemma norm_integral_cutPow_le (E : ProjectionValuedMeasure ℝ H₁) (n : ℕ) {w : ℂ}
    (hw : |w.re| ≤ 1) : ‖E.integral (cutPow n w)‖ ≤ n + 1 :=
  E.norm_integral_le (measurable_cutPow n w) ⟨_, norm_cutPow_le n w⟩
    (norm_cutPow_le_of_abs_re_le_one n hw) (by positivity)

private lemma norm_integral_cutPow_le_one (E : ProjectionValuedMeasure ℝ H₁) (n : ℕ) {w : ℂ}
    (hw : w.re = 0) : ‖E.integral (cutPow n w)‖ ≤ 1 :=
  E.norm_integral_le (measurable_cutPow n w) ⟨_, norm_cutPow_le n w⟩
    (norm_cutPow_le_of_re_eq_zero n hw) zero_le_one

private lemma norm_windowConj_le (V : H₁ →L[ℂ] H₂) (n : ℕ) {z : ℂ}
    (hz : z ∈ im ⁻¹' Icc 0 (1 / 2)) : ‖windowConj E₁ E₂ V n z‖ ≤ (n + 1) * (‖V‖ * (n + 1)) := by
  have h₁ : |(-I * z).re| ≤ 1 := by
    simp only [neg_mul, neg_re, mul_re, I_re, I_im, zero_mul, one_mul, zero_sub, neg_neg]
    rw [abs_le]
    constructor <;> linarith [hz.1, hz.2]
  have h₂ : |(I * z).re| ≤ 1 := by
    simp only [mul_re, I_re, I_im, zero_mul, one_mul, zero_sub]
    rw [abs_le]
    constructor <;> linarith [hz.1, hz.2]
  refine (ContinuousLinearMap.opNorm_comp_le _ _).trans ?_
  refine mul_le_mul (norm_integral_cutPow_le E₂ n h₁) ((ContinuousLinearMap.opNorm_comp_le _ _).trans
    (mul_le_mul_of_nonneg_left (norm_integral_cutPow_le E₁ n h₂) (norm_nonneg _)))
    (by positivity) (by positivity)

private lemma norm_windowConj_ofReal_le (V : H₁ →L[ℂ] H₂) (n : ℕ) (t : ℝ) :
    ‖windowConj E₁ E₂ V n t‖ ≤ ‖V‖ := by
  refine (ContinuousLinearMap.opNorm_comp_le _ _).trans ?_
  calc _ ≤ 1 * (‖V‖ * 1) := mul_le_mul (norm_integral_cutPow_le_one E₂ n (by simp))
          ((ContinuousLinearMap.opNorm_comp_le _ _).trans (mul_le_mul_of_nonneg_left
            (norm_integral_cutPow_le_one E₁ n (by simp)) (norm_nonneg _)))
          (by positivity) zero_le_one
    _ = ‖V‖ := by ring

/-- The cut-off families only see `E₁((0, ∞)) x`. -/
private lemma windowConj_apply_Ioi (V : H₁ →L[ℂ] H₂) (n : ℕ) (z : ℂ) (x : H₁) :
    windowConj E₁ E₂ V n z (E₁ (Ioi 0) x) = windowConj E₁ E₂ V n z x := by
  simp only [windowConj, ContinuousLinearMap.comp_apply, E₁.integral_cutPow_apply_Ioi]

/-- The cut-off families take values in `E₂((0, ∞)) H₂`. -/
private lemma apply_Ioi_windowConj (V : H₁ →L[ℂ] H₂) (n : ℕ) (z : ℂ) (x : H₁) :
    E₂ (Ioi 0) (windowConj E₁ E₂ V n z x) = windowConj E₁ E₂ V n z x := by
  simp only [windowConj, ContinuousLinearMap.comp_apply, E₂.apply_Ioi_integral_cutPow]

/-- `B^{-iz} V A^{iz}` restricted to a window is the restriction of the one on a larger window. -/
private lemma windowConj_eq_comp (V : H₁ →L[ℂ] H₂) {n m : ℕ} (h : n ≤ m) (z : ℂ) :
    windowConj E₁ E₂ V n z = E₂ (window n) ∘L windowConj E₁ E₂ V m z ∘L E₁ (window n) := by
  simp only [windowConj, ← ContinuousLinearMap.comp_assoc, E₂.apply_comp_integral_cutPow h]
  simp only [ContinuousLinearMap.comp_assoc, E₁.integral_cutPow_comp_apply h]

/-- `√λ = λ^{1/2}` on `(0, ∞)`. -/
private lemma ofReal_sqrt_eq {t : ℝ} (ht : 0 < t) :
    ((Real.sqrt t : ℝ) : ℂ) = cexp (1 / 2 * Real.log t) := by
  rw [Real.sqrt_eq_rpow, Real.rpow_def_of_pos ht, ofReal_exp]
  push_cast
  ring_nf

/-- **The upper boundary line**: the intertwining `B^{1/2} V ⊇ V' A^{1/2}` turns
`B^{-i(t + i/2)} V A^{i(t + i/2)}` into `B^{-it} V' A^{it}` (on each window). -/
private lemma windowConj_add_half {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ E₁.sqrt.graph → (V x, V' u) ∈ E₂.sqrt.graph) (n : ℕ) (t : ℝ) :
    windowConj E₁ E₂ V n (t + I / 2) = windowConj E₁ E₂ V' n t := by
  have hsq : Measurable fun t : ℝ => (Real.sqrt t : ℂ) :=
    Complex.measurable_ofReal.comp Real.continuous_sqrt.measurable
  have hI : I * I = -1 := I_mul_I
  -- the two function identities on the window
  have hf₁ : (fun s : ℝ => (Real.sqrt s : ℂ)) * cutPow n (I * (t + I / 2)) = cutPow n (I * t) := by
    funext s
    by_cases hs : s ∈ window n
    · simp only [Pi.mul_apply, cutPow, indicator_of_mem hs, ofReal_sqrt_eq (pos_of_mem_window hs),
        ← Complex.exp_add]
      congr 1
      linear_combination ((Real.log s : ℂ) / 2) * hI
    · simp [cutPow, hs]
  have hf₂ : cutPow n (-I * (t + I / 2)) =
      cutPow n (-I * t) * fun s : ℝ => (Real.sqrt s : ℂ) := by
    funext s
    by_cases hs : s ∈ window n
    · simp only [Pi.mul_apply, cutPow, indicator_of_mem hs, ofReal_sqrt_eq (pos_of_mem_window hs),
        ← Complex.exp_add]
      congr 1
      linear_combination (-(Real.log s : ℂ) / 2) * hI
    · simp [cutPow, hs]
  ext x
  simp only [windowConj, ContinuousLinearMap.comp_apply]
  set a := E₁.integral (cutPow n (I * (t + I / 2))) x
  have hb₁ : ∃ C, ∀ s, ‖cutPow n (I * (t + I / 2)) s‖ ≤ C := ⟨_, norm_cutPow_le n _⟩
  have hb₂ : ∃ C, ∀ s, ‖cutPow n (-I * t) s‖ ≤ C := ⟨_, norm_cutPow_le n _⟩
  -- `(a, A^{it} x) ∈ graph A^{1/2}` on the window
  have hgraph : (a, E₁.integral (cutPow n (I * t)) x) ∈ E₁.sqrt.graph := by
    have hmem : MemLp ((fun s : ℝ => (Real.sqrt s : ℂ)) * cutPow n (I * (t + I / 2))) 2
        (E₁.measure x) := by
      rw [hf₁]
      exact E₁.memLp_measure_of_bound (measurable_cutPow n _) (norm_cutPow_le n _) x
    refine E₁.mem_graph_integralPMap.mpr ⟨(E₁.memLp_measure_integral_apply_iff hsq
      (measurable_cutPow n _) hb₁ x).mpr hmem, ?_⟩
    rw [E₁.integralApply_integral_apply hsq (measurable_cutPow n _) hb₁ hmem, hf₁,
      E₁.integral_apply (measurable_cutPow n _) ⟨_, norm_cutPow_le n _⟩]
  obtain ⟨hmem₂, hval₂⟩ := E₂.mem_graph_integralPMap.mp (hVV' _ _ hgraph)
  rw [hf₂, E₂.integral_apply ((measurable_cutPow n _).mul hsq) ⟨_, fun s => by
      rw [← hf₂]
      exact norm_cutPow_le n _ s⟩,
    ← E₂.integral_integralApply hsq (measurable_cutPow n _) hb₂ hmem₂, hval₂]

/-- **Maximum principle**: on the closed strip, `‖B^{-iz} V A^{iz}‖ ≤ max ‖V‖ ‖V'‖` on each
window. -/
private lemma norm_windowConj_le_max {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ E₁.sqrt.graph → (V x, V' u) ∈ E₂.sqrt.graph) (n : ℕ) {z : ℂ}
    (hz : z ∈ im ⁻¹' Icc 0 (1 / 2)) : ‖windowConj E₁ E₂ V n z‖ ≤ max ‖V‖ ‖V'‖ := by
  refine Complex.norm_le_of_im_mem_Icc
    (differentiable_windowConj E₁ E₂ V n).diffContOnCl
    ⟨(n + 1) * (‖V‖ * (n + 1)), ?_⟩ (fun w hw => ?_) (fun w hw => ?_) hz
  · rintro _ ⟨w, hw, rfl⟩
    exact norm_windowConj_le E₁ E₂ V n hw
  · have hw' : w = (w.re : ℂ) := Complex.ext (by simp) (by simp [hw])
    rw [hw']
    exact (norm_windowConj_ofReal_le E₁ E₂ V n _).trans (le_max_left _ _)
  · have hw' : w = (w.re : ℂ) + I / 2 := Complex.ext (by simp) (by simp [hw])
    rw [hw', windowConj_add_half E₁ E₂ hVV']
    exact (norm_windowConj_ofReal_le E₁ E₂ V' n _).trans (le_max_right _ _)

/-- **Three lines**: `‖B^{-iz} V A^{iz}‖ ≤ ‖V‖^{1 - 2 im z} ‖V'‖^{2 im z}` on each window. -/
private lemma norm_windowConj_le_interp {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ E₁.sqrt.graph → (V x, V' u) ∈ E₂.sqrt.graph) (n : ℕ) {z : ℂ}
    (hz : z ∈ im ⁻¹' Icc 0 (1 / 2)) :
    ‖windowConj E₁ E₂ V n z‖ ≤ ‖V‖ ^ (1 - 2 * z.im) * ‖V'‖ ^ (2 * z.im) := by
  have h := Complex.HadamardThreeLines.norm_le_interp_of_im_mem_Icc (f := windowConj E₁ E₂ V n)
    (a := 0) (b := 1 / 2) (Ma := ‖V‖) (Mb := ‖V'‖) (by norm_num)
    (differentiable_windowConj E₁ E₂ V n).diffContOnCl
    ⟨(n + 1) * (‖V‖ * (n + 1)), by
      rintro _ ⟨w, hw, rfl⟩
      exact norm_windowConj_le E₁ E₂ V n hw⟩ (fun w hw => ?_) (fun w hw => ?_) hz
  · have e₁ : (1 / 2 - z.im) / (1 / 2 - 0) = 1 - 2 * z.im := by ring
    have e₂ : (z.im - 0) / (1 / 2 - 0) = 2 * z.im := by ring
    rwa [e₁, e₂] at h
  · have hw' : w = (w.re : ℂ) := Complex.ext (by simp) (by simp [hw])
    rw [hw']
    exact norm_windowConj_ofReal_le E₁ E₂ V n _
  · have hw' : w = (w.re : ℂ) + I / 2 := Complex.ext (by simp) (by simp [hw])
    rw [hw', windowConj_add_half E₁ E₂ hVV']
    exact norm_windowConj_ofReal_le E₁ E₂ V' n _

/-- On the range of a window projection, the cut-off families form a Cauchy sequence: they are
the spectral cut-offs `E₂(window n) a_m` of one another, so `‖a_m - a_n‖² = ‖a_m‖² - ‖a_n‖²` and
`‖a_n‖²` increases to a finite limit. -/
private lemma cauchySeq_windowConj_apply_window {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ E₁.sqrt.graph → (V x, V' u) ∈ E₂.sqrt.graph) {z : ℂ}
    (hz : z ∈ im ⁻¹' Icc 0 (1 / 2)) (N : ℕ) (x : H₁) :
    CauchySeq fun n => windowConj E₁ E₂ V n z (E₁ (window N) x) := by
  set a := fun n => windowConj E₁ E₂ V n z (E₁ (window N) x)
  have hcons : ∀ n m, N ≤ n → n ≤ m → a n = E₂ (window n) (a m) := fun n m hn hnm => by
    simp only [a]
    rw [windowConj_eq_comp E₁ E₂ V hnm z]
    simp only [ContinuousLinearMap.comp_apply]
    rw [E₁.apply_apply_of_subset (measurableSet_window N) (measurableSet_window n)
      (window_mono hn)]
  have hpyth : ∀ n m, N ≤ n → n ≤ m → ‖a m - a n‖ ^ 2 = ‖a m‖ ^ 2 - ‖a n‖ ^ 2 :=
    fun n m hn hnm => by
      rw [hcons n m hn hnm]
      exact E₂.norm_sub_apply_sq (measurableSet_window n) _
  have hbound : ∀ n, ‖a n‖ ≤ max ‖V‖ ‖V'‖ * ‖E₁ (window N) x‖ := fun n =>
    (ContinuousLinearMap.le_opNorm _ _).trans (mul_le_mul_of_nonneg_right
      (norm_windowConj_le_max E₁ E₂ hVV' n hz) (norm_nonneg _))
  set s : ℕ → ℝ := fun k => ‖a (k + N)‖ ^ 2
  have hmono : Monotone s := fun k k' hkk' => by
    have := hpyth (k + N) (k' + N) (by omega) (by omega)
    simp only [s]
    nlinarith [sq_nonneg ‖a (k' + N) - a (k + N)‖]
  have hbdd : BddAbove (range s) := ⟨(max ‖V‖ ‖V'‖ * ‖E₁ (window N) x‖) ^ 2, by
    rintro _ ⟨k, rfl⟩
    exact pow_le_pow_left₀ (norm_nonneg _) (hbound _) 2⟩
  have hL := tendsto_atTop_ciSup hmono hbdd
  refine (cauchySeq_shift N).mp (Metric.cauchySeq_iff'.mpr fun ε hε => ?_)
  obtain ⟨K, hK⟩ := Metric.tendsto_atTop.mp hL (ε ^ 2) (by positivity)
  refine ⟨K, fun k hk => ?_⟩
  have h1 := hpyth (K + N) (k + N) (by omega) (by omega)
  have h2 : s k ≤ ⨆ i, s i := le_ciSup hbdd k
  have h3 := hK K le_rfl
  rw [Real.dist_eq, abs_lt] at h3
  rw [dist_eq_norm]
  have h4 : ‖a (k + N) - a (K + N)‖ ^ 2 < ε ^ 2 := by
    rw [h1]
    simp only [s] at h2 h3
    linarith
  exact lt_of_pow_lt_pow_left₀ 2 hε.le h4

/-- The cut-off families converge strongly on the closed strip. -/
private lemma cauchySeq_windowConj_apply {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ E₁.sqrt.graph → (V x, V' u) ∈ E₂.sqrt.graph) {z : ℂ}
    (hz : z ∈ im ⁻¹' Icc 0 (1 / 2)) (x : H₁) :
    CauchySeq fun n => windowConj E₁ E₂ V n z x := by
  set C := max ‖V‖ ‖V'‖
  have hC : 0 ≤ C := (norm_nonneg _).trans (le_max_left _ _)
  have hb : ∀ n v, ‖windowConj E₁ E₂ V n z v‖ ≤ C * ‖v‖ := fun n v =>
    (ContinuousLinearMap.le_opNorm _ _).trans (mul_le_mul_of_nonneg_right
      (norm_windowConj_le_max E₁ E₂ hVV' n hz) (norm_nonneg _))
  refine Metric.cauchySeq_iff.mpr fun ε hε => ?_
  have hδ : 0 < ε / (3 * (C + 1)) := by positivity
  obtain ⟨N, hN⟩ := Metric.tendsto_atTop.mp (E₁.tendsto_apply_window x) _ hδ
  obtain ⟨K, hK⟩ := Metric.cauchySeq_iff.mp
    (cauchySeq_windowConj_apply_window E₁ E₂ hVV' hz N x) (ε / 3) (by positivity)
  refine ⟨K, fun m hm n hn => ?_⟩
  set x' := E₁ (window N) x
  -- the families only see `E₁((0, ∞)) x`, which the window vectors approximate
  have hP : ∀ k, windowConj E₁ E₂ V k z x = windowConj E₁ E₂ V k z (E₁ (Ioi 0) x) := fun k =>
    (windowConj_apply_Ioi E₁ E₂ V k z x).symm
  rw [hP m, hP n]
  set x := E₁ (Ioi 0) x
  have hxN : ‖x - x'‖ < ε / (3 * (C + 1)) := by
    rw [← dist_eq_norm, dist_comm]
    exact hN N le_rfl
  have hCδ : C * (ε / (3 * (C + 1))) ≤ ε / 3 := by
    rw [mul_div_assoc', div_le_div_iff₀ (by positivity) (by positivity)]
    nlinarith
  have hsplit : windowConj E₁ E₂ V m z x - windowConj E₁ E₂ V n z x =
      windowConj E₁ E₂ V m z (x - x') +
        (windowConj E₁ E₂ V m z x' - windowConj E₁ E₂ V n z x') +
          windowConj E₁ E₂ V n z (x' - x) := by
    simp only [map_sub]
    abel
  rw [dist_eq_norm, hsplit]
  refine (norm_add₃_le).trans_lt ?_
  have h₁ : ‖windowConj E₁ E₂ V m z (x - x')‖ ≤ ε / 3 :=
    (hb m _).trans ((mul_le_mul_of_nonneg_left hxN.le hC).trans hCδ)
  have h₃ : ‖windowConj E₁ E₂ V n z (x' - x)‖ ≤ ε / 3 :=
    (hb n _).trans ((mul_le_mul_of_nonneg_left (by rw [norm_sub_rev]; exact hxN.le) hC).trans hCδ)
  have h₂ := hK m hm n hn
  rw [dist_eq_norm] at h₂
  linarith

/-- `T_n u_n → T u` if `T_n → T` strongly, `‖T_n‖ ≤ C` and `u_n → u`. -/
private lemma tendsto_apply_apply {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E]
    [NormedAddCommGroup F] [NormedSpace ℂ F] {T : ℕ → E →L[ℂ] F} {T₀ : E →L[ℂ] F} {u : ℕ → E}
    {u₀ : E} {C : ℝ} (hT : ∀ v, Tendsto (fun n => T n v) atTop (𝓝 (T₀ v)))
    (hC : ∀ n, ‖T n‖ ≤ C) (hu : Tendsto u atTop (𝓝 u₀)) :
    Tendsto (fun n => T n (u n)) atTop (𝓝 (T₀ u₀)) := by
  have h1 : Tendsto (fun n => T n (u n - u₀)) atTop (𝓝 0) := by
    refine squeeze_zero_norm (fun n => (ContinuousLinearMap.le_opNorm _ _).trans
      (mul_le_mul_of_nonneg_right (hC n) (norm_nonneg _))) ?_
    simpa using (tendsto_iff_norm_sub_tendsto_zero.mp hu).const_mul C
  have := h1.add (hT u₀)
  simp only [map_sub, sub_add_cancel, zero_add] at this
  exact this

/-- The limit of the cut-off families on the real line. -/
private lemma tendsto_windowConj_ofReal (V : H₁ →L[ℂ] H₂) (t : ℝ) (x : H₁) :
    Tendsto (fun n => windowConj E₁ E₂ V n t x) atTop
      (𝓝 ((E₂.imaginaryPower (-t) ∘L V ∘L E₁.imaginaryPower t) x)) := by
  have e₁ : ((Ioi 0).indicator fun s : ℝ => cexp (I * t * Real.log s)) =
      (Ioi 0).indicator fun s : ℝ => cexp (t * Real.log s * I) := by
    congr 1
    funext s
    ring_nf
  have e₂ : ((Ioi 0).indicator fun s : ℝ => cexp (-I * t * Real.log s)) =
      (Ioi 0).indicator fun s : ℝ => cexp (↑(-t) * Real.log s * I) := by
    congr 1
    funext s
    push_cast
    ring_nf
  simp only [windowConj, imaginaryPower, ContinuousLinearMap.comp_apply]
  rw [← e₁, ← e₂]
  have hre₁ : (I * (t : ℂ)).re = 0 := by simp
  have hre₂ : (-I * (t : ℂ)).re = 0 := by simp
  exact tendsto_apply_apply (T := fun n => E₂.integral (cutPow n (-I * t)))
    (fun v => E₂.tendsto_integral_cutPow hre₂ v)
    (fun n => norm_integral_cutPow_le_one E₂ n hre₂)
    (V.continuous.tendsto _ |>.comp (E₁.tendsto_integral_cutPow hre₁ x))

/-! ### Strong continuity up to the boundary -/

/-- The window projections converge to `E((0, ∞))` uniformly on compact sets: cover the set by
finitely many small balls. -/
private lemma eventually_norm_sub_apply_window_lt (E : ProjectionValuedMeasure ℝ H₂)
    {K : Set H₂} (hK : IsCompact K) {ε : ℝ} (hε : 0 < ε) :
    ∀ᶠ n : ℕ in atTop, ∀ y ∈ K, ‖E (Ioi 0) y - E (window n) y‖ < ε := by
  obtain ⟨t, -, ht, hKt⟩ := finite_cover_balls_of_compact hK (show 0 < ε / 3 by positivity)
  have hfin : ∀ᶠ n : ℕ in atTop, ∀ a ∈ t, ‖E (Ioi 0) a - E (window n) a‖ < ε / 3 :=
    (ht.eventually_all).mpr fun a _ => by
      have h := tendsto_iff_norm_sub_tendsto_zero.mp (E.tendsto_apply_window a)
      filter_upwards [(tendsto_order.mp h).2 _ (show (0 : ℝ) < ε / 3 by positivity)] with n hn
      rwa [norm_sub_rev]
  filter_upwards [hfin] with n hn y hy
  obtain ⟨a, ha, hya⟩ := mem_iUnion₂.mp (hKt hy)
  rw [mem_ball, dist_eq_norm] at hya
  have hsplit : E (Ioi 0) y - E (window n) y =
      E (Ioi 0) (y - a) + (E (Ioi 0) a - E (window n) a) + E (window n) (a - y) := by
    simp only [map_sub]
    abel
  rw [hsplit]
  calc ‖E (Ioi 0) (y - a) + (E (Ioi 0) a - E (window n) a) + E (window n) (a - y)‖
      ≤ ‖E (Ioi 0) (y - a)‖ + ‖E (Ioi 0) a - E (window n) a‖ + ‖E (window n) (a - y)‖ :=
        norm_add₃_le
    _ ≤ ‖y - a‖ + ‖E (Ioi 0) a - E (window n) a‖ + ‖y - a‖ := by
        gcongr
        · exact E.norm_apply_le _ _
        · exact (E.norm_apply_le _ _).trans (norm_sub_rev _ _).le
    _ < ε / 3 + ε / 3 + ε / 3 := by
        gcongr
        exact hn a ha
    _ = ε := by ring

/-- `‖E((0, ∞)) y - E(window n) y‖ ≤ ‖y‖`. -/
private lemma norm_sub_apply_window_le (E : ProjectionValuedMeasure ℝ H₂) (n : ℕ) (y : H₂) :
    ‖E (Ioi 0) y - E (window n) y‖ ≤ ‖y‖ := by
  rw [E.apply_Ioi_sub_apply_window]
  exact E.norm_apply_le _ _

/-- For `N ≤ n ≤ m`, the difference of the cut-off families on a window vector `x' = E₁(window N) x`
is `∫ 1_m λ^{-iz} dE₂ ((1 - E₂(window n)) V A_N^{iz} x)`, with `A_N^{iz} = ∫ 1_N λ^{iz} dE₁`. -/
private lemma windowConj_sub_windowConj_apply_window (V : H₁ →L[ℂ] H₂) {N n m : ℕ} (hNn : N ≤ n)
    (hnm : n ≤ m) (z : ℂ) (x : H₁) :
    windowConj E₁ E₂ V m z (E₁ (window N) x) - windowConj E₁ E₂ V n z (E₁ (window N) x) =
      E₂.integral (cutPow m (-I * z)) (V (E₁.integral (cutPow N (I * z)) x) -
        E₂ (window n) (V (E₁.integral (cutPow N (I * z)) x))) := by
  have h₁ : ∀ k, N ≤ k → E₁.integral (cutPow k (I * z)) (E₁ (window N) x) =
      E₁.integral (cutPow N (I * z)) x := fun k hk => by
    rw [← ContinuousLinearMap.comp_apply, E₁.integral_cutPow_comp_apply hk]
  have h₂ : ∀ y, E₂.integral (cutPow n (-I * z)) y = E₂.integral (cutPow m (-I * z)) (E₂ (window n) y) :=
    fun y => by rw [← ContinuousLinearMap.comp_apply, E₂.integral_cutPow_comp_apply hnm]
  simp only [windowConj, ContinuousLinearMap.comp_apply]
  rw [h₁ m (hNn.trans hnm), h₁ n hNn, h₂, map_sub]

/-- On the real line, the difference of the cut-off families on a window vector is bounded by
`‖(E₂((0, ∞)) - E₂(window n)) V A_N^{it} x‖`, with the cut-off power `A_N^{it} = ∫ 1_N λ^{it} dE₁`. -/
private lemma norm_windowConj_sub_windowConj_apply_window_le (V : H₁ →L[ℂ] H₂) {N n m : ℕ}
    (hNn : N ≤ n) (hnm : n ≤ m) (t : ℝ) (x : H₁) :
    ‖windowConj E₁ E₂ V m t (E₁ (window N) x) - windowConj E₁ E₂ V n t (E₁ (window N) x)‖ ≤
      ‖E₂ (Ioi 0) (V (E₁.integral (cutPow N (I * t)) x)) -
        E₂ (window n) (V (E₁.integral (cutPow N (I * t)) x))‖ := by
  rw [windowConj_sub_windowConj_apply_window E₁ E₂ V hNn hnm, ← E₂.integral_cutPow_apply_Ioi,
    map_sub, E₂.apply_Ioi_apply_window]
  exact (ContinuousLinearMap.le_opNorm _ _).trans (le_of_le_of_eq (mul_le_of_le_one_left (norm_nonneg _)
    (norm_integral_cutPow_le_one E₂ m (by simp))) rfl)

omit [CompleteSpace H₂] in
/-- `t ↦ V A_N^{it} x` is continuous. -/
private lemma continuous_apply_integral_cutPow (V : H₁ →L[ℂ] H₂) (N : ℕ) (x : H₁) :
    Continuous fun t : ℝ => V (E₁.integral (cutPow N (I * t)) x) :=
  V.continuous.comp (((E₁.differentiable_integral_cutPow N I).continuous.comp
    continuous_ofReal).clm_apply continuous_const)

omit [CompleteSpace H₂] in
/-- `‖V A_N^{it} x‖ ≤ ‖V‖ ‖x‖`. -/
private lemma norm_apply_integral_cutPow_le (V : H₁ →L[ℂ] H₂) (N : ℕ) (t : ℝ) (x : H₁) :
    ‖V (E₁.integral (cutPow N (I * t)) x)‖ ≤ ‖V‖ * ‖x‖ :=
  (V.le_opNorm _).trans (mul_le_mul_of_nonneg_left ((ContinuousLinearMap.le_opNorm _ _).trans
    (mul_le_of_le_one_left (norm_nonneg _) (norm_integral_cutPow_le_one E₁ N (by simp))))
    (norm_nonneg _))

/-- `|e^{-(z - c)²}| = e^{(im z)² - (re z - c)²}`. -/
private lemma norm_cexp_neg_sq (c : ℝ) (z : ℂ) :
    ‖cexp (-(z - c) ^ 2)‖ = Real.exp ((z.im) ^ 2 - (z.re - c) ^ 2) := by
  rw [norm_exp]
  congr 1
  simp only [neg_re, sq, mul_re, sub_re, ofReal_re, sub_im, ofReal_im, sub_zero]
  ring

/-- **Local uniform convergence of the cut-off families on a window vector.** Near the vertical
line `re z = c` the cut-off families `F_n(z) x'` form a uniform Cauchy sequence on the closed
strip: the maximum principle for the entire function `e^{-(z - c)²} (F_m - F_n)(z) x'` reduces the
estimate to the boundary lines, where the Gaussian factor is small far from `c` and the window
projections converge uniformly on the compact set `{V A_N^{it} x | |t - c| ≤ R}`, with the cut-off
power `A_N^{it} = ∫ 1_N λ^{it} dE₁`. -/
private lemma eventually_norm_windowConj_sub_le {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ E₁.sqrt.graph → (V x, V' u) ∈ E₂.sqrt.graph) (N : ℕ) (x : H₁) (c : ℝ)
    {ε : ℝ} (hε : 0 < ε) :
    ∀ᶠ n : ℕ in atTop, ∀ m, n ≤ m → ∀ z ∈ im ⁻¹' Icc 0 (1 / 2), |z.re - c| ≤ 1 →
      ‖windowConj E₁ E₂ V m z (E₁ (window N) x) - windowConj E₁ E₂ V n z (E₁ (window N) x)‖ ≤ ε := by
  set g : ℝ → H₂ := fun t => V (E₁.integral (cutPow N (I * t)) x)
  set g' : ℝ → H₂ := fun t => V' (E₁.integral (cutPow N (I * t)) x)
  set M₀ := (‖V‖ + ‖V'‖) * ‖x‖
  have hM₀ : 0 ≤ M₀ := by positivity
  set δ := ε / Real.exp 2
  have hδ : 0 < δ := by positivity
  set R := M₀ / δ + 1
  have hR : 0 < R := by positivity
  have hgM : ∀ t, ‖g t‖ ≤ M₀ := fun t => (norm_apply_integral_cutPow_le E₁ V N t x).trans
    (mul_le_mul_of_nonneg_right (by linarith [norm_nonneg V']) (norm_nonneg _))
  have hgM' : ∀ t, ‖g' t‖ ≤ M₀ := fun t => (norm_apply_integral_cutPow_le E₁ V' N t x).trans
    (mul_le_mul_of_nonneg_right (by linarith [norm_nonneg V]) (norm_nonneg _))
  have hK := (isCompact_Icc (a := c - R) (b := c + R)).image (continuous_apply_integral_cutPow E₁ V N x)
  have hK' := (isCompact_Icc (a := c - R) (b := c + R)).image
    (continuous_apply_integral_cutPow E₁ V' N x)
  -- off `[c - R, c + R]` the Gaussian factor is small: `e^{-s²} M₀ ≤ δ` for `|s| ≥ R`
  have hgauss : ∀ s : ℝ, R ≤ |s| → Real.exp (-s ^ 2) * M₀ ≤ δ := fun s hs => by
    have h₁ : |s| ≤ Real.exp (s ^ 2) := by
      nlinarith [Real.add_one_le_exp (s ^ 2), sq_abs s, abs_nonneg s]
    have h₂ : M₀ ≤ δ * R := by
      rw [mul_add, mul_div_cancel₀ _ hδ.ne', mul_one]
      linarith
    rw [Real.exp_neg, inv_mul_le_iff₀ (Real.exp_pos _)]
    calc M₀ ≤ δ * R := h₂
      _ ≤ δ * |s| := mul_le_mul_of_nonneg_left hs hδ.le
      _ ≤ δ * Real.exp (s ^ 2) := mul_le_mul_of_nonneg_left h₁ hδ.le
      _ = Real.exp (s ^ 2) * δ := mul_comm _ _
  -- the boundary estimate, for either operator
  have hbdry : ∀ (W : H₁ →L[ℂ] H₂) (n : ℕ), (∀ t, ‖(fun t : ℝ => W (E₁.integral (cutPow N (I * t)) x)) t‖ ≤ M₀) →
      (∀ y ∈ (fun t : ℝ => W (E₁.integral (cutPow N (I * t)) x)) '' Icc (c - R) (c + R),
        ‖E₂ (Ioi 0) y - E₂ (window n) y‖ < δ) → ∀ t : ℝ,
      Real.exp (-(t - c) ^ 2) * ‖E₂ (Ioi 0) (W (E₁.integral (cutPow N (I * t)) x)) -
        E₂ (window n) (W (E₁.integral (cutPow N (I * t)) x))‖ ≤ δ := fun W n hW hn t => by
    by_cases ht : |t - c| ≤ R
    · have hmem : W (E₁.integral (cutPow N (I * t)) x) ∈
          (fun t : ℝ => W (E₁.integral (cutPow N (I * t)) x)) '' Icc (c - R) (c + R) :=
        ⟨t, by constructor <;> linarith [abs_le.mp ht], rfl⟩
      calc _ ≤ 1 * δ := mul_le_mul (Real.exp_le_one_iff.mpr (by nlinarith)) (hn _ hmem).le
            (norm_nonneg _) zero_le_one
        _ = δ := one_mul _
    · calc _ ≤ Real.exp (-(t - c) ^ 2) * M₀ := mul_le_mul_of_nonneg_left
            ((norm_sub_apply_window_le E₂ n _).trans (hW t)) (Real.exp_pos _).le
        _ ≤ δ := hgauss _ (not_le.mp ht).le
  filter_upwards [eventually_ge_atTop N, eventually_norm_sub_apply_window_lt E₂ hK hδ,
    eventually_norm_sub_apply_window_lt E₂ hK' hδ] with n hNn hn hn' m hnm z hz hzc
  set G : ℂ → H₂ := fun w => cexp (-(w - c) ^ 2) •
    (windowConj E₁ E₂ V m w (E₁ (window N) x) - windowConj E₁ E₂ V n w (E₁ (window N) x))
  have hGd : Differentiable ℂ G := by
    refine ((differentiable_id.sub_const _).pow 2).neg.cexp.smul ?_
    exact ((differentiable_windowConj E₁ E₂ V m).clm_apply (differentiable_const _)).sub
      ((differentiable_windowConj E₁ E₂ V n).clm_apply (differentiable_const _))
  have hGB : BddAbove ((norm ∘ G) '' (im ⁻¹' Icc 0 (1 / 2))) := by
    refine ⟨Real.exp 1 * (((m + 1) * (‖V‖ * (m + 1)) + (n + 1) * (‖V‖ * (n + 1))) *
      ‖E₁ (window N) x‖), ?_⟩
    rintro _ ⟨w, hw, rfl⟩
    simp only [Function.comp_apply, G, norm_smul]
    refine mul_le_mul ?_ ((norm_sub_le _ _).trans ?_) (norm_nonneg _) (Real.exp_pos _).le
    · rw [norm_cexp_neg_sq, Real.exp_le_exp]
      nlinarith [hw.1, hw.2, sq_nonneg (w.re - c)]
    · rw [add_mul]
      exact add_le_add
        ((ContinuousLinearMap.le_opNorm _ _).trans (mul_le_mul_of_nonneg_right
          (norm_windowConj_le E₁ E₂ V m hw) (norm_nonneg _)))
        ((ContinuousLinearMap.le_opNorm _ _).trans (mul_le_mul_of_nonneg_right
          (norm_windowConj_le E₁ E₂ V n hw) (norm_nonneg _)))
  have hGz : ‖G z‖ ≤ Real.exp (1 / 4) * δ := by
    refine Complex.norm_le_of_im_mem_Icc hGd.diffContOnCl hGB (fun w hw => ?_) (fun w hw => ?_) hz
    · have hw' : w = (w.re : ℂ) := Complex.ext (by simp) (by simp [hw])
      rw [hw']
      simp only [G, norm_smul, norm_cexp_neg_sq, ofReal_im, ofReal_re]
      rw [show (0 : ℝ) ^ 2 - (w.re - c) ^ 2 = -(w.re - c) ^ 2 by ring]
      calc _ ≤ Real.exp (-(w.re - c) ^ 2) * ‖E₂ (Ioi 0) (V (E₁.integral (cutPow N (I * w.re)) x)) -
              E₂ (window n) (V (E₁.integral (cutPow N (I * w.re)) x))‖ :=
            mul_le_mul_of_nonneg_left
              (norm_windowConj_sub_windowConj_apply_window_le E₁ E₂ V hNn hnm w.re x)
              (Real.exp_pos _).le
        _ ≤ δ := hbdry V n hgM hn w.re
        _ ≤ Real.exp (1 / 4) * δ := le_mul_of_one_le_left hδ.le (Real.one_le_exp (by norm_num))
    · have hw' : w = (w.re : ℂ) + I / 2 := Complex.ext (by simp) (by simp [hw])
      rw [hw']
      simp only [G, norm_smul, norm_cexp_neg_sq]
      rw [windowConj_add_half E₁ E₂ hVV', windowConj_add_half E₁ E₂ hVV']
      have him : ((w.re : ℂ) + I / 2).im ^ 2 - (((w.re : ℂ) + I / 2).re - c) ^ 2 =
          1 / 4 + -(w.re - c) ^ 2 := by
        simp
        ring
      rw [him, Real.exp_add, mul_assoc]
      refine mul_le_mul_of_nonneg_left ?_ (Real.exp_pos _).le
      calc _ ≤ Real.exp (-(w.re - c) ^ 2) * ‖E₂ (Ioi 0) (V' (E₁.integral (cutPow N (I * w.re)) x)) -
              E₂ (window n) (V' (E₁.integral (cutPow N (I * w.re)) x))‖ :=
            mul_le_mul_of_nonneg_left
              (norm_windowConj_sub_windowConj_apply_window_le E₁ E₂ V' hNn hnm w.re x)
              (Real.exp_pos _).le
        _ ≤ δ := hbdry V' n hgM' hn' w.re
  -- near `re z = c`, `|e^{-(z - c)²}| ≥ e^{-1}`
  have hlow : Real.exp (-1) ≤ ‖cexp (-(z - c) ^ 2)‖ := by
    rw [norm_cexp_neg_sq, Real.exp_le_exp]
    have : (z.re - c) ^ 2 ≤ 1 := by
      rw [← sq_abs]
      nlinarith [abs_nonneg (z.re - c)]
    nlinarith [sq_nonneg z.im]
  have hGz' : Real.exp (-1) * ‖windowConj E₁ E₂ V m z (E₁ (window N) x) -
      windowConj E₁ E₂ V n z (E₁ (window N) x)‖ ≤ Real.exp (1 / 4) * δ :=
    (mul_le_mul_of_nonneg_right hlow (norm_nonneg _)).trans (by simpa [G, norm_smul] using hGz)
  calc _ = Real.exp 1 * (Real.exp (-1) * ‖windowConj E₁ E₂ V m z (E₁ (window N) x) -
        windowConj E₁ E₂ V n z (E₁ (window N) x)‖) := by
          rw [← mul_assoc, ← Real.exp_add, add_neg_cancel, Real.exp_zero, one_mul]
    _ ≤ Real.exp 1 * (Real.exp (1 / 4) * δ) := mul_le_mul_of_nonneg_left hGz' (Real.exp_pos _).le
    _ ≤ Real.exp 2 * δ := by
        rw [← mul_assoc, ← Real.exp_add]
        exact mul_le_mul_of_nonneg_right (Real.exp_le_exp.mpr (by norm_num)) hδ.le
    _ = ε := mul_div_cancel₀ _ (Real.exp_pos _).ne'

/-- The interpolation theorem in terms of the projection-valued measures `E₁`, `E₂` of `A` and `B`,
with `A^{it} = ∫_{(0,∞)} e^{it log λ} dE₁(λ)`. -/
private lemma exists_stripContinuation_pvm {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ E₁.sqrt.graph → (V x, V' u) ∈ E₂.sqrt.graph) :
    ∃ F : ℂ → H₁ →L[ℂ] H₂, DifferentiableOn ℂ F (im ⁻¹' Ioo 0 (1 / 2)) ∧
      (∀ x y, DiffContOnCl ℂ (fun z => ⟪y, F z x⟫_ℂ) (im ⁻¹' Ioo 0 (1 / 2))) ∧
      (∀ x, ContinuousOn (fun z => F z x) (im ⁻¹' Icc 0 (1 / 2))) ∧
      (∀ z ∈ im ⁻¹' Icc 0 (1 / 2), ‖F z‖ ≤ ‖V‖ ^ (1 - 2 * z.im) * ‖V'‖ ^ (2 * z.im)) ∧
      (∀ t : ℝ, F t = E₂.imaginaryPower (-t) ∘L V ∘L E₁.imaginaryPower t) ∧
      ∀ t : ℝ, F (t + I / 2) = E₂.imaginaryPower (-t) ∘L V' ∘L E₁.imaginaryPower t := by
  classical
  set S := im ⁻¹' Icc (0 : ℝ) (1 / 2) with hS
  set C := max ‖V‖ ‖V'‖
  have hC : 0 ≤ C := (norm_nonneg _).trans (le_max_left _ _)
  have hU : IsOpen (im ⁻¹' Ioo (0 : ℝ) (1 / 2)) := isOpen_Ioo.preimage continuous_im
  have hUS : im ⁻¹' Ioo (0 : ℝ) (1 / 2) ⊆ S := preimage_mono Ioo_subset_Icc_self
  have hcl : closure (im ⁻¹' Ioo (0 : ℝ) (1 / 2)) = S := closure_preimage_im_Ioo (by norm_num)
  have hconv : ∀ z ∈ S, Tendsto (fun n x => windowConj E₁ E₂ V n z x) atTop
      (𝓝 fun x => limUnder atTop fun n => windowConj E₁ E₂ V n z x) := fun z hz =>
    tendsto_pi_nhds.mpr fun x => (cauchySeq_windowConj_apply E₁ E₂ hVV' hz x).tendsto_limUnder
  let F : ℂ → H₁ →L[ℂ] H₂ := fun z =>
    if hz : z ∈ S then continuousLinearMapOfTendsto _ (hconv z hz) else 0
  have hF : ∀ z ∈ S, ∀ x, Tendsto (fun n => windowConj E₁ E₂ V n z x) atTop (𝓝 (F z x)) :=
    fun z hz x => by
      simp only [F, hz, ↓reduceDIte]
      exact tendsto_pi_nhds.mp (hconv z hz) x
  have hFb : ∀ z ∈ S, ‖F z‖ ≤ C := fun z hz => ContinuousLinearMap.opNorm_le_bound _ hC fun x =>
    le_of_tendsto (hF z hz x).norm (Eventually.of_forall fun n => (ContinuousLinearMap.le_opNorm _ _).trans
      (mul_le_mul_of_nonneg_right (norm_windowConj_le_max E₁ E₂ hVV' n hz) (norm_nonneg _)))
  -- `F z` only sees `E₁((0, ∞)) x` and takes values in `E₂((0, ∞)) H₂`
  have hFP : ∀ z ∈ S, ∀ x, F z (E₁ (Ioi 0) x) = F z x := fun z hz x =>
    tendsto_nhds_unique ((hF z hz _).congr fun n => windowConj_apply_Ioi E₁ E₂ V n z x) (hF z hz x)
  have hFQ : ∀ z ∈ S, ∀ x y, ⟪y, F z x⟫_ℂ = ⟪E₂ (Ioi 0) y, F z x⟫_ℂ := fun z hz x y => by
    have hQ : E₂ (Ioi 0) (F z x) = F z x := tendsto_nhds_unique
      (((E₂ (Ioi 0)).continuous.tendsto _).comp (hF z hz x))
      ((hF z hz x).congr fun n => (apply_Ioi_windowConj E₁ E₂ V n z x).symm)
    rw [E₂.inner_apply_left, hQ]
  -- weak holomorphy and continuity, by uniform approximation on the windows
  have hweak : ∀ x y, DiffContOnCl ℂ (fun z => ⟪y, F z x⟫_ℂ) (im ⁻¹' Ioo 0 (1 / 2)) := by
    intro x y
    set f : ℕ → ℂ → ℂ := fun N z =>
      ⟪E₂ (window N) y, windowConj E₁ E₂ V N z (E₁ (window N) x)⟫_ℂ
    have hfd : ∀ N, Differentiable ℂ (f N) := fun N =>
      (innerSL ℂ (E₂ (window N) y)).differentiable.comp
        ((differentiable_windowConj E₁ E₂ V N).clm_apply (differentiable_const _))
    have hfeq : ∀ N, ∀ z ∈ S, ⟪E₂ (window N) y, F z (E₁ (window N) x)⟫_ℂ = f N z := by
      intro N z hz
      refine tendsto_nhds_unique (tendsto_const_nhds.inner (hF z hz _))
        (tendsto_const_nhds.congr' ?_)
      filter_upwards [eventually_ge_atTop N] with n hn
      simp only [f]
      rw [windowConj_eq_comp E₁ E₂ V hn z]
      simp only [ContinuousLinearMap.comp_apply]
      rw [E₁.apply_apply_self (measurableSet_window N), ← E₂.inner_apply_left,
        E₂.apply_apply_self (measurableSet_window N)]
    have hb : Tendsto (fun N => C * (‖E₂ (Ioi 0) y - E₂ (window N) y‖ * ‖x‖ +
        ‖y‖ * ‖E₁ (Ioi 0) x - E₁ (window N) x‖)) atTop (𝓝 0) := by
      have hy := tendsto_iff_norm_sub_tendsto_zero.mp (E₂.tendsto_apply_window y)
      have hx := tendsto_iff_norm_sub_tendsto_zero.mp (E₁.tendsto_apply_window x)
      simp only [norm_sub_rev _ (E₂ (Ioi 0) y), norm_sub_rev _ (E₁ (Ioi 0) x)] at hy hx
      simpa using ((hy.mul_const ‖x‖).add (hx.const_mul ‖y‖)).const_mul C
    have huni : TendstoUniformlyOn f (fun z => ⟪y, F z x⟫_ℂ) atTop S := by
      refine Metric.tendstoUniformlyOn_iff.mpr fun ε hε => ?_
      filter_upwards [(Metric.tendsto_atTop.mp hb) ε hε |> fun ⟨N, hN⟩ =>
        eventually_atTop.mpr ⟨N, hN⟩] with N hN z hz
      rw [Real.dist_eq, sub_zero, abs_of_nonneg (by positivity)] at hN
      rw [← hfeq N z hz, dist_eq_norm]
      have hsplit : ⟪y, F z x⟫_ℂ - ⟪E₂ (window N) y, F z (E₁ (window N) x)⟫_ℂ =
          ⟪E₂ (Ioi 0) y - E₂ (window N) y, F z x⟫_ℂ +
            ⟪E₂ (window N) y, F z (E₁ (Ioi 0) x - E₁ (window N) x)⟫_ℂ := by
        rw [inner_sub_left, map_sub, inner_sub_right, hFP z hz, ← hFQ z hz]
        ring
      rw [hsplit]
      refine (norm_add_le _ _).trans_lt (lt_of_le_of_lt ?_ hN)
      have hFz : ∀ v, ‖F z v‖ ≤ C * ‖v‖ := fun v =>
        (ContinuousLinearMap.le_opNorm _ _).trans (mul_le_mul_of_nonneg_right (hFb z hz) (norm_nonneg _))
      calc _ ≤ ‖E₂ (Ioi 0) y - E₂ (window N) y‖ * (C * ‖x‖) +
            ‖E₂ (window N) y‖ * (C * ‖E₁ (Ioi 0) x - E₁ (window N) x‖) :=
          add_le_add ((norm_inner_le_norm _ _).trans
              (mul_le_mul_of_nonneg_left (hFz _) (norm_nonneg _)))
            ((norm_inner_le_norm _ _).trans (mul_le_mul_of_nonneg_left (hFz _) (norm_nonneg _)))
        _ ≤ ‖E₂ (Ioi 0) y - E₂ (window N) y‖ * (C * ‖x‖) +
            ‖y‖ * (C * ‖E₁ (Ioi 0) x - E₁ (window N) x‖) := by
          gcongr
          exact E₂.norm_apply_le _ _
        _ = _ := by ring
    refine ⟨(huni.mono hUS).tendstoLocallyUniformlyOn.differentiableOn
      (Eventually.of_forall fun N => (hfd N).differentiableOn) hU, ?_⟩
    rw [hcl]
    exact huni.continuousOn (Frequently.of_forall fun N => (hfd N).continuous.continuousOn)
  have hFi : ∀ z ∈ S, ‖F z‖ ≤ ‖V‖ ^ (1 - 2 * z.im) * ‖V'‖ ^ (2 * z.im) := fun z hz =>
    ContinuousLinearMap.opNorm_le_bound _ (by positivity) fun x =>
      le_of_tendsto (hF z hz x).norm (Eventually.of_forall fun n =>
        (ContinuousLinearMap.le_opNorm _ _).trans (mul_le_mul_of_nonneg_right
          (norm_windowConj_le_interp E₁ E₂ hVV' n hz) (norm_nonneg _)))
  -- strong continuity: first on window vectors, by local uniform convergence
  have hwin : ∀ N x, ContinuousOn (fun z => F z (E₁ (window N) x)) S := by
    intro N x z₀ hz₀
    set T := S ∩ {z : ℂ | |z.re - z₀.re| ≤ 1}
    have hT : TendstoUniformlyOn (fun n z => windowConj E₁ E₂ V n z (E₁ (window N) x))
        (fun z => F z (E₁ (window N) x)) atTop T := by
      refine UniformCauchySeqOn.tendstoUniformlyOn_of_tendsto ?_ fun z hz => hF z hz.1 _
      refine Metric.uniformCauchySeqOn_iff.mpr fun ε hε => ?_
      obtain ⟨n₀, hn₀⟩ := eventually_atTop.mp
        (eventually_norm_windowConj_sub_le E₁ E₂ hVV' N x z₀.re (half_pos hε))
      refine ⟨n₀, fun m hm n hn z hz => ?_⟩
      rw [dist_eq_norm]
      rcases le_total n m with hnm | hmn
      · exact (hn₀ n hn m hnm z hz.1 hz.2).trans_lt (half_lt_self hε)
      · rw [norm_sub_rev]
        exact (hn₀ m hm n hmn z hz.1 hz.2).trans_lt (half_lt_self hε)
    have hcont := hT.continuousOn (Frequently.of_forall fun n =>
      ((differentiable_windowConj E₁ E₂ V n).continuous.clm_apply continuous_const).continuousOn)
    refine (hcont z₀ ⟨hz₀, by simp⟩).mono_of_mem_nhdsWithin (inter_mem_nhdsWithin S ?_)
    refine mem_of_superset ((isOpen_lt ((continuous_re.sub continuous_const).abs)
      continuous_const).mem_nhds (show |z₀.re - z₀.re| < 1 by simp)) fun z hz => le_of_lt hz
  -- then on all vectors, as uniform limits
  have hstrong : ∀ x, ContinuousOn (fun z => F z x) S := by
    intro x
    refine TendstoUniformlyOn.continuousOn (F := fun N z => F z (E₁ (window N) x))
      (p := atTop) ?_ (Frequently.of_forall fun N => hwin N x)
    refine Metric.tendstoUniformlyOn_iff.mpr fun ε hε => ?_
    have hx := tendsto_iff_norm_sub_tendsto_zero.mp (E₁.tendsto_apply_window x)
    filter_upwards [(tendsto_order.mp hx).2 (ε / (C + 1)) (by positivity)] with N hN z hz
    rw [dist_eq_norm, ← hFP z hz x, ← map_sub]
    calc ‖F z (E₁ (Ioi 0) x - E₁ (window N) x)‖ ≤ C * ‖E₁ (Ioi 0) x - E₁ (window N) x‖ :=
          (ContinuousLinearMap.le_opNorm _ _).trans
            (mul_le_mul_of_nonneg_right (hFb z hz) (norm_nonneg _))
      _ ≤ C * (ε / (C + 1)) := by
          gcongr
          rw [norm_sub_rev]
          exact hN.le
      _ < ε := by
          rw [mul_div_assoc', div_lt_iff₀ (by positivity)]
          nlinarith
  refine ⟨F, Complex.differentiableOn_continuousLinearMap_of_inner hU
    (fun x y => (hweak x y).differentiableOn), hweak, hstrong, hFi, fun t => ?_, fun t => ?_⟩
  · have ht : (t : ℂ) ∈ S := by simp [hS]
    ext x
    exact tendsto_nhds_unique (hF _ ht x) (tendsto_windowConj_ofReal E₁ E₂ V t x)
  · have ht : (t : ℂ) + I / 2 ∈ S := by simp [hS]
    ext x
    refine tendsto_nhds_unique (hF _ ht x) ?_
    simp only [windowConj_add_half E₁ E₂ hVV']
    exact tendsto_windowConj_ofReal E₁ E₂ V' t x

/-- The intertwining passes to the adjoints: `B^{1/2} V ⊇ V' A^{1/2}` gives
`A^{1/2} V'† ⊇ V† B^{1/2}`, as `A^{1/2}` and `B^{1/2}` are self-adjoint. -/
private lemma adjoint_mem_graph_sqrt {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ E₁.sqrt.graph → (V x, V' u) ∈ E₂.sqrt.graph) (y w : H₂)
    (h : (y, w) ∈ E₂.sqrt.graph) : ((V'†) y, (V†) w) ∈ E₁.sqrt.graph := by
  have hs : Measurable fun t : ℝ => (Real.sqrt t : ℂ) :=
    Complex.measurable_ofReal.comp Real.continuous_sqrt.measurable
  have hself₁ : E₁.sqrt† = E₁.sqrt := by
    simp only [sqrt, E₁.adjoint_integralPMap hs, conj_ofReal]
  have hself₂ : E₂.sqrt† = E₂.sqrt := by
    simp only [sqrt, E₂.adjoint_integralPMap hs, conj_ofReal]
  rw [← hself₂, LinearPMap.mem_graph_adjoint_iff (E₂.dense_integralDomain hs)] at h
  rw [← hself₁, LinearPMap.mem_graph_adjoint_iff (E₁.dense_integralDomain hs)]
  intro v v' hv
  rw [ContinuousLinearMap.adjoint_inner_right, ContinuousLinearMap.adjoint_inner_right]
  exact h _ _ (hVV' v v' hv)

/-- `a^{1 - 2y} b^{2y} ≤ a + b` for `0 ≤ y ≤ 1/2`. -/
private lemma rpow_mul_rpow_le_add {a b y : ℝ} (ha : 0 ≤ a) (hb : 0 ≤ b) (hy : y ∈ Icc 0 (1 / 2)) :
    a ^ (1 - 2 * y) * b ^ (2 * y) ≤ a + b := by
  refine (Real.geom_mean_le_arith_mean2_weighted (by linarith [hy.2]) (by linarith [hy.1]) ha hb
    (by ring)).trans ?_
  nlinarith [hy.1, hy.2]

/-- The interpolation theorem with `*`-strong continuity up to the boundary. The adjoints `F(z)†`
are the values `G(z̄ + i/2)` of the continuation `G` of `t ↦ A^{-it} V'† B^{it}`, which exists by
the intertwining `A^{1/2} V'† ⊇ V† B^{1/2}`; the matrix coefficients of `F(z)` and `G(z̄ + i/2)†`
are holomorphic, bounded and agree on the real line, hence on the strip. -/
private lemma exists_stripContinuation_pvm_star {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ E₁.sqrt.graph → (V x, V' u) ∈ E₂.sqrt.graph) :
    ∃ F : ℂ → H₁ →L[ℂ] H₂, DifferentiableOn ℂ F (im ⁻¹' Ioo 0 (1 / 2)) ∧
      (∀ x, ContinuousOn (fun z => F z x) (im ⁻¹' Icc 0 (1 / 2))) ∧
      (∀ y, ContinuousOn (fun z => ((F z)†) y) (im ⁻¹' Icc 0 (1 / 2))) ∧
      (∀ z ∈ im ⁻¹' Icc 0 (1 / 2), ‖F z‖ ≤ ‖V‖ ^ (1 - 2 * z.im) * ‖V'‖ ^ (2 * z.im)) ∧
      (∀ t : ℝ, F t = E₂.imaginaryPower (-t) ∘L V ∘L E₁.imaginaryPower t) ∧
      ∀ t : ℝ, F (t + I / 2) = E₂.imaginaryPower (-t) ∘L V' ∘L E₁.imaginaryPower t := by
  obtain ⟨F, hFd, hFw, hFs, hFb, hF0, hF1⟩ := E₁.exists_stripContinuation_pvm E₂ hVV'
  obtain ⟨G, -, hGw, hGs, hGb, -, hG1⟩ := E₂.exists_stripContinuation_pvm E₁
    (V := V'†) (V' := V†) (adjoint_mem_graph_sqrt E₁ E₂ hVV')
  set S := im ⁻¹' Icc (0 : ℝ) (1 / 2) with hS
  set U := im ⁻¹' Ioo (0 : ℝ) (1 / 2)
  have hU : IsOpen U := isOpen_Ioo.preimage continuous_im
  have hcl : closure U = S := closure_preimage_im_Ioo (by norm_num)
  -- `z ↦ z̄ + i/2` maps the strip to itself
  have hmaps : MapsTo (fun z : ℂ => conj z + I / 2) S S := fun z hz => by
    simp only [hS, mem_preimage, mem_Icc, add_im, conj_im, div_ofNat_im, I_im] at hz ⊢
    constructor <;> linarith [hz.1, hz.2]
  have hmapsU : MapsTo (fun z : ℂ => conj z + I / 2) U U := fun z hz => by
    simp only [U, mem_preimage, mem_Ioo, add_im, conj_im, div_ofNat_im, I_im] at hz ⊢
    constructor <;> linarith [hz.1, hz.2]
  have hFB : ∀ z ∈ S, ‖F z‖ ≤ ‖V‖ + ‖V'‖ := fun z hz =>
    (hFb z hz).trans (rpow_mul_rpow_le_add (norm_nonneg _) (norm_nonneg _) hz)
  have hGB : ∀ z ∈ S, ‖G z‖ ≤ ‖V'†‖ + ‖V†‖ := fun z hz =>
    (hGb z hz).trans (rpow_mul_rpow_le_add (norm_nonneg _) (norm_nonneg _) hz)
  -- `F(z)† = G(z̄ + i/2)`
  have key : ∀ z ∈ S, (F z)† = G (conj z + I / 2) := by
    intro z hz
    refine ContinuousLinearMap.ext fun y => ext_inner_left ℂ fun x => ?_
    rw [ContinuousLinearMap.adjoint_inner_right]
    set f : ℂ → ℂ := fun z => ⟪y, F z x⟫_ℂ - conj ⟪x, G (conj z + I / 2) y⟫_ℂ
    have hψd : DifferentiableOn ℂ (fun z => conj ⟪x, G (conj z + I / 2) y⟫_ℂ) U := fun w hw => by
      have h₁ : DifferentiableAt ℂ (fun v => ⟪x, G v y⟫_ℂ) (conj w + I / 2) :=
        (hGw y x).differentiableOn.differentiableAt (hU.mem_nhds (hmapsU hw))
      have hg : DifferentiableAt ℂ (fun v => ⟪x, G (v + I / 2) y⟫_ℂ) (conj w) :=
        DifferentiableAt.comp (g := fun v => ⟪x, G v y⟫_ℂ) (f := fun v : ℂ => v + I / 2) (conj w) h₁
          (differentiableAt_id.add_const _)
      have h₂ := hg.conj_conj
      rw [conj_conj] at h₂
      exact h₂.differentiableWithinAt
    have hψc : ContinuousOn (fun z => conj ⟪x, G (conj z + I / 2) y⟫_ℂ) S :=
      continuous_conj.comp_continuousOn ((hcl ▸ (hGw y x).continuousOn).comp
        (continuous_conj.add continuous_const).continuousOn hmaps)
    have hfd : DiffContOnCl ℂ f U :=
      ⟨(hFw x y).differentiableOn.sub hψd, hcl ▸ (hcl ▸ (hFw x y).continuousOn).sub hψc⟩
    have hfB : BddAbove ((norm ∘ f) '' S) := by
      refine ⟨‖y‖ * ((‖V‖ + ‖V'‖) * ‖x‖) + ‖x‖ * ((‖V'†‖ + ‖V†‖) * ‖y‖), ?_⟩
      rintro _ ⟨w, hw, rfl⟩
      refine (norm_sub_le _ _).trans (add_le_add ((norm_inner_le_norm _ _).trans ?_) ?_)
      · exact mul_le_mul_of_nonneg_left ((ContinuousLinearMap.le_opNorm _ _).trans
          (mul_le_mul_of_nonneg_right (hFB w hw) (norm_nonneg _))) (norm_nonneg _)
      · rw [RCLike.norm_conj]
        exact (norm_inner_le_norm _ _).trans (mul_le_mul_of_nonneg_left
          ((ContinuousLinearMap.le_opNorm _ _).trans (mul_le_mul_of_nonneg_right
            (hGB _ (hmaps hw)) (norm_nonneg _))) (norm_nonneg _))
    have hf0 : ∀ w : ℂ, w.im = 0 → f w = 0 := fun w hw => by
      have hw' : w = (w.re : ℂ) := Complex.ext (by simp) (by simp [hw])
      rw [hw']
      simp only [f, conj_ofReal, hF0, hG1, ContinuousLinearMap.comp_apply]
      rw [inner_conj_symm, ← E₁.star_imaginaryPower w.re, ContinuousLinearMap.star_eq_adjoint,
        ContinuousLinearMap.adjoint_inner_left, ContinuousLinearMap.adjoint_inner_left,
        ← ContinuousLinearMap.adjoint_inner_right, ← ContinuousLinearMap.star_eq_adjoint,
        ProjectionValuedMeasure.star_imaginaryPower, sub_self]
    have h := Complex.eqOn_zero_of_eqOn_zero_im_eq_lower hfd hfB hf0 hz
    have h' : ⟪y, F z x⟫_ℂ = conj ⟪x, G (conj z + I / 2) y⟫_ℂ := sub_eq_zero.mp h
    rw [← inner_conj_symm, h', conj_conj]
  refine ⟨F, hFd, hFs, fun y => ?_, hFb, hF0, hF1⟩
  refine ((hGs y).comp (continuous_conj.add continuous_const).continuousOn hmaps).congr
    fun z hz => ?_
  rw [Function.comp_apply, key z hz]
  rfl

end Interpolation

end MeasureTheory.ProjectionValuedMeasure

namespace IsSelfAdjoint

variable {H₁ H₂ : Type*} [NormedAddCommGroup H₁] [InnerProductSpace ℂ H₁] [CompleteSpace H₁]
  [NormedAddCommGroup H₂] [InnerProductSpace ℂ H₂] [CompleteSpace H₂]
  {A : H₁ →ₗ.[ℂ] H₁} {B : H₂ →ₗ.[ℂ] H₂}

/-- **Interpolation between the imaginary powers of two positive operators.** Let `A` on `H₁` and
`B` on `H₂` be self-adjoint operators (only their positive parts enter: `A^{1/2}` and `A^{it}`
vanish on `E_A((-∞, 0]) H₁`) and `V`, `V'` bounded operators with `B^{1/2} V ⊇ V' A^{1/2}`.
Then `t ↦ B^{-it} V A^{it}` extends to a family `F z` of bounded operators on the strip
`0 ≤ im z ≤ 1/2`, holomorphic in the operator norm in the interior and `*`-strongly continuous on
the closed strip, with `‖F z‖ ≤ ‖V‖^{1 - 2 im z} ‖V'‖^{2 im z}` and
`F (t + i/2) = B^{-it} V' A^{it}`. Here `A^{it} = ∫_{(0,∞)} λ^{it} dE_A(λ)` are the imaginary powers
(`IsSelfAdjoint.imaginaryPower`), partial isometries vanishing on `E_A((-∞, 0]) H₁` (the kernel of a
positive `A`); for a positive injective `A` they are the unitary group generated by `log A`
(`IsSelfAdjoint.imaginaryPower_eq_unitaryGroup`). -/
theorem exists_stripContinuation (hA : IsSelfAdjoint A) (hB : IsSelfAdjoint B)
    {V V' : H₁ →L[ℂ] H₂}
    (hVV' : (V' : H₁ →ₗ[ℂ] H₂).compPMap hA.sqrt ≤ hB.sqrt.compNat ((V : H₁ →ₗ[ℂ] H₂).toPMap ⊤)) :
    ∃ F : ℂ → H₁ →L[ℂ] H₂, DifferentiableOn ℂ F (im ⁻¹' Ioo 0 (1 / 2)) ∧
      (∀ x, ContinuousOn (fun z => F z x) (im ⁻¹' Icc 0 (1 / 2))) ∧
      (∀ y, ContinuousOn (fun z => ((F z)†) y) (im ⁻¹' Icc 0 (1 / 2))) ∧
      (∀ z ∈ im ⁻¹' Icc 0 (1 / 2), ‖F z‖ ≤ ‖V‖ ^ (1 - 2 * z.im) * ‖V'‖ ^ (2 * z.im)) ∧
      (∀ t : ℝ, F t = hB.imaginaryPower (-t) ∘L V ∘L hA.imaginaryPower t) ∧
      ∀ t : ℝ, F (t + I / 2) = hB.imaginaryPower (-t) ∘L V' ∘L hA.imaginaryPower t :=
  -- the continuation is built from spectral cutoffs, vector by vector
  hA.pvm.exists_stripContinuation_pvm_star hB.pvm fun _ _ h =>
    LinearPMap.compPMap_le_compNat_toPMap_iff.mp hVV' h

section Semilinear

variable {σ : ℂ →+* ℂ} [RingHomInvPair σ σ] [RingHomIsometric σ] {T₁ : H₁ →ₛₗ.[σ] H₁}
  {T₂ : H₂ →ₛₗ.[σ] H₂}

/-- **Borchers' Theorem A for semilinear contractions.** Let `T₁` on `H₁` and `T₂` on `H₂` be
`σ`-semilinear operators, `σ` the identity or the conjugation, `A`, `B` self-adjoint operators on
`H₁`, `H₂`, and `U₁`, `U₂` `σ`-semilinear contractions with `U₁ A^{1/2} ⊆ T₁` and
`U₂ T₂ ⊆ B^{1/2}`. Let `V` be a bounded operator with `V T₁ ⊆ T₂ V`. Then `t ↦ B^{-it} V A^{it}`,
with the imaginary powers (`IsSelfAdjoint.imaginaryPower`, partial isometries vanishing on
`E((-∞, 0])`), extends to a family `F z` of bounded operators on the strip `0 ≤ im z ≤ 1/2`,
holomorphic in the operator norm in the interior and `*`-strongly continuous on the closed strip,
with `‖F z‖ ≤ ‖V‖` and `F (t + i/2) = B^{-it} U₂ V U₁ A^{it}`.

The three inclusions give `(U₂ V U₁) A^{1/2} ⊆ U₂ V T₁ ⊆ U₂ T₂ V ⊆ B^{1/2} V`, where the composite
`U₂ V U₁` of two `σ`-semilinear maps and a complex-linear one is complex-linear, and the
interpolation theorem `IsSelfAdjoint.exists_stripContinuation` applies. The intended case is that
of polar decompositions `Tᵢ = Jᵢ Δᵢ^{1/2}`, with `U₁ = J₁` and `U₂ = J₂†`:
`IsSelfAdjoint.exists_stripContinuation_polarIsometry`. -/
theorem exists_stripContinuation_of_le (hA : IsSelfAdjoint A) (hB : IsSelfAdjoint B)
    (U₁ : H₁ →SL[σ] H₁) (U₂ : H₂ →SL[σ] H₂) (hU₁n : ‖U₁‖ ≤ 1) (hU₂n : ‖U₂‖ ≤ 1)
    (hU₁ : (U₁ : H₁ →ₛₗ[σ] H₁).compPMap hA.sqrt ≤ T₁)
    (hU₂ : (U₂ : H₂ →ₛₗ[σ] H₂).compPMap T₂ ≤ hB.sqrt)
    (V : H₁ →L[ℂ] H₂)
    (hV : (V : H₁ →ₗ[ℂ] H₂).compPMap T₁ ≤ T₂.compNat ((V : H₁ →ₗ[ℂ] H₂).toPMap ⊤)) :
    ∃ F : ℂ → H₁ →L[ℂ] H₂, DifferentiableOn ℂ F (im ⁻¹' Ioo 0 (1 / 2)) ∧
      (∀ x, ContinuousOn (fun z => F z x) (im ⁻¹' Icc 0 (1 / 2))) ∧
      (∀ y, ContinuousOn (fun z => ((F z)†) y) (im ⁻¹' Icc 0 (1 / 2))) ∧
      (∀ z ∈ im ⁻¹' Icc 0 (1 / 2), ‖F z‖ ≤ ‖V‖) ∧
      (∀ t : ℝ, F t = hB.imaginaryPower (-t) ∘L V ∘L hA.imaginaryPower t) ∧
      ∀ (t : ℝ) (x : H₁), F (t + I / 2) x =
        hB.imaginaryPower (-t) (U₂ (V (U₁ (hA.imaginaryPower t x)))) := by
  let V' : H₁ →L[ℂ] H₂ := U₂.comp (V.comp U₁)
  have hV' : ∀ u, V' u = U₂ (V (U₁ u)) := fun _ => rfl
  have hnorm : ‖V'‖ ≤ ‖V‖ := by
    refine ContinuousLinearMap.opNorm_le_bound _ (norm_nonneg _) fun u => ?_
    rw [hV']
    calc ‖U₂ (V (U₁ u))‖ ≤ 1 * ‖V (U₁ u)‖ :=
          (U₂.le_opNorm _).trans (mul_le_mul_of_nonneg_right hU₂n (norm_nonneg _))
      _ ≤ ‖V‖ * (1 * ‖u‖) := by
          rw [one_mul]
          exact (V.le_opNorm _).trans (mul_le_mul_of_nonneg_left
            ((U₁.le_opNorm _).trans (mul_le_mul_of_nonneg_right hU₁n (norm_nonneg _)))
            (norm_nonneg _))
      _ = ‖V‖ * ‖u‖ := by rw [one_mul]
  -- `V' A^{1/2} = U₂ V U₁ A^{1/2} ⊆ U₂ V T₁ ⊆ U₂ T₂ V ⊆ B^{1/2} V`
  set u₁ := (U₁ : H₁ →ₛₗ[σ] H₁)
  set u₂ := (U₂ : H₂ →ₛₗ[σ] H₂)
  set v := (V : H₁ →ₗ[ℂ] H₂)
  have hV'r : (V' : H₁ →ₗ[ℂ] H₂) = u₂.comp (v.comp u₁) := LinearMap.ext fun _ => rfl
  have hVV' : (V' : H₁ →ₗ[ℂ] H₂).compPMap hA.sqrt ≤ hB.sqrt.compNat (v.toPMap ⊤) := by
    rw [hV'r, LinearPMap.compPMap_comp, LinearPMap.compPMap_comp]
    calc u₂.compPMap (v.compPMap (u₁.compPMap hA.sqrt))
        ≤ u₂.compPMap (v.compPMap T₁) :=
          LinearPMap.compPMap_mono _ (LinearPMap.compPMap_mono _ hU₁)
      _ ≤ u₂.compPMap (T₂.compNat (v.toPMap ⊤)) := LinearPMap.compPMap_mono _ hV
      _ = (u₂.compPMap T₂).compNat (v.toPMap ⊤) := (LinearPMap.compPMap_compNat _ _ _).symm
      _ ≤ hB.sqrt.compNat (v.toPMap ⊤) := LinearPMap.compNat_mono hU₂ le_rfl
  obtain ⟨F, hFd, hFs, hFs', hFb, hF0, hF1⟩ := hA.exists_stripContinuation hB hVV'
  refine ⟨F, hFd, hFs, hFs', fun z hz => (hFb z hz).trans ?_, hF0, fun t x => ?_⟩
  · -- `‖V‖^{1 - 2y} ‖V'‖^{2y} ≤ ‖V‖^{1 - 2y} ‖V‖^{2y} = ‖V‖`
    have hy : 0 ≤ 2 * z.im := by linarith [hz.1]
    calc ‖V‖ ^ (1 - 2 * z.im) * ‖V'‖ ^ (2 * z.im) ≤ ‖V‖ ^ (1 - 2 * z.im) * ‖V‖ ^ (2 * z.im) :=
          mul_le_mul_of_nonneg_left (Real.rpow_le_rpow (norm_nonneg _) hnorm hy) (by positivity)
      _ = ‖V‖ := by rw [← Real.rpow_add' (norm_nonneg _) (by norm_num), sub_add_cancel,
          Real.rpow_one]
  · rw [hF1]
    rfl

/-- **Borchers' Theorem A for semilinear operators, polar decomposition form.** Let `T₁` on `H₁`
and `T₂` on `H₂` be closed `σ`-semilinear operators, with polar decompositions `Tᵢ = Jᵢ Δᵢ^{1/2}`:
`Δ₁ = T₁†T₁`, `Δ₂ = T₂†T₂` and the partial isometries `Jᵢ` (`IsSelfAdjoint.polarIsometry`). Let
`V` be a bounded operator with `V T₁ ⊆ T₂ V`. Then `t ↦ Δ₂^{-it} V Δ₁^{it}` extends to a family
`F z` of bounded operators on the strip `0 ≤ im z ≤ 1/2`, holomorphic in the operator norm in the
interior and `*`-strongly continuous on the closed strip, with `‖F z‖ ≤ ‖V‖` and
`F (t + i/2) = Δ₂^{-it} J₂† V J₁ Δ₁^{it}`, for the adjoint `J₂†` of `J₂`
(`ContinuousLinearMap.adjointₛₗ`), which inverts `J₂` on the range of `Δ₂^{1/2}`.

This is `IsSelfAdjoint.exists_stripContinuation_of_le` with `U₁ = J₁` and `U₂ = J₂†`:
`T₁ = J₁ Δ₁^{1/2}` and `Δ₂^{1/2} = J₂† T₂` hold for every polar decomposition
(`IsSelfAdjoint.eq_polarIsometry_compPMap`, `IsSelfAdjoint.adjointₛₗ_polarIsometry_compPMap`). For
the Tomita operators of standard subspaces, `J₂† = J₂` and it is Borchers' Theorem A
(`StandardSubspace.exists_modularGroup_continuation`); for relative Tomita operators,
`J₂† = J_{Ω₂,η₂}` and it is the relative version
(`VonNeumannAlgebra.exists_relativeModularGroup_continuation_of_le`). -/
theorem exists_stripContinuation_polarIsometry (hA : IsSelfAdjoint A) (hB : IsSelfAdjoint B)
    (hAT : A = T₁.adjointₛₗ.compNat T₁) (hBT : B = T₂.adjointₛₗ.compNat T₂)
    (hT₁ : T₁.IsClosedₛₗ) (hT₂ : T₂.IsClosedₛₗ) (V : H₁ →L[ℂ] H₂)
    (hV : (V : H₁ →ₗ[ℂ] H₂).compPMap T₁ ≤ T₂.compNat ((V : H₁ →ₗ[ℂ] H₂).toPMap ⊤)) :
    ∃ F : ℂ → H₁ →L[ℂ] H₂, DifferentiableOn ℂ F (im ⁻¹' Ioo 0 (1 / 2)) ∧
      (∀ x, ContinuousOn (fun z => F z x) (im ⁻¹' Icc 0 (1 / 2))) ∧
      (∀ y, ContinuousOn (fun z => ((F z)†) y) (im ⁻¹' Icc 0 (1 / 2))) ∧
      (∀ z ∈ im ⁻¹' Icc 0 (1 / 2), ‖F z‖ ≤ ‖V‖) ∧
      (∀ t : ℝ, F t = hB.imaginaryPower (-t) ∘L V ∘L hA.imaginaryPower t) ∧
      ∀ (t : ℝ) (x : H₁), F (t + I / 2) x =
        hB.imaginaryPower (-t) ((hB.polarIsometry hBT hT₂).adjointₛₗ
          (V (hA.polarIsometry hAT hT₁ (hA.imaginaryPower t x)))) :=
  hA.exists_stripContinuation_of_le hB (hA.polarIsometry hAT hT₁)
    (hB.polarIsometry hBT hT₂).adjointₛₗ (hA.norm_polarIsometry_le hAT hT₁)
    (hB.norm_adjointₛₗ_polarIsometry_le hBT hT₂)
    (hA.eq_polarIsometry_compPMap hAT hT₁).ge (hB.adjointₛₗ_polarIsometry_compPMap hBT hT₂).le V hV

end Semilinear

end IsSelfAdjoint
