/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import QuantumSystem.Analysis.SpectralTheory.SpectralTheorem
public import QuantumSystem.Analysis.SpectralTheory.ScalarSpectralMeasure
public import QuantumSystem.Analysis.SpectralTheory.UnitaryRepresentation
public import QuantumSystem.ForMathlib.MeasureTheory.Function.MemLpMulSelf

/-!
# Unitary groups, logarithms and complex powers of self-adjoint operators

For a self-adjoint operator `B` with projection-valued measure `E_B`, the **unitary group**
generated by `B` is `t ↦ e^{itB} = ∫ e^{itλ} dE_B(λ)` (`IsSelfAdjoint.unitaryGroup`), the Fourier
transform of `E_B` along the multiplication pairing of `ℝ`
(`MeasureTheory.ProjectionValuedMeasure.fourier`).

For a self-adjoint `A`, `log A = ∫ log λ dE_A(λ)` (`IsSelfAdjoint.logPMap`) and the complex
powers are `A^z = ∫_{(0,∞)} λ^z dE_A(λ)` (`IsSelfAdjoint.cpow`), with the **support convention**
`0^z = 0` of relative modular theory (Araki–Masuda, Connes' cocycle): `A^z` vanishes on
`E_A((-∞, 0]) E`, and `A^0 = E_A((0, ∞))` is the support projection of a positive `A`. For
positive `A`, `A^1 = A` (`IsSelfAdjoint.cpow_one`); for every self-adjoint `A`, `A^{1/2}` is the
square root `∫ √λ dE_A(λ)` (`IsSelfAdjoint.cpow_one_half`, `IsSelfAdjoint.sqrt`), the unique
positive square root when `A` is positive.

On the imaginary axis the powers are bounded, and `A^{it}` (`IsSelfAdjoint.cpow_ofReal_mul_I`) is
the bounded operator `IsSelfAdjoint.imaginaryPower t`: a partial isometry with initial and final
space `E_A((0, ∞)) E` (`IsSelfAdjoint.norm_imaginaryPower_apply`,
`IsSelfAdjoint.pvm_Ioi_imaginaryPower_apply`), with `A^{i(s+t)} = A^{is} A^{it}`
(`IsSelfAdjoint.imaginaryPower_add`) and `A^{i0} = E_A((0, ∞))`, strongly continuous in `t`
(`IsSelfAdjoint.continuous_imaginaryPower_apply`). It agrees with the unitary group `e^{it log A}`
exactly when `A` is positive and injective (`IsSelfAdjoint.imaginaryPower_eq_unitaryGroup_iff`),
and then forms a unitary group (`IsSelfAdjoint.imaginaryPowerGroup`); for a positive injective
`A`, whose projection-valued measure lives on `(0, ∞)` (`IsSelfAdjoint.measure_pvm_Iic_zero`),
also `A^z = e^{z log A}` (`IsSelfAdjoint.cpow_eq_integralPMap_exp_log`).

## Junk values

`Real.log` is extended by `log 0 = 0` and `log (-λ) = log λ`, so `log A` is defined for every
self-adjoint `A`. For a positive injective `A` the junk values sit on the `E_A`-null set `(-∞, 0]`
and do not affect anything; without positivity or injectivity `log A` is not the logarithm of `A`
in any useful sense (for instance `A = 0` gives `log A = 0`, whose unitary group is `1`, while
`A^{it} = 0`). The powers `A^z`, the square root and the imaginary powers instead vanish on
`E_A((-∞, 0]) E` and only see the positive part of `A`.

The name `logPMap` keeps this unbounded operator apart from Mathlib's lemma `IsSelfAdjoint.log`
(on the continuous functional calculus).

## Main definitions

* `MeasureTheory.ProjectionValuedMeasure.cpow P z`, `MeasureTheory.ProjectionValuedMeasure.sqrt P`,
  `MeasureTheory.ProjectionValuedMeasure.imaginaryPower P t` — `∫_{(0,∞)} λ^z dP(λ)`,
  `∫ √λ dP(λ)` and the bounded `∫_{(0,∞)} λ^{it} dP(λ)` for a projection-valued measure `P` on
  `ℝ`; the operator versions below are these for `P = E_A`.
* `IsSelfAdjoint.unitaryGroup hB` — the strongly continuous unitary group `t ↦ e^{itB}`.
* `IsSelfAdjoint.logPMap hA` — `log A`.
* `IsSelfAdjoint.cpow hA z` — `A^z = ∫_{(0,∞)} λ^z dE_A(λ)`.
* `IsSelfAdjoint.imaginaryPower hA t` — `A^{it}` as a bounded operator.
* `IsSelfAdjoint.imaginaryPowerGroup hA hpos hinj` — for a positive injective `A`, the unitary
  group `t ↦ A^{it}`.
* `IsSelfAdjoint.sqrt hA` — `A^{1/2} = ∫ √λ dE_A(λ)`, vanishing on `E_A((-∞, 0]) E`.

## Main results

* `IsSelfAdjoint.coe_unitaryGroup_apply` — `e^{itB} = ∫ e^{itλ} dE_B(λ)`.
* `IsSelfAdjoint.continuous_unitaryGroup_apply`,
  `IsSelfAdjoint.isStronglyContinuous_unitaryGroup` — strong continuity.
* `IsSelfAdjoint.isSelfAdjoint_logPMap`, `IsSelfAdjoint.pvm_logPMap` — `log A` is self-adjoint with
  projection-valued measure `log_* E_A`.
* `IsSelfAdjoint.cpow_one` — `A^1 = A` for positive `A`.
* `IsSelfAdjoint.cpow_one_half` — `A^{1/2}` is the square root.
* `IsSelfAdjoint.cpow_ofReal_mul_I` — `A^{it}` is the bounded imaginary power.
* `IsSelfAdjoint.measure_pvm_Iic_zero`, `IsSelfAdjoint.pvm_Iic_eq_zero`, `IsSelfAdjoint.pvm_Ioi_eq_one`,
  `IsSelfAdjoint.ker_sqrt_eq_bot` — a positive injective `A` has `E_A((-∞, 0]) = 0`,
  `E_A((0, ∞)) = 1` and injective square root.
* `IsSelfAdjoint.cpow_eq_integralPMap_exp_log` — for positive injective `A`, `A^z = e^{z log A}`.
* `IsSelfAdjoint.coe_unitaryGroup_logPMap_apply` — `e^{it log A} = ∫ e^{it log λ} dE_A(λ)`.
* `MeasureTheory.ProjectionValuedMeasure.star_imaginaryPower` — `(λ^{it})⋆ = λ^{-it}`.
* `IsSelfAdjoint.imaginaryPower_add` — `A^{i(s+t)} = A^{is} A^{it}`.
* `IsSelfAdjoint.norm_imaginaryPower_apply`, `IsSelfAdjoint.imaginaryPower_zero` — `A^{it}` is a
  partial isometry, `‖A^{it} x‖ = ‖E_A((0, ∞)) x‖`, and `A^{i0} = E_A((0, ∞))`.
* `IsSelfAdjoint.imaginaryPower_eq_unitaryGroup`, `IsSelfAdjoint.imaginaryPower_eq_unitaryGroup_iff`
  — `A^{it} = e^{it log A}` exactly for positive injective `A`.
* `IsSelfAdjoint.pvm_Ioi_eq_starProjection_orthogonal` — for positive `A`, `E_A((0, ∞))` is the
  projection onto `(ker A)ᗮ`.
* `IsSelfAdjoint.imaginaryPower_eq_unitaryGroup_mul`, `IsSelfAdjoint.pvm_Ioi_imaginaryPower_apply`
  — `A^{it} = e^{it log A} E_A((0, ∞))`, with final space `E_A((0, ∞)) E`.
* `IsSelfAdjoint.continuous_imaginaryPower_apply`,
  `IsSelfAdjoint.isStronglyContinuous_imaginaryPowerGroup` — strong continuity of `t ↦ A^{it}`.
* `IsSelfAdjoint.sqrt_compNat_sqrt`, `IsSelfAdjoint.eq_sqrt_of_compNat_self_eq` — for positive
  `A`, `A^{1/2}` is the unique positive self-adjoint square root of `A`.

## References

* H. Araki, T. Masuda, *Positive cones and Lp-spaces for von Neumann algebras*,
  Publ. RIMS 18 (1982) — the support convention for `Δ_{η,ξ}^z`.
* A. Connes, *Une classification des facteurs de type III*, Ann. Sci. ENS 6 (1973) — the cocycle
  `(Dη : Dξ)_t`.
* K. Schmüdgen, *Unbounded Self-adjoint Operators on Hilbert Space*, GTM 265 (2012), §5.
-/

@[expose] public section

open Set Filter Topology MeasureTheory Complex
open scoped InnerProductSpace ComplexConjugate LinearPMap

namespace MeasureTheory.ProjectionValuedMeasure

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  (P : ProjectionValuedMeasure ℝ H)

/-! ### Square roots and imaginary powers of a projection-valued measure -/

/-- The **square root** `∫ √λ dP(λ)` of the self-adjoint operator `∫ λ dP(λ)`, with Mathlib's
`√λ = 0` for `λ ≤ 0` (`IsSelfAdjoint.sqrt`). -/
noncomputable def sqrt : H →ₗ.[ℂ] H :=
  P.integralPMap fun t : ℝ => (Real.sqrt t : ℂ)

/-- The **complex powers** `∫_{(0,∞)} λ^z dP(λ)` of the self-adjoint operator `∫ λ dP(λ)`, with
Mathlib's principal power `λ^z` for `λ > 0` and the support convention `0^z = 0` for every `z`
(`IsSelfAdjoint.cpow`). -/
noncomputable def cpow (z : ℂ) : H →ₗ.[ℂ] H :=
  P.integralPMap ((Ioi 0).indicator fun s : ℝ => (s : ℂ) ^ z)

/-- The **imaginary powers** `∫_{(0,∞)} λ^{it} dP(λ)` of the self-adjoint operator `∫ λ dP(λ)`,
with `λ^{it} = e^{it log λ}` for `λ > 0` and `0^{it} = 0` (`IsSelfAdjoint.imaginaryPower`). -/
noncomputable def imaginaryPower (t : ℝ) : H →L[ℂ] H :=
  P.integral ((Ioi 0).indicator fun s : ℝ => cexp (t * Real.log s * I))

/-- The integrand of `λ^{it}` is measurable. -/
lemma measurable_indicator_exp_log (t : ℝ) :
    Measurable ((Ioi 0).indicator fun s : ℝ => cexp (t * Real.log s * I)) :=
  Measurable.indicator (by fun_prop) measurableSet_Ioi

/-- The integrand of `λ^{it}` has modulus `1` on `(0, ∞)` and `0` elsewhere. -/
lemma norm_indicator_exp_log (t s : ℝ) :
    ‖(Ioi 0).indicator (fun s : ℝ => cexp (t * Real.log s * I)) s‖ =
      (Ioi 0).indicator (1 : ℝ → ℝ) s := by
  by_cases hs : s ∈ Ioi 0
  · rw [indicator_of_mem hs, indicator_of_mem hs, Pi.one_apply, ← ofReal_mul, norm_exp_ofReal_mul_I]
  · rw [indicator_of_notMem hs, indicator_of_notMem hs, norm_zero]

/-- The integrand of `λ^{it}` is bounded by `1`. -/
lemma norm_indicator_exp_log_le (t s : ℝ) :
    ‖(Ioi 0).indicator (fun s : ℝ => cexp (t * Real.log s * I)) s‖ ≤ 1 := by
  rw [norm_indicator_exp_log]
  by_cases hs : s ∈ Ioi 0 <;> simp [hs]

/-- **`(λ^{it})⋆ = λ^{-it}`**: `(∫_{(0,∞)} λ^{it} dP)⋆ = ∫_{(0,∞)} λ^{-it} dP`. -/
lemma star_imaginaryPower (t : ℝ) :
    star (P.imaginaryPower t) = P.imaginaryPower (-t) := by
  rw [imaginaryPower, P.star_integral (measurable_indicator_exp_log t) ⟨1, norm_indicator_exp_log_le t⟩,
    imaginaryPower]
  congr 1
  funext s
  by_cases hs : s ∈ Ioi (0 : ℝ)
  · simp only [indicator_of_mem hs, ← Complex.exp_conj]
    congr 1
    simp only [map_mul, conj_ofReal, conj_I, ofReal_neg]
    ring
  · simp [indicator_of_notMem hs]

/-- **`λ^{i(s+t)} = λ^{is} λ^{it}`**: `∫_{(0,∞)} λ^{i(s+t)} dP = (∫_{(0,∞)} λ^{is} dP)
(∫_{(0,∞)} λ^{it} dP)`. -/
lemma imaginaryPower_add (s t : ℝ) :
    P.imaginaryPower (s + t) = P.imaginaryPower s * P.imaginaryPower t := by
  rw [imaginaryPower, imaginaryPower, imaginaryPower,
    ← P.integral_mul (measurable_indicator_exp_log s) ⟨1, norm_indicator_exp_log_le s⟩
      (measurable_indicator_exp_log t) ⟨1, norm_indicator_exp_log_le t⟩]
  congr 1
  funext x
  by_cases hx : x ∈ Ioi (0 : ℝ)
  · simp only [Pi.mul_apply, indicator_of_mem hx, ← Complex.exp_add]
    congr 1
    push_cast
    ring
  · simp [indicator_of_notMem hx]

end MeasureTheory.ProjectionValuedMeasure

namespace IsSelfAdjoint

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E] [CompleteSpace E]
  {A B : E →ₗ.[ℂ] E}

/-! ### The unitary group generated by a self-adjoint operator -/

/-- The **unitary group** `t ↦ e^{itB} = ∫ e^{itλ} dE_B(λ)` generated by a self-adjoint operator
`B`: the Fourier transform of its projection-valued measure along the multiplication of `ℝ`. -/
noncomputable def unitaryGroup (hB : IsSelfAdjoint B) : AddChar ℝ (unitary (E →L[ℂ] E)) :=
  hB.pvm.fourier (LinearMap.mul ℝ ℝ) fun t => by simpa using measurable_id.mul_const t

variable (hB : IsSelfAdjoint B) (hA : IsSelfAdjoint A)

/-- `e^{itB} = ∫ e^{itλ} dE_B(λ)`. -/
lemma coe_unitaryGroup_apply (t : ℝ) :
    (hB.unitaryGroup t : E →L[ℂ] E) = hB.pvm.integral fun s : ℝ => cexp (t * s * I) := by
  rw [unitaryGroup, ProjectionValuedMeasure.coe_fourier_apply]
  congr 1
  ext s
  simp [mul_comm]

/-- **Strong continuity** of `t ↦ e^{itB}`. -/
lemma continuous_unitaryGroup_apply (y : E) :
    Continuous fun t => (hB.unitaryGroup t : E →L[ℂ] E) y :=
  hB.pvm.continuous_fourier_apply _ _ (fun s => by simpa using continuous_const_mul s) y

/-- **Strong continuity** of `t ↦ e^{itB}`, as a unitary representation. -/
lemma isStronglyContinuous_unitaryGroup : hB.unitaryGroup.IsStronglyContinuous :=
  hB.pvm.isStronglyContinuous_fourier _ _ fun s => by simpa using continuous_const_mul s

/-! ### Logarithms and complex powers -/

/-- The **logarithm** `log A = ∫ log λ dE_A(λ)` of a self-adjoint operator, with Mathlib's junk
values `log 0 = 0` and `log (-λ) = log λ`; it is the logarithm of `A` when `A` is positive and
injective (`IsSelfAdjoint.measure_pvm_Iic_zero`). -/
noncomputable def logPMap : E →ₗ.[ℂ] E :=
  hA.pvm.integralPMap fun s : ℝ => (Real.log s : ℂ)

/-- `log A` is self-adjoint. -/
lemma isSelfAdjoint_logPMap : IsSelfAdjoint hA.logPMap :=
  hA.pvm.isSelfAdjoint_integralPMap_ofReal Real.measurable_log

/-- The projection-valued measure of `log A` is the image of `E_A` under `log`. -/
lemma pvm_logPMap : hA.isSelfAdjoint_logPMap.pvm = hA.pvm.map Real.log Real.measurable_log :=
  hA.pvm.pvm_integralPMap_ofReal Real.measurable_log

/-- The **complex powers** `A^z = ∫_{(0,∞)} λ^z dE_A(λ)` of a self-adjoint operator, with the
support convention `0^z = 0` for every `z` (Araki–Masuda): `A^z` vanishes on `E_A((-∞, 0]) E`, so
that `A^0 = E_A((0, ∞))` is the support projection of a positive `A`, `A^1 = A` for positive `A`
(`IsSelfAdjoint.cpow_one`), `A^{1/2}` is the square root (`IsSelfAdjoint.cpow_one_half`) and
`A^{it}` is the imaginary power (`IsSelfAdjoint.cpow_ofReal_mul_I`). -/
noncomputable def cpow (z : ℂ) : E →ₗ.[ℂ] E :=
  hA.pvm.cpow z

/-- For a positive `A`, `A^1 = A`. -/
lemma cpow_one (hpos : A.IsPositive) : hA.cpow 1 = A := by
  rw [cpow, ProjectionValuedMeasure.cpow,
    hA.pvm.integralPMap_congr_ae (Measurable.indicator (by fun_prop) measurableSet_Ioi)
      Complex.measurable_ofReal fun y => (hA.ae_nonneg_measure_pvm y hpos).mono fun s hs => ?_]
  · exact hA.eq_integralPMap_pvm.symm
  · rcases hs.lt_or_eq with hs | rfl
    · simp [indicator_of_mem (mem_Ioi.mpr hs)]
    · simp

/-- The imaginary powers `A^{it} = e^{it log A} = ∫ e^{it log λ} dE_A(λ)`. -/
lemma coe_unitaryGroup_logPMap_apply (t : ℝ) :
    (hA.isSelfAdjoint_logPMap.unitaryGroup t : E →L[ℂ] E) =
      hA.pvm.integral fun s : ℝ => cexp (t * Real.log s * I) := by
  rw [coe_unitaryGroup_apply, pvm_logPMap, ProjectionValuedMeasure.integral_map (by fun_prop)
    ⟨1, fun s => by rw [← ofReal_mul, norm_exp_ofReal_mul_I]⟩ Real.measurable_log]
  rfl

/-- A positive injective self-adjoint operator has its spectral measures on `(0, ∞)`. -/
lemma measure_pvm_Iic_zero (hpos : A.IsPositive) (hinj : A.ker = ⊥)
    (y : E) : hA.pvm.measure y (Iic 0) = 0 := by
  have h0 : hA.pvm.measure y {0} = 0 := by
    rw [hA.measure_pvm_singleton_eq_zero_iff]
    have hbot : hA.isClosed.eigenspace ((0 : ℝ) : ℂ) = ⊥ := by
      refine eq_bot_iff.mpr fun u hu => ?_
      rw [LinearPMap.IsClosed.mem_eigenspace_iff, ofReal_zero, zero_smul] at hu
      rw [LinearPMap.ker_eq_bot_iff_mem_graph.mp hinj u hu]
      exact zero_mem _
    rw [hbot]
    simp
  rw [← Iio_union_right, measure_union_null (hA.measure_pvm_Iio_zero y hpos) h0]

/-- A positive injective self-adjoint operator has `E_A((-∞, 0]) = 0`. -/
lemma pvm_Iic_eq_zero (hpos : A.IsPositive) (hinj : A.ker = ⊥) : hA.pvm (Iic 0) = 0 :=
  (hA.pvm.apply_eq_zero_iff measurableSet_Iic).mpr (hA.measure_pvm_Iic_zero hpos hinj)

/-- A positive injective self-adjoint operator has `E_A((0, ∞)) = 1`. -/
lemma pvm_Ioi_eq_one (hpos : A.IsPositive) (hinj : A.ker = ⊥) : hA.pvm (Ioi 0) = 1 := by
  have h := hA.pvm.apply_union (Set.Iic_disjoint_Ioi (le_refl (0 : ℝ))).symm measurableSet_Ioi
    measurableSet_Iic
  rwa [Ioi_union_Iic, ProjectionValuedMeasure.apply_univ, hA.pvm_Iic_eq_zero hpos hinj, add_zero,
    eq_comm] at h

/-- For a positive injective `A`, `A^z = e^{z log A} = ∫ e^{z log λ} dE_A(λ)`. -/
lemma cpow_eq_integralPMap_exp_log (hpos : A.IsPositive) (hinj : A.ker = ⊥) (z : ℂ) :
    hA.cpow z = hA.pvm.integralPMap fun s : ℝ => cexp (z * Real.log s) := by
  refine ProjectionValuedMeasure.integralPMap_congr_ae _
    (Measurable.indicator (by fun_prop) measurableSet_Ioi) (by fun_prop) fun y => ?_
  have h := measure_eq_zero_iff_ae_notMem.mp (hA.measure_pvm_Iic_zero hpos hinj y)
  refine h.mono fun s hs => ?_
  have hs : 0 < s := not_le.mp hs
  change (Ioi 0).indicator (fun s : ℝ => (s : ℂ) ^ z) s = cexp (z * Real.log s)
  rw [indicator_of_mem (mem_Ioi.mpr hs), cpow_def_of_ne_zero (ofReal_ne_zero.mpr hs.ne'),
    ← ofReal_log hs.le, mul_comm]

/-- The **imaginary powers** `t ↦ A^{it} = ∫_{(0,∞)} λ^{it} dE_A(λ)` of a self-adjoint operator, as
bounded operators, with `λ^{it} = e^{it log λ}` for `λ > 0` and `0^{it} = 0`, so that `A^{it}` is
the complex power `IsSelfAdjoint.cpow (t * I)` (`IsSelfAdjoint.cpow_ofReal_mul_I`): a partial
isometry with initial and final space `E_A((0, ∞)) E` (`IsSelfAdjoint.norm_imaginaryPower_apply`,
`IsSelfAdjoint.pvm_Ioi_imaginaryPower_apply`), strongly continuous in `t`
(`IsSelfAdjoint.continuous_imaginaryPower_apply`), and for a positive injective `A` the family is
the unitary group generated by `log A` (`IsSelfAdjoint.imaginaryPower_eq_unitaryGroup`). For a
positive `A` with a kernel this is the family of the literature (Araki–Masuda's `Δ_{η,ξ}^{it}` for
vectors that are not cyclic and separating, Connes' cocycle `(Dη : Dξ)_t = Δ_{η,ξ}^{it} Δ_ξ^{-it}`),
which vanishes on `ker A`, whereas the unitary group of `log A` is the identity there (`Real.log 0 = 0`). -/
noncomputable def imaginaryPower (t : ℝ) : E →L[ℂ] E :=
  hA.pvm.imaginaryPower t

/-- **`A^{it}` as a complex power**: the complex power `A^{it}` (`IsSelfAdjoint.cpow`) is the
bounded imaginary power. -/
lemma cpow_ofReal_mul_I (t : ℝ) :
    hA.cpow (t * I) = (hA.imaginaryPower t : E →ₗ[ℂ] E).toPMap ⊤ := by
  have h : ((Ioi 0).indicator fun s : ℝ => (s : ℂ) ^ ((t : ℂ) * I)) =
      (Ioi 0).indicator fun s : ℝ => cexp (t * Real.log s * I) := by
    funext s
    by_cases hs : s ∈ Ioi (0 : ℝ)
    · rw [indicator_of_mem hs, indicator_of_mem hs, cpow_def_of_ne_zero (ofReal_ne_zero.mpr
        (ne_of_gt hs)), ← ofReal_log (le_of_lt hs)]
      ring_nf
    · rw [indicator_of_notMem hs, indicator_of_notMem hs]
  rw [cpow, ProjectionValuedMeasure.cpow, h, imaginaryPower, ProjectionValuedMeasure.imaginaryPower,
    ProjectionValuedMeasure.integralPMap_eq_toPMap _
      (ProjectionValuedMeasure.measurable_indicator_exp_log t)
      ⟨1, ProjectionValuedMeasure.norm_indicator_exp_log_le t⟩]

/-- **`A^{it}` is a partial isometry** with initial space `E_A((0, ∞)) E`:
`‖A^{it} x‖ = ‖E_A((0, ∞)) x‖`. -/
lemma norm_imaginaryPower_apply (t : ℝ) (x : E) :
    ‖hA.imaginaryPower t x‖ = ‖hA.pvm (Ioi 0) x‖ := by
  refine (pow_left_inj₀ (norm_nonneg _) (norm_nonneg _) two_ne_zero).mp ?_
  rw [imaginaryPower, ProjectionValuedMeasure.imaginaryPower,
    hA.pvm.norm_integral_apply_sq (ProjectionValuedMeasure.measurable_indicator_exp_log t)
      ⟨1, ProjectionValuedMeasure.norm_indicator_exp_log_le t⟩,
    ← hA.pvm.measureReal_apply x measurableSet_Ioi, ← integral_indicator_one measurableSet_Ioi]
  refine integral_congr_ae (Eventually.of_forall fun s => ?_)
  change ‖_‖ ^ 2 = _
  rw [ProjectionValuedMeasure.norm_indicator_exp_log]
  by_cases hs : s ∈ Ioi 0 <;> simp [hs]

/-- For a positive injective `A`, the imaginary powers `A^{it}` are the unitary group generated by
`log A`. -/
lemma imaginaryPower_eq_unitaryGroup (hpos : A.IsPositive) (hinj : A.ker = ⊥) (t : ℝ) :
    hA.imaginaryPower t = (hA.isSelfAdjoint_logPMap.unitaryGroup t : E →L[ℂ] E) := by
  rw [coe_unitaryGroup_logPMap_apply, imaginaryPower, ProjectionValuedMeasure.imaginaryPower]
  refine ProjectionValuedMeasure.integral_congr_ae _
    (ProjectionValuedMeasure.measurable_indicator_exp_log t) (by fun_prop)
    fun y => ?_
  have h := measure_eq_zero_iff_ae_notMem.mp (hA.measure_pvm_Iic_zero hpos hinj y)
  exact h.mono fun s hs => indicator_of_mem (mem_Ioi.mpr (not_le.mp hs)) _

/-- **Group law** `A^{i(s+t)} = A^{is} A^{it}` for every self-adjoint `A`: the imaginary powers form
a group of partial isometries on `E_A((0, ∞)) E`, with unit `A^{i0} = E_A((0, ∞))`
(`IsSelfAdjoint.imaginaryPower_zero`). -/
lemma imaginaryPower_add (s t : ℝ) :
    hA.imaginaryPower (s + t) = hA.imaginaryPower s * hA.imaginaryPower t :=
  hA.pvm.imaginaryPower_add s t

/-- `A^{i0} = E_A((0, ∞))`, the support projection of a positive `A`. -/
lemma imaginaryPower_zero : hA.imaginaryPower 0 = hA.pvm (Ioi 0) := by
  rw [imaginaryPower, ProjectionValuedMeasure.imaginaryPower,
    ← hA.pvm.integral_indicator_one measurableSet_Ioi]
  congr 1
  ext s
  simp [Pi.one_def]

/-- For a positive `A`, the support projection `E_A((0, ∞))` is the projection onto `(ker A)ᗮ`, the
orthogonal complement of the eigenspace `ker (A - 0)` (`IsSelfAdjoint.pvm_singleton`). -/
lemma pvm_Ioi_eq_starProjection_orthogonal (hpos : A.IsPositive) :
    hA.pvm (Ioi 0) = A.kerᗮ.starProjection := by
  have hk : (hA.isClosed.eigenspace ((0 : ℝ) : ℂ)).toSubmodule = A.ker := by
    ext u
    rw [ClosedSubmodule.mem_toSubmodule_iff, LinearPMap.IsClosed.mem_eigenspace_iff, ofReal_zero,
      zero_smul]
    simp [LinearPMap.mem_ker_iff, LinearPMap.mem_graph_iff, eq_comm]
  simp_rw [← hk]
  have hu := hA.pvm.apply_union (Iic_disjoint_Ioi (le_refl (0 : ℝ))).symm measurableSet_Ioi
    measurableSet_Iic
  have hIic := hA.pvm.apply_union (s := Iio (0 : ℝ)) (t := {0})
    (Set.disjoint_singleton_right.mpr (lt_irrefl 0)) measurableSet_Iio (measurableSet_singleton 0)
  rw [Iio_union_right, (hA.isPositive_iff_pvm_Iio_eq_zero).mp hpos, zero_add,
    hA.pvm_singleton] at hIic
  rw [Ioi_union_Iic, ProjectionValuedMeasure.apply_univ, hIic] at hu
  rw [Submodule.starProjection_orthogonal', hu, add_sub_cancel_right]

/-- The imaginary powers `A^{it}` are the unitary group generated by `log A` **exactly** for a
positive injective `A`: conversely, `A^{i0} = E_A((0, ∞))` must be `1`, so `E_A((-∞, 0]) = 0`. -/
lemma imaginaryPower_eq_unitaryGroup_iff :
    (∀ t, hA.imaginaryPower t = (hA.isSelfAdjoint_logPMap.unitaryGroup t : E →L[ℂ] E)) ↔
      A.IsPositive ∧ A.ker = ⊥ := by
  refine ⟨fun h => ?_, fun ⟨hpos, hinj⟩ => hA.imaginaryPower_eq_unitaryGroup hpos hinj⟩
  have h1 : hA.pvm (Ioi 0) = 1 := by
    rw [← imaginaryPower_zero, h 0, AddChar.map_zero_eq_one, OneMemClass.coe_one]
  have hIic : hA.pvm (Iic 0) = 0 := by
    have hu := hA.pvm.apply_union (Iic_disjoint_Ioi (le_refl (0 : ℝ))).symm measurableSet_Ioi
      measurableSet_Iic
    rwa [Ioi_union_Iic, ProjectionValuedMeasure.apply_univ, h1, left_eq_add] at hu
  have hm : ∀ y, hA.pvm.measure y (Iic 0) = 0 := fun y => by
    rw [hA.pvm.measure_apply y measurableSet_Iic, hIic]
    simp
  refine ⟨(hA.isPositive_iff_pvm_Iio_eq_zero).mpr ((hA.pvm.apply_eq_zero_iff measurableSet_Iio).mpr
    fun y => measure_mono_null Iio_subset_Iic_self (hm y)),
    LinearPMap.ker_eq_bot_iff_mem_graph.mpr fun u hu => ?_⟩
  have he : u ∈ hA.isClosed.eigenspace ((0 : ℝ) : ℂ) := by
    rwa [LinearPMap.IsClosed.mem_eigenspace_iff, ofReal_zero, zero_smul]
  have h0 := (hA.measure_pvm_singleton_eq_zero_iff u 0).mp
    (measure_mono_null (singleton_subset_iff.mpr (mem_Iic.mpr le_rfl)) (hm u))
  rwa [Submodule.starProjection_eq_self_iff.mpr he] at h0

/-- `A^{it} = e^{it log A} E_A((0, ∞))`: the imaginary powers are the unitary group of `log A`
cut down to the support `E_A((0, ∞)) E`. -/
lemma imaginaryPower_eq_unitaryGroup_mul (t : ℝ) :
    hA.imaginaryPower t =
      (hA.isSelfAdjoint_logPMap.unitaryGroup t : E →L[ℂ] E) * hA.pvm (Ioi 0) := by
  rw [coe_unitaryGroup_logPMap_apply, ← hA.pvm.integral_indicator_one measurableSet_Ioi,
    ← hA.pvm.integral_mul (by fun_prop) ⟨1, fun s => by rw [← ofReal_mul, norm_exp_ofReal_mul_I]⟩
      (measurable_one.indicator measurableSet_Ioi)
      ⟨1, fun s => by by_cases hs : s ∈ Ioi (0 : ℝ) <;> simp [hs]⟩,
    imaginaryPower, ProjectionValuedMeasure.imaginaryPower]
  congr 1
  ext s
  by_cases hs : s ∈ Ioi (0 : ℝ) <;> simp [hs]

/-- `E_A((0, ∞)) A^{it} = A^{it}`. -/
lemma pvm_Ioi_mul_imaginaryPower (t : ℝ) :
    hA.pvm (Ioi 0) * hA.imaginaryPower t = hA.imaginaryPower t := by
  rw [imaginaryPower, ProjectionValuedMeasure.imaginaryPower,
    ← hA.pvm.integral_indicator_one measurableSet_Ioi,
    ← hA.pvm.integral_mul (measurable_one.indicator measurableSet_Ioi)
      ⟨1, fun s => by by_cases hs : s ∈ Ioi (0 : ℝ) <;> simp [hs]⟩
      (ProjectionValuedMeasure.measurable_indicator_exp_log t)
      ⟨1, ProjectionValuedMeasure.norm_indicator_exp_log_le t⟩]
  congr 1
  ext s
  by_cases hs : s ∈ Ioi (0 : ℝ) <;> simp [hs]

/-- **`A^{it}` has final space `E_A((0, ∞)) E`**: `E_A((0, ∞)) (A^{it} x) = A^{it} x`. -/
lemma pvm_Ioi_imaginaryPower_apply (t : ℝ) (x : E) :
    hA.pvm (Ioi 0) (hA.imaginaryPower t x) = hA.imaginaryPower t x :=
  congrArg (· x) (hA.pvm_Ioi_mul_imaginaryPower t)

/-- **Strong continuity** of `t ↦ A^{it}`. -/
lemma continuous_imaginaryPower_apply (x : E) :
    Continuous fun t => hA.imaginaryPower t x := by
  simp_rw [imaginaryPower_eq_unitaryGroup_mul, mul_apply_eq_comp]
  exact hA.isSelfAdjoint_logPMap.continuous_unitaryGroup_apply _

/-- For a positive injective `A`, the imaginary powers `t ↦ A^{it}` as a unitary group: the
unitary group generated by `log A` (`IsSelfAdjoint.imaginaryPower_eq_unitaryGroup`), with
`A^{it}` itself as its value at `t` (`IsSelfAdjoint.coe_imaginaryPowerGroup_apply`). -/
noncomputable def imaginaryPowerGroup (hpos : A.IsPositive) (hinj : A.ker = ⊥) :
    AddChar ℝ (unitary (E →L[ℂ] E)) where
  toFun t := ⟨hA.imaginaryPower t, by
    rw [hA.imaginaryPower_eq_unitaryGroup hpos hinj]
    exact (hA.isSelfAdjoint_logPMap.unitaryGroup t).2⟩
  map_zero_eq_one' := Subtype.ext <| by
    change hA.imaginaryPower 0 = 1
    rw [hA.imaginaryPower_eq_unitaryGroup hpos hinj, AddChar.map_zero_eq_one, OneMemClass.coe_one]
  map_add_eq_mul' s t := Subtype.ext <| by
    change hA.imaginaryPower (s + t) = hA.imaginaryPower s * hA.imaginaryPower t
    simp only [hA.imaginaryPower_eq_unitaryGroup hpos hinj, AddChar.map_add_eq_mul]
    rfl

/-- The unitary `A^{it}` of `IsSelfAdjoint.imaginaryPowerGroup` is `A^{it}`. -/
@[simp]
lemma coe_imaginaryPowerGroup_apply (hpos : A.IsPositive) (hinj : A.ker = ⊥) (t : ℝ) :
    (hA.imaginaryPowerGroup hpos hinj t : E →L[ℂ] E) = hA.imaginaryPower t :=
  rfl

/-- **Strong continuity** of the unitary group `t ↦ A^{it}`. -/
lemma isStronglyContinuous_imaginaryPowerGroup (hpos : A.IsPositive) (hinj : A.ker = ⊥) :
    (hA.imaginaryPowerGroup hpos hinj).IsStronglyContinuous :=
  AddChar.isStronglyContinuous_iff.mpr hA.continuous_imaginaryPower_apply

/-! ### Square roots -/

/-- The **square root** `A^{1/2} = ∫ √λ dE_A(λ)` of a self-adjoint operator, with Mathlib's
`√λ = 0` for `λ ≤ 0`, so that it vanishes on `E_A((-∞, 0]) E` and is the complex power
`A^{1/2}` (`IsSelfAdjoint.cpow_one_half`); it is positive and self-adjoint for every self-adjoint
`A`, and the positive square root of `A` when `A` is positive (`IsSelfAdjoint.sqrt_compNat_sqrt`,
`IsSelfAdjoint.eq_sqrt_of_compNat_self_eq`). -/
noncomputable def sqrt : E →ₗ.[ℂ] E :=
  hA.pvm.sqrt

/-- The square root of a self-adjoint operator is self-adjoint. -/
lemma isSelfAdjoint_sqrt : IsSelfAdjoint hA.sqrt :=
  hA.pvm.isSelfAdjoint_integralPMap_ofReal Real.continuous_sqrt.measurable

/-- The square root of a self-adjoint operator is positive. -/
lemma isPositive_sqrt : hA.sqrt.IsPositive :=
  hA.pvm.isPositive_integralPMap_ofReal Real.continuous_sqrt.measurable Real.sqrt_nonneg

/-- The square root of a positive injective self-adjoint operator is injective. -/
lemma ker_sqrt_eq_bot (hpos : A.IsPositive) (hinj : A.ker = ⊥) : hA.sqrt.ker = ⊥ :=
  hA.pvm.ker_integralPMap_eq_bot (Complex.measurable_ofReal.comp Real.continuous_sqrt.measurable)
    fun y => (measure_eq_zero_iff_ae_notMem.mp (hA.measure_pvm_Iic_zero hpos hinj y)).mono
      fun _ ht => ofReal_ne_zero.mpr (Real.sqrt_pos.mpr (not_le.mp ht)).ne'

/-- The square root is the complex power `A^{1/2}`. -/
lemma cpow_one_half : hA.cpow (1 / 2) = hA.sqrt := by
  rw [cpow, ProjectionValuedMeasure.cpow, sqrt, ProjectionValuedMeasure.sqrt]
  congr 1
  funext s
  by_cases hs : s ∈ Ioi (0 : ℝ)
  · rw [indicator_of_mem hs, Real.sqrt_eq_rpow, ofReal_cpow (le_of_lt hs)]
    norm_num
  · rw [indicator_of_notMem hs, Real.sqrt_eq_zero'.mpr (not_lt.mp hs), ofReal_zero]

include hA in
/-- For a positive self-adjoint `A`, `A^{1/2} A^{1/2} = A`. -/
lemma sqrt_compNat_sqrt (hpos : A.IsPositive) : hA.sqrt.compNat hA.sqrt = A := by
  have hm : Measurable fun t : ℝ => (Real.sqrt t : ℂ) :=
    Complex.measurable_ofReal.comp Real.continuous_sqrt.measurable
  rw [sqrt, ProjectionValuedMeasure.sqrt, hA.pvm.compNat_integralPMap hm hm fun y h => memLp_of_memLp_mul_self hm h,
    hA.pvm.integralPMap_congr_ae (hm.mul hm) Complex.measurable_ofReal fun y =>
      (hA.ae_nonneg_measure_pvm y hpos).mono fun t ht => ?_]
  · exact hA.eq_integralPMap_pvm.symm
  · simp only [Pi.mul_apply, ← ofReal_mul, Real.mul_self_sqrt ht]

include hA in
/-- **Uniqueness of the positive square root**: a positive self-adjoint `B` with `B B = A` is
`A^{1/2}`. -/
theorem eq_sqrt_of_compNat_self_eq (hB : IsSelfAdjoint B) (hBpos : B.IsPositive)
    (h : B.compNat B = A) : B = hA.sqrt := by
  set F := hB.pvm
  have hid : Measurable fun t : ℝ => (t : ℂ) := Complex.measurable_ofReal
  have hsq : Measurable fun t : ℝ => t ^ 2 := measurable_id.pow_const 2
  -- `A = ∫ λ² dE_B(λ)`, so `E_A = (λ ↦ λ²)_* E_B`
  have hA' : A = (F.map (fun t : ℝ => t ^ 2) hsq).integralPMap fun t => (t : ℂ) := by
    rw [← h, hB.eq_integralPMap_pvm, F.compNat_integralPMap hid hid fun y h =>
      memLp_of_memLp_mul_self hid h, ProjectionValuedMeasure.integralPMap_map hsq _ hid]
    congr 1
    ext t
    simp [sq]
  have hpvm := hA.eq_pvm_of_eq_integralPMap _ hA'
  rw [sqrt, ProjectionValuedMeasure.sqrt, ← hpvm, ProjectionValuedMeasure.integralPMap_map hsq _
    (f := fun t : ℝ => (Real.sqrt t : ℂ))
    (Complex.measurable_ofReal.comp Real.continuous_sqrt.measurable)]
  conv_lhs => rw [hB.eq_integralPMap_pvm]
  refine F.integralPMap_congr_ae hid (by fun_prop) fun y =>
    (hB.ae_nonneg_measure_pvm y hBpos).mono fun t ht => ?_
  simp [Real.sqrt_sq ht]

end IsSelfAdjoint
