/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import QuantumSystem.Analysis.SpectralTheory.ProjectionValuedIntegral.Bounded

/-!
# Strongly continuous unitary representations and Fourier transforms of projection-valued measures

A unitary representation `U : G → unitary (H →L[ℂ] H)` of a topological additive monoid is
**strongly continuous** (`AddChar.IsStronglyContinuous`) if it is continuous into the strong
operator topology, Mathlib's copy `H →Lₚₜ[ℂ] H`; equivalently `g ↦ U g y` is continuous for every
vector `y` (`AddChar.isStronglyContinuous_iff`).

For a bilinear pairing `L : W × V → ℝ`, the **Fourier transform** of a projection-valued measure on
`W` is the unitary representation `v ↦ ∫ exp (i L(w, v)) dE(w)` of `V`
(`ProjectionValuedMeasure.fourier`); for `W = ℝ` and the multiplication it is the unitary group
generated by a self-adjoint operator, and for `W` the dual of `V` it is the form of a unitary
representation given by the SNAG theorem.

## Main definitions

* `AddChar.IsStronglyContinuous U` — the unitary representation `U` is continuous into the strong
  operator topology, the topology of `H →Lₚₜ[ℂ] H`.
* `ProjectionValuedMeasure.fourier E L hL` — the unitary representation
  `v ↦ ∫ exp (i L(w, v)) dE(w)`, an `AddChar V (unitary (H →L[ℂ] H))`.

## Main results

* `ProjectionValuedMeasure.inner_fourier_apply_self` — `⟪y, U(v) y⟫ = ∫ exp (i L(w, v)) dE_y(w)`.
* `AddChar.isStronglyContinuous_iff` — strong continuity is continuity of `g ↦ U g y` for every
  `y`.
* `AddChar.IsStronglyContinuous.compAddMonoidHom` — pullbacks along continuous homomorphisms are
  strongly continuous.
* `ProjectionValuedMeasure.continuous_fourier_apply`,
  `ProjectionValuedMeasure.isStronglyContinuous_fourier` — the Fourier transform is strongly
  continuous when the pairing is continuous in `v`.

## References

* [W. Rudin, *Functional Analysis*][rudin1991], §12.17–12.21
-/

@[expose] public section

open Set Filter Topology ContinuousLinearMap MeasureTheory
open scoped ENNReal InnerProductSpace ComplexConjugate

/-! ### Strongly continuous unitary representations -/

namespace AddChar

variable {G H : Type*} [AddMonoid G] [TopologicalSpace G] [NormedAddCommGroup H]
  [InnerProductSpace ℂ H] [CompleteSpace H]

/-- A unitary representation `U` of `G` on `H` is **strongly continuous** if `g ↦ U g` is
continuous into the strong operator topology, i.e. into Mathlib's copy `H →Lₚₜ[ℂ] H` of
`H →L[ℂ] H` with the topology of pointwise convergence, the copy in which projection-valued
measures are countably additive. Equivalently, `g ↦ U g y` is continuous for every vector `y`
(`AddChar.isStronglyContinuous_iff`). -/
def IsStronglyContinuous (U : AddChar G (unitary (H →L[ℂ] H))) : Prop :=
  Continuous fun g =>
    (toUniformConvergenceCLM (RingHom.id ℂ) H {T : Set H | Finite T} (U g) : H →Lₚₜ[ℂ] H)

/-- A unitary representation is strongly continuous iff `g ↦ U g y` is continuous for every
vector `y`. -/
lemma isStronglyContinuous_iff {U : AddChar G (unitary (H →L[ℂ] H))} :
    U.IsStronglyContinuous ↔ ∀ y, Continuous fun g => (U g : H →L[ℂ] H) y := by
  refine ⟨fun h y => ?_, fun h => PointwiseConvergenceCLM.continuous_of_continuous_eval fun y => by
    simpa [toUniformConvergenceCLM_apply] using h y⟩
  exact (PointwiseConvergenceCLM.evalCLM (RingHom.id ℂ) H y).continuous.comp h

/-- The matrix coefficients `g ↦ ⟪x, U g y⟫` of a strongly continuous representation are
continuous. -/
lemma IsStronglyContinuous.continuous_inner_apply {U : AddChar G (unitary (H →L[ℂ] H))}
    (hU : U.IsStronglyContinuous) (x y : H) : Continuous fun g => ⟪x, (U g : H →L[ℂ] H) y⟫_ℂ :=
  continuous_const.inner (isStronglyContinuous_iff.mp hU y)

/-- The pullback `U ∘ f` of a strongly continuous representation along a continuous
homomorphism `f` is strongly continuous. -/
lemma IsStronglyContinuous.compAddMonoidHom {U : AddChar G (unitary (H →L[ℂ] H))}
    (hU : U.IsStronglyContinuous) {G' : Type*} [AddMonoid G'] [TopologicalSpace G'] (f : G' →+ G)
    (hf : Continuous f) : (U.compAddMonoidHom f).IsStronglyContinuous :=
  hU.comp hf

end AddChar

namespace MeasureTheory.ProjectionValuedMeasure

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-! ### Fourier transforms of projection-valued measures -/

section Fourier

variable {V W : Type*} [AddCommGroup V] [Module ℝ V] [AddCommGroup W] [Module ℝ W]
  [MeasurableSpace W] (E : ProjectionValuedMeasure W H) (L : W →ₗ[ℝ] V →ₗ[ℝ] ℝ)
  (hL : ∀ v, Measurable fun w => L w v)

include hL in
/-- The phase `w ↦ exp (i L(w, v))` of a pairing measurable in `w` is measurable. -/
lemma measurable_exp_pairing (v : V) :
    Measurable fun w => Complex.exp (L w v * Complex.I) :=
  ((Complex.measurable_ofReal.comp (hL v)).mul_const _).cexp

/-- The **Fourier transform** of a projection-valued measure `E` on `W` along a bilinear pairing
`L : W × V → ℝ`: the unitary representation `v ↦ ∫ exp (i L(w, v)) dE(w)` of `V`. For `W = ℝ` and
`L` the multiplication it is the unitary group `t ↦ exp (i t A)` of the self-adjoint operator `A`
with projection-valued measure `E`; for `W` the dual of `V` and `L` the evaluation pairing it is
the representation whose projection-valued measure the SNAG theorem recovers. -/
noncomputable def fourier : AddChar V (unitary (H →L[ℂ] H)) where
  toFun v := ⟨E.integral fun w => Complex.exp (L w v * Complex.I),
    E.integral_mem_unitary (measurable_exp_pairing L hL v)
      fun w => Complex.norm_exp_ofReal_mul_I _⟩
  map_zero_eq_one' := by
    ext1
    simp
  map_add_eq_mul' v v' := by
    ext1
    have h : (fun w => Complex.exp (L w (v + v') * Complex.I)) =
        (fun w => Complex.exp (L w v * Complex.I)) * fun w => Complex.exp (L w v' * Complex.I) := by
      ext w
      simp [add_mul, Complex.exp_add]
    change E.integral _ = E.integral _ * E.integral _
    rw [h, E.integral_mul (measurable_exp_pairing L hL v)
      ⟨1, fun _ => (Complex.norm_exp_ofReal_mul_I _).le⟩ (measurable_exp_pairing L hL v')
      ⟨1, fun _ => (Complex.norm_exp_ofReal_mul_I _).le⟩]

/-- The Fourier transform of `E` is the spectral integral of the phases `exp (i L(·, v))`. -/
lemma coe_fourier_apply (v : V) :
    (E.fourier L hL v : H →L[ℂ] H) = E.integral fun w => Complex.exp (L w v * Complex.I) :=
  rfl

/-- `⟪y, U(v) y⟫ = ∫ exp (i L(w, v)) dE_y(w)`: the diagonal matrix elements of the Fourier
transform are the Fourier transforms of the diagonal measures. -/
lemma inner_fourier_apply_self (v : V) (y : H) :
    ⟪y, (E.fourier L hL v : H →L[ℂ] H) y⟫_ℂ =
      ∫ w, Complex.exp (L w v * Complex.I) ∂(E.measure y) :=
  E.inner_integral_self (measurable_exp_pairing L hL v)
    ⟨1, fun _ => (Complex.norm_exp_ofReal_mul_I _).le⟩ y

variable [TopologicalSpace V] [FirstCountableTopology V]

/-- **Strong continuity**: if `L(w, ·)` is continuous for every `w`, then `v ↦ U(v) y` is
continuous for every `y`. -/
lemma continuous_fourier_apply (hLc : ∀ w, Continuous fun v => L w v) (y : H) :
    Continuous fun v => (E.fourier L hL v : H →L[ℂ] H) y := by
  set e : V → W → ℂ := fun v w => Complex.exp (L w v * Complex.I)
  have hb : ∀ v, ∃ C, ∀ w, ‖e v w‖ ≤ C := fun v => ⟨1, fun _ => (Complex.norm_exp_ofReal_mul_I _).le⟩
  refine continuous_iff_continuousAt.mpr fun v₀ => ?_
  rw [ContinuousAt, tendsto_iff_norm_sub_tendsto_zero]
  have hsq : ∀ v, ‖(E.fourier L hL v : H →L[ℂ] H) y - (E.fourier L hL v₀ : H →L[ℂ] H) y‖ =
      √(∫ w, ‖e v w - e v₀ w‖ ^ 2 ∂(E.measure y)) := fun v => by
    rw [coe_fourier_apply, coe_fourier_apply, ← sub_apply,
      ← E.integral_sub (measurable_exp_pairing L hL v) (hb v) (measurable_exp_pairing L hL v₀)
        (hb v₀), ← Real.sqrt_sq (norm_nonneg _),
      E.norm_integral_apply_sq ((measurable_exp_pairing L hL v).sub (measurable_exp_pairing L hL v₀))
        ⟨2, fun w => (norm_sub_le _ _).trans (by
          rw [Complex.norm_exp_ofReal_mul_I, Complex.norm_exp_ofReal_mul_I]; norm_num)⟩]
    rfl
  have hc : Continuous fun v => ∫ w, ‖e v w - e v₀ w‖ ^ 2 ∂(E.measure y) := by
    refine continuous_of_dominated (bound := fun _ => 4)
      (fun v => (((measurable_exp_pairing L hL v).sub
        (measurable_exp_pairing L hL v₀)).norm.pow_const 2).aestronglyMeasurable)
      (fun v => Eventually.of_forall fun w => ?_) (integrable_const _)
      (Eventually.of_forall fun w => ?_)
    · rw [Real.norm_eq_abs, abs_of_nonneg (by positivity), show (4 : ℝ) = 2 ^ 2 by norm_num]
      refine pow_le_pow_left₀ (norm_nonneg _) ((norm_sub_le _ _).trans ?_) 2
      simp only [e, Complex.norm_exp_ofReal_mul_I]
      norm_num
    · have := hLc w
      fun_prop
  simp_rw [hsq]
  have h0 : ((fun x => √x) ∘ fun v => ∫ w, ‖e v w - e v₀ w‖ ^ 2 ∂(E.measure y)) v₀ = 0 := by
    simp
  rw [← h0]
  exact (Real.continuous_sqrt.comp hc).tendsto v₀

/-- **Strong continuity**: if `L(w, ·)` is continuous for every `w`, the Fourier transform
`v ↦ ∫ exp (i L(w, v)) dE(w)` is a strongly continuous unitary representation, continuous into
the copy `H →Lₚₜ[ℂ] H` of `H →L[ℂ] H` with the topology of pointwise convergence. -/
lemma isStronglyContinuous_fourier (hLc : ∀ w, Continuous fun v => L w v) :
    (E.fourier L hL).IsStronglyContinuous :=
  AddChar.isStronglyContinuous_iff.mpr (E.continuous_fourier_apply L hL hLc)

end Fourier

end MeasureTheory.ProjectionValuedMeasure
