name = "QuantumSystem"
version = "0.1.0"
defaultTargets = ["QuantumSystem"]

[[lean_lib]]
name = "QuantumSystem"
leanOptions = { warningAsError = true }

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0-rc1"

[[lean_exe]]
name = "mk_all"
srcDir = "scripts"
root = "mk_all"
