/-
Copyright (c) 2025 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import Mathlib.Analysis.CStarAlgebra.ApproximateUnit
public import QuantumSystem.ForMathlib.Algebra.Order.Module.PositiveLinearMap
public import QuantumSystem.ForMathlib.Algebra.Order.Star.Basic
public import QuantumSystem.ForMathlib.Analysis.CStarAlgebra.GelfandNaimarkSegal

/-!
# States on a C\*-algebra

A *state* on a (possibly non-unital) C\*-algebra `A` is a positive linear functional
`ω : A → ℂ` of norm one (Bratteli–Robinson, §2.3.2; Murphy, §3.3).

`State A` extends Mathlib's positive linear maps `A →ₚ[ℂ] ℂ` by the single normalisation field
`‖ω‖ = 1`.  Nothing else needs to be assumed: a positive linear map between C\*-algebras is
automatically bounded (`PositiveLinearMap.exists_norm_apply_le`) and `*`-preserving, so `State A`
is a `ContinuousLinearMapClass` and a `StarHomClass` for free.

The order on `A` is a type-class parameter `[PartialOrder A] [StarOrderedRing A]`, as in
Mathlib's `PositiveLinearMap.GNS`.  Concrete algebras carry their own order (the Loewner order on
`H →L[ℂ] H`, `ComplexOrder` on `ℂ`, the spectral order on `Unitization ℂ A`); for an abstract
C\*-algebra with no preferred order, `CStarAlgebra.spectralOrder` and
`CStarAlgebra.spectralOrderedRing` can be installed locally.  Since a star-ordered ring's cone is
generated by the `a* a`, every such order on a C\*-algebra has the same positive cone.

## Main definitions

* `State A` — the states on `A`.
* `State.ofContinuousLinearMap` — the state defined by a positive continuous linear functional
  of norm one.
* `State.normalize` — the state `‖f‖ₒₚ⁻¹ f` of a nonzero positive linear functional `f`.
* `State.convexCombination s w hw ω` — the convex combination `Σᵢ wᵢ ωᵢ` of states, with weights
  `wᵢ ≥ 0` summing to one; the states form a convex set.
* `State.ofPositiveLinearMap f hf` — on a unital algebra, the state of a positive functional with
  `f 1 = 1`.
* `State.comp ω α hα` — on unital algebras, the state `ω ∘ α` for a unital positive map `α`.

## Main results

* `State.norm_apply_le` — `‖ω a‖ ≤ ‖a‖`.
* `State.apply_star_mul_self_nonneg` — `0 ≤ ω (a* a)`.
* `State.norm_apply_sq_le` — `|ω a|² ≤ ω (a* a)`.
* `State.tendsto_approximateUnit` — `ω e_α → 1` along any increasing approximate unit.
* `State.apply_one` — `ω 1 = 1` on a unital algebra.
* `State.coe_convexCombination` — the convex combination is `Σᵢ wᵢ • ωᵢ` as a positive functional.

The Cauchy–Schwarz inequality `|ω (a* b)|² ≤ |ω (a* a)| |ω (b* b)|` needs no restatement: Mathlib's
`PositiveLinearMap.norm_map_star_mul_sq_le` applies to `ω` directly.  `State.norm_apply_sq_le` and
`State.tendsto_approximateUnit` are the norm-one cases of Mathlib's
`PositiveContinuousLinearMap.norm_map_sq_le_opNorm_mul` and
`PositiveContinuousLinearMap.tendsto_nhds_opNorm`, applied to
`PositiveContinuousLinearMap.ofClass ω`.

## TODO

States are represented twice in this repository: as the structure `State A` here (used by GNS,
local nets and the entropies), and as elements of `WeakDual ℂ A` in a convex, weak-* compact set
(`QuasiStateSpace A`, with `PureState A` its extreme points). Bratteli–Robinson (§2.3.2) and
Kadison–Ringrose (§4.3) treat a state as one element of the dual `A*` and the state space as a
convex subset of `A*`; unify the two encodings, so that convexity statements (e.g. concavity of
the von Neumann entropy) can use Mathlib's `ConcaveOn` on the state space.
-/

@[expose] public section

open scoped ComplexOrder InnerProductSpace NNReal
open Filter Topology PositiveLinearMap

/-- A state on a (possibly non-unital) C\*-algebra `A`: a positive linear functional
`A →ₚ[ℂ] ℂ` of norm one. -/
structure State (A : Type*) [NonUnitalCStarAlgebra A] [PartialOrder A] [StarOrderedRing A]
    extends A →ₚ[ℂ] ℂ where
  /-- The normalisation `‖ω‖ₒₚ = 1`, for the operator norm of the (automatically bounded)
  positive functional. -/
  norm_eq_one : ‖toPositiveLinearMap‖ₒₚ = 1

namespace State

variable {A : Type*} [NonUnitalCStarAlgebra A] [PartialOrder A] [StarOrderedRing A]

noncomputable instance : FunLike (State A) A ℂ where
  coe ω := ω.toPositiveLinearMap
  coe_injective ω₁ ω₂ h := by
    obtain ⟨f₁, _⟩ := ω₁
    obtain ⟨f₂, _⟩ := ω₂
    congr
    exact DFunLike.coe_injective h

instance : LinearMapClass (State A) ℂ A ℂ where
  map_add ω := map_add ω.toPositiveLinearMap
  map_smulₛₗ ω := map_smul ω.toPositiveLinearMap

instance : OrderHomClass (State A) A ℂ where
  map_rel ω _ _ h := OrderHomClass.mono ω.toPositiveLinearMap h

/-- States are bounded: positive maps between C\*-algebras are continuous. -/
instance : ContinuousLinearMapClass (State A) ℂ A ℂ := inferInstance

/-- States are `*`-preserving: `ω (a*) = conj (ω a)`. -/
instance : StarHomClass (State A) A ℂ := inferInstance

/-- A state is in particular a positive linear functional, and results about general positive
functionals (such as the GNS triplets `GNS.Representation f`) apply to `ω.toPositiveLinearMap`,
written and displayed as `↑ω`. -/
instance : CoeOut (State A) (A →ₚ[ℂ] ℂ) := ⟨toPositiveLinearMap⟩

attribute [coe] State.toPositiveLinearMap

variable (ω : State A)

@[simp] lemma coe_toPositiveLinearMap : ⇑ω.toPositiveLinearMap = ω := rfl

@[simp] lemma toLinearMap_apply (a : A) : ω.toLinearMap a = ω a := rfl

@[ext] lemma ext {ω₁ ω₂ : State A} (h : ∀ a, ω₁ a = ω₂ a) : ω₁ = ω₂ :=
  DFunLike.ext ω₁ ω₂ h

/-! ### Norm -/

/-- `‖ω a‖ ≤ ‖a‖`. -/
lemma norm_apply_le (a : A) : ‖ω a‖ ≤ ‖a‖ := by
  simpa [norm_eq_one] using
    (PositiveContinuousLinearMap.ofClass ω.toPositiveLinearMap : A →L[ℂ] ℂ).le_opNorm a

/-- States are `1`-Lipschitz. -/
lemma lipschitzWith_one : LipschitzWith 1 ω := by
  have h : ‖(PositiveContinuousLinearMap.ofClass ω.toPositiveLinearMap : A →L[ℂ] ℂ)‖₊ = 1 :=
    NNReal.eq ω.norm_eq_one
  exact h ▸ (PositiveContinuousLinearMap.ofClass ω.toPositiveLinearMap : A →L[ℂ] ℂ).lipschitzWith

lemma continuous : Continuous ω := map_continuous ω

/-! ### Positivity -/

/-- `0 ≤ ω a` for every positive `a`. -/
lemma apply_nonneg {a : A} (ha : 0 ≤ a) : 0 ≤ ω a := ω.toPositiveLinearMap.map_nonneg ha

/-- `0 ≤ ω (a* a)`. -/
lemma apply_star_mul_self_nonneg (a : A) : 0 ≤ ω (star a * a) :=
  ω.apply_nonneg (star_mul_self_nonneg a)

/-- `0 ≤ Re ω (a* a)`. -/
lemma re_apply_star_mul_self_nonneg (a : A) : 0 ≤ (ω (star a * a)).re :=
  (Complex.nonneg_iff.mp (ω.apply_star_mul_self_nonneg a)).1

/-- `ω (a* a)` is real: `Re ω (a* a) = ω (a* a)`. -/
lemma ofReal_re_apply_star_mul_self (a : A) : ((ω (star a * a)).re : ℂ) = ω (star a * a) :=
  Complex.ext rfl (Complex.nonneg_iff.mp (ω.apply_star_mul_self_nonneg a)).2

/-- `|ω a|² ≤ ω (a* a)`: the norm-one case of
`PositiveContinuousLinearMap.norm_map_sq_le_opNorm_mul`. -/
lemma norm_apply_sq_le (a : A) : ‖ω a‖ ^ 2 ≤ (ω (star a * a)).re := by
  have h := (PositiveContinuousLinearMap.ofClass ω.toPositiveLinearMap).norm_map_sq_le_opNorm_mul a
  rwa [ω.norm_eq_one, one_mul, PositiveContinuousLinearMap.coe_ofClass, coe_toPositiveLinearMap,
    ← Complex.re_eq_norm.mpr (ω.apply_star_mul_self_nonneg a)] at h

/-- Evaluation of a state along any increasing approximate unit converges to `1`: `ω e_α → 1`.
This is the norm-one case of `PositiveContinuousLinearMap.tendsto_nhds_opNorm`. -/
theorem tendsto_approximateUnit {l : Filter A} (hl : l.IsIncreasingApproximateUnit) :
    Tendsto (fun e : A => ω e) l (𝓝 1) := by
  simpa [ω.norm_eq_one] using
    (PositiveContinuousLinearMap.ofClass ω.toPositiveLinearMap).tendsto_nhds_opNorm hl

/-! ### Construction from a continuous functional -/

/-- The state defined by a continuous linear functional `f` of norm one that sends positive
elements to nonnegative numbers.  Positivity is usually checked on the `a* a` alone, via
`StarOrderedRing.map_nonneg_of_star_mul_self_nonneg`. -/
noncomputable def ofContinuousLinearMap (f : A →L[ℂ] ℂ) (hf : ∀ a, 0 ≤ a → 0 ≤ f a)
    (h : ‖f‖ = 1) : State A :=
  let g : A →ₚ[ℂ] ℂ := PositiveLinearMap.mk₀ f.toLinearMap hf
  { toPositiveLinearMap := g
    norm_eq_one := by
      rw [show (PositiveContinuousLinearMap.ofClass g : A →L[ℂ] ℂ) = f from
        ContinuousLinearMap.ext fun _ => rfl]
      exact h }

@[simp] lemma ofContinuousLinearMap_apply (f : A →L[ℂ] ℂ) (hf : ∀ a, 0 ≤ a → 0 ≤ f a)
    (h : ‖f‖ = 1) (a : A) : ofContinuousLinearMap f hf h a = f a := rfl

/-! ### Normalisation of a positive functional -/

/-- The state `‖f‖ₒₚ⁻¹ f` obtained by normalising a nonzero positive linear functional. -/
noncomputable def normalize (f : A →ₚ[ℂ] ℂ) (hf : f ≠ 0) : State A :=
  ofContinuousLinearMap (((‖f‖ₒₚ⁻¹ : ℝ) : ℂ) • (PositiveContinuousLinearMap.ofClass f : A →L[ℂ] ℂ))
    (fun _ ha => mul_nonneg (Complex.zero_le_real.mpr (inv_nonneg.mpr (norm_nonneg _)))
      (f.map_nonneg ha))
    (by rw [norm_smul, Complex.norm_real, Real.norm_eq_abs, abs_inv, abs_norm,
      inv_mul_cancel₀ ((opNorm_eq_zero_iff f).not.mpr hf)])

/-- `normalize f hf a = ‖f‖ₒₚ⁻¹ f a`. -/
@[simp] lemma normalize_apply (f : A →ₚ[ℂ] ℂ) (hf : f ≠ 0) (a : A) :
    normalize f hf a = (‖f‖ₒₚ⁻¹ : ℝ) * f a := rfl

/-- The positive functional underlying a state is nonzero. -/
lemma toPositiveLinearMap_ne_zero (ω : State A) : ω.toPositiveLinearMap ≠ 0 := by
  intro h
  have := ω.norm_eq_one
  rw [(opNorm_eq_zero_iff _).mpr h] at this
  exact zero_ne_one this

/-- Normalising a state gives the state back. -/
@[simp] lemma normalize_toPositiveLinearMap (ω : State A) :
    normalize ω.toPositiveLinearMap ω.toPositiveLinearMap_ne_zero = ω := by
  ext a
  simp [ω.norm_eq_one]

/-- A state is determined by its underlying positive functional. -/
lemma toPositiveLinearMap_injective :
    Function.Injective (toPositiveLinearMap : State A → A →ₚ[ℂ] ℂ) :=
  fun _ _ h => ext fun a => congrArg (fun f : A →ₚ[ℂ] ℂ => f a) h

/-! ### Convex combinations -/

/-- The **convex combination** `Σᵢ∈s wᵢ ωᵢ` of states `ωᵢ` with weights `wᵢ ≥ 0` summing to one is a
state: along an increasing approximate unit `e`, the norm of the positive functional `Σᵢ wᵢ ωᵢ` is
the limit of `Σᵢ wᵢ ωᵢ(e) → Σᵢ wᵢ = 1` (`PositiveContinuousLinearMap.tendsto_nhds_opNorm`,
`State.tendsto_approximateUnit`). The algebra need not be unital. -/
noncomputable def convexCombination {ι : Type*} (s : Finset ι) (w : ι → ℝ≥0)
    (hw : ∑ i ∈ s, w i = 1) (ω : ι → State A) : State A where
  toPositiveLinearMap := ∑ i ∈ s, w i • (ω i).toPositiveLinearMap
  norm_eq_one := by
    set f : A →ₚ[ℂ] ℂ := ∑ i ∈ s, w i • (ω i).toPositiveLinearMap
    have hl := CStarAlgebra.increasingApproximateUnit A
    have h1 := (PositiveContinuousLinearMap.ofClass f).tendsto_nhds_opNorm hl
    have h2 : Tendsto (fun e : A => f e) (CStarAlgebra.approximateUnit A) (𝓝 1) := by
      have : Tendsto (fun e : A => ∑ i ∈ s, (w i : ℂ) * (ω i) e) (CStarAlgebra.approximateUnit A)
          (𝓝 (∑ i ∈ s, (w i : ℂ) * 1)) :=
        tendsto_finsetSum _ fun i _ => (ω i).tendsto_approximateUnit hl |>.const_mul _
      have hw' : ∑ i ∈ s, ((w i : ℝ) : ℂ) = 1 := by
        rw [← Complex.ofReal_sum, ← NNReal.coe_sum, hw, NNReal.coe_one, Complex.ofReal_one]
      simpa [f, NNReal.smul_def, hw'] using this
    exact_mod_cast tendsto_nhds_unique h1 h2

/-- The convex combination is `Σᵢ wᵢ • ωᵢ` as a positive functional. -/
@[simp] lemma coe_convexCombination {ι : Type*} (s : Finset ι) (w : ι → ℝ≥0)
    (hw : ∑ i ∈ s, w i = 1) (ω : ι → State A) :
    (convexCombination s w hw ω : A →ₚ[ℂ] ℂ) = ∑ i ∈ s, w i • (ω i : A →ₚ[ℂ] ℂ) :=
  rfl

/-- The convex combination evaluates as `Σᵢ wᵢ ωᵢ(a)`. -/
lemma convexCombination_apply {ι : Type*} (s : Finset ι) (w : ι → ℝ≥0)
    (hw : ∑ i ∈ s, w i = 1) (ω : ι → State A) (a : A) :
    convexCombination s w hw ω a = ∑ i ∈ s, (w i : ℂ) * ω i a := by
  change (∑ i ∈ s, w i • (ω i).toPositiveLinearMap) a = _
  simp [NNReal.smul_def]

end State

/-! ### Unital algebras -/

namespace State

variable {A : Type*} [CStarAlgebra A] [PartialOrder A] [StarOrderedRing A] (ω : State A)

/-- On a unital C\*-algebra, `ω 1 = 1`: the norm of a positive functional is its value at `1`
(`PositiveContinuousLinearMap.ofReal_opNorm_eq_map_one`). -/
@[simp] lemma apply_one : ω 1 = 1 := by
  simpa [ω.norm_eq_one] using (PositiveContinuousLinearMap.ofReal_opNorm_eq_map_one
    (PositiveContinuousLinearMap.ofClass ω.toPositiveLinearMap)).symm

/-! ### Construction and composition on unital algebras -/

/-- On a unital C\*-algebra, a positive functional with `f 1 = 1` is a state: its norm is `f 1`
(`PositiveContinuousLinearMap.ofReal_opNorm_eq_map_one`). -/
noncomputable def ofPositiveLinearMap (f : A →ₚ[ℂ] ℂ) (hf : f 1 = 1) : State A where
  toPositiveLinearMap := f
  norm_eq_one := by
    have h := PositiveContinuousLinearMap.ofReal_opNorm_eq_map_one (PositiveContinuousLinearMap.ofClass f)
    rw [PositiveContinuousLinearMap.coe_ofClass, hf] at h
    exact_mod_cast h

@[simp] lemma coe_ofPositiveLinearMap (f : A →ₚ[ℂ] ℂ) (hf : f 1 = 1) :
    (ofPositiveLinearMap f hf : A →ₚ[ℂ] ℂ) = f :=
  rfl

@[simp] lemma ofPositiveLinearMap_apply (f : A →ₚ[ℂ] ℂ) (hf : f 1 = 1) (a : A) :
    ofPositiveLinearMap f hf a = f a :=
  rfl

variable {B : Type*} [CStarAlgebra B] [PartialOrder B] [StarOrderedRing B]
  {F : Type*} [FunLike F B A] [LinearMapClass F ℂ B A] [OrderHomClass F B A]

/-- The **pullback** `ω ∘ α` of a state along a unital positive map `α : B → A`, for instance the
restriction of a state to a subalgebra, or a state transformed by the Heisenberg-picture dual of a
quantum channel. -/
noncomputable def comp (α : F) (hα : α 1 = 1) : State B :=
  ofPositiveLinearMap (ω.toPositiveLinearMap.comp (PositiveLinearMap.ofClass α)) (by
    change ω (α 1) = 1
    rw [hα, ω.apply_one])

@[simp] lemma coe_comp (α : F) (hα : α 1 = 1) :
    (ω.comp α hα : B →ₚ[ℂ] ℂ) = (ω : A →ₚ[ℂ] ℂ).comp (PositiveLinearMap.ofClass α) :=
  rfl

@[simp] lemma comp_apply (α : F) (hα : α 1 = 1) (b : B) : ω.comp α hα b = ω (α b) :=
  rfl

end State
