/-
Copyright (c) 2025 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import QuantumSystem.ForMathlib.Analysis.CStarAlgebra.StateSpace
public import QuantumSystem.ForMathlib.Algebra.Order.Module.PositiveLinearMap
public import QuantumSystem.ForMathlib.Analysis.CStarAlgebra.GelfandNaimarkSegal

/-!
# States on a C\*-algebra

A *state* on a (possibly non-unital) C\*-algebra `A` is a positive linear functional
`ω : A → ℂ` of norm one (Bratteli–Robinson, §2.3.2; Murphy, §3.3).

As in Bratteli–Robinson, a state is an element of the dual: `State A` is the subtype of the state
space `StateSpace A ⊆ WeakDual ℂ A` (`QuantumSystem.ForMathlib.Analysis.CStarAlgebra.StateSpace`), the convex
set of positive functionals of norm one. Convexity statements about states (such as the concavity
of the von Neumann entropy) are stated on `StateSpace A` with Mathlib's `Convex`/`ConcaveOn`, and
pure states (`PureState A`) are elements of the same dual.

A state is a `ContinuousLinearMapClass` and an `OrderHomClass`, so results about positive linear
functionals apply to `PositiveLinearMap.ofClass ω`, and `*`-preservation comes for free
(`StarHomClass`).

The order on `A` is a type-class parameter, as in Mathlib's `PositiveLinearMap.GNS`. `State A`
itself needs only `[PartialOrder A]`, but it is the usual notion of state only under
`[StarOrderedRing A]`, when positivity refers to the C\*-positive cone; the API below assumes it.  Concrete algebras carry their own order (the Loewner order on
`H →L[ℂ] H`, `ComplexOrder` on `ℂ`, the spectral order on `Unitization ℂ A`); for an abstract
C\*-algebra with no preferred order, `CStarAlgebra.spectralOrder` and
`CStarAlgebra.spectralOrderedRing` can be installed locally.  Since a star-ordered ring's cone is
generated by the `a* a`, every such order on a C\*-algebra has the same positive cone.

## Main definitions

* `State A` — the states on `A`, the elements of `StateSpace A`.
* `State.ofContinuousLinearMap` — the state defined by a positive continuous linear functional
  of norm one.
* `State.normalize` — the state `‖f‖ₒₚ⁻¹ f` of a nonzero positive linear functional `f`.
* `State.ofPositiveLinearMap f hf` — on a unital algebra, the state of a positive functional with
  `f 1 = 1`.
* `State.comp ω α hα` — on unital algebras, the state `ω ∘ α` for a unital positive map `α`.

## Main results

* `State.norm_eq_one`, `State.opNorm_ofClass_eq_one` — `‖ω‖ = 1`.
* `State.norm_apply_le` — `‖ω a‖ ≤ ‖a‖`.
* `State.apply_star_mul_self_nonneg` — `0 ≤ ω (a* a)`.
* `State.norm_apply_sq_le` — `|ω a|² ≤ ω (a* a)`.
* `State.tendsto_approximateUnit` — `ω e_α → 1` along any increasing approximate unit.
* `State.apply_one` — `ω 1 = 1` on a unital algebra.

The Cauchy–Schwarz inequality `|ω (a* b)|² ≤ |ω (a* a)| |ω (b* b)|` needs no restatement: Mathlib's
`PositiveLinearMap.norm_map_star_mul_sq_le` applies to `ω` directly.  `State.norm_apply_sq_le` and
`State.tendsto_approximateUnit` are the norm-one cases of Mathlib's
`PositiveContinuousLinearMap.norm_map_sq_le_opNorm_mul` and
`PositiveContinuousLinearMap.tendsto_nhds_opNorm`, applied to
`PositiveContinuousLinearMap.ofClass ω`.
-/

@[expose] public section

open scoped ComplexOrder InnerProductSpace NNReal
open Filter Topology PositiveLinearMap

/-- A state on a (possibly non-unital) C\*-algebra `A`: an element of the state space
`StateSpace A`, a positive continuous linear functional of norm one. -/
def State (A : Type*) [NonUnitalCStarAlgebra A] [PartialOrder A] :=
  {φ : WeakDual ℂ A // φ ∈ StateSpace A}

namespace State

variable {A : Type*} [NonUnitalCStarAlgebra A] [PartialOrder A]

noncomputable instance : FunLike (State A) A ℂ where
  coe ω := ω.val
  coe_injective _ _ h := Subtype.ext (DFunLike.coe_injective h)

instance : LinearMapClass (State A) ℂ A ℂ where
  map_add ω := map_add ω.val
  map_smulₛₗ ω := map_smul ω.val

instance : ContinuousLinearMapClass (State A) ℂ A ℂ where
  map_continuous ω := ω.val.continuous

variable (ω : State A)

@[simp] lemma coe_val : ⇑ω.val = ω := rfl

@[ext] lemma ext {ω₁ ω₂ : State A} (h : ∀ a, ω₁ a = ω₂ a) : ω₁ = ω₂ :=
  DFunLike.ext ω₁ ω₂ h

/-- The normalisation `‖ω‖ = 1`. -/
lemma norm_eq_one : ‖WeakDual.toStrongDual ω.val‖ = 1 :=
  (mem_stateSpace_iff.mp ω.2).2

/-! ### Norm -/

/-- `‖ω a‖ ≤ ‖a‖`. -/
lemma norm_apply_le (a : A) : ‖ω a‖ ≤ ‖a‖ := by
  simpa [norm_eq_one] using (WeakDual.toStrongDual ω.val).le_opNorm a

/-- States are `1`-Lipschitz. -/
lemma lipschitzWith_one : LipschitzWith 1 ω := by
  have h : ‖WeakDual.toStrongDual ω.val‖₊ = 1 := NNReal.eq ω.norm_eq_one
  exact h ▸ (WeakDual.toStrongDual ω.val).lipschitzWith

lemma continuous : Continuous ω := map_continuous ω

/-! ### Positivity -/

/-- `0 ≤ ω a` for every positive `a`. -/
lemma apply_nonneg {a : A} (ha : 0 ≤ a) : 0 ≤ ω a := ω.2.1 a ha

/-! ### Construction from a continuous functional -/

/-- The state defined by a continuous linear functional `f` of norm one that sends positive
elements to nonnegative numbers.  Positivity is usually checked on the `a* a` alone, via
`StarOrderedRing.map_nonneg_of_star_mul_self_nonneg`. -/
noncomputable def ofContinuousLinearMap (f : A →L[ℂ] ℂ) (hf : ∀ a, 0 ≤ a → 0 ≤ f a) (h : ‖f‖ = 1) :
    State A :=
  ⟨StrongDual.toWeakDual f, mem_stateSpace_iff.mpr ⟨hf, h⟩⟩

@[simp] lemma ofContinuousLinearMap_apply (f : A →L[ℂ] ℂ) (hf : ∀ a, 0 ≤ a → 0 ≤ f a)
    (h : ‖f‖ = 1) (a : A) : ofContinuousLinearMap f hf h a = f a := rfl

section StarOrderedRing

variable [StarOrderedRing A]

instance : OrderHomClass (State A) A ℂ where
  map_rel ω a b h := by
    have := ω.2.1 (b - a) (sub_nonneg.mpr h)
    change 0 ≤ ω.val (b - a) at this
    rw [map_sub, sub_nonneg] at this
    exact this

/-- The normalisation `‖ω‖ₒₚ = 1`, through the positive functional `PositiveLinearMap.ofClass ω`. -/
lemma opNorm_ofClass_eq_one : ‖PositiveLinearMap.ofClass ω‖ₒₚ = 1 :=
  ω.norm_eq_one

/-- States are `*`-preserving: `ω (a*) = conj (ω a)`. -/
instance : StarHomClass (State A) A ℂ := inferInstance

/-- `0 ≤ ω (a* a)`. -/
lemma apply_star_mul_self_nonneg (a : A) : 0 ≤ ω (star a * a) :=
  ω.apply_nonneg (star_mul_self_nonneg a)

/-- `0 ≤ Re ω (a* a)`. -/
lemma re_apply_star_mul_self_nonneg (a : A) : 0 ≤ (ω (star a * a)).re :=
  (Complex.nonneg_iff.mp (ω.apply_star_mul_self_nonneg a)).1

/-- `ω (a* a)` is real: `Re ω (a* a) = ω (a* a)`. -/
lemma ofReal_re_apply_star_mul_self (a : A) : ((ω (star a * a)).re : ℂ) = ω (star a * a) :=
  Complex.ext rfl (Complex.nonneg_iff.mp (ω.apply_star_mul_self_nonneg a)).2

/-- `|ω a|² ≤ ω (a* a)`: the norm-one case of
`PositiveContinuousLinearMap.norm_map_sq_le_opNorm_mul`. -/
lemma norm_apply_sq_le (a : A) : ‖ω a‖ ^ 2 ≤ (ω (star a * a)).re := by
  have h := (PositiveContinuousLinearMap.ofClass ω).norm_map_sq_le_opNorm_mul a
  rwa [show ‖(PositiveContinuousLinearMap.ofClass ω : A →L[ℂ] ℂ)‖ = 1 from ω.norm_eq_one, one_mul,
    PositiveContinuousLinearMap.coe_ofClass,
    ← Complex.re_eq_norm.mpr (ω.apply_star_mul_self_nonneg a)] at h

/-- Evaluation of a state along any increasing approximate unit converges to `1`: `ω e_α → 1`.
This is the norm-one case of `PositiveContinuousLinearMap.tendsto_nhds_opNorm`. -/
theorem tendsto_approximateUnit {l : Filter A} (hl : l.IsIncreasingApproximateUnit) :
    Tendsto (fun e : A => ω e) l (𝓝 1) :=
  StateSpace.tendsto_approximateUnit ω.2 hl

/-! ### Normalisation of a positive functional -/

/-- The state `‖f‖ₒₚ⁻¹ f` obtained by normalising a nonzero positive linear functional. -/
noncomputable def normalize (f : A →ₚ[ℂ] ℂ) (hf : f ≠ 0) : State A :=
  ofContinuousLinearMap (((‖f‖ₒₚ⁻¹ : ℝ) : ℂ) • (PositiveContinuousLinearMap.ofClass f : A →L[ℂ] ℂ))
    (fun _ ha => mul_nonneg (Complex.zero_le_real.mpr (inv_nonneg.mpr (norm_nonneg _)))
      (f.map_nonneg ha))
    (by rw [norm_smul, Complex.norm_real, Real.norm_eq_abs, abs_inv, abs_norm,
      inv_mul_cancel₀ ((opNorm_eq_zero_iff f).not.mpr hf)])

/-- `normalize f hf a = ‖f‖ₒₚ⁻¹ f a`. -/
@[simp] lemma normalize_apply (f : A →ₚ[ℂ] ℂ) (hf : f ≠ 0) (a : A) :
    normalize f hf a = (‖f‖ₒₚ⁻¹ : ℝ) * f a := rfl

/-- The positive functional underlying a state is nonzero. -/
lemma ofClass_ne_zero (ω : State A) : PositiveLinearMap.ofClass ω ≠ 0 := by
  intro h
  have := ω.opNorm_ofClass_eq_one
  rw [(opNorm_eq_zero_iff _).mpr h] at this
  exact zero_ne_one this

/-- Normalising a state gives the state back. -/
@[simp] lemma normalize_ofClass (ω : State A) :
    normalize (PositiveLinearMap.ofClass ω) ω.ofClass_ne_zero = ω := by
  ext a
  simp [ω.opNorm_ofClass_eq_one]

end StarOrderedRing

end State

/-! ### Unital algebras -/

namespace State

variable {A : Type*} [CStarAlgebra A] [PartialOrder A] [StarOrderedRing A] (ω : State A)

/-- On a unital C\*-algebra, `ω 1 = 1`: the norm of a positive functional is its value at `1`
(`PositiveContinuousLinearMap.ofReal_opNorm_eq_map_one`). -/
@[simp] lemma apply_one : ω 1 = 1 := by
  have h := PositiveContinuousLinearMap.ofReal_opNorm_eq_map_one (PositiveContinuousLinearMap.ofClass ω)
  rw [show ‖(PositiveContinuousLinearMap.ofClass ω : A →L[ℂ] ℂ)‖ = 1 from ω.norm_eq_one,
    PositiveContinuousLinearMap.coe_ofClass] at h
  exact_mod_cast h.symm

/-! ### Construction and composition on unital algebras -/

/-- On a unital C\*-algebra, a positive functional with `f 1 = 1` is a state: its norm is `f 1`
(`PositiveContinuousLinearMap.ofReal_opNorm_eq_map_one`). -/
noncomputable def ofPositiveLinearMap (f : A →ₚ[ℂ] ℂ) (hf : f 1 = 1) : State A :=
  ofContinuousLinearMap (PositiveContinuousLinearMap.ofClass f) (fun _ ha => f.map_nonneg ha) (by
    have h := PositiveContinuousLinearMap.ofReal_opNorm_eq_map_one (PositiveContinuousLinearMap.ofClass f)
    rw [PositiveContinuousLinearMap.coe_ofClass, hf] at h
    exact_mod_cast h)

@[simp] lemma ofClass_ofPositiveLinearMap (f : A →ₚ[ℂ] ℂ) (hf : f 1 = 1) :
    PositiveLinearMap.ofClass (ofPositiveLinearMap f hf) = f :=
  rfl

@[simp] lemma ofPositiveLinearMap_apply (f : A →ₚ[ℂ] ℂ) (hf : f 1 = 1) (a : A) :
    ofPositiveLinearMap f hf a = f a :=
  rfl

variable {B : Type*} [CStarAlgebra B] [PartialOrder B] [StarOrderedRing B]
  {F : Type*} [FunLike F B A] [LinearMapClass F ℂ B A] [OrderHomClass F B A]

/-- The **pullback** `ω ∘ α` of a state along a unital positive map `α : B → A`, for instance the
restriction of a state to a subalgebra, or a state transformed by the Heisenberg-picture dual of a
quantum channel. -/
noncomputable def comp (α : F) (hα : α 1 = 1) : State B :=
  ofPositiveLinearMap ((PositiveLinearMap.ofClass ω).comp (PositiveLinearMap.ofClass α)) (by
    change ω (α 1) = 1
    rw [hα, ω.apply_one])

@[simp] lemma ofClass_comp (α : F) (hα : α 1 = 1) :
    PositiveLinearMap.ofClass (ω.comp α hα) =
      (PositiveLinearMap.ofClass ω).comp (PositiveLinearMap.ofClass α) :=
  rfl

@[simp] lemma comp_apply (α : F) (hα : α 1 = 1) (b : B) : ω.comp α hα b = ω (α b) :=
  rfl

end State
