module

public import Mathlib.Analysis.CStarAlgebra.ApproximateUnit
public import Mathlib.Analysis.CStarAlgebra.GelfandNaimarkSegal
public import QuantumSystem.ForMathlib.Algebra.Order.Star.Basic

/-!
# States on a C\*-algebra

A *state* on a (possibly non-unital) C\*-algebra `A` is a positive linear functional
`ω : A → ℂ` of norm one (Bratteli–Robinson, §2.3.2; Murphy, §3.3).

`State A` extends Mathlib's positive linear maps `A →ₚ[ℂ] ℂ` by the single normalisation field
`‖ω‖ = 1`.  Nothing else needs to be assumed: a positive linear map between C\*-algebras is
automatically bounded (`PositiveLinearMap.exists_norm_apply_le`) and `*`-preserving, so `State A`
is a `ContinuousLinearMapClass` and a `StarHomClass` for free.

The order on `A` is a type-class parameter `[PartialOrder A] [StarOrderedRing A]`, as in
Mathlib's `PositiveLinearMap.GNS`.  Concrete algebras carry their own order (the Loewner order on
`H →L[ℂ] H`, `ComplexOrder` on `ℂ`, the spectral order on `Unitization ℂ A`); for an abstract
C\*-algebra with no preferred order, `CStarAlgebra.spectralOrder` and
`CStarAlgebra.spectralOrderedRing` can be installed locally.  Since a star-ordered ring's cone is
generated by the `a* a`, every such order on a C\*-algebra has the same positive cone.

## Main definitions

* `State A` — the states on `A`.
* `State.toContinuousLinearMap` — a state as a continuous linear functional `A →L[ℂ] ℂ`.
* `State.ofContinuousLinearMap` — the state defined by a positive continuous linear functional
  of norm one.

## Main results

* `State.norm_apply_le` — `‖ω a‖ ≤ ‖a‖`.
* `State.apply_star_mul_self_nonneg` — `0 ≤ ω (a* a)`.
* `State.norm_apply_star_mul_sq_le` — the Cauchy–Schwarz inequality
  `|ω (a* b)|² ≤ ω (a* a) ω (b* b)`, read off the semi-inner product of Mathlib's GNS space.
* `State.norm_apply_sq_le` — `|ω a|² ≤ ω (a* a)`, from Cauchy–Schwarz along an approximate unit.
-/

@[expose] public section

open scoped ComplexOrder InnerProductSpace
open Filter Topology PositiveLinearMap

/-- A state on a (possibly non-unital) C\*-algebra `A`: a positive linear functional
`A →ₚ[ℂ] ℂ` of norm one. -/
structure State (A : Type*) [NonUnitalCStarAlgebra A] [PartialOrder A] [StarOrderedRing A]
    extends A →ₚ[ℂ] ℂ where
  /-- The normalisation `‖ω‖ = 1`, for the operator norm of the (automatically bounded)
  positive functional. -/
  norm_eq_one : ‖(⟨toLinearMap, map_continuous toPositiveLinearMap⟩ : A →L[ℂ] ℂ)‖ = 1

namespace State

variable {A : Type*} [NonUnitalCStarAlgebra A] [PartialOrder A] [StarOrderedRing A]

noncomputable instance : FunLike (State A) A ℂ where
  coe ω := ω.toPositiveLinearMap
  coe_injective' ω₁ ω₂ h := by
    obtain ⟨f₁, _⟩ := ω₁
    obtain ⟨f₂, _⟩ := ω₂
    congr
    exact DFunLike.coe_injective h

instance : LinearMapClass (State A) ℂ A ℂ where
  map_add ω := map_add ω.toPositiveLinearMap
  map_smulₛₗ ω := map_smul ω.toPositiveLinearMap

instance : OrderHomClass (State A) A ℂ where
  map_rel ω _ _ h := OrderHomClass.mono ω.toPositiveLinearMap h

/-- States are bounded: positive maps between C\*-algebras are continuous. -/
instance : ContinuousLinearMapClass (State A) ℂ A ℂ := inferInstance

/-- States are `*`-preserving: `ω (a*) = conj (ω a)`. -/
instance : StarHomClass (State A) A ℂ := inferInstance

variable (ω : State A)

@[simp] lemma coe_toPositiveLinearMap : ⇑ω.toPositiveLinearMap = ω := rfl

@[simp] lemma toLinearMap_apply (a : A) : ω.toLinearMap a = ω a := rfl

@[ext] lemma ext {ω₁ ω₂ : State A} (h : ∀ a, ω₁ a = ω₂ a) : ω₁ = ω₂ :=
  DFunLike.ext ω₁ ω₂ h

/-! ### Norm -/

/-- A state as a continuous linear functional `A →L[ℂ] ℂ`. -/
noncomputable def toContinuousLinearMap : A →L[ℂ] ℂ := ⟨ω.toLinearMap, map_continuous ω⟩

@[simp] lemma toContinuousLinearMap_apply (a : A) : ω.toContinuousLinearMap a = ω a := rfl

/-- `‖ω‖ = 1`. -/
lemma norm_toContinuousLinearMap : ‖ω.toContinuousLinearMap‖ = 1 := ω.norm_eq_one

/-- `‖ω a‖ ≤ ‖a‖`. -/
lemma norm_apply_le (a : A) : ‖ω a‖ ≤ ‖a‖ := by
  simpa [norm_toContinuousLinearMap] using ω.toContinuousLinearMap.le_opNorm a

/-- States are `1`-Lipschitz. -/
lemma lipschitzWith_one : LipschitzWith 1 ω := by
  have h : ‖ω.toContinuousLinearMap‖₊ = 1 := NNReal.eq ω.norm_toContinuousLinearMap
  simpa [h] using ω.toContinuousLinearMap.lipschitz

lemma continuous : Continuous ω := map_continuous ω

/-! ### Positivity -/

/-- `0 ≤ ω a` for every positive `a`. -/
lemma apply_nonneg {a : A} (ha : 0 ≤ a) : 0 ≤ ω a := ω.toPositiveLinearMap.map_nonneg ha

/-- `0 ≤ ω (a* a)`. -/
lemma apply_star_mul_self_nonneg (a : A) : 0 ≤ ω (star a * a) :=
  ω.apply_nonneg (star_mul_self_nonneg a)

/-- `0 ≤ Re ω (a* a)`. -/
lemma re_apply_star_mul_self_nonneg (a : A) : 0 ≤ (ω (star a * a)).re :=
  (Complex.nonneg_iff.mp (ω.apply_star_mul_self_nonneg a)).1

/-- `ω (a* a)` is real: `Re ω (a* a) = ω (a* a)`. -/
lemma ofReal_re_apply_star_mul_self (a : A) : ((ω (star a * a)).re : ℂ) = ω (star a * a) :=
  Complex.ext rfl (Complex.nonneg_iff.mp (ω.apply_star_mul_self_nonneg a)).2

/-- The Cauchy–Schwarz inequality for a state: `|ω (a* b)|² ≤ ω (a* a) ω (b* b)`.

It is the Cauchy–Schwarz inequality for the semi-inner product `⟪a, b⟫ = ω (a* b)` of Mathlib's
GNS pre-Hilbert space `PositiveLinearMap.PreGNS`. -/
lemma norm_apply_star_mul_sq_le (a b : A) :
    ‖ω (star a * b)‖ ^ 2 ≤ (ω (star a * a)).re * (ω (star b * b)).re := by
  set f := ω.toPositiveLinearMap
  have hsq (x : A) : ‖f.toPreGNS x‖ ^ 2 = (ω (star x * x)).re := by
    rw [← inner_self_eq_norm_sq (𝕜 := ℂ), preGNS_inner_def]
    rfl
  have h : ‖ω (star a * b)‖ ≤ ‖f.toPreGNS a‖ * ‖f.toPreGNS b‖ := by
    simpa [preGNS_inner_def, f] using norm_inner_le_norm (𝕜 := ℂ) (f.toPreGNS a) (f.toPreGNS b)
  calc ‖ω (star a * b)‖ ^ 2
      ≤ (‖f.toPreGNS a‖ * ‖f.toPreGNS b‖) ^ 2 := by gcongr
    _ = (ω (star a * a)).re * (ω (star b * b)).re := by rw [mul_pow, hsq, hsq]

/-- `|ω a|² ≤ ω (a* a)`.

For a unital algebra this is Cauchy–Schwarz against `1`; in general it is Cauchy–Schwarz
against the self-adjoint contractions `e` of an approximate unit, `|ω (e a)|² ≤ ω (e* e) ω (a* a)
≤ ω (a* a)`, in the limit `e a → a`. -/
lemma norm_apply_sq_le (a : A) : ‖ω a‖ ^ 2 ≤ (ω (star a * a)).re := by
  have h_approx := CStarAlgebra.increasingApproximateUnit (A := A)
  haveI : (CStarAlgebra.approximateUnit A).NeBot := h_approx.toIsApproximateUnit.neBot
  -- `ω (e a) → ω a` along the approximate unit, hence `‖ω (e a)‖² → ‖ω a‖²`.
  have h_tendsto : Tendsto (fun e => ‖ω (e * a)‖ ^ 2) (CStarAlgebra.approximateUnit A)
      (𝓝 (‖ω a‖ ^ 2)) :=
    ((continuous_norm.pow 2).tendsto _).comp
      ((ω.continuous.tendsto _).comp (h_approx.tendsto_mul_right a))
  refine le_of_tendsto h_tendsto ?_
  filter_upwards [h_approx.eventually_star_eq, h_approx.eventually_nnnorm] with e he_star he_norm
  have he : ‖e‖ ≤ 1 := by simpa using he_norm
  have hee : (ω (star e * e)).re ≤ 1 :=
    calc (ω (star e * e)).re
        ≤ ‖ω (star e * e)‖ := Complex.re_le_norm _
      _ ≤ ‖star e * e‖ := ω.norm_apply_le _
      _ = ‖e‖ * ‖e‖ := CStarRing.norm_star_mul_self
      _ ≤ 1 := by nlinarith [norm_nonneg e]
  calc ‖ω (e * a)‖ ^ 2
      = ‖ω (star e * a)‖ ^ 2 := by rw [he_star]
    _ ≤ (ω (star e * e)).re * (ω (star a * a)).re := ω.norm_apply_star_mul_sq_le e a
    _ ≤ 1 * (ω (star a * a)).re := by gcongr; exact ω.re_apply_star_mul_self_nonneg a
    _ = (ω (star a * a)).re := one_mul _

/-! ### Construction from a continuous functional -/

/-- The state defined by a continuous linear functional `f` of norm one that sends positive
elements to nonnegative numbers.  Positivity is usually checked on the `a* a` alone, via
`StarOrderedRing.map_nonneg_of_star_mul_self_nonneg`. -/
noncomputable def ofContinuousLinearMap (f : A →L[ℂ] ℂ) (hf : ∀ a, 0 ≤ a → 0 ≤ f a)
    (h : ‖f‖ = 1) : State A :=
  let g : A →ₚ[ℂ] ℂ := PositiveLinearMap.mk₀ f.toLinearMap hf
  { toPositiveLinearMap := g
    norm_eq_one := by
      rw [show (⟨g.toLinearMap, map_continuous g⟩ : A →L[ℂ] ℂ) = f from
        ContinuousLinearMap.ext fun _ => rfl]
      exact h }

@[simp] lemma ofContinuousLinearMap_apply (f : A →L[ℂ] ℂ) (hf : ∀ a, 0 ≤ a → 0 ≤ f a)
    (h : ‖f‖ = 1) (a : A) : ofContinuousLinearMap f hf h a = f a := rfl

end State
