/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import QuantumSystem.Analysis.CStarAlgebra.Representation.Conjugation
public import QuantumSystem.Physics.LocalNet.QuasiLocalAlgebra

/-!
# The DHR selection criterion

Doplicher–Haag–Roberts superselection theory singles out, among the representations of the
quasi-local C⋆-algebra `𝔄` of a local net, those that are indistinguishable from a reference
representation `π₀` (the vacuum representation) by measurements far away: a representation `R`
satisfies the **DHR selection criterion** if for every localisation region `Λ` the restrictions of
`R` and `π₀` to the observables `𝔄(Λ')` localised in the causal complement of `Λ` are unitarily
equivalent. Here `𝔄(Λ')` is generated by the local algebras `𝔄(O₁)` of the regions `O₁` outside
`Λ`, so the equivalence is stated region by region on those local algebras.

## Localisation regions

The localisation regions are a family of their own (`LocalisationRegions K C`), not the index set
`K` of the net. Doplicher–Haag–Roberts localise in double cones, which form the index set itself
(`LocalisationRegions.ofOrthogonal`). Naaijkens' lattice criterion localises in *cones* `Λ ⊂ ℤ²`
and restricts to `𝔄(Λᶜ)`: a cone is an infinite region and is not a region of the net over finite
sets of sites at all. The relation between the two kinds of region is `Outside O₁ Λ`, "`O₁` lies in
the causal complement of `Λ`".

Quantifying over the index set itself would be wrong on the lattice. There the empty region is
causally orthogonal to every region, so at `Λ = ∅` the criterion asks `U R(X) = π₀(X) U` on every
local algebra; these are dense in `𝔄`, so it would force `R ≅ π₀` and leave no sector. The axiom
`LocalisationRegions.exists_not_outside` — the causal complement of a localisation region is a
proper part of the net — rules out this degeneracy at `Λ = ∅`, and its companion
`LocalisationRegions.exists_outside` — every region of the net lies outside some localisation
region — rules out the opposite one, an `Outside` relating nothing, under which the criterion
would only compare Hilbert dimensions. These are necessary conditions, not a characterisation of
the physically right family: on a quantum spin system the finite sets of sites satisfy both and
still give only the trivial irreducible sector (see the TODO below), which is why the literature
localises in cones.

The reference representation is an arbitrary `CStarRep` of `𝔄`: the vacuum representation is the
case the literature treats, but the criterion uses nothing about it.

Conjugating `R` by a unitary `U` witnessing the criterion at `Λ` gives a representation
`R.conjBy U` on the Hilbert space of `π₀` itself, and it *coincides* with `π₀` on every observable
localised outside `Λ` (`LocalNet.conjBy_π_ιLocalCStar_eq_of_isDHRIntertwiner`). This is the step
from which, in the presence of Haag duality, one reads off an endomorphism of `𝔄` localised in `Λ`
(Naaijkens, §3.2); Haag duality and the localised endomorphisms are not formalised here.

## Main definitions

* `LocalisationRegions K C` — a family `C` of localisation regions for a net over `K`, with the
  relation `Outside O₁ Λ`; `LocalisationRegions.ofOrthogonal` takes `C = K` with `Outside = ⟂`
  for a causal index set with no self-orthogonal region, and `LocalisationRegions.ofNonempty`
  takes the nonempty sets of an infinite set of sites for a lattice net over `Finset α`, the
  ambient family of the lattice's cones.
* `LocalNet.IsDHRIntertwiner` — `U : R.H ≃ₗᵢ[ℂ] π₀.H` intertwines `R` and `π₀` on every
  observable localised outside a localisation region `Λ`.
* `LocalNet.SatisfiesDHR` — the DHR selection criterion: such a `U` exists for every `Λ`.

## Main results

* `LocalNet.conjBy_π_ιLocalCStar_eq_of_isDHRIntertwiner` — **the conjugated representation acts
  as `π₀` outside the localisation region**.
* `LocalNet.satisfiesDHR_refl` — the reference representation satisfies the criterion.

## TODO

* Naaijkens' cones `Λ ⊂ ℤ²` as a type of localisation regions for the lattice net over
  `Finset (ℤ × ℤ)`, a subfamily of `LocalisationRegions.ofNonempty`, and its instance. On the
  ambient family a finite `Λ` is nondegenerate but physically uninformative for a quantum spin
  system (site algebras `M_d`): there `𝔄 = 𝔄(Λ) ⊗ 𝔄(Λᶜ)` with `𝔄(Λ)` a full matrix algebra, and
  counting multiplicities shows that an irreducible `R` meeting the criterion at a finite `Λ` is
  equivalent to `π₀`.
* Localisation *in* a region (`O ≤ Λ`) and the compatibility of the two relations with `⟂`, needed
  for endomorphisms localised in `Λ` and for Haag duality.

## References

* S. Doplicher, R. Haag, J. E. Roberts, *Local observables and particle statistics I*,
  Comm. Math. Phys. 23 (1971), 199–230
* P. Naaijkens, *Anyons in Infinite Quantum Systems*, PhD thesis, Radboud University Nijmegen
  (2012), §3.2
-/

@[expose] public section

open scoped CausalOrthogonality

/-- A family `C` of **localisation regions** for a net over the index set `K`, with the relation
    `Outside O₁ Λ`: the region `O₁` of the net lies in the causal complement of the localisation
    region `Λ`. The relation is hereditary in `O₁`, and the causal complement of a localisation
    region is never all of `K` (`exists_not_outside`) and every region lies outside some
    localisation region (`exists_outside`).

    This is model-dependent geometric input, like `⟂` itself: Doplicher–Haag–Roberts take the
    double cones with spacelike separation (`LocalisationRegions.ofOrthogonal`), Naaijkens the
    cones of the lattice with disjointness. The two nondegeneracy axioms exclude a localisation
    region whose complement contains every region, at which the DHR criterion would collapse onto
    unitary equivalence with `π₀` on the whole quasi-local algebra, and an `Outside` relation
    under which no region is outside anything, at which the criterion would hold for any `R` on a
    Hilbert space of the dimension of `π₀`'s. They are the analogue of the causal complements of
    `CausalIndexSet`, not a characterisation of the physically right family. -/
class LocalisationRegions (K : Type*) [Preorder K] (C : Type*) where
  /-- `Outside O₁ Λ`: the region `O₁` lies in the causal complement of the localisation region
      `Λ`. -/
  Outside : K → C → Prop
  /-- Shrinking a region keeps it outside `Λ`. -/
  outside_mono_left : ∀ ⦃O₀ O₁ : K⦄ ⦃Λ : C⦄, O₀ ≤ O₁ → Outside O₁ Λ → Outside O₀ Λ
  /-- **Nondegeneracy**: some region of the net is not outside `Λ`. -/
  exists_not_outside : ∀ Λ : C, ∃ O : K, ¬ Outside O Λ
  /-- **Causal complements**: every region of the net lies outside some localisation region. -/
  exists_outside : ∀ O : K, ∃ Λ : C, Outside O Λ

namespace LocalisationRegions

/-- **Localisation in the regions of the net** (Doplicher–Haag–Roberts): on a causal index set
    with no self-orthogonal region, such as the double cones of Minkowski space, the regions
    themselves are the localisation regions and `Outside` is causal orthogonality. `Λ` itself is
    not outside `Λ`, and the causal complements of `CausalIndexSet` supply the localisation
    regions a region lies outside of. A `def` rather than an instance, since the lattice index set
    has the self-orthogonal empty region. -/
@[reducible] def ofOrthogonal (K : Type*) [Preorder K] [CausalOrthogonality K] [CausalIndexSet K]
    (h : ∀ O : K, ¬ O ⟂ O) : LocalisationRegions K K where
  Outside O₁ Λ := O₁ ⟂ Λ
  outside_mono_left _ _ _ h₀ h := h.mono_left h₀
  exists_not_outside Λ := ⟨Λ, h Λ⟩
  exists_outside O := CausalIndexSet.exists_orthogonal O

/-- **The ambient lattice localisation regions**: the nonempty sets of sites `Λ`, possibly
    infinite, for a lattice net over the finite sets of an infinite set of sites; a finite region
    is outside `Λ` when it is disjoint from it. `{p}` for a site `p ∈ Λ` is not outside `Λ` — the
    empty set is excluded because every region is disjoint from it — and a finite region `O`
    lies outside `{p}` for a site `p ∉ O`.

    This is the ambient family of the literature's localisation regions, not the family itself:
    it contains the finite sets of sites, at which the DHR criterion on a quantum spin system
    admits only the trivial irreducible sector (see the module docstring). Naaijkens' cones are a
    subfamily, not yet built; this is a `def` rather than an instance so that the cones can carry
    the instance. -/
@[reducible] def ofNonempty (α : Type*) [Infinite α] :
    LocalisationRegions (Finset α) {Λ : Set α // Λ.Nonempty} where
  Outside O Λ := Disjoint (O : Set α) Λ
  outside_mono_left _ _ _ h₀ h := h.mono_left (Finset.coe_subset.2 h₀)
  exists_not_outside Λ :=
    let ⟨p, hp⟩ := Λ.2
    ⟨{p}, fun h => Set.disjoint_left.1 h (Finset.mem_coe.2 (Finset.mem_singleton_self p)) hp⟩
  exists_outside O :=
    let ⟨p, hp⟩ := Infinite.exists_notMem_finset O
    ⟨⟨{p}, Set.singleton_nonempty p⟩, Set.disjoint_singleton_right.2 (Finset.mem_coe.not.2 hp)⟩

end LocalisationRegions

namespace LocalNet

open LocalisationRegions (Outside)

variable {K : Type*} [Preorder K] [CausalOrthogonality K] [IsDirectedOrder K] [Nonempty K]
variable {C : Type*} [LocalisationRegions K C]
variable (N : LocalNet K) [N.Faithful]

/-- `U : R.H ≃ₗᵢ[ℂ] π₀.H` is a **DHR intertwiner for the localisation region `Λ`**: it intertwines
    `R` with the reference representation `π₀` on every observable localised in a region `O₁`
    outside `Λ`, that is, `U R(X) = π₀(X) U` for `X ∈ 𝔄(O₁)`. -/
def IsDHRIntertwiner (π₀ R : CStarRep N.quasiLocalCStarAlgebra) (Λ : C)
    (U : R.H ≃ₗᵢ[ℂ] π₀.H) : Prop :=
  ∀ ⦃O₁ : K⦄, Outside O₁ Λ → ∀ X : N.algebra O₁,
    (U : R.H →L[ℂ] π₀.H) ∘L R.π (N.ιLocalCStar O₁ X) =
      π₀.π (N.ιLocalCStar O₁ X) ∘L (U : R.H →L[ℂ] π₀.H)

variable (C) in
/-- The **DHR selection criterion** (Doplicher–Haag–Roberts) for the localisation regions `C`:
    for every `Λ : C`, the representation `R` is unitarily equivalent to the reference
    representation `π₀` on the observables localised in the causal complement of `Λ`. -/
def SatisfiesDHR (π₀ R : CStarRep N.quasiLocalCStarAlgebra) : Prop :=
  ∀ Λ : C, ∃ U : R.H ≃ₗᵢ[ℂ] π₀.H, N.IsDHRIntertwiner π₀ R Λ U

variable {N}

/-- **The conjugated representation acts as `π₀` outside the localisation region**: if `U` is a
    DHR intertwiner for `Λ`, then `R.conjBy U`, a representation on the Hilbert space of `π₀`,
    agrees with `π₀` on every observable localised in a region `O₁` outside `Λ`. -/
theorem conjBy_π_ιLocalCStar_eq_of_isDHRIntertwiner {π₀ R : CStarRep N.quasiLocalCStarAlgebra}
    {Λ : C} {U : R.H ≃ₗᵢ[ℂ] π₀.H} (hU : N.IsDHRIntertwiner π₀ R Λ U) {O₁ : K}
    (hO₁ : Outside O₁ Λ) (X : N.algebra O₁) :
    (R.conjBy U).π (N.ιLocalCStar O₁ X) = π₀.π (N.ιLocalCStar O₁ X) :=
  CStarRep.conjBy_π_eq_of_intertwined U (hU hO₁ X)

/-- Under the DHR selection criterion, for every localisation region `Λ` some conjugate of `R` on
    the Hilbert space of `π₀` agrees with `π₀` on every observable localised in a region `O₁`
    outside `Λ`. -/
lemma exists_conjBy_π_ιLocalCStar_eq_of_satisfiesDHR {π₀ R : CStarRep N.quasiLocalCStarAlgebra}
    (h : N.SatisfiesDHR C π₀ R) (Λ : C) :
    ∃ U : R.H ≃ₗᵢ[ℂ] π₀.H, ∀ ⦃O₁ : K⦄, Outside O₁ Λ → ∀ X : N.algebra O₁,
      (R.conjBy U).π (N.ιLocalCStar O₁ X) = π₀.π (N.ιLocalCStar O₁ X) :=
  (h Λ).imp fun _ hU _ hO₁ X => conjBy_π_ιLocalCStar_eq_of_isDHRIntertwiner hU hO₁ X

variable (N) in
/-- The identity is a DHR intertwiner of the reference representation with itself, for every
    localisation region. -/
lemma isDHRIntertwiner_refl (π₀ : CStarRep N.quasiLocalCStarAlgebra) (Λ : C) :
    N.IsDHRIntertwiner π₀ π₀ Λ (LinearIsometryEquiv.refl ℂ π₀.H) := fun _ _ _ => by
  ext
  rfl

variable (N C) in
/-- The reference representation satisfies the DHR selection criterion. -/
lemma satisfiesDHR_refl (π₀ : CStarRep N.quasiLocalCStarAlgebra) : N.SatisfiesDHR C π₀ π₀ :=
  fun Λ => ⟨_, N.isDHRIntertwiner_refl π₀ Λ⟩

end LocalNet
