/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import QuantumSystem.Analysis.CStarAlgebra.Representation.Conjugation
public import QuantumSystem.Physics.LocalNet.QuasiLocalAlgebra

/-!
# The DHR selection criterion

Doplicher–Haag–Roberts superselection theory singles out, among the representations of the
quasi-local C⋆-algebra `𝔄` of a local net, those that are indistinguishable from a reference
representation `π₀` (the vacuum representation) by measurements far away: a representation `R`
satisfies the **DHR selection criterion** if for every localisation region `Λ` the restrictions of
`R` and `π₀` to the observables `𝔄(Λ')` localised in the causal complement of `Λ` are unitarily
equivalent. Here `𝔄(Λ')` is generated by the local algebras `𝔄(O₁)` of the regions `O₁` outside
`Λ`, so the equivalence is stated region by region on those local algebras.

## Localisation regions

The localisation regions are a family of their own (`LocalizationRegions K C`), not the index set
`K` of the net. Doplicher–Haag–Roberts localise in double cones, which form the index set itself
(`LocalizationRegions.ofOrthogonal`). Naaijkens' lattice criterion localises in *cones* `Λ ⊂ ℤ²`
and restricts to `𝔄(Λᶜ)`: a cone is an infinite region and is not a region of the net over finite
sets of sites at all. The relations between the two kinds of region are `Outside O₁ Λ`, "`O₁` lies
in the causal complement of `Λ`", which the criterion uses, and `Inside O Λ`, "`O` lies in `Λ`",
which a region outside `Λ` must be causally orthogonal to.

Quantifying over the index set itself would be wrong on the lattice. There the empty region is
causally orthogonal to every region, so at `Λ = ∅` the criterion asks `U R(X) = π₀(X) U` on every
local algebra; these are dense in `𝔄`, so it would force `R ≅ π₀` and leave no sector. The axiom
`LocalizationRegions.exists_inside_not_orthogonal` — a localisation region contains a region of
the net that is not orthogonal to itself — rules out this degeneracy at `Λ = ∅`: with the
compatibility axiom it makes the causal complement of `Λ` a proper part of the net
(`LocalizationRegions.exists_not_outside`). Its companion
`LocalizationRegions.exists_outside` — every region of the net lies outside some localisation
region — rules out the opposite one, an `Outside` relating nothing, under which the criterion
would only compare Hilbert dimensions. These are necessary conditions, not a characterisation of
the physically right family: on a quantum spin system the finite sets of sites satisfy both and
still give only the trivial irreducible sector (see the TODO below), which is why the literature
localises in cones.

The reference representation is an arbitrary `CStarRep` of `𝔄`: the vacuum representation is the
case the literature treats, but the criterion uses nothing about it.

Conjugating `R` by a unitary `U` witnessing the criterion at `Λ` gives a representation
`R.conjBy U` on the Hilbert space of `π₀` itself, and it *coincides* with `π₀` on every observable
localised outside `Λ` (`LocalNet.conjBy_π_ιLocalCStar_eq_of_isDHRIntertwiner`). This is the step
from which, in the presence of Haag duality, one reads off an endomorphism of `𝔄` localised in `Λ`
(Naaijkens, §3.2); Haag duality and the localised endomorphisms are not formalised here.

## Main definitions

* `LocalizationRegions K C` — a family `C` of localisation regions for a net over `K`, with the
  relations `Outside O₁ Λ` and `Inside O Λ`, compatible with `⟂`;
  `LocalizationRegions.ofOrthogonal` takes `C = K` with `Outside = ⟂` and `Inside = ≤` for a
  causal index set with no self-orthogonal region, and `LocalizationRegions.ofNonempty` takes the
  nonempty sets of an infinite set of sites for a lattice net over `Finset α`, with disjointness
  and inclusion, the ambient family of the lattice's cones.
* `LocalNet.IsDHRIntertwiner` — `U : R.H ≃ₗᵢ[ℂ] π₀.H` intertwines `R` and `π₀` on every
  observable localised outside a localisation region `Λ`.
* `LocalNet.SatisfiesDHR` — the DHR selection criterion: such a `U` exists for every `Λ`.

## Main results

* `LocalNet.conjBy_π_ιLocalCStar_eq_of_isDHRIntertwiner` — **the conjugated representation acts
  as `π₀` outside the localisation region**.
* `LocalNet.satisfiesDHR_refl` — the reference representation satisfies the criterion.
* `LocalizationRegions.exists_not_outside` — the causal complement of a localisation region is a
  proper part of the net.

## TODO

* Naaijkens' cones `Λ ⊂ ℤ²` as a type of localisation regions for the lattice net over
  `Finset (ℤ × ℤ)`, a subfamily of `LocalizationRegions.ofNonempty`, and its instance. On the
  ambient family a finite `Λ` is nondegenerate but physically uninformative for a quantum spin
  system (site algebras `M_d`): there `𝔄 = 𝔄(Λ) ⊗ 𝔄(Λᶜ)` with `𝔄(Λ)` a full matrix algebra, and
  counting multiplicities shows that an irreducible `R` meeting the criterion at a finite `Λ` is
  equivalent to `π₀`.

## References

* S. Doplicher, R. Haag, J. E. Roberts, *Local observables and particle statistics I*,
  Comm. Math. Phys. 23 (1971), 199–230
* P. Naaijkens, *Anyons in Infinite Quantum Systems*, PhD thesis, Radboud University Nijmegen
  (2012), §3.2
-/

@[expose] public section

open scoped CausalOrthogonality

/-- A family `C` of **localisation regions** for a net over the index set `K`, with two relations
    between the regions of the net and the localisation regions: `Outside O₁ Λ`, the region `O₁`
    lies in the causal complement of `Λ`, and `Inside O Λ`, the region `O` lies in `Λ`. Both are
    hereditary in the region of the net, and they are compatible with causal orthogonality: a
    region outside `Λ` is causally orthogonal to every region inside `Λ`
    (`orthogonal_of_outside_of_inside`). Every localisation region contains a region of the net
    that is not causally orthogonal to itself (`exists_inside_not_orthogonal`), and every region
    of the net lies outside some localisation region (`exists_outside`).

    This is model-dependent geometric input, like `⟂` itself: Doplicher–Haag–Roberts take the
    double cones with spacelike separation (`LocalizationRegions.ofOrthogonal`), Naaijkens the
    cones of the lattice with disjointness. `Outside` has no meaning of its own: it is read
    relative to `Inside`, and it is `Inside` that fixes which side of `Λ` the relation `Outside`
    describes. Through the compatibility axiom and `exists_inside_not_orthogonal`, a region outside
    `Λ` lies on the opposite side of `Λ` from the regions inside `Λ`: an `Outside` that really meant
    "inside", such as `O₁ ⊆ Λ` on the lattice, would make the region supplied by
    `exists_inside_not_orthogonal` orthogonal to itself. The two nondegeneracy axioms exclude a
    localisation region whose complement contains every region (`exists_not_outside` follows), at
    which the DHR criterion would collapse onto unitary equivalence with `π₀` on the whole
    quasi-local algebra, and an `Outside` relation under which no region is outside anything, at
    which the criterion would hold for any `R` on a Hilbert space of the dimension of `π₀`'s. They
    are the analogue of the causal complements of `CausalIndexSet`, not a characterisation of the
    physically right family. -/
class LocalizationRegions (K : Type*) [Preorder K] [CausalOrthogonality K] (C : Type*) where
  /-- `Outside O₁ Λ`: the region `O₁` lies in the causal complement of the localisation region
      `Λ`, on the side opposite to the regions `Inside` `Λ` (`orthogonal_of_outside_of_inside`). -/
  Outside : K → C → Prop
  /-- `Inside O Λ`: the region `O` lies in the localisation region `Λ`. -/
  Inside : K → C → Prop
  /-- Shrinking a region keeps it outside `Λ`. -/
  outside_mono_left : ∀ ⦃O₀ O₁ : K⦄ ⦃Λ : C⦄, O₀ ≤ O₁ → Outside O₁ Λ → Outside O₀ Λ
  /-- Shrinking a region keeps it inside `Λ`. -/
  inside_mono_left : ∀ ⦃O₀ O₁ : K⦄ ⦃Λ : C⦄, O₀ ≤ O₁ → Inside O₁ Λ → Inside O₀ Λ
  /-- **Compatibility with causal orthogonality**: a region outside `Λ` is causally orthogonal to
      every region inside `Λ`. -/
  orthogonal_of_outside_of_inside :
    ∀ ⦃O₁ O₂ : K⦄ ⦃Λ : C⦄, Outside O₁ Λ → Inside O₂ Λ → O₁ ⟂ O₂
  /-- **Nondegeneracy**: `Λ` contains a region of the net that is not causally orthogonal to
      itself. -/
  exists_inside_not_orthogonal : ∀ Λ : C, ∃ O : K, Inside O Λ ∧ ¬ O ⟂ O
  /-- **Causal complements**: every region of the net lies outside some localisation region. -/
  exists_outside : ∀ O : K, ∃ Λ : C, Outside O Λ

namespace LocalizationRegions

variable {K : Type*} [Preorder K] [CausalOrthogonality K] {C : Type*} [LocalizationRegions K C]

/-- **The causal complement of a localisation region is a proper part of the net**: some region
    is not outside `Λ`. A region inside `Λ` that is not orthogonal to itself
    (`exists_inside_not_orthogonal`) cannot lie outside `Λ`, by the compatibility axiom. -/
lemma exists_not_outside (Λ : C) : ∃ O : K, ¬ Outside O Λ :=
  let ⟨O, hin, hO⟩ := exists_inside_not_orthogonal Λ
  ⟨O, fun hout => hO (orthogonal_of_outside_of_inside hout hin)⟩

/-- **Localisation in the regions of the net** (Doplicher–Haag–Roberts): on a causal index set
    with no self-orthogonal region, such as the double cones of Minkowski space, the regions
    themselves are the localisation regions, `Outside` is causal orthogonality and `Inside` is the
    order of `K`. `Λ` itself is inside `Λ`, and the causal complements of `CausalIndexSet` supply
    the localisation regions a region lies outside of. A `def` rather than an instance, since the
    lattice index set has the self-orthogonal empty region; the nonempty finite sets of sites
    are an index set it applies to (`LocalNet.Examples.nonemptyFinsetLocalizationRegions`). -/
@[reducible] def ofOrthogonal (K : Type*) [Preorder K] [CausalOrthogonality K] [CausalIndexSet K]
    (h : ∀ O : K, ¬ O ⟂ O) : LocalizationRegions K K where
  Outside O₁ Λ := O₁ ⟂ Λ
  Inside O Λ := O ≤ Λ
  outside_mono_left _ _ _ h₀ h := h.mono_left h₀
  inside_mono_left _ _ _ h₀ h := h₀.trans h
  orthogonal_of_outside_of_inside _ _ _ hout hin := hout.mono_right hin
  exists_inside_not_orthogonal Λ := ⟨Λ, le_rfl, h Λ⟩
  exists_outside O := CausalIndexSet.exists_orthogonal O

/-- **The ambient lattice localisation regions**: the nonempty sets of sites `Λ`, possibly
    infinite, for a lattice net over the finite sets of an infinite set of sites; a finite region
    is outside `Λ` when it is disjoint from it, and inside `Λ` when it is contained in it. `{p}`
    for a site `p ∈ Λ` is inside `Λ` and not orthogonal to itself — the empty set is excluded
    because it contains no such region — and a finite region `O` lies outside `{p}` for a site
    `p ∉ O`.

    This is the ambient family of the literature's localisation regions, not the family itself:
    it contains the finite sets of sites, at which the DHR criterion on a quantum spin system
    admits only the trivial irreducible sector (see the module docstring). Naaijkens' cones are a
    subfamily, not yet built; this is a `def` rather than an instance so that the cones can carry
    the instance. -/
@[reducible] def ofNonempty (α : Type*) [Infinite α] :
    LocalizationRegions (Finset α) {Λ : Set α // Λ.Nonempty} where
  Outside O Λ := Disjoint (O : Set α) Λ
  Inside O Λ := (O : Set α) ⊆ Λ
  outside_mono_left _ _ _ h₀ h := h.mono_left (Finset.coe_subset.2 h₀)
  inside_mono_left _ _ _ h₀ h := (Finset.coe_subset.2 h₀).trans h
  orthogonal_of_outside_of_inside _ _ _ hout hin := Finset.disjoint_coe.1 (hout.mono_right hin)
  exists_inside_not_orthogonal Λ :=
    let ⟨p, hp⟩ := Λ.2
    ⟨{p}, by simpa using hp, fun h => Finset.singleton_ne_empty p (disjoint_self.1 h)⟩
  exists_outside O :=
    let ⟨p, hp⟩ := Infinite.exists_notMem_finset O
    ⟨⟨{p}, Set.singleton_nonempty p⟩, Set.disjoint_singleton_right.2 (Finset.mem_coe.not.2 hp)⟩

end LocalizationRegions

namespace LocalNet

open LocalizationRegions (Outside)

variable {K : Type*} [Preorder K] [CausalOrthogonality K] [IsDirectedOrder K] [Nonempty K]
variable {C : Type*} [LocalizationRegions K C]
variable (N : LocalNet K) [N.Faithful]

/-- `U : R.H ≃ₗᵢ[ℂ] π₀.H` is a **DHR intertwiner for the localisation region `Λ`**: it intertwines
    `R` with the reference representation `π₀` on every observable localised in a region `O₁`
    outside `Λ`, that is, `U R(X) = π₀(X) U` for `X ∈ 𝔄(O₁)`. -/
def IsDHRIntertwiner (π₀ R : CStarRep N.quasiLocalCStarAlgebra) (Λ : C)
    (U : R.H ≃ₗᵢ[ℂ] π₀.H) : Prop :=
  ∀ ⦃O₁ : K⦄, Outside O₁ Λ → ∀ X : N.algebra O₁,
    (U : R.H →L[ℂ] π₀.H) ∘L R.π (N.ιLocalCStar O₁ X) =
      π₀.π (N.ιLocalCStar O₁ X) ∘L (U : R.H →L[ℂ] π₀.H)

variable (C) in
/-- The **DHR selection criterion** (Doplicher–Haag–Roberts) for the localisation regions `C`:
    for every `Λ : C`, the representation `R` is unitarily equivalent to the reference
    representation `π₀` on the observables localised in the causal complement of `Λ`. -/
def SatisfiesDHR (π₀ R : CStarRep N.quasiLocalCStarAlgebra) : Prop :=
  ∀ Λ : C, ∃ U : R.H ≃ₗᵢ[ℂ] π₀.H, N.IsDHRIntertwiner π₀ R Λ U

variable {N}

/-- **The conjugated representation acts as `π₀` outside the localisation region**: if `U` is a
    DHR intertwiner for `Λ`, then `R.conjBy U`, a representation on the Hilbert space of `π₀`,
    agrees with `π₀` on every observable localised in a region `O₁` outside `Λ`. -/
theorem conjBy_π_ιLocalCStar_eq_of_isDHRIntertwiner {π₀ R : CStarRep N.quasiLocalCStarAlgebra}
    {Λ : C} {U : R.H ≃ₗᵢ[ℂ] π₀.H} (hU : N.IsDHRIntertwiner π₀ R Λ U) {O₁ : K}
    (hO₁ : Outside O₁ Λ) (X : N.algebra O₁) :
    (R.conjBy U).π (N.ιLocalCStar O₁ X) = π₀.π (N.ιLocalCStar O₁ X) :=
  CStarRep.conjBy_π_eq_of_intertwined U (hU hO₁ X)

/-- Under the DHR selection criterion, for every localisation region `Λ` some conjugate of `R` on
    the Hilbert space of `π₀` agrees with `π₀` on every observable localised in a region `O₁`
    outside `Λ`. -/
lemma exists_conjBy_π_ιLocalCStar_eq_of_satisfiesDHR {π₀ R : CStarRep N.quasiLocalCStarAlgebra}
    (h : N.SatisfiesDHR C π₀ R) (Λ : C) :
    ∃ U : R.H ≃ₗᵢ[ℂ] π₀.H, ∀ ⦃O₁ : K⦄, Outside O₁ Λ → ∀ X : N.algebra O₁,
      (R.conjBy U).π (N.ιLocalCStar O₁ X) = π₀.π (N.ιLocalCStar O₁ X) :=
  (h Λ).imp fun _ hU _ hO₁ X => conjBy_π_ιLocalCStar_eq_of_isDHRIntertwiner hU hO₁ X

variable (N) in
/-- The identity is a DHR intertwiner of the reference representation with itself, for every
    localisation region. -/
lemma isDHRIntertwiner_refl (π₀ : CStarRep N.quasiLocalCStarAlgebra) (Λ : C) :
    N.IsDHRIntertwiner π₀ π₀ Λ (LinearIsometryEquiv.refl ℂ π₀.H) := fun _ _ _ => by
  ext
  rfl

variable (N C) in
/-- The reference representation satisfies the DHR selection criterion. -/
lemma satisfiesDHR_refl (π₀ : CStarRep N.quasiLocalCStarAlgebra) : N.SatisfiesDHR C π₀ π₀ :=
  fun Λ => ⟨_, N.isDHRIntertwiner_refl π₀ Λ⟩

end LocalNet
