/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import QuantumSystem.Analysis.CStarAlgebra.GNS.Construction
public import QuantumSystem.Physics.LocalNet.SplitProperty

/-!
# Infinite lattice regions and the split property

On the finite regions of a lattice the split property says nothing about a spin net: every local
von Neumann algebra `𝓡(Λ)` of a finite region is a finite-dimensional factor, hence a type I factor,
and every inclusion between two of them splits. The lattice literature's split property — Matsui's
half-chain split property, Naaijkens' split property for cones — is a statement about **infinite**
regions. This module makes those regions available.

* The infinite regions are `Set α`, with causal orthogonality `Disjoint`
  (the `CausalOrthogonality (Set α)` instance in `QuantumSystem.Physics.LocalNet.Basic`).
* `ProperContainment.ofCThickening α δ` is the separating proper containment of a metric on the
  sites: `S₁ ⋐ S₂` iff the closed `δ`-thickening of `S₁` lies strictly inside `S₂`.
* `VonNeumannNet.extend` passes from a net of von Neumann algebras over the finite regions to the
  infinite ones: `𝓡(S)` is the von Neumann algebra generated by the `𝓡(Λ)` of the finite regions
  `Λ ⊆ S`. It agrees with the given net on finite regions (`VonNeumannNet.extend_algebra_coe`).
* `LocalNet.vonNeumannNetSet R` is that extension of the local von Neumann algebras of a
  representation, so `(N.vonNeumannNetSet R).SplitProperty` is the split property of a lattice net
  `N : LocalNet (Finset α)` on infinite regions.
* `LocalNet.IsSplitPairAt ω S₁ S₂` is the split property of a *state* `ω` on the quasi-local
  algebra for a pair of regions, in the GNS representation of `ω`, and
  `LocalNet.HasHalfChainSplit ω` is the **half-chain split property** in its split-inclusion
  form, the pair `(-∞, 0]`, `[1, ∞)` of the integer chain. Matsui's own definition is the
  quasi-equivalence of `ω` with the product `ω_L ⊗ ω_R` of its half-chain restrictions. The
  split-inclusion form implies it for every state, and the two agree for pure (more generally
  factor) states; their agreement for an arbitrary state is not claimed here.

## What is and is not expressible

Both half-chain forms are expressible. The *gapped* form follows from the nested split property:
on the integer chain with `ofCThickening ℤ 1`, `Set.Iic 0 ⋐ Set.Iic 2`, and
`VonNeumannNet.SplitProperty.isSplitPair` against `Set.Ici 3` gives `𝓡(Iic 0) ≤ 𝔑 ≤ 𝓡(Ici 3)′`
(`LocalNet.IsSplitPairAt.of_splitProperty`). Matsui's *gap-free* form, between `𝓡(Iic 0)` and
`𝓡(Ici 1)′`, cannot come from `⋐`, since `⋐` is irreflexive; it is stated directly as a split pair
(`VonNeumannNet.IsSplitPair`, `LocalNet.HasHalfChainSplit`).

Matsui's defining form — `ω` quasi-equivalent to `ω_L ⊗ ω_R` — is not expressible yet: it needs
the identification of the chain's quasi-local algebra with `𝔄_L ⊗ 𝔄_R` and product states on it,
neither of which is built. Its equivalence with the split-inclusion form is therefore not proved
either.

What is also not proved is Matsui's characterisation for pure states — the half-chain split
property holds iff `𝓡(Iic 0)` is a type I factor. The representation-theoretic input is
available — the GNS representation of a pure state is irreducible
(`GNS.Representation.isPure_iff_isIrreducible`) and so has commutant `ℂ1`
(`CStarRep.isIrreducible_iff_centralizer`) — but the argument also needs
joins of von Neumann algebras, which the development does not have yet. Cones need a cone region
type and are not built here. No spin net is built either, so no non-trivial positive model of the
infinite-region split property exists yet;
`QuantumSystem.Physics.LocalNet.Examples` has refuters and one-dimensional witnesses.

## TODO

* Matsui's quasi-equivalence form of the half-chain split property, once `𝔄 ≅ 𝔄_L ⊗ 𝔄_R` and
  product states are available, with the implication from `LocalNet.HasHalfChainSplit` (valid for
  every state) and the converse for pure, more generally factor, states.
* Settle the converse for an arbitrary, possibly mixed, state: whether quasi-equivalence of `ω`
  with `ω_L ⊗ ω_R` yields a type I factor `𝔑` with `𝓡_ω((-∞, 0]) ≤ 𝔑 ≤ 𝓡_ω([1, ∞))′` in the GNS
  representation of `ω` itself. Quasi-equivalence gives such a factor only after amplification,
  and it is not checked here whether it can be compressed back to the GNS space; until then the
  two forms are not asserted to agree beyond factor states.

## Notation

`𝓡(S)` in the prose above is documentation shorthand for `vnNet.extend.algebra S`, following the
convention stated in `QuantumSystem.Physics.LocalNet.Basic`.
-/

@[expose] public section

open scoped ProperContainment VonNeumannAlgebra ComplexOrder GNS

namespace ProperContainment

/-- **Proper containment of infinite lattice regions from a metric on the sites**: `S₁ ⋐ S₂` iff
    the closed `δ`-thickening `Metric.cthickening δ S₁` is a strict subset of `S₂`, for a
    *positive* width `δ`. The closed thickening is monotone and contains the region, so this is
    `ofThicken`; it is the metric form of the literature's separation "`Ō₁` lies inside `O₂` with
    room to spare" (`closure_subset_interior_of_properlyContained`).

    Positivity is what makes the room to spare: at `δ ≤ 0` the closed thickening is the closure,
    and on the discrete `Set ℤ` the model would collapse to `ofLT`, admitting the touching pair
    `Iic 0 ⋐ Iic 1`. On the integer chain `δ = 1` gives the nearest-neighbour buffer of the finite
    model `ProperContainment.integerChain`. A `def` rather than an instance, for the same reason as
    there: a global instance would fix one metric and one `δ` for every downstream `Set α`. -/
@[reducible] noncomputable def ofCThickening (α : Type*) [PseudoMetricSpace α]
    (δ : {δ : ℝ // 0 < δ}) : ProperContainment (Set α) :=
  ofThicken (fun _ _ h => h) (Metric.cthickening δ) Metric.self_subset_cthickening
    (fun _ _ h => Metric.cthickening_subset_of_subset δ h)

open scoped ProperContainment in
/-- **The metric proper containment is the literature's separation**: under
    `ofCThickening α δ`, `S₁ ⋐ S₂` puts the closure of `S₁` inside the interior of `S₂`. The open
    `δ`-thickening of `S₁` is an open set containing `closure S₁` (this is where `0 < δ` enters)
    and contained in the closed one, hence in `S₂`. -/
lemma closure_subset_interior_of_properlyContained {α : Type*} [PseudoMetricSpace α]
    {δ : {δ : ℝ // 0 < δ}} {S₁ S₂ : Set α}
    (h : letI := ofCThickening α δ; S₁ ⋐ S₂) : closure S₁ ⊆ interior S₂ :=
  (Metric.closure_subset_thickening δ.2 S₁).trans <| interior_maximal
    ((Metric.thickening_subset_cthickening (δ : ℝ) S₁).trans
      (show Metric.cthickening (δ : ℝ) S₁ < S₂ from h).le) Metric.isOpen_thickening

end ProperContainment

namespace VonNeumannNet

variable {α : Type*}
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- The operators localised in *some* finite region inside `S`: the union of the algebras
    `vnNet.algebra Λ` over the finite regions `Λ ⊆ S`. It generates `vnNet.extend.algebra S`. -/
def finiteLocalOperators (vnNet : VonNeumannNet (Finset α) H) (S : Set α) :
    Set (H →L[ℂ] H) :=
  ⋃ (Λ : Finset α) (_ : (Λ : Set α) ⊆ S), (vnNet.algebra Λ : Set (H →L[ℂ] H))

/-- Membership in `finiteLocalOperators`: `x` is localised in some finite region `Λ ⊆ S`, i.e.
`x ∈ vnNet.algebra Λ`. -/
lemma mem_finiteLocalOperators {vnNet : VonNeumannNet (Finset α) H} {S : Set α}
    {x : H →L[ℂ] H} :
    x ∈ vnNet.finiteLocalOperators S ↔ ∃ Λ : Finset α, (Λ : Set α) ⊆ S ∧ x ∈ vnNet.algebra Λ := by
  simp [finiteLocalOperators]

/-- **The extension of a finite-region net to infinite regions**: the von Neumann algebra of an
    arbitrary region `S` is the one generated by the algebras of the finite regions inside `S`,
    `𝓡(S) = (⋃_{Λ ⊆ S finite} 𝓡(Λ))″`. This is how the lattice literature assigns algebras to
    half-chains and cones. Isotony is monotonicity of `generated`; locality holds because every
    generator of `𝓡(S₁)` commutes with every generator of `𝓡(S₂)` and its adjoint, by locality of
    the finite net on the disjoint finite regions involved. -/
noncomputable def extend (vnNet : VonNeumannNet (Finset α) H) : VonNeumannNet (Set α) H where
  algebra S := VonNeumannAlgebra.generated (vnNet.finiteLocalOperators S)
  algebra_mono _ _ h := VonNeumannAlgebra.generated_mono fun x hx => by
    obtain ⟨Λ, hΛ, hx⟩ := mem_finiteLocalOperators.1 hx
    exact mem_finiteLocalOperators.2 ⟨Λ, hΛ.trans h, hx⟩
  algebra_le_commutant_of_orthogonal S₁ S₂ hd := by
    rw [VonNeumannAlgebra.commutant_generated]
    refine VonNeumannAlgebra.generated_le fun x hx => ?_
    obtain ⟨Λ₁, hΛ₁, hx⟩ := mem_finiteLocalOperators.1 hx
    refine SetLike.mem_coe.2 (VonNeumannAlgebra.mem_commutantSet_iff.2 fun g hg => ?_)
    obtain ⟨Λ₂, hΛ₂, hg⟩ := mem_finiteLocalOperators.1 hg
    have hdisj : Disjoint Λ₁ Λ₂ :=
      Finset.disjoint_coe.1 (Set.disjoint_of_subset hΛ₁ hΛ₂ hd)
    have hcomm := VonNeumannAlgebra.mem_commutant_iff.1
      (vnNet.algebra_le_commutant_of_orthogonal hdisj hx)
    exact ⟨hcomm g hg, hcomm (star g) (star_mem hg)⟩

/-- A finite region's algebra lies in the extended algebra of every region containing it. -/
lemma algebra_le_extend_algebra (vnNet : VonNeumannNet (Finset α) H) {Λ : Finset α} {S : Set α}
    (h : (Λ : Set α) ⊆ S) : vnNet.algebra Λ ≤ vnNet.extend.algebra S := fun _ hx =>
  VonNeumannAlgebra.mem_generated_of_mem (mem_finiteLocalOperators.2 ⟨Λ, h, hx⟩)

/-- **The extension agrees with the net on finite regions**: `𝓡(↑Λ) = 𝓡(Λ)`. So the
    infinite-region net genuinely extends the finite one, and its split property restricted to
    finite pairs is the finite-region property. -/
@[simp] lemma extend_algebra_coe (vnNet : VonNeumannNet (Finset α) H) (Λ : Finset α) :
    vnNet.extend.algebra (Λ : Set α) = vnNet.algebra Λ := by
  refine le_antisymm (VonNeumannAlgebra.generated_le fun x hx => ?_)
    (vnNet.algebra_le_extend_algebra subset_rfl)
  obtain ⟨Λ₀, hΛ₀, hx⟩ := mem_finiteLocalOperators.1 hx
  exact vnNet.algebra_mono (Finset.coe_subset.1 hΛ₀) hx

end VonNeumannNet

namespace LocalNet

variable {α : Type*} (N : LocalNet (Finset α)) [N.Faithful]

/-- **The local von Neumann algebras of infinite regions** in a representation `R` of the
    quasi-local C⋆-algebra of a lattice net: the extension (`VonNeumannNet.extend`) of the net
    `N.vonNeumannNet R` of finite-region algebras. Its split property,
    `(N.vonNeumannNetSet R).SplitProperty`, is the lattice split property on infinite regions. -/
noncomputable abbrev vonNeumannNetSet (R : CStarRep N.quasiLocalCStarAlgebra) :
    VonNeumannNet (Set α) R.H :=
  (N.vonNeumannNet R).extend

/-- On a finite region the infinite-region net is the local von Neumann algebra of that region. -/
lemma vonNeumannNetSet_algebra_coe (R : CStarRep N.quasiLocalCStarAlgebra) (Λ : Finset α) :
    (N.vonNeumannNetSet R).algebra (Λ : Set α) = N.localVonNeumannAlgebra R Λ :=
  (N.vonNeumannNet R).extend_algebra_coe Λ

/-! ### The split property of a state -/

section State

variable [PartialOrder N.quasiLocalCStarAlgebra] [StarOrderedRing N.quasiLocalCStarAlgebra]

/-- **The split property of a state for a pair of regions**: in the GNS representation of the
    state `ω` on the quasi-local algebra, the regions `S₁` and `S₂` form a split pair
    (`VonNeumannNet.IsSplitPair`), `𝓡_ω(S₁) ≤ 𝔑 ≤ 𝓡_ω(S₂)′` with `𝔑` a type I factor. The regions
    may be infinite; `𝓡_ω` is `N.vonNeumannNetSet` at the GNS representation
    `GNS[ω].toCStarRep`.

    The order on the quasi-local algebra is a parameter rather than a fixed choice, because
    `State` needs one and the quasi-local algebra carries none; the spectral order
    `CStarAlgebra.spectralOrder` is the canonical instance. -/
def IsSplitPairAt (ω : State N.quasiLocalCStarAlgebra) (S₁ S₂ : Set α) : Prop :=
  (N.vonNeumannNetSet GNS[ω].toCStarRep).IsSplitPair S₁ S₂

/-- **The nested split property yields split pairs with a gap**: if the GNS net of `ω` has the
    split property and `S₁ ⋐ S₂` with `S₃` disjoint from `S₂`, then `(S₁, S₃)` is a split pair
    of `ω`. On the integer chain with `ofCThickening ℤ 1` this gives the gapped half-chain pair
    `(Iic 0, Ici 3)` from `Iic 0 ⋐ Iic 2`; the gap-free pair `(Iic 0, Ici 1)` is not reachable. -/
theorem IsSplitPairAt.of_splitProperty [ProperContainment (Set α)]
    {ω : State N.quasiLocalCStarAlgebra}
    (hs : (N.vonNeumannNetSet GNS[ω].toCStarRep).SplitProperty)
    {S₁ S₂ S₃ : Set α} (h : S₁ ⋐ S₂) (hd : Disjoint S₂ S₃) : N.IsSplitPairAt ω S₁ S₃ :=
  VonNeumannNet.SplitProperty.isSplitPair hs h hd

/-- **Every multiplicative state splits every pair of regions**, trivially: its GNS
    representation acts by scalars (`GNS.Representation.π_eq_smul_one_of_map_mul`), so every local
    algebra lies in the scalar algebra `ℂ1 = 𝓑(H)′`, which is a type I factor
    (`VonNeumannAlgebra.isTypeIFactor_commutant_boundedLinearOperators`) commuting with everything.
    This is the degenerate end of the split property, as the one-dimensional case is for nets. -/
theorem IsSplitPairAt.of_map_mul {ω : State N.quasiLocalCStarAlgebra}
    (hω : ∀ a b, ω (a * b) = ω a * ω b) (S₁ S₂ : Set α) : N.IsSplitPairAt ω S₁ S₂ := by
  refine ⟨_, VonNeumannAlgebra.isTypeIFactor_commutant_boundedLinearOperators, ?_, ?_⟩
  · refine VonNeumannAlgebra.generated_le fun x hx => ?_
    obtain ⟨Λ, -, hx⟩ := VonNeumannNet.mem_finiteLocalOperators.1 hx
    refine VonNeumannAlgebra.generated_le
      (M := (𝓑(GNS[ω].H))′) ?_ hx
    rintro _ ⟨a, rfl⟩
    simp only
    rw [GNS[ω].π_eq_smul_one_of_map_mul hω]
    exact SetLike.mem_coe.2 (SMulMemClass.smul_mem _ (one_mem _))
  · intro x hx
    obtain ⟨c, rfl⟩ := VonNeumannAlgebra.exists_eq_smul_one_of_mem_commutant_boundedLinearOperators hx
    exact VonNeumannAlgebra.mem_commutant_iff.2 fun g _ =>
      (mul_smul_one c g).trans (smul_one_mul c g).symm

end State

section HalfChain

variable (N : LocalNet (Finset ℤ)) [N.Faithful]
variable [PartialOrder N.quasiLocalCStarAlgebra] [StarOrderedRing N.quasiLocalCStarAlgebra]

/-- The **half-chain split property** of a state `ω` on the quasi-local algebra of a chain, in
    split-inclusion form: the left half-chain `(-∞, 0]` and the right half-chain `[1, ∞)` form a
    split pair in the GNS representation of `ω`,

      `𝓡_ω((-∞, 0]) ≤ 𝔑 ≤ 𝓡_ω([1, ∞))′`, with `𝔑` a type I factor.

    The half-chains are adjacent: there is no gap, so this is not a consequence of any nested split
    property through `⋐`.

    Matsui (*The split property and the symmetry breaking of the quantum spin chain*, Comm. Math.
    Phys. 218, 2001) *defines* the split property as the quasi-equivalence of `ω` with
    `ω_L ⊗ ω_R`, the product of its restrictions to the two half-chains. The split inclusion above
    implies that quasi-equivalence for every state, and conversely for pure (more generally
    factor) states; for a pure state both are equivalent to `𝓡_ω((-∞, 0])` being a type I factor.
    Neither the quasi-equivalence form nor these equivalences are formalised (see the module
    docstring). -/
def HasHalfChainSplit (ω : State N.quasiLocalCStarAlgebra) : Prop :=
  N.IsSplitPairAt ω (Set.Iic 0) (Set.Ici 1)

end HalfChain

end LocalNet
