/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import QuantumSystem.Analysis.CStarAlgebra.Representation.Basic
public import QuantumSystem.Analysis.VonNeumannAlgebra.Basic
public import QuantumSystem.Physics.LocalNet.QuasiLocalAlgebra

/-!
# Nets of von Neumann algebras

A **net of von Neumann algebras** (`VonNeumannNet`) is an isotone, local assignment `O ↦ 𝓡(O)` of
von Neumann algebras on a fixed Hilbert space over a bare causal index set: no directedness, no
quasi-local C⋆-algebra and no faithfulness. This is the level at which Buchholz's local rings
`𝓡(O)`, Doplicher–Longo's `W*`-inclusions and Köster's chiral nets are stated; in particular the
proper intervals of `S¹` (the index set of a chiral net) are not directed, since two intervals
covering the circle have no proper upper bound.

A representation `R` of the quasi-local C⋆-algebra of a local net `N` gives one instance: the
**local von Neumann algebras** `𝓡(O) = R.π(𝔄(O))″` (`LocalNet.localVonNeumannAlgebra`) form the
net `LocalNet.vonNeumannNet`. The hypotheses `[IsDirectedOrder K]`, `[Nonempty K]` and
`[N.Faithful]` belong to that instance: the quasi-local algebra's direct limit needs a directed
index set with a base point, and its C⋆-norm needs injective isotony embeddings.

## Main definitions and results

* `VonNeumannNet` — an isotone (`VonNeumannNet.algebra_mono`), local
  (`VonNeumannNet.algebra_le_commutant_of_orthogonal`) net of von Neumann algebras over a causal
  index set.
* `LocalNet.localVonNeumannAlgebra` — the local von Neumann algebra `𝓡(O) = R.π(𝔄(O))″` of a
  region in a representation of the quasi-local algebra, containing the represented local
  observables (`π_ιLocalCStar_mem_localVonNeumannAlgebra`), with isotony
  (`localVonNeumannAlgebra_mono`) and locality
  (`localVonNeumannAlgebra_le_commutant_of_orthogonal`).
* `LocalNet.vonNeumannNet` — the net of local von Neumann algebras of a representation, as a
  `VonNeumannNet`.

## Notation

`𝔄(O)` and `𝓡(O)` in the prose above are documentation shorthand for the local C⋆-algebra
`N.algebra O` and the local von Neumann algebra `N.localVonNeumannAlgebra R O`; the convention —
and why neither is a Lean notation — is stated in full in `QuantumSystem.Physics.LocalNet.Basic`.
-/

@[expose] public section

open scoped CausalOrthogonality VonNeumannAlgebra

/-- A **net of von Neumann algebras** over a causal index set `K`, acting on a fixed Hilbert space
    `H`: the assignment `O ↦ 𝓡(O)` together with **isotony** (`algebra_mono`) and **locality**
    (`algebra_le_commutant_of_orthogonal`, Einstein causality `𝓡(O₁) ≤ 𝓡(O₂)′` for `O₁ ⟂ O₂`).

    This is the level at which the split property is stated in the literature — Buchholz's local
    rings `𝓡(O)`, Doplicher–Longo's `W*`-inclusions, Köster's chiral nets assigning a von Neumann
    algebra to each proper interval. The index set carries only a `Preorder` and `⟂`; in
    particular it is not assumed directed, so the index sets those sources use are expressible. -/
structure VonNeumannNet (K : Type*) [Preorder K] [CausalOrthogonality K]
    (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H] where
  /-- The local von Neumann algebra `𝓡(O)` assigned to a region. -/
  algebra : K → VonNeumannAlgebra H
  /-- **Isotony**: a larger region carries a larger algebra. -/
  algebra_mono : Monotone algebra
  /-- **Locality** (microcausality): causally orthogonal regions carry commuting algebras. -/
  algebra_le_commutant_of_orthogonal : ∀ ⦃O₁ O₂ : K⦄, O₁ ⟂ O₂ → algebra O₁ ≤ (algebra O₂)′

namespace LocalNet

open scoped VonNeumannAlgebra

section LocalAlgebras

variable {K : Type*} [Preorder K] [CausalOrthogonality K] [IsDirectedOrder K] [Nonempty K]
variable (N : LocalNet K) [N.Faithful]

/-- The **local von Neumann algebra** `𝓡(O) = R.π(𝔄(O))″` of a region in a representation of the
    quasi-local C⋆-algebra: the von Neumann algebra generated by the image of the local algebra.
    The generating set is star-closed (`star_range_π_ιLocalCStar`), so
    `VonNeumannAlgebra.generated` — which symmetrizes in general — is literally the double
    commutant here (`coe_localVonNeumannAlgebra`). Since `R.π` is a possibly non-unital
    `*`-homomorphism, `𝓡(O)` always contains `1` even when `R.π(𝔄(O))` does not, matching the `″`
    convention. -/
noncomputable def localVonNeumannAlgebra (R : CStarRep N.quasiLocalCStarAlgebra) (O : K) :
    VonNeumannAlgebra R.H :=
  VonNeumannAlgebra.generated (Set.range fun a : N.algebra O => R.π (N.ιLocalCStar O a))

/-- Local observables are represented inside the local von Neumann algebra of their region. -/
lemma π_ιLocalCStar_mem_localVonNeumannAlgebra (R : CStarRep N.quasiLocalCStarAlgebra) (O : K)
    (a : N.algebra O) : R.π (N.ιLocalCStar O a) ∈ N.localVonNeumannAlgebra R O :=
  VonNeumannAlgebra.mem_generated_of_mem ⟨a, rfl⟩

/-- The generating set of `𝓡(O)` is star-closed: `𝔄(O)` is star-closed, and both the embedding
    into the quasi-local algebra and `R.π` are `*`-maps, so `Set.star_range` applies to the
    composite. -/
lemma star_range_π_ιLocalCStar (R : CStarRep N.quasiLocalCStarAlgebra) (O : K) :
    star (Set.range fun a : N.algebra O => R.π (N.ιLocalCStar O a))
      = Set.range fun a : N.algebra O => R.π (N.ιLocalCStar O a) :=
  Set.star_range fun a => by rw [N.ιLocalCStar_star, map_star]

/-- **`𝓡(O)` is literally the double commutant `R.π(𝔄(O))″`.** `VonNeumannAlgebra.generated`
    symmetrizes its generating set in general; here the set is already star-closed
    (`star_range_π_ιLocalCStar`), so no symmetrization happens and the definition agrees with the
    `″` of the operator-algebra literature. -/
lemma coe_localVonNeumannAlgebra (R : CStarRep N.quasiLocalCStarAlgebra) (O : K) :
    (N.localVonNeumannAlgebra R O : Set (R.H →L[ℂ] R.H))
      = (Set.range fun a : N.algebra O => R.π (N.ιLocalCStar O a)).centralizer.centralizer :=
  VonNeumannAlgebra.coe_generated_of_star_eq (N.star_range_π_ιLocalCStar R O)

/-- **Isotony** of the local von Neumann algebras: `O ≤ O'` gives `𝓡(O) ≤ 𝓡(O')`. -/
lemma localVonNeumannAlgebra_mono (R : CStarRep N.quasiLocalCStarAlgebra) {O O' : K}
    (h : O ≤ O') : N.localVonNeumannAlgebra R O ≤ N.localVonNeumannAlgebra R O' := by
  refine VonNeumannAlgebra.generated_mono ?_
  rintro _ ⟨a, rfl⟩
  exact ⟨N.incl h a, by simp⟩

/-- **Locality** of the local von Neumann algebras: causally orthogonal regions have commuting
    algebras, `𝓡(O₁) ≤ 𝓡(O₂)′`. Einstein causality survives the double commutant. -/
lemma localVonNeumannAlgebra_le_commutant_of_orthogonal (R : CStarRep N.quasiLocalCStarAlgebra)
    {O₁ O₂ : K} (hd : O₁ ⟂ O₂) :
    N.localVonNeumannAlgebra R O₁ ≤ (N.localVonNeumannAlgebra R O₂)′ := by
  have key : VonNeumannAlgebra.generated
      (Set.range fun a : N.algebra O₁ => R.π (N.ιLocalCStar O₁ a))
      ≤ VonNeumannAlgebra.commutantSet
        (Set.range fun b : N.algebra O₂ => R.π (N.ιLocalCStar O₂ b)) := by
    refine VonNeumannAlgebra.generated_le ?_
    rintro _ ⟨a, rfl⟩
    rw [SetLike.mem_coe, VonNeumannAlgebra.mem_commutantSet_iff]
    rintro _ ⟨b, rfl⟩
    refine ⟨(N.ιLocalCStar_commute_of_orthogonal hd.symm b a).map R.π, ?_⟩
    have hb : star (R.π (N.ιLocalCStar O₂ b)) = R.π (N.ιLocalCStar O₂ (star b)) := by
      rw [← map_star, N.ιLocalCStar_star]
    rw [hb]
    exact (N.ιLocalCStar_commute_of_orthogonal hd.symm (star b) a).map R.π
  exact key.trans_eq (VonNeumannAlgebra.commutant_generated _).symm

/-- **The net of local von Neumann algebras** of a representation, as a `VonNeumannNet`: isotony
    is `localVonNeumannAlgebra_mono` and locality is
    `localVonNeumannAlgebra_le_commutant_of_orthogonal`, both already proved. This is the bridge
    from the C⋆-level net data to the von-Neumann-level object the split property is about. -/
noncomputable def vonNeumannNet (R : CStarRep N.quasiLocalCStarAlgebra) :
    VonNeumannNet K R.H where
  algebra := N.localVonNeumannAlgebra R
  algebra_mono _ _ h := N.localVonNeumannAlgebra_mono R h
  algebra_le_commutant_of_orthogonal _ _ hd :=
    N.localVonNeumannAlgebra_le_commutant_of_orthogonal R hd

/-- The algebras of the net `vonNeumannNet R` are the local von Neumann algebras themselves. -/
@[simp] lemma vonNeumannNet_algebra (R : CStarRep N.quasiLocalCStarAlgebra) (O : K) :
    (N.vonNeumannNet R).algebra O = N.localVonNeumannAlgebra R O := rfl

end LocalAlgebras

end LocalNet
