/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import QuantumSystem.ForMathlib.Analysis.CStarAlgebra.GelfandNaimarkSegal
public import QuantumSystem.ForMathlib.Analysis.CStarAlgebra.KPositiveMap
public import QuantumSystem.ForMathlib.Analysis.CStarAlgebra.PositiveMapCommutative
public import QuantumSystem.ForMathlib.Analysis.CStarAlgebra.RussoDye

/-!
# Kadison's inequality and the norm of positive maps

Two consequences of Stinespring's theorem
(`CompletelyPositiveMapClass.of_orderHomClass_of_commCStarAlgebra`: a positive map on a commutative
unital C⋆-algebra is completely positive) for a positive linear map `φ` from a unital C⋆-algebra
`A₁` into a C⋆-algebra `A₂`.

* The **Kadison–Schwarz inequality for normal elements**, `φ(a)⋆ φ(a) ≤ ‖φ 1‖ • φ(a⋆ a)` for
  normal `a` (Kadison 1952 for self-adjoint `a`, Choi 1974 for normal `a`). The restriction of `φ`
  to the C⋆-algebra generated by `a`, `ψ = φ ∘ cfcHom : C(σ(a), ℂ) → A₂`, is positive on a
  commutative C⋆-algebra, hence completely positive and in particular `2`-positive; the
  Kadison–Schwarz inequality for `2`-positive maps (`KPositiveMapClass.le_norm_smul_map_star_mul`)
  for `ψ` at the identity function of `σ(a)` is the claim. For self-adjoint `a` and `φ 1 ≤ 1` it
  is **Kadison's inequality** `φ(a)² ≤ φ(a²)`.
* **A positive map attains its norm at the unit**, `‖φ‖ = ‖φ 1‖` (Russo–Dye 1966; Paulsen,
  Corollary 2.9). For unitary `u`, the Kadison–Schwarz inequality gives
  `‖φ u‖² ≤ ‖φ 1‖ ‖φ(u⋆ u)‖ = ‖φ 1‖²`. The set `{x | ‖φ x‖ ≤ ‖φ 1‖}` is closed and convex, so it
  contains the closed convex hull of the unitaries, which is the closed unit ball by the
  Russo–Dye theorem (`CStarAlgebra.closedConvexHull_unitary`).

For a `2`-positive map the Kadison–Schwarz inequality holds at every `a`
(`KPositiveMapClass.le_norm_smul_map_star_mul`); for a merely positive map normality cannot be
dropped. The transpose map on `2 × 2` matrices is positive and unital; at the matrix unit
`a = E₁₂` it has `φ(a)⋆ φ(a) = E₁₁` and `φ(a⋆ a) = E₂₂`, and `E₁₁ ≰ E₂₂`. In particular a positive
map with `φ 1 ≤ 1` need not be a Schwarz map.

This file lives outside `ForMathlib/` because it needs `KPositiveMap.lean`,
`PositiveMapCommutative.lean`, `RussoDye.lean` and, for the operator norm `‖φ‖ₒₚ`
(`PositiveLinearMap.opNorm`), `GelfandNaimarkSegal.lean` of `ForMathlib/Analysis/CStarAlgebra/`,
and a `ForMathlib` file imports Mathlib only.

## Main results

* `OrderHomClass.le_norm_smul_map_star_mul_of_isStarNormal` — **the Kadison–Schwarz inequality
  for normal elements** `φ(a)⋆ φ(a) ≤ ‖φ 1‖ • φ(a⋆ a)` for positive `φ` and normal `a`;
  `OrderHomClass.le_map_star_mul_of_isStarNormal` — its normalised form under `φ 1 ≤ 1`.
* `OrderHomClass.sq_map_le_map_sq` — **Kadison's inequality** `φ(a)² ≤ φ(a²)` for positive `φ`
  with `φ 1 ≤ 1` and self-adjoint `a`.
* `OrderHomClass.opNorm_eq_norm_map_one` — **a positive map on a unital C⋆-algebra attains its
  norm at the unit**, `‖φ‖ₒₚ = ‖φ 1‖`; `OrderHomClass.norm_apply_le_norm_map_one` — its pointwise
  form `‖φ a‖ ≤ ‖φ 1‖ ‖a‖`.
* `OrderHomClass.norm_apply_le_of_map_one_le` — a positive map with `φ 1 ≤ 1` is a contraction,
  since `‖φ 1‖ ≤ 1` (`OrderHomClass.norm_map_one_le_one`, in `KPositiveMap.lean`).

## References

* M.-D. Choi, *A Schwarz inequality for positive linear maps on C⋆-algebras*, Illinois J. Math.
  18 (1974), 565–574.
* R. V. Kadison, *A generalized Schwarz inequality and algebraic invariants for operator
  algebras*, Ann. of Math. 56 (1952), 494–503.
* V. Paulsen, *Completely Bounded Maps and Operator Algebras*, Cambridge Stud. Adv. Math. 78
  (2002), Corollary 2.9 and Theorem 3.11.
* B. Russo, H. A. Dye, *A note on unitary operators in C⋆-algebras*, Duke Math. J. 33 (1966),
  413–416.
-/

@[expose] public section

open Metric
open scoped ComplexOrder PositiveLinearMap

/-- The unit of a C⋆-algebra has norm at most `1`; it is `1` unless the algebra is trivial. -/
private lemma norm_one_le_one {A : Type*} [CStarAlgebra A] : ‖(1 : A)‖ ≤ 1 := by
  nontriviality A
  simp

namespace OrderHomClass

section Unital

variable {F A₁ A₂ : Type*} [CStarAlgebra A₁] [NonUnitalCStarAlgebra A₂] [PartialOrder A₁]
  [PartialOrder A₂] [StarOrderedRing A₁] [StarOrderedRing A₂] [FunLike F A₁ A₂]
  [LinearMapClass F ℂ A₁ A₂] [OrderHomClass F A₁ A₂]

/-- The **Kadison–Schwarz inequality for normal elements** (Kadison 1952 for self-adjoint `a`, Choi
1974): a positive map `φ` on a unital C⋆-algebra satisfies `φ(a)⋆ φ(a) ≤ ‖φ 1‖ • φ(a⋆ a)` for every
normal `a`. The positive map `ψ = φ ∘ cfcHom` on the commutative C⋆-algebra `C(σ(a), ℂ)` is
completely positive (`CompletelyPositiveMapClass.of_orderHomClass_of_commCStarAlgebra`), so the
Kadison–Schwarz inequality for `2`-positive maps (`KPositiveMapClass.le_norm_smul_map_star_mul`)
applies to `ψ` at the identity function `f` of `σ(a)`, with `ψ f = φ a`, `ψ 1 = φ 1` and
`ψ (f⋆ f) = φ (a⋆ a)`. -/
theorem le_norm_smul_map_star_mul_of_isStarNormal (φ : F) (a : A₁) [IsStarNormal a] :
    star (φ a) * φ a ≤ ‖φ 1‖ • φ (star a * a) := by
  have ha : IsStarNormal a := inferInstance
  let ψ : C(spectrum ℂ a, ℂ) →ₚ[ℂ] A₂ :=
    (PositiveLinearMap.ofClass φ).comp (PositiveLinearMap.ofClass (cfcHom ha))
  have := CompletelyPositiveMapClass.of_orderHomClass_of_commCStarAlgebra
    (F := C(spectrum ℂ a, ℂ) →ₚ[ℂ] A₂)
  let f : C(spectrum ℂ a, ℂ) := (ContinuousMap.id ℂ).restrict (spectrum ℂ a)
  have h := KPositiveMapClass.le_norm_smul_map_star_mul ψ f
  have hf : ψ f = φ a := congrArg φ (cfcHom_id ha)
  have h₁ : ψ 1 = φ 1 := congrArg φ (map_one (cfcHom ha))
  have hff : ψ (star f * f) = φ (star a * a) := by
    change φ (cfcHom ha (star f * f)) = _
    rw [map_mul, map_star, cfcHom_id ha]
  rwa [hf, h₁, hff] at h

/-- A positive map on a unital C⋆-algebra is bounded by its value at the unit on unitaries,
`‖φ u‖ ≤ ‖φ 1‖`: by the Kadison–Schwarz inequality for the normal element `u`,
`‖φ u‖² = ‖φ(u)⋆ φ(u)‖ ≤ ‖φ 1‖ ‖φ(u⋆ u)‖ = ‖φ 1‖²`. -/
private lemma norm_map_le_norm_map_one_of_mem_unitary (φ : F) {u : A₁} (hu : u ∈ unitary A₁) :
    ‖φ u‖ ≤ ‖φ 1‖ := by
  have : IsStarNormal u := isStarNormal_of_mem_unitary hu
  have h := le_norm_smul_map_star_mul_of_isStarNormal φ u
  rw [Unitary.star_mul_self_of_mem hu] at h
  have h' := CStarAlgebra.norm_le_norm_of_le_of_nonneg h (star_mul_self_nonneg _)
  rw [CStarRing.norm_star_mul_self, norm_smul, norm_norm] at h'
  exact (mul_self_le_mul_self_iff (norm_nonneg _) (norm_nonneg _)).2 h'

/-- A positive map on a unital C⋆-algebra is bounded by its value at the unit,
`‖φ a‖ ≤ ‖φ 1‖ ‖a‖` (Russo–Dye 1966; Paulsen, Corollary 2.9). The set `{x | ‖φ x‖ ≤ ‖φ 1‖}` is
closed and convex and contains the unitaries (Kadison–Schwarz inequality for normal elements), so
it contains their closed convex hull, which is the closed unit ball by the Russo–Dye theorem
(`CStarAlgebra.closedConvexHull_unitary`); apply this to `a / ‖a‖`. -/
lemma norm_apply_le_norm_map_one (φ : F) (a : A₁) : ‖φ a‖ ≤ ‖φ 1‖ * ‖a‖ := by
  let S : Set A₁ := ((φ : A₁ →ₗ[ℂ] A₂).restrictScalars ℝ) ⁻¹' closedBall 0 ‖φ 1‖
  have hS : closedBall 0 1 ⊆ S := by
    rw [← CStarAlgebra.closedConvexHull_unitary]
    refine closedConvexHull_min (fun u hu => ?_) ((convex_closedBall _ _).linear_preimage _)
      (isClosed_closedBall.preimage (map_continuous φ))
    exact mem_closedBall_zero_iff.2 (norm_map_le_norm_map_one_of_mem_unitary φ hu)
  rcases eq_or_ne a 0 with rfl | ha
  · simp
  have hpos : 0 < ‖a‖ := norm_pos_iff.2 ha
  have h : ‖φ ((‖a‖⁻¹ : ℂ) • a)‖ ≤ ‖φ 1‖ := by
    refine mem_closedBall_zero_iff.1 (hS (mem_closedBall_zero_iff.2 ?_))
    rw [norm_smul, norm_inv, Complex.norm_real, norm_norm, inv_mul_cancel₀ hpos.ne']
  rw [map_smul, norm_smul, norm_inv, Complex.norm_real, norm_norm, inv_mul_le_iff₀ hpos] at h
  linarith

/-- A positive map on a unital C⋆-algebra attains its norm at the unit, `‖φ‖ₒₚ = ‖φ 1‖`
(Russo–Dye 1966; Paulsen, Corollary 2.9), where `‖φ‖ₒₚ` is the operator norm
`PositiveLinearMap.opNorm φ` of the bounded positive map `PositiveContinuousLinearMap.ofClass φ`
(`OrderHomClass.norm_apply_le_norm_map_one`). -/
theorem opNorm_eq_norm_map_one (φ : F) : ‖φ‖ₒₚ = ‖φ 1‖ := by
  refine le_antisymm ?_ ?_
  · rw [PositiveLinearMap.opNorm_def]
    exact ContinuousLinearMap.opNorm_le_bound _ (norm_nonneg _) (norm_apply_le_norm_map_one φ)
  · calc ‖φ 1‖ ≤ ‖φ‖ₒₚ * ‖(1 : A₁)‖ := PositiveLinearMap.norm_apply_le_opNorm_mul φ 1
      _ ≤ ‖φ‖ₒₚ * 1 := mul_le_mul_of_nonneg_left norm_one_le_one (PositiveLinearMap.opNorm_nonneg φ)
      _ = _ := mul_one _

end Unital

section Unital₂

variable {F A₁ A₂ : Type*} [CStarAlgebra A₁] [CStarAlgebra A₂] [PartialOrder A₁] [PartialOrder A₂]
  [StarOrderedRing A₁] [StarOrderedRing A₂] [FunLike F A₁ A₂] [LinearMapClass F ℂ A₁ A₂]
  [OrderHomClass F A₁ A₂]

/-- The **Kadison–Schwarz inequality for normal elements**, normalised form: a positive map with
`φ 1 ≤ 1` satisfies `φ(a)⋆ φ(a) ≤ φ(a⋆ a)` for every normal `a`; `‖φ 1‖ ≤ 1`
(`OrderHomClass.norm_map_one_le_one`) in
`OrderHomClass.le_norm_smul_map_star_mul_of_isStarNormal`. -/
lemma le_map_star_mul_of_isStarNormal (φ : F) (hφ : φ 1 ≤ 1) (a : A₁) [IsStarNormal a] :
    star (φ a) * φ a ≤ φ (star a * a) := by
  refine (le_norm_smul_map_star_mul_of_isStarNormal φ a).trans ?_
  calc ‖φ 1‖ • φ (star a * a) ≤ (1 : ℝ) • φ (star a * a) :=
        smul_le_smul_of_nonneg_right (norm_map_one_le_one φ hφ)
          (map_nonneg φ (star_mul_self_nonneg a))
    _ = φ (star a * a) := one_smul _ _

/-- **Kadison's inequality** (Kadison 1952): a positive map with `φ 1 ≤ 1` satisfies
`φ(a)² ≤ φ(a²)` for every self-adjoint `a`. This is
`OrderHomClass.le_map_star_mul_of_isStarNormal` for the normal element `a`, since `φ a` is again
self-adjoint. -/
theorem sq_map_le_map_sq (φ : F) (hφ : φ 1 ≤ 1) {a : A₁} (ha : IsSelfAdjoint a) :
    φ a ^ 2 ≤ φ (a ^ 2) := by
  have : IsStarNormal a := ha.isStarNormal
  have h := le_map_star_mul_of_isStarNormal φ hφ a
  rwa [(ha.map φ).star_eq, ha.star_eq, ← sq, ← sq] at h

/-- A positive map with `φ 1 ≤ 1` is a contraction, `‖φ a‖ ≤ ‖a‖`: `‖φ 1‖ ≤ 1`
(`OrderHomClass.norm_map_one_le_one`) in `OrderHomClass.norm_apply_le_norm_map_one`. -/
lemma norm_apply_le_of_map_one_le (φ : F) (hφ : φ 1 ≤ 1) (a : A₁) : ‖φ a‖ ≤ ‖a‖ := by
  calc ‖φ a‖ ≤ ‖φ 1‖ * ‖a‖ := norm_apply_le_norm_map_one φ a
    _ ≤ 1 * ‖a‖ := by gcongr; exact norm_map_one_le_one φ hφ
    _ = ‖a‖ := one_mul _

end Unital₂

end OrderHomClass
