module

public import Mathlib.Analysis.VonNeumannAlgebra.Basic
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.Algebra.Group.Center
public import Mathlib.Algebra.Group.Equiv.Defs

/-!
# The commutant of a set, the generated von Neumann algebra, and unitary conjugation

Mathlib's `VonNeumannAlgebra.commutant` takes the commutant of a von Neumann algebra. This file
provides the companion constructions that take an *arbitrary* set of bounded operators, together
with the transport of a von Neumann algebra along a linear isometric equivalence:

* `VonNeumannAlgebra.commutantSet s` — the commutant `s'` of a set `s`, as a von Neumann algebra.
  The double-commutant property is automatic (`Set.centralizer_centralizer_centralizer`), and
  `StarSubalgebra.centralizer` already symmetrises by `s ∪ star s`, so no self-adjointness
  hypothesis is needed.
* `VonNeumannAlgebra.generated s` — the von Neumann algebra `s''` generated by `s`, defined as the
  commutant of `commutantSet s`.
* `VonNeumannAlgebra.conj U N` — the spatial conjugate `U N U⋆` of a von Neumann algebra `N` on
  `H` by a linear isometric equivalence `U : H ≃ₗᵢ H'`, a von Neumann algebra on `H'`. Conjugation
  by the induced `*`-isomorphism `U.conjStarAlgEquiv` commutes with taking commutants
  (`conj_commutant`), hence with the generated-algebra construction (`conj_generated`): this is the
  statement that a unitary equivalence of representations carries `s''` to `(U s U⋆)''`.

These let one build `B(H₁) ⊗̄ 1` and `1 ⊗̄ B(H₂)` (and any concretely-generated von Neumann
algebra) without unfolding the bicommutant by hand, and transport the generation theorem
`N = ⟨matrix units⟩''` of a type I factor along the spatial isomorphism.

## Notation

The prime notation of the operator-algebra literature lives in the opt-in `VonNeumannAlgebra`
scope; activate it with `open scoped VonNeumannAlgebra`.

| Symbol | Expansion | How to activate |
|---|---|---|
| `M′` | `VonNeumannAlgebra.commutant M` | `open scoped VonNeumannAlgebra` |
| `s″` | `VonNeumannAlgebra.generated s`, i.e. `(s ∪ s⋆)''` | `open scoped VonNeumannAlgebra` |
-/

@[expose] public section

/-- A multiplicative bijection carries the centralizer of a set onto the centralizer of the image:
`φ '' s' = (φ '' s)'`. This is the algebraic core of the fact that a spatial isomorphism of von
Neumann algebras commutes with taking commutants. -/
theorem Set.image_centralizer {M₁ M₂ F : Type*} [Mul M₁] [Mul M₂]
    [EquivLike F M₁ M₂] [MulEquivClass F M₁ M₂] (φ : F) (s : Set M₁) :
    ⇑φ '' Set.centralizer s = Set.centralizer (⇑φ '' s) := by
  ext y
  simp only [Set.mem_image, Set.mem_centralizer_iff]
  constructor
  · rintro ⟨x, hx, rfl⟩ _ ⟨a, ha, rfl⟩
    rw [← map_mul, ← map_mul, hx a ha]
  · intro hy
    obtain ⟨x, rfl⟩ := EquivLike.surjective φ y
    refine ⟨x, fun a ha => ?_, rfl⟩
    have h := hy (φ a) ⟨a, ha, rfl⟩
    apply EquivLike.injective φ
    rw [map_mul, map_mul, h]

namespace VonNeumannAlgebra

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- A von Neumann algebra is closed under scalar multiplication. This upgrades the `SubringClass`
and `StarMemClass` instances of `VonNeumannAlgebra` with the missing `ℂ`-scalar closure, so that
the subtype `↥N` inherits an `Algebra ℂ ↥N` structure (via `SubalgebraClass.toAlgebra`) and
`*`-algebra equivalences `N ≃⋆ₐ[ℂ] _` typecheck. -/
instance instSMulMemClass : SMulMemClass (VonNeumannAlgebra H) ℂ (H →L[ℂ] H) where
  smul_mem {s} c _ hx := s.toStarSubalgebra.smul_mem hx c

/-- The commutant `(s ∪ s⋆)′` of the *symmetrized* set of an arbitrary set of bounded operators,
packaged as a von Neumann algebra. For star-closed `s` — in particular for every self-adjoint
generating set — this coincides with the commutant `s′` of the operator-algebra literature; for
non-star-closed `s` the literal `s′` is a larger, non-star-closed algebra, and symmetrizing is
what makes the construction land in `VonNeumannAlgebra H`. -/
noncomputable def commutantSet (s : Set (H →L[ℂ] H)) : VonNeumannAlgebra H where
  toStarSubalgebra := StarSubalgebra.centralizer ℂ s
  centralizer_centralizer' := by simp

@[simp] theorem coe_commutantSet (s : Set (H →L[ℂ] H)) :
    (commutantSet s : Set (H →L[ℂ] H)) = (s ∪ star s).centralizer :=
  StarSubalgebra.coe_centralizer ℂ s

theorem mem_commutantSet_iff {s : Set (H →L[ℂ] H)} {z : H →L[ℂ] H} :
    z ∈ commutantSet s ↔ ∀ g ∈ s, g * z = z * g ∧ star g * z = z * star g :=
  StarSubalgebra.mem_centralizer_iff ℂ

/-- The von Neumann algebra `s''` generated by a set `s` of bounded operators, defined as the
commutant of its commutant. -/
noncomputable def generated (s : Set (H →L[ℂ] H)) : VonNeumannAlgebra H :=
  (commutantSet s).commutant

/-- The carrier of a von Neumann algebra is norm-closed: it is a double centralizer, and
centralizers are closed. (Von Neumann algebras are even weakly closed, but the norm-closedness
is what the subalgebra-membership lemmas of the continuous functional calculus consume.) -/
theorem isClosed_coe (N : VonNeumannAlgebra H) : IsClosed (N : Set (H →L[ℂ] H)) := by
  rw [show (N : Set (H →L[ℂ] H)) = Set.centralizer (Set.centralizer (N : Set (H →L[ℂ] H))) from
    N.centralizer_centralizer.symm]
  exact Set.isClosed_centralizer _

/-- `M′` denotes the commutant `VonNeumannAlgebra.commutant M`, the prime of the operator-algebra
literature. -/
scoped postfix:max "′" => VonNeumannAlgebra.commutant

/-- `s″` denotes the von Neumann algebra `VonNeumannAlgebra.generated s` generated by a set `s`.
For star-closed `s` this is the double prime `s''` of the operator-algebra literature; in general
it is `(s ∪ s⋆)''`, the smallest von Neumann algebra containing `s` (see `generated_le`). -/
scoped postfix:max "″" => VonNeumannAlgebra.generated

/-- The commutant of the generated von Neumann algebra `s''` is the commutant `s'`. -/
@[simp] theorem commutant_generated (s : Set (H →L[ℂ] H)) :
    (generated s).commutant = commutantSet s :=
  VonNeumannAlgebra.commutant_commutant (commutantSet s)

/-- A set is contained in the von Neumann algebra it generates. -/
theorem mem_generated_of_mem {s : Set (H →L[ℂ] H)} {x : H →L[ℂ] H} (hx : x ∈ s) :
    x ∈ generated s := by
  have h1 : x ∈ (commutantSet s : Set (H →L[ℂ] H)).centralizer := by
    rw [coe_commutantSet]
    exact Set.subset_centralizer_centralizer (Set.mem_union_left _ hx)
  rwa [← VonNeumannAlgebra.coe_commutant] at h1

/-- Taking the commutant of von Neumann algebras is antitone. Named to match the Mathlib
`centralizer_le` family (`Subalgebra.centralizer_le`, `Subring.centralizer_le`, …). -/
theorem commutant_le {P Q : VonNeumannAlgebra H} (h : P ≤ Q) :
    Q.commutant ≤ P.commutant := by
  intro x hx
  rw [← SetLike.mem_coe, VonNeumannAlgebra.coe_commutant] at hx ⊢
  exact Set.centralizer_subset (SetLike.coe_subset_coe.2 h) hx

/-- The von Neumann algebra generated by `s` is the smallest von Neumann algebra containing `s`:
if a von Neumann algebra `M` contains `s`, then it contains `generated s`. -/
theorem generated_le {s : Set (H →L[ℂ] H)} {M : VonNeumannAlgebra H}
    (hsM : s ⊆ (M : Set (H →L[ℂ] H))) : generated s ≤ M := by
  have hstar : s ∪ star s ⊆ (M : Set (H →L[ℂ] H)) := by
    refine Set.union_subset hsM fun x hx => ?_
    rw [Set.mem_star] at hx
    simpa using star_mem (hsM hx)
  have h1 : M.commutant ≤ (generated s).commutant := by
    rw [commutant_generated]
    intro x hx
    rw [← SetLike.mem_coe, coe_commutantSet]
    rw [← SetLike.mem_coe, VonNeumannAlgebra.coe_commutant] at hx
    exact Set.centralizer_subset hstar hx
  have h2 := commutant_le h1
  rwa [VonNeumannAlgebra.commutant_commutant, VonNeumannAlgebra.commutant_commutant] at h2

/-! ### Unitary conjugation of a von Neumann algebra -/

variable {H' : Type*} [NormedAddCommGroup H'] [InnerProductSpace ℂ H'] [CompleteSpace H']

/-- The **spatial conjugate** `U N U⋆` of a von Neumann algebra `N ⊆ B(H)` by a linear isometric
equivalence `U : H ≃ₗᵢ H'`, as a von Neumann algebra on `H'`. This is the adjoint action `Ad U`,
written `U N U⋆` (and `U • N` in informal notes); since `U` is unitary, `U⋆ = U.symm`. Its carrier
is the image of `N` under the conjugation `*`-isomorphism `U.conjStarAlgEquiv : B(H) ≃⋆ₐ B(H')`; the
double-commutant property is inherited from `N` because conjugation commutes with taking
centralizers. -/
noncomputable def conj (U : H ≃ₗᵢ[ℂ] H') (N : VonNeumannAlgebra H) : VonNeumannAlgebra H' where
  toStarSubalgebra :=
    N.toStarSubalgebra.map (U.conjStarAlgEquiv : (H →L[ℂ] H) →⋆ₐ[ℂ] H' →L[ℂ] H')
  centralizer_centralizer' := by
    have hcoe : ((N.toStarSubalgebra.map
        (U.conjStarAlgEquiv : (H →L[ℂ] H) →⋆ₐ[ℂ] H' →L[ℂ] H')).carrier)
        = ⇑U.conjStarAlgEquiv '' (N : Set (H →L[ℂ] H)) :=
      StarSubalgebra.coe_map _ _
    rw [hcoe, ← Set.image_centralizer, ← Set.image_centralizer, N.centralizer_centralizer]

@[simp] theorem coe_conj (U : H ≃ₗᵢ[ℂ] H') (N : VonNeumannAlgebra H) :
    (conj U N : Set (H' →L[ℂ] H')) = ⇑U.conjStarAlgEquiv '' (N : Set (H →L[ℂ] H)) :=
  StarSubalgebra.coe_map _ _

/-- **Spatial conjugation is monotone.** If `P ≤ Q` then `U P U⋆ ≤ U Q U⋆`: conjugation transports
inclusions, since its carrier is the image of the carrier under `U.conjStarAlgEquiv`. -/
theorem conj_mono (U : H ≃ₗᵢ[ℂ] H') {P Q : VonNeumannAlgebra H} (h : P ≤ Q) :
    conj U P ≤ conj U Q := by
  intro x hx
  rw [← SetLike.mem_coe, coe_conj] at hx ⊢
  exact Set.image_mono (SetLike.coe_subset_coe.2 h) hx

/-- **Conjugation commutes with the commutant.** `(U N U⋆)' = U N' U⋆`. -/
theorem conj_commutant (U : H ≃ₗᵢ[ℂ] H') (N : VonNeumannAlgebra H) :
    (conj U N).commutant = conj U N.commutant := by
  apply SetLike.coe_injective
  rw [VonNeumannAlgebra.coe_commutant, coe_conj, coe_conj, VonNeumannAlgebra.coe_commutant,
    Set.image_centralizer]

/-- **Conjugation commutes with the commutant of a set.** `U s' U⋆ = (U s U⋆)'`. -/
theorem conj_commutantSet (U : H ≃ₗᵢ[ℂ] H') (s : Set (H →L[ℂ] H)) :
    conj U (commutantSet s) = commutantSet (⇑U.conjStarAlgEquiv '' s) := by
  have hstar : ⇑U.conjStarAlgEquiv '' star s = star (⇑U.conjStarAlgEquiv '' s) := by
    ext z
    simp only [Set.mem_image, Set.mem_star]
    constructor
    · rintro ⟨w, hw, rfl⟩
      exact ⟨star w, hw, by rw [map_star]⟩
    · rintro ⟨x, hx, hz⟩
      exact ⟨star x, by simpa using hx, by rw [map_star, hz, star_star]⟩
  apply SetLike.coe_injective
  rw [coe_conj, coe_commutantSet, coe_commutantSet, Set.image_centralizer, Set.image_union, hstar]

/-- **Conjugation commutes with the generated von Neumann algebra.** A spatial isomorphism carries
`s''` to `(U s U⋆)''`: `U ⟨s⟩'' U⋆ = ⟨U s U⋆⟩''`. -/
theorem conj_generated (U : H ≃ₗᵢ[ℂ] H') (s : Set (H →L[ℂ] H)) :
    conj U (generated s) = generated (⇑U.conjStarAlgEquiv '' s) := by
  rw [generated, ← conj_commutant, conj_commutantSet, generated]

/-! ### Transport of a von Neumann algebra as a `*`-algebra -/

/-- **Spatial conjugation as a `*`-algebra equivalence.** The conjugation `*`-isomorphism
`U.conjStarAlgEquiv : B(H) ≃⋆ₐ B(H')` restricts to a `*`-isomorphism `N ≃⋆ₐ U N U⋆` of the
subtypes: the carrier of `conj U N` is exactly the image of `N` (`coe_conj`), so `x ↦ U x U⋆`
is a bijection between the two. -/
noncomputable def conjEquiv (U : H ≃ₗᵢ[ℂ] H') (N : VonNeumannAlgebra H) :
    N ≃⋆ₐ[ℂ] conj U N where
  toFun x := ⟨U.conjStarAlgEquiv (x : H →L[ℂ] H), by
    rw [← SetLike.mem_coe, coe_conj]; exact ⟨x, x.2, rfl⟩⟩
  invFun y := ⟨U.conjStarAlgEquiv.symm (y : H' →L[ℂ] H'), by
    have hy : (y : H' →L[ℂ] H') ∈ ⇑U.conjStarAlgEquiv '' (N : Set (H →L[ℂ] H)) := by
      rw [← coe_conj]; exact y.2
    obtain ⟨x, hx, hxy⟩ := hy
    rw [← SetLike.mem_coe, ← hxy, StarAlgEquiv.symm_apply_apply]; exact hx⟩
  left_inv x := Subtype.ext (U.conjStarAlgEquiv.symm_apply_apply (x : H →L[ℂ] H))
  right_inv y := Subtype.ext (U.conjStarAlgEquiv.apply_symm_apply (y : H' →L[ℂ] H'))
  map_mul' x y := Subtype.ext (map_mul U.conjStarAlgEquiv (x : H →L[ℂ] H) (y : H →L[ℂ] H))
  map_add' x y := Subtype.ext (map_add U.conjStarAlgEquiv (x : H →L[ℂ] H) (y : H →L[ℂ] H))
  map_smul' c x := Subtype.ext (map_smul U.conjStarAlgEquiv c (x : H →L[ℂ] H))
  map_star' x := Subtype.ext (map_star U.conjStarAlgEquiv (x : H →L[ℂ] H))

/-- **Definitional-equality transport as a `*`-algebra equivalence.** Two equal von Neumann
algebras have `*`-isomorphic subtypes via the identity on operators. -/
def equivOfEq {N M : VonNeumannAlgebra H} (h : N = M) : N ≃⋆ₐ[ℂ] M where
  toFun x := ⟨x, h ▸ x.2⟩
  invFun x := ⟨x, h ▸ x.2⟩
  left_inv _ := rfl
  right_inv _ := rfl
  map_mul' _ _ := rfl
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  map_star' _ := rfl

end VonNeumannAlgebra
