/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import QuantumSystem.Analysis.SpectralTheory.AnalyticContinuation
public import QuantumSystem.Analysis.UnboundedOperator.Adjoint
public import QuantumSystem.Analysis.SpectralTheory.PolarDecomposition
public import QuantumSystem.ForMathlib.Analysis.InnerProductSpace.StandardSubspace
public import QuantumSystem.ForMathlib.Topology.Algebra.Module.LinearPMap

/-!
# Tomita's theorem for standard subspaces

Let `K` be a standard subspace of a complex Hilbert space `H` (Mathlib's `StandardSubspace`: a
closed real subspace with `K ∩ i K = 0` and `K + i K` dense; `ξ ∈ K` is membership through
`StandardSubspace.instSetLike`, and `K.symplComp` is the symplectic complement `K'`). The **Tomita operator**
`S_K : x + i y ↦ x - i y` on `K + i K` (`StandardSubspace.tomita`) is a closed, densely defined,
conjugate-linear involution `H →ₛₗ.[starRingEnd ℂ] H`, with `K = {ξ | S_K ξ = ξ}`. Its polar decomposition
`S_K = J_K Δ_K^{1/2}` (`QuantumSystem.Analysis.SpectralTheory.PolarDecomposition`) defines the
**modular operator** `Δ_K = S_K† S_K` (`StandardSubspace.modular`; the adjoint `S_K†` is the
conjugate-linear `LinearPMap.adjointₛₗ`, so `Δ_K` is complex-linear), positive, self-adjoint and
injective (its spectral measure vanishes on `(-∞, 0]`, `StandardSubspace.pvm_modular_Iic_eq_zero`),
and the **modular conjugation** `J_K` (`StandardSubspace.modularConj`), an antiunitary
involution with `J_K Δ_K^{1/2} J_K = Δ_K^{-1/2}`. The modular group `Δ_K^{it} = e^{it log Δ_K}`
(`StandardSubspace.modularGroup`) is the unitary group generated by `log Δ_K`.

**Tomita's theorem** for standard subspaces (Rieffel–van Daele; Longo, *Lectures on Conformal
Nets*, §2.1):
* `Δ_K^{it} K = K` (`StandardSubspace.modularGroup_apply_mem_iff`): `Δ_K^{it}` commutes with
  `Δ_K^{1/2}` and with `J_K`, hence with `S_K`, whose fixed points form `K`;
* `S_{K'} = S_K†` for the symplectic complement `K'` (`StandardSubspace.tomita_symplComp`), and
  `S_K† = Δ_K^{1/2} J_K = J_K Δ_K^{-1/2}` is the polar decomposition of `S_{K'}`, so that
  `Δ_{K'} = Δ_K⁻¹` (`StandardSubspace.modular_symplComp`, with Mathlib's `LinearPMap.inverse`),
  `Δ_{K'}^{it} = Δ_K^{-it}` (`StandardSubspace.modularGroup_symplComp`) and `J_{K'} = J_K`
  (`StandardSubspace.modularConj_symplComp`);
* `J_K K = K'` (`StandardSubspace.modularConj_mem_symplComp_iff`);
* `ξ ∈ K` iff `J_K Δ_K^{1/2} ξ = ξ` (`StandardSubspace.mem_iff_modularConj_sqrt`).

## Main definitions

* `StandardSubspace.tomita K` — the Tomita operator `S_K`.
* `StandardSubspace.modular K` — the modular operator `Δ_K = S_K† S_K`.
* `StandardSubspace.modularConj K` — the modular conjugation `J_K`.
* `StandardSubspace.modularGroup K` — the modular group `t ↦ Δ_K^{it}`.

## Notation

Under `open scoped StandardSubspace`, `S[K]`, `Δ[K]`, `Δ[K]^{1/2}`, `J[K]`, `Δ[K]^{i t}` and
`Δ[K]^{-i t}` denote `S_K`, `Δ_K`, `Δ_K^{1/2}` (`IsSelfAdjoint.sqrt`), `J_K` and the bounded operators
`Δ_K^{it}`, `Δ_K^{-it}`; the exponent is parsed at `max` precedence (`Δ[K]^{i (s + t)}`).

## Main results

* `StandardSubspace.isClosed_tomita`, `dense_domain_tomita`, `tomita_compNat_tomita`,
  `mem_iff_mem_graph_tomita` — `S_K` is a closed densely defined conjugate-linear involution with
  fixed points `K`.
* `StandardSubspace.isSelfAdjoint_modular`, `isPositive_modular` — `Δ_K = S_K† S_K` is positive
  self-adjoint (von Neumann's theorem).
* `StandardSubspace.tomita_eq_modularConj_compPMap` — **polar decomposition** `S_K = J_K Δ_K^{1/2}`.
* `StandardSubspace.compPMap_tomita_le_of_apply_mem` — `V S_{K₁} ⊆ S_{K₂} V` for a bounded `V`
  with `V K₁ ⊆ K₂`.
* `StandardSubspace.adjointₛₗ_modularConj` — `J_K† = J_K` for the antilinear adjoint.
* `StandardSubspace.eq_top_of_le`, `ext_continuousLinearMap`, `eq_zero_of_forall_inner_eq_zero` —
  cyclicity: a closed real subspace containing `K` and `i K` is everything.
* `StandardSubspace.ker_modular_eq_bot`, `pvm_modular_Iic_eq_zero`, `ker_sqrt_modular_eq_bot` —
  `Δ_K` and `Δ_K^{1/2}` are injective.
* `StandardSubspace.modularConj_modularConj`, `sqrt_modular_compNat_modularConj` — `J_K² = 1` and
  `Δ_K^{1/2} J_K = J_K Δ_K^{-1/2}`.
* `StandardSubspace.modularGroup_compPMap_sqrt_le` — `Δ_K^{it} Δ_K^{1/2} ⊆ Δ_K^{1/2} Δ_K^{it}`.
* `StandardSubspace.coe_modularGroup_apply`, `modularConj_comm_modularGroup` —
  `Δ_K^{it} = ∫ λ^{it} dE_Δ(λ)` and `J_K Δ_K^{it} = Δ_K^{it} J_K`.
* `StandardSubspace.modularGroup_apply_mem_iff` — `Δ_K^{it} K = K`.
* `StandardSubspace.tomita_symplComp`, `tomita_symplComp_eq_compNat` — `S_{K'} = S_K† = Δ_K^{1/2} J_K`.
* `StandardSubspace.sqrt_modular_symplComp`, `modular_symplComp`, `modularGroup_symplComp`,
  `modularConj_symplComp` — `Δ_{K'}^{1/2} = Δ_K^{-1/2}`, `Δ_{K'} = Δ_K⁻¹`, `Δ_{K'}^{it} = Δ_K^{-it}`
  and `J_{K'} = J_K`.
* `StandardSubspace.modularConj_mem_symplComp_iff` — `J_K K = K'`.
* `StandardSubspace.exists_diffContOnCl_modularGroup` — for `ξ ∈ K`, `t ↦ Δ_K^{-it} ξ` continues
  analytically to the strip `0 ≤ im z ≤ 1/2` with `Δ_K^{-i(t + i/2)} ξ = J_K Δ_K^{-it} ξ` (one half
  of the KMS characterisation of `K`; the converse is `mem_iff_modularConj_sqrt`).
* **Covariance**: for a unitary or antiunitary `V : H₁ ≃ₛₗᵢ[σ] H₂` with `V K₁ = K₂`,
  `StandardSubspace.map_mem_symplComp_iff` (`V K₁' = K₂'`), `modular_compNat_eq`, `pvm_modular_map`,
  `sqrt_modular_compNat_eq` (`Δ_{K₂} V = V Δ_{K₁}`), `modularConj_map` (`J_{K₂} = V J_{K₁} V⁻¹`);
  for the modular group
  `modularGroup_map` (`V Δ_{K₁}^{it} V* = Δ_{K₂}^{it}` for unitary `V`) and
  `modularGroup_map_of_antiunitary` (`V Δ_{K₁}^{it} V* = Δ_{K₂}^{-it}` for antiunitary `V`).

## References

* [R. Longo, *Lectures on Conformal Nets, Part I*](https://www.mat.uniroma2.it/longo/Lecture-Notes_files/LN-Part1.pdf),
  §2.1
* M. A. Rieffel, A. van Daele, *A bounded operator approach to Tomita–Takesaki theory*,
  Pacific J. Math. 69 (1977), 187–221
-/

@[expose] public section

open Set Filter Topology Complex ClosedSubmodule MeasureTheory
open scoped InnerProductSpace InnerProduct ComplexConjugate LinearPMap

namespace StandardSubspace

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] (K : StandardSubspace H)

/-! ### The Tomita operator -/

/-- The real-linear map `(x, y) ↦ (x + i y, x - i y)`, whose image of `K × K` is the graph of the
Tomita operator. -/
noncomputable def tomitaMap : (H × H) →ₗ[ℝ] (H × H) where
  toFun p := (p.1 + I • p.2, p.1 - I • p.2)
  map_add' p q := by
    ext <;> simp only [Prod.fst_add, Prod.snd_add, smul_add] <;> abel
  map_smul' r p := by
    ext <;> simp [smul_add, smul_sub, smul_comm r I]

/-- The graph `{(x + i y, x - i y) | x, y ∈ K}` of the Tomita operator. -/
noncomputable def tomitaGraph : Submodule ℝ (H × H) :=
  (K.toClosedSubmodule.toSubmodule.prod K.toClosedSubmodule.toSubmodule).map (tomitaMap (H := H))

/-- Membership in the graph of the Tomita operator. -/
lemma mem_tomitaGraph {u v : H} :
    (u, v) ∈ K.tomitaGraph ↔ ∃ x ∈ K, ∃ y ∈ K,
      x + I • y = u ∧ x - I • y = v := by
  simp only [tomitaGraph, Submodule.mem_map, Submodule.mem_prod, Prod.exists, tomitaMap,
    LinearMap.coe_mk, AddHom.coe_mk, Prod.mk.injEq, mem_toSubmodule_iff]
  exact ⟨fun ⟨x, y, ⟨hx, hy⟩, h⟩ => ⟨x, hx, y, hy, h⟩, fun ⟨x, hx, y, hy, h⟩ => ⟨x, y, ⟨hx, hy⟩, h⟩⟩

/-- `K ∩ i K = 0`: if `x ∈ K` and `x = i y` with `y ∈ K`, then `x = 0`. -/
lemma eq_zero_of_eq_I_smul {x y : H} (hx : x ∈ K) (hy : y ∈ K)
    (h : x = I • y) : x = 0 := by
  have hxi : x ∈ K.toClosedSubmodule.mulI := by
    rw [mem_mapEquiv_iff, scalarSMulCLE_symm_apply, h, Units.smul_def]
    simp [smul_smul, hy]
  have := K.IsSeparating
  rw [eq_bot_iff] at this
  exact ClosedSubmodule.mem_bot.mp (this ⟨hx, hxi⟩)

/-- Real combinations stay in `K`. -/
private lemma comb_mem {x y : H} (hx : x ∈ K) (hy : y ∈ K)
    (a b : ℝ) : a • x + b • y ∈ K :=
  K.toClosedSubmodule.toSubmodule.add_mem (K.toClosedSubmodule.toSubmodule.smul_mem a hx)
    (K.toClosedSubmodule.toSubmodule.smul_mem b hy)

/-- The graph of the Tomita operator is invariant under `(u, v) ↦ (c u, c̄ v)`: `S_K` is
conjugate-linear. -/
lemma smul_mem_tomitaGraph (c : ℂ) {u v : H} (h : (u, v) ∈ K.tomitaGraph) :
    (c • u, starRingEnd ℂ c • v) ∈ K.tomitaGraph := by
  obtain ⟨x, hx, y, hy, rfl, rfl⟩ := K.mem_tomitaGraph.mp h
  refine K.mem_tomitaGraph.mpr ⟨c.re • x + (-c.im) • y, K.comb_mem hx hy _ _,
    c.im • x + c.re • y, K.comb_mem hx hy _ _, ?_, ?_⟩
  · have hc : c = (c.re : ℂ) + c.im * I := (re_add_im c).symm
    have hcI : c * I = -(c.im : ℂ) + c.re * I := by
      rw [hc]
      ring_nf
      rw [I_sq]
      simp
      ring
    have hcx : c • x = (c.re : ℂ) • x + ((c.im : ℂ) * I) • x := by rw [← add_smul, ← hc]
    simp only [← Complex.coe_smul, smul_add, smul_smul, hcI, hcx]
    module
  · have hc : starRingEnd ℂ c = (c.re : ℂ) - c.im * I := by
      apply Complex.ext <;> simp
    have hcI : starRingEnd ℂ c * I = (c.im : ℂ) + c.re * I := by
      rw [hc]
      ring_nf
      rw [I_sq]
      ring
    have hcx : starRingEnd ℂ c • x = (c.re : ℂ) • x - ((c.im : ℂ) * I) • x := by
      rw [← sub_smul, ← hc]
    simp only [← Complex.coe_smul, smul_sub, smul_add, smul_smul, hcI, hcx]
    module

/-- The graph of the Tomita operator is the graph of a function: `x + i y = 0` forces
`x - i y = 0`, because `K ∩ i K = 0`. -/
lemma eq_zero_of_mem_tomitaGraph {v : H} (h : ((0 : H), v) ∈ K.tomitaGraph) : v = 0 := by
  obtain ⟨x, hx, y, hy, hu, rfl⟩ := K.mem_tomitaGraph.mp h
  have hx0 : x = 0 := K.eq_zero_of_eq_I_smul hx (K.toClosedSubmodule.toSubmodule.neg_mem hy)
    (by rw [smul_neg, eq_neg_iff_add_eq_zero, hu])
  rw [hx0, zero_add] at hu
  rw [hx0, hu, sub_zero]

/-- The **Tomita operator** `S_K : x + i y ↦ x - i y` of a standard subspace, a conjugate-linear
operator on the domain `K + i K`; it is well defined because `K ∩ i K = 0`. -/
noncomputable def tomita : H →ₛₗ.[starRingEnd ℂ] H :=
  LinearPMap.ofGraphₛₗ K.tomitaGraph.toAddSubgroup (fun c _ _ h => K.smul_mem_tomitaGraph c h)
    fun _ h => K.eq_zero_of_mem_tomitaGraph h

/-- `S[K]` is the Tomita operator `S_K` of the standard subspace `K`. -/
scoped notation "S[" K "]" => StandardSubspace.tomita K

/-- The graph of the Tomita operator. -/
lemma mem_graph_tomita {u v : H} :
    (u, v) ∈ S[K].graphₛₗ ↔ ∃ x ∈ K, ∃ y ∈ K,
      x + I • y = u ∧ x - I • y = v := by
  rw [tomita, LinearPMap.graphₛₗ_ofGraphₛₗ, Submodule.mem_toAddSubgroup, mem_tomitaGraph]

/-- The Tomita operator is closed: its graph is the preimage of `K × K` under the continuous map
`(u, v) ↦ ((u + v)/2, (u - v)/(2i))`. -/
lemma isClosed_tomita : S[K].IsClosedₛₗ := by
  have hI : I * (-I / 2) = 1 / 2 := by
    ring_nf
    rw [I_sq]
    ring
  have hgraph : (S[K].graphₛₗ : Set (H × H)) =
      (fun p : H × H => ((1 / 2 : ℂ) • (p.1 + p.2), (-I / 2) • (p.1 - p.2))) ⁻¹'
        ((K : Set H) ×ˢ (K : Set H)) := by
    ext ⟨u, v⟩
    simp only [SetLike.mem_coe, mem_preimage, mem_prod]
    rw [K.mem_graph_tomita]
    constructor
    · rintro ⟨x, hx, y, hy, rfl, rfl⟩
      constructor
      · convert hx using 1
        module
      · convert hy using 1
        simp only [smul_sub, smul_add, smul_smul]
        rw [show -I / 2 * I = 1 / 2 by rw [mul_comm, hI]]
        module
    · rintro ⟨hx, hy⟩
      refine ⟨_, hx, _, hy, ?_, ?_⟩
      · rw [smul_smul, hI]
        module
      · rw [smul_smul, hI]
        module
  rw [LinearPMap.IsClosedₛₗ, hgraph]
  exact (K.toClosedSubmodule.isClosed.prod K.toClosedSubmodule.isClosed).preimage (by fun_prop)

/-- The domain `K + i K` of the Tomita operator is dense. -/
lemma dense_domain_tomita : Dense (S[K].domain : Set H) := by
  have hsub : ((K.toClosedSubmodule.toSubmodule ⊔ K.toClosedSubmodule.mulI.toSubmodule :
      Submodule ℝ H) : Set H) ⊆ S[K].domain := fun z hz => by
    obtain ⟨x, hx, w, hw, rfl⟩ := Submodule.mem_sup.mp hz
    have hy : (-I) • w ∈ K := by
      have := (mem_mapEquiv_iff _ _ _).mp hw
      simpa [Units.smul_def] using this
    refine LinearPMap.mem_domain_of_mem_graphₛₗ (y := x - I • ((-I) • w))
      (K.mem_graph_tomita.mpr ⟨x, hx, _, hy, ?_, rfl⟩)
    rw [smul_smul]
    simp
  have htop := K.IsCyclic
  rw [eq_top_iff] at htop
  refine dense_iff_closure_eq.mpr (eq_univ_of_forall fun z => closure_mono hsub ?_)
  exact ClosedSubmodule.mem_sup.mp (htop ClosedSubmodule.mem_top)

/-- `S u = v` implies `S v = u`. -/
private lemma mem_graph_tomita_swap {u v : H} (h : (u, v) ∈ S[K].graphₛₗ) :
    (v, u) ∈ S[K].graphₛₗ := by
  obtain ⟨x, hx, y, hy, rfl, rfl⟩ := K.mem_graph_tomita.mp h
  refine K.mem_graph_tomita.mpr ⟨x, hx, -y, K.toClosedSubmodule.toSubmodule.neg_mem hy, ?_, ?_⟩ <;>
    simp [sub_eq_add_neg]

/-- **The Tomita operator is an involution**: `S_K² = 1` on `dom S_K`. -/
lemma tomita_compNat_tomita : S[K].compNat S[K] = (LinearMap.id : H →ₗ[ℂ] H).toPMap S[K].domain :=
  -- `S (x + i y) = x - i y` is computed on the generating vectors
  LinearPMap.compNat_self_eq_id_iff.mpr fun _ _ h => K.mem_graph_tomita_swap h

/-- `K` is the set of fixed points of the Tomita operator. -/
lemma mem_iff_mem_graph_tomita {ξ : H} :
    ξ ∈ K ↔ (ξ, ξ) ∈ S[K].graphₛₗ := by
  constructor
  · intro hξ
    exact K.mem_graph_tomita.mpr ⟨ξ, hξ, 0, K.toClosedSubmodule.toSubmodule.zero_mem, by simp,
      by simp⟩
  · intro h
    obtain ⟨x, hx, y, hy, h₁, h₂⟩ := K.mem_graph_tomita.mp h
    have hy0 : I • y = 0 := by
      have : (2 : ℂ) • (I • y) = 0 := by
        rw [two_smul]
        nth_rewrite 1 [← sub_eq_zero.mpr (h₁.trans h₂.symm)]
        abel
      exact (smul_eq_zero.mp this).resolve_left two_ne_zero
    rw [← h₁, hy0, add_zero]
    exact hx

/-! ### Cyclicity -/

/-- **Cyclicity**: a closed real subspace containing `K` and `i K` is the whole space. -/
lemma eq_top_of_le {S : ClosedSubmodule ℝ H} (hK : K.toClosedSubmodule ≤ S)
    (hI : ∀ x ∈ K, I • x ∈ S) : S = ⊤ := by
  refine eq_top_iff.mpr (K.IsCyclic ▸ sup_le hK fun x hx => ?_)
  have h := hI _ ((mem_mapEquiv_iff _ _ x).mp hx)
  simpa [Units.smul_def, smul_smul] using h

/-- Two continuous complex-linear maps which agree on a standard subspace are equal. -/
lemma ext_continuousLinearMap {F : Type*} [NormedAddCommGroup F] [NormedSpace ℂ F]
    {f g : H →L[ℂ] F} (h : ∀ x ∈ K, f x = g x) : f = g := by
  let S : ClosedSubmodule ℝ H :=
    ⟨LinearMap.ker ((f - g).restrictScalars ℝ : H →ₗ[ℝ] F),
      ((f - g).restrictScalars ℝ).isClosed_ker⟩
  have hS : S = ⊤ := K.eq_top_of_le (fun x hx => sub_eq_zero.mpr (h x hx)) fun x hx => by
    change (f - g) (I • x) = 0
    rw [map_smul, sub_apply, h x hx, sub_self, smul_zero]
  refine ContinuousLinearMap.ext fun x => sub_eq_zero.mp ?_
  have hx : x ∈ S := hS ▸ ClosedSubmodule.mem_top
  exact hx

/-- A vector orthogonal to a standard subspace vanishes. -/
lemma eq_zero_of_forall_inner_eq_zero {v : H} (h : ∀ x ∈ K, ⟪x, v⟫_ℂ = 0) :
    v = 0 := by
  have hv := K.ext_continuousLinearMap (f := innerSL ℂ v) (g := 0) fun x hx => by
    rw [innerSL_apply_apply, ← inner_conj_symm, h x hx, map_zero, zero_apply]
  have := congrArg (fun f : H →L[ℂ] ℂ => f v) hv
  simpa using this

/-! ### The modular operator and the modular conjugation -/

variable [CompleteSpace H]

/-- The **modular operator** `Δ_K = S_K† S_K` of a standard subspace, a positive self-adjoint
complex-linear operator (`StandardSubspace.isSelfAdjoint_modular`): the composite of the
conjugate-linear `S_K` and its conjugate-linear adjoint is complex-linear. -/
noncomputable def modular : H →ₗ.[ℂ] H :=
  S[K].adjointₛₗ.compNat S[K]

/-- `Δ[K]` is the modular operator `Δ_K` of the standard subspace `K`. -/
scoped notation "Δ[" K "]" => StandardSubspace.modular K

/-- `Δ_K = S_K† S_K`. -/
lemma modular_def : Δ[K] = S[K].adjointₛₗ.compNat S[K] :=
  rfl

/-- The modular operator is self-adjoint (von Neumann's theorem). -/
lemma isSelfAdjoint_modular : IsSelfAdjoint Δ[K] :=
  LinearPMap.isSelfAdjoint_adjointₛₗ_compNat_self K.isClosed_tomita K.dense_domain_tomita

/-- `Δ[K]^{1/2}` is the positive square root `Δ_K^{1/2}` of the modular operator. -/
scoped notation "Δ[" K "]^{1/2}" => IsSelfAdjoint.sqrt (StandardSubspace.isSelfAdjoint_modular K)

open Lean PrettyPrinter Delaborator SubExpr in
/-- Delaborator displaying `IsSelfAdjoint.sqrt (StandardSubspace.isSelfAdjoint_modular K)` as
`Δ[K]^{1/2}`; an unexpander cannot do this, since the proof argument is elided as `⋯`. -/
@[scoped delab app.IsSelfAdjoint.sqrt]
meta def delabSqrtModular : Delab := do
  let e ← getExpr
  guard <| e.appArg!.isAppOfArity ``StandardSubspace.isSelfAdjoint_modular 5
  let K ← withAppArg <| withNaryArg 3 delab
  `(Δ[$K]^{1/2})

/-- The modular operator is positive. -/
lemma isPositive_modular : Δ[K].IsPositive :=
  LinearPMap.isPositive_adjointₛₗ_compNat_self K.dense_domain_tomita

omit [CompleteSpace H] in
/-- The Tomita operator is injective. -/
lemma ker_tomita_eq_bot : S[K].ker = ⊥ :=
  LinearPMap.ker_eq_bot_of_involution K.tomita_compNat_tomita

omit [CompleteSpace H] in
/-- The Tomita operator has dense range: its range is its domain. -/
lemma dense_range_tomita : Dense (Set.range S[K]) :=
  LinearPMap.dense_range_of_involution K.tomita_compNat_tomita K.dense_domain_tomita

/-- The modular operator is injective. -/
lemma ker_modular_eq_bot : Δ[K].ker = ⊥ :=
  (K.isSelfAdjoint_modular.ker_eq_bot_iff_of_eq_adjointₛₗ_compNat K.modular_def).mpr
    K.ker_tomita_eq_bot

/-- The modular operator is positive and injective: its spectral measure vanishes on `(-∞, 0]`. -/
lemma pvm_modular_Iic_eq_zero : K.isSelfAdjoint_modular.pvm (Iic 0) = 0 :=
  K.isSelfAdjoint_modular.pvm_Iic_eq_zero K.isPositive_modular K.ker_modular_eq_bot

/-- The modular operator is injective: its spectral measure lives on `(0, ∞)`. -/
lemma ae_pos_measure_pvm_modular (y : H) :
    ∀ᵐ t ∂(K.isSelfAdjoint_modular.pvm.measure y), 0 < t :=
  (measure_eq_zero_iff_ae_notMem.mp (K.isSelfAdjoint_modular.measure_pvm_Iic_zero
    K.isPositive_modular K.ker_modular_eq_bot y)).mono
    fun _ ht => not_le.mp ht

/-- The **modular conjugation** `J_K`: the antiunitary part of the polar decomposition
`S_K = J_K Δ_K^{1/2}` (`StandardSubspace.tomita_eq_modularConj_compPMap`). -/
noncomputable def modularConj : H ≃ₗᵢ⋆[ℂ] H :=
  K.isSelfAdjoint_modular.polarIsometryEquiv K.modular_def K.isClosed_tomita
    K.ker_tomita_eq_bot K.dense_range_tomita

/-- `J[K]` is the modular conjugation `J_K` of the standard subspace `K`. -/
scoped notation "J[" K "]" => StandardSubspace.modularConj K

/-- `J_K² = 1`. -/
@[simp]
lemma modularConj_modularConj (x : H) : J[K] (J[K] x) = x :=
  K.isSelfAdjoint_modular.polarIsometryEquiv_apply_apply _ _ K.tomita_compNat_tomita x

/-- **`J_K† = J_K`**: `J_K` is an antiunitary involution, so its adjoint `J_K⁻¹` is `J_K`. -/
lemma adjointₛₗ_modularConj : (J[K] : H →L⋆[ℂ] H).adjointₛₗ = J[K] := by
  rw [LinearIsometryEquiv.adjointₛₗ_eq_symm]
  ext x
  change J[K].symm x = J[K] x
  conv_lhs => rw [← K.modularConj_modularConj x]
  exact J[K].symm_apply_apply _

/-- **Polar decomposition** `S_K = J_K Δ_K^{1/2}`. -/
theorem tomita_eq_modularConj_compPMap :
    S[K] = (J[K] : H →ₗ⋆[ℂ] H).compPMap Δ[K]^{1/2} :=
  K.isSelfAdjoint_modular.eq_polarIsometry_compPMap K.modular_def K.isClosed_tomita

/-- `S_K = J_K Δ_K^{1/2}`, pointwise. -/
private lemma mem_graph_tomita_iff {u v : H} :
    (u, v) ∈ S[K].graphₛₗ ↔ ∃ w, (u, w) ∈ Δ[K]^{1/2}.graph ∧ J[K] w = v := by
  conv_lhs => rw [K.tomita_eq_modularConj_compPMap]
  rw [LinearPMap.mem_graphₛₗ_compPMap]
  simp only [LinearPMap.mem_graphₛₗ_iff_mem_graph]
  rfl

/-- **`ξ ∈ K` iff `J_K Δ_K^{1/2} ξ = ξ`**. -/
lemma mem_iff_modularConj_sqrt {ξ : H} :
    ξ ∈ K ↔
      ∃ w, (ξ, w) ∈ Δ[K]^{1/2}.graph ∧ J[K] w = ξ := by
  rw [K.mem_iff_mem_graph_tomita, mem_graph_tomita_iff]

/-- **`J_K Δ_K^{1/2} J_K = Δ_K^{-1/2}`**, as `Δ_K^{1/2} J_K = J_K Δ_K^{-1/2}`. -/
lemma sqrt_modular_compNat_modularConj :
    Δ[K]^{1/2}.compNat ((J[K] : H →ₗ⋆[ℂ] H).toPMap ⊤) =
      (J[K] : H →ₗ⋆[ℂ] H).compPMap Δ[K]^{1/2}.inverse :=
  K.isSelfAdjoint_modular.sqrt_compNat_polarIsometryEquiv _ _ K.tomita_compNat_tomita

/-- `Δ_K^{-1/2} x = u` iff `Δ_K^{1/2} (J_K x) = J_K u`. -/
private lemma mem_graph_inverse_sqrt_modular_iff {x u : H} :
    (x, u) ∈ Δ[K]^{1/2}.inverse.graph ↔
      (J[K] x, J[K] u) ∈ Δ[K]^{1/2}.graph :=
  (LinearPMap.compNat_toPMap_eq_compPMap_iff J[K].toLinearEquiv).mp
    K.sqrt_modular_compNat_modularConj x u

/-- `Δ_K^{1/2}` is injective. -/
lemma ker_sqrt_modular_eq_bot : Δ[K]^{1/2}.ker = ⊥ :=
  K.isSelfAdjoint_modular.ker_sqrt_eq_bot K.isPositive_modular K.ker_modular_eq_bot

/-- `J_K Δ_K^{1/2} J_K = Δ_K^{-1/2}` in graph form: `Δ_K^{1/2} x = u` iff
`Δ_K^{1/2} (J_K u) = J_K x`. -/
private lemma mem_graph_sqrt_modularConj_iff {x u : H} :
    (x, u) ∈ Δ[K]^{1/2}.graph ↔
      (J[K] u, J[K] x) ∈ Δ[K]^{1/2}.graph := by
  rw [← K.mem_graph_inverse_sqrt_modular_iff, LinearPMap.mem_graph_inverse_iff
    K.ker_sqrt_modular_eq_bot]

/-- The **modular group** `t ↦ Δ_K^{it}`: the imaginary powers of the positive injective `Δ_K`
(`IsSelfAdjoint.imaginaryPowerGroup`), the unitary group `e^{it log Δ_K}` generated by `log Δ_K`
(`IsSelfAdjoint.imaginaryPower_eq_unitaryGroup`). -/
noncomputable abbrev modularGroup : AddChar ℝ (unitary (H →L[ℂ] H)) :=
  K.isSelfAdjoint_modular.imaginaryPowerGroup K.isPositive_modular K.ker_modular_eq_bot

/-- `Δ[K]^{i t}` is the unitary `Δ_K^{it}` of the modular group, as a bounded operator. The
exponent is parsed at `max` precedence, so a compound exponent needs parentheses:
`Δ[K]^{i (s + t)}`. -/
scoped notation "Δ[" K "]^{i " t:max "}" => Subtype.val (StandardSubspace.modularGroup K t)

/-- `Δ[K]^{-i t}` is `Δ_K^{-it} = Δ_K^{i(-t)}`. -/
scoped notation "Δ[" K "]^{-i " t:max "}" => Subtype.val (StandardSubspace.modularGroup K (-t))

open Lean PrettyPrinter Delaborator SubExpr in
/-- Delaborator displaying the bounded operator `↑(StandardSubspace.modularGroup K t)` as
`Δ[K]^{i t}`, and `↑(StandardSubspace.modularGroup K (-t))` as `Δ[K]^{-i t}`. -/
@[scoped delab app.Subtype.val]
meta def delabModularGroupVal : Delab := do
  -- the argument is `DFunLike.coe (StandardSubspace.modularGroup K) t`
  let g := (← getExpr).appArg!
  guard <| g.isAppOfArity ``DFunLike.coe 6
  guard <| (g.getArg! 4).isAppOfArity ``StandardSubspace.modularGroup 5
  let K ← withAppArg <| withNaryArg 4 <| withNaryArg 3 delab
  if (g.getArg! 5).isAppOfArity ``Neg.neg 3 then
    let t ← withAppArg <| withNaryArg 5 <| withAppArg delab
    `(Δ[$K]^{-i $t})
  else
    let t ← withAppArg <| withNaryArg 5 delab
    `(Δ[$K]^{i $t})

/-- `Δ_K^{it} = ∫ λ^{it} dE_Δ(λ)`, with `λ^{it} = e^{it log λ}`. -/
lemma coe_modularGroup_apply (t : ℝ) :
    Δ[K]^{i t} =
      K.isSelfAdjoint_modular.pvm.integral fun s : ℝ => cexp (t * Real.log s * I) :=
  (K.isSelfAdjoint_modular.imaginaryPower_eq_unitaryGroup K.isPositive_modular K.ker_modular_eq_bot
    t).trans (K.isSelfAdjoint_modular.coe_unitaryGroup_logPMap_apply t)

/-- **`J_K Δ_K^{it} J_K = Δ_K^{it}`**. -/
lemma modularConj_modularGroup_apply (t : ℝ) (x : H) :
    J[K] (Δ[K]^{i t} (J[K] x)) =
      Δ[K]^{i t} x := by
  rw [coe_modularGroup_apply]
  have h := K.isSelfAdjoint_modular.polarIsometryEquiv_integral_apply K.modular_def
    K.isClosed_tomita K.tomita_compNat_tomita
    (f := fun s : ℝ => cexp (t * Real.log s * I)) (by fun_prop)
    ⟨1, fun s => by rw [← ofReal_mul, norm_exp_ofReal_mul_I]⟩ x
  refine h.trans (congrArg (fun f => K.isSelfAdjoint_modular.pvm.integral f x) (funext fun s => ?_))
  rw [Real.log_inv, ← exp_conj, map_mul, map_mul, conj_I, Complex.conj_ofReal,
    Complex.conj_ofReal]
  push_cast
  ring_nf

/-- `J_K` commutes with `Δ_K^{it}`. -/
lemma modularConj_comm_modularGroup (t : ℝ) (x : H) :
    J[K] (Δ[K]^{i t} x) =
      Δ[K]^{i t} (J[K] x) := by
  conv_lhs => rw [← K.modularConj_modularConj x]
  rw [K.modularConj_modularGroup_apply]

/-- `J_K` is an antiunitary involution: `⟪J_K x, y⟫ = ⟪J_K y, x⟫`. -/
lemma inner_modularConj_left (x y : H) : ⟪J[K] x, y⟫_ℂ = ⟪J[K] y, x⟫_ℂ := by
  conv_lhs => rw [← K.modularConj_modularConj y]
  rw [J[K].inner_map_mapₛₗ, inner_conj_symm]

/-- `Δ_K^{-it} = (Δ_K^{it})*`. -/
lemma inner_modularGroup_neg_left (t : ℝ) (x y : H) :
    ⟪Δ[K]^{-i t} x, y⟫_ℂ = ⟪x, Δ[K]^{i t} y⟫_ℂ := by
  rw [AddChar.map_neg_eq_inv, ← Unitary.star_eq_inv, Unitary.coe_star,
    ContinuousLinearMap.star_eq_adjoint, ContinuousLinearMap.adjoint_inner_left]

/-- **`Δ_K^{it}` commutes with `Δ_K^{1/2}`**: `Δ_K^{it} Δ_K^{1/2} ⊆ Δ_K^{1/2} Δ_K^{it}`. -/
lemma modularGroup_compPMap_sqrt_le (t : ℝ) :
    ((Δ[K]^{i t} : H →L[ℂ] H) : H →ₗ[ℂ] H).compPMap Δ[K]^{1/2} ≤
      Δ[K]^{1/2}.compNat (((Δ[K]^{i t} : H →L[ℂ] H) : H →ₗ[ℂ] H).toPMap ⊤) := by
  rw [coe_modularGroup_apply]
  exact K.isSelfAdjoint_modular.pvm.integral_compPMap_integralPMap_le
    (Complex.measurable_ofReal.comp Real.continuous_sqrt.measurable) (by fun_prop)
    ⟨1, fun s => by rw [← ofReal_mul, norm_exp_ofReal_mul_I]⟩

/-- `Δ_K^{it}` maps the graph of `Δ_K^{1/2}` into itself. -/
private lemma mem_graph_sqrt_modularGroup (t : ℝ) {x u : H}
    (h : (x, u) ∈ Δ[K]^{1/2}.graph) :
    (Δ[K]^{i t} x, Δ[K]^{i t} u) ∈ Δ[K]^{1/2}.graph :=
  LinearPMap.compPMap_le_compNat_toPMap_iff.mp (K.modularGroup_compPMap_sqrt_le t) h

/-- **`Δ_K^{it} K ⊆ K`**. -/
lemma modularGroup_apply_mem {ξ : H} (hξ : ξ ∈ K) (t : ℝ) :
    Δ[K]^{i t} ξ ∈ K := by
  obtain ⟨w, hw, hwξ⟩ := K.mem_iff_modularConj_sqrt.mp hξ
  refine K.mem_iff_modularConj_sqrt.mpr ⟨_, K.mem_graph_sqrt_modularGroup t hw, ?_⟩
  rw [K.modularConj_comm_modularGroup, hwξ]

/-- **`Δ_K^{it} K = K`**: `ξ ∈ K` iff `Δ_K^{it} ξ ∈ K`. -/
lemma modularGroup_apply_mem_iff {ξ : H} (t : ℝ) :
    Δ[K]^{i t} ξ ∈ K ↔ ξ ∈ K := by
  refine ⟨fun h => ?_, fun h => K.modularGroup_apply_mem h t⟩
  have h' := K.modularGroup_apply_mem h (-t)
  rwa [← mul_apply_eq_comp, ← Submonoid.coe_mul, ← AddChar.map_add_eq_mul, neg_add_cancel,
    AddChar.map_zero_eq_one, OneMemClass.coe_one, one_apply_eq_self] at h'

/-! ### The symplectic complement -/

omit [CompleteSpace H] in
/-- **`S_{K'} = S_K†`**: the Tomita operator of the symplectic complement is the adjoint of the
Tomita operator. -/
theorem tomita_symplComp [CompleteSpace H] : K.symplComp.tomita = S[K].adjointₛₗ := by
  have hI : I * (-I / 2) = 1 / 2 := by
    ring_nf
    rw [I_sq]
    ring
  refine LinearPMap.eq_of_eq_graphₛₗ (AddSubgroup.ext fun ⟨u, v⟩ => ?_)
  rw [LinearPMap.mem_graphₛₗ_adjointₛₗ_iff_re K.dense_domain_tomita, K.symplComp.mem_graph_tomita]
  constructor
  · rintro ⟨x', hx', y', hy', rfl, rfl⟩ a b hab
    obtain ⟨x, hx, y, hy, rfl, rfl⟩ := K.mem_graph_tomita.mp hab
    have h₂ : (⟪x', y⟫_ℂ).im = 0 := by
      rw [← inner_conj_symm, conj_im, (mem_symplComp_iff.mp hx') y hy, neg_zero]
    have h₃ : (⟪y', x⟫_ℂ).im = 0 := by
      rw [← inner_conj_symm, conj_im, (mem_symplComp_iff.mp hy') x hx, neg_zero]
    simp only [inner_add_left, inner_add_right, inner_sub_left, inner_sub_right, inner_smul_left,
      inner_smul_right, conj_I, mul_re, neg_re, neg_im, I_re, I_im, add_re, sub_re, mul_im, add_im,
      sub_im]
    linarith
  · intro h
    have h₁ : ∀ x ∈ K, (⟪x, u⟫_ℂ).re = (⟪x, v⟫_ℂ).re := fun x hx => by
      have := h x x (K.mem_iff_mem_graph_tomita.mp hx)
      rw [← inner_conj_symm u, ← inner_conj_symm v, conj_re, conj_re] at this
      linarith
    have h₂ : ∀ x ∈ K, (⟪x, u + v⟫_ℂ).im = 0 := fun x hx => by
      have := h (0 + I • x) (0 - I • x)
        (K.mem_graph_tomita.mpr ⟨0, K.toClosedSubmodule.toSubmodule.zero_mem, x, hx, rfl, rfl⟩)
      rw [← inner_conj_symm u, ← inner_conj_symm v, conj_re, conj_re] at this
      simp only [zero_add, zero_sub, inner_neg_left, inner_smul_left, conj_I, neg_re, mul_re, neg_im,
        I_re, I_im] at this
      rw [inner_add_right, add_im]
      linarith
    refine ⟨(1 / 2 : ℂ) • (u + v), ?_, (-I / 2) • (u - v), ?_, ?_, ?_⟩
    · refine mem_symplComp_iff.mpr fun x hx => ?_
      rw [inner_smul_right, mul_im, h₂ x hx]
      simp
    · refine mem_symplComp_iff.mpr fun x hx => ?_
      rw [inner_smul_right, mul_im, inner_sub_right, sub_re, h₁ x hx]
      simp
    · rw [smul_smul, hI]
      module
    · rw [smul_smul, hI]
      module

/-- `S_{K'} u = v` iff `Δ_K^{1/2} J_K u = v`. -/
private lemma mem_graph_tomita_symplComp_iff {u v : H} :
    (u, v) ∈ K.symplComp.tomita.graphₛₗ ↔
      (J[K] u, v) ∈ Δ[K]^{1/2}.graph := by
  rw [tomita_symplComp, K.tomita_eq_modularConj_compPMap,
    show (J[K] : H →ₗ⋆[ℂ] H) = ((J[K] : H →L⋆[ℂ] H) : H →ₗ⋆[ℂ] H) from rfl,
    LinearPMap.adjointₛₗ_compPMap K.isSelfAdjoint_modular.isSelfAdjoint_sqrt.dense_domain,
    adjointₛₗ_modularConj, LinearPMap.mem_graphₛₗ_compNat_toPMap, LinearPMap.adjointₛₗ_eq_adjoint,
    LinearPMap.isSelfAdjoint_def.mp K.isSelfAdjoint_modular.isSelfAdjoint_sqrt,
    LinearPMap.mem_graphₛₗ_iff_mem_graph]
  rfl

/-- **`S_{K'} = Δ_K^{1/2} J_K`**. -/
lemma tomita_symplComp_eq_compNat :
    K.symplComp.tomita = Δ[K]^{1/2}.compNat ((J[K] : H →ₗ⋆[ℂ] H).toPMap ⊤) :=
  LinearPMap.eq_of_eq_graphₛₗ (AddSubgroup.ext fun ⟨_, _⟩ => by
    rw [mem_graph_tomita_symplComp_iff, LinearPMap.mem_graphₛₗ_compNat_toPMap,
      LinearPMap.mem_graphₛₗ_iff_mem_graph]
    rfl)

/-- **`J_K K = K'`**: `J_K ξ ∈ K'` iff `ξ ∈ K`. -/
lemma modularConj_mem_symplComp_iff {ξ : H} :
    J[K] ξ ∈ K.symplComp ↔ ξ ∈ K := by
  rw [K.symplComp.mem_iff_mem_graph_tomita, mem_graph_tomita_symplComp_iff, modularConj_modularConj,
    K.mem_iff_modularConj_sqrt]
  constructor
  · intro h
    exact ⟨_, h, K.modularConj_modularConj ξ⟩
  · rintro ⟨w, hw, hwξ⟩
    have hξw : J[K] ξ = w := by rw [← hwξ, modularConj_modularConj]
    rwa [hξw]

/-- **`J_K K' ⊆ K`**. -/
lemma modularConj_mem_of_mem_symplComp {ξ : H} (hξ : ξ ∈ K.symplComp) :
    J[K] ξ ∈ K :=
  K.modularConj_mem_symplComp_iff.mp (by rwa [modularConj_modularConj])

/-- The Tomita involution has injective modular operator: `Δ_K^{1/2}` does not vanish
`E_Δ`-almost everywhere. -/
private lemma ae_sqrt_ne_zero (y : H) :
    ∀ᵐ t ∂(K.isSelfAdjoint_modular.pvm.measure y), (Real.sqrt t : ℂ) ≠ 0 :=
  (K.ae_pos_measure_pvm_modular y).mono fun _ ht => ofReal_ne_zero.mpr (Real.sqrt_pos.mpr ht).ne'

/-- `Δ_K^{-1/2} = ∫ λ^{-1/2} dE_{Δ_K}`. -/
private lemma integralPMap_inv_sqrt :
    (K.isSelfAdjoint_modular.pvm.integralPMap fun t => (((Real.sqrt t)⁻¹ : ℝ) : ℂ)) =
      Δ[K]^{1/2}.inverse := by
  simp_rw [ofReal_inv]
  exact K.isSelfAdjoint_modular.pvm.integralPMap_inv
    (Complex.measurable_ofReal.comp Real.continuous_sqrt.measurable) K.ae_sqrt_ne_zero

/-- The graph of `∫ λ^{-1/2} dE_{Δ_K}` is the flipped graph of `Δ_K^{1/2}`. -/
private lemma mem_graph_integralPMap_inv_sqrt_iff {u w : H} :
    (u, w) ∈ (K.isSelfAdjoint_modular.pvm.integralPMap fun t =>
      (((Real.sqrt t)⁻¹ : ℝ) : ℂ)).graph ↔ (w, u) ∈ Δ[K]^{1/2}.graph := by
  rw [integralPMap_inv_sqrt, LinearPMap.mem_graph_inverse_iff K.ker_sqrt_modular_eq_bot]

/-- `Δ_{K'}^{1/2} = ∫ λ^{-1/2} dE_{Δ_K}`. -/
private lemma sqrt_modular_symplComp_eq_integralPMap :
    K.symplComp.isSelfAdjoint_modular.sqrt =
      K.isSelfAdjoint_modular.pvm.integralPMap fun t => (((Real.sqrt t)⁻¹ : ℝ) : ℂ) := by
  set E' := K.isSelfAdjoint_modular.pvm
  set Jr := K.isSelfAdjoint_modular.polarIsometry K.modular_def K.isClosed_tomita
  have hinvgraph : ∀ u w, (u, w) ∈ (E'.integralPMap fun t => (((Real.sqrt t)⁻¹ : ℝ) : ℂ)).graph ↔
      (w, u) ∈ Δ[K]^{1/2}.graph := fun u w =>
    K.mem_graph_integralPMap_inv_sqrt_iff
  have hsa : IsSelfAdjoint (E'.integralPMap fun t => (((Real.sqrt t)⁻¹ : ℝ) : ℂ)) :=
    E'.isSelfAdjoint_integralPMap_ofReal Real.continuous_sqrt.measurable.inv
  have hpos : (E'.integralPMap fun t => (((Real.sqrt t)⁻¹ : ℝ) : ℂ)).IsPositive :=
    E'.isPositive_integralPMap_ofReal Real.continuous_sqrt.measurable.inv
      fun t => inv_nonneg.mpr (Real.sqrt_nonneg t)
  have hJ : ∀ x, ‖Jr x‖ = ‖x‖ := K.isSelfAdjoint_modular.norm_polarIsometry_of_ker_eq_bot
    K.modular_def K.isClosed_tomita K.ker_tomita_eq_bot
  refine (K.symplComp.isSelfAdjoint_modular.eq_sqrt_of_eq_compPMap
    K.symplComp.modular_def hsa hpos Jr (fun y _ => hJ y) ?_).symm
  refine LinearPMap.eq_of_eq_graphₛₗ (AddSubgroup.ext fun ⟨u, v⟩ => ?_)
  rw [mem_graph_tomita_symplComp_iff, LinearPMap.mem_graphₛₗ_compPMap]
  simp only [LinearPMap.mem_graphₛₗ_iff_mem_graph]
  constructor
  · intro h
    refine ⟨J[K] v, ?_, ?_⟩
    · rw [hinvgraph, K.mem_graph_sqrt_modularConj_iff, modularConj_modularConj]
      exact h
    · change J[K] (J[K] v) = v
      exact K.modularConj_modularConj v
  · rintro ⟨w, hw, rfl⟩
    rw [hinvgraph, K.mem_graph_sqrt_modularConj_iff] at hw
    exact hw

/-- **`Δ_{K'}^{1/2} = Δ_K^{-1/2}`**: the square root of the modular operator of the symplectic
complement is the inverse of that of `K`. -/
lemma sqrt_modular_symplComp :
    K.symplComp.isSelfAdjoint_modular.sqrt = Δ[K]^{1/2}.inverse := by
  rw [sqrt_modular_symplComp_eq_integralPMap, integralPMap_inv_sqrt]

/-- `Δ_{K'} = ∫ λ⁻¹ dE_{Δ_K}`. -/
private lemma modular_symplComp_eq_integralPMap :
    K.symplComp.modular = K.isSelfAdjoint_modular.pvm.integralPMap fun t => ((t⁻¹ : ℝ) : ℂ) := by
  set E' := K.isSelfAdjoint_modular.pvm
  have hm : Measurable fun t : ℝ => (((Real.sqrt t)⁻¹ : ℝ) : ℂ) :=
    Complex.measurable_ofReal.comp Real.continuous_sqrt.measurable.inv
  rw [← K.symplComp.isSelfAdjoint_modular.sqrt_compNat_sqrt K.symplComp.isPositive_modular,
    sqrt_modular_symplComp_eq_integralPMap,
    E'.compNat_integralPMap hm hm fun y h => memLp_of_memLp_mul_self hm h]
  refine E'.integralPMap_congr_ae (hm.mul hm) (by fun_prop) fun y =>
    (K.isSelfAdjoint_modular.ae_nonneg_measure_pvm y K.isPositive_modular).mono fun t ht => ?_
  simp only [Pi.mul_apply, ← ofReal_mul, ← mul_inv, Real.mul_self_sqrt ht]

/-- **`Δ_{K'} = Δ_K⁻¹`**: the modular operator of the symplectic complement is the inverse of that
of `K`. -/
lemma modular_symplComp : K.symplComp.modular = Δ[K].inverse := by
  rw [modular_symplComp_eq_integralPMap]
  conv_rhs => rw [K.isSelfAdjoint_modular.eq_integralPMap_pvm]
  simp_rw [ofReal_inv]
  exact K.isSelfAdjoint_modular.pvm.integralPMap_inv Complex.measurable_ofReal fun y =>
    (K.ae_pos_measure_pvm_modular y).mono fun _ ht => ofReal_ne_zero.mpr ht.ne'

/-- **`J_{K'} = J_K`**. -/
lemma modularConj_symplComp (x : H) : K.symplComp.modularConj x = J[K] x := by
  -- both agree on the range of `Δ_{K'}^{1/2} = Δ_K^{-1/2}`, which contains `dom Δ_K^{1/2}`
  have hagree : ∀ u w, (u, w) ∈ K.symplComp.isSelfAdjoint_modular.sqrt.graph →
      K.symplComp.modularConj w = J[K] w := fun u w h => by
    have h₁ := (K.symplComp.mem_graph_tomita_iff).mpr ⟨w, h, rfl⟩
    have h₂ : (u, J[K] w) ∈ K.symplComp.tomita.graphₛₗ := by
      rw [mem_graph_tomita_symplComp_iff, K.mem_graph_sqrt_modularConj_iff.symm]
      rw [sqrt_modular_symplComp_eq_integralPMap] at h
      exact K.mem_graph_integralPMap_inv_sqrt_iff.mp h
    exact LinearPMap.mem_graphₛₗ_snd_inj h₁ h₂
  have hdense : Dense (Δ[K]^{1/2}.domain : Set H) :=
    K.isSelfAdjoint_modular.isSelfAdjoint_sqrt.dense_domain
  have hclosed : IsClosed {w : H | K.symplComp.modularConj w = J[K] w} :=
    isClosed_eq K.symplComp.modularConj.continuous J[K].continuous
  refine hclosed.closure_subset_iff.mpr (fun w hw => ?_) (hdense.closure_eq ▸ mem_univ x)
  obtain ⟨u, hu⟩ : ∃ u, (u, w) ∈ K.symplComp.isSelfAdjoint_modular.sqrt.graph := by
    refine ⟨Δ[K]^{1/2} ⟨w, hw⟩, ?_⟩
    rw [sqrt_modular_symplComp_eq_integralPMap]
    exact K.mem_graph_integralPMap_inv_sqrt_iff.mpr (Δ[K]^{1/2}.mem_graph ⟨w, hw⟩)
  exact hagree u w hu


/-- **`Δ_{K'}^{it} = Δ_K^{-it}`**. -/
lemma modularGroup_symplComp (t : ℝ) : Δ[K.symplComp]^{i t} = Δ[K]^{-i t} := by
  have hinv : Measurable fun s : ℝ => s⁻¹ := measurable_inv
  have hpvm : K.symplComp.isSelfAdjoint_modular.pvm = K.isSelfAdjoint_modular.pvm.map _ hinv := by
    have key : ∀ {A B : H →ₗ.[ℂ] H} (hA : IsSelfAdjoint A) (hB : IsSelfAdjoint B), A = B →
        hA.pvm = hB.pvm := by
      rintro _ _ _ _ rfl
      rfl
    rw [key _ (K.isSelfAdjoint_modular.pvm.isSelfAdjoint_integralPMap_ofReal hinv)
      K.modular_symplComp_eq_integralPMap, ProjectionValuedMeasure.pvm_integralPMap_ofReal]
  rw [coe_modularGroup_apply, coe_modularGroup_apply, hpvm,
    ProjectionValuedMeasure.integral_map (by fun_prop)
      ⟨1, fun s => by rw [← ofReal_mul, norm_exp_ofReal_mul_I]⟩ hinv]
  congr 1
  funext s
  simp only [Function.comp_apply, Real.log_inv, ofReal_neg]
  ring_nf

/-! ### Analytic continuation of the modular orbits -/

/-- **Analytic continuation of the modular orbits** (the KMS condition satisfied by `ξ ∈ K`): for
`ξ ∈ K`, the orbit `t ↦ Δ_K^{-it} ξ` extends to the bounded function `z ↦ Δ_K^{-iz} ξ`
(`IsSelfAdjoint.cpow`) on the strip `0 ≤ im z ≤ 1/2`, holomorphic in the interior and continuous
on the closure, with boundary values `J_K Δ_K^{-it} ξ` on `im z = 1/2`. -/
theorem exists_diffContOnCl_modularGroup {ξ : H} (hξ : ξ ∈ K) :
    ∃ F : ℂ → H, DiffContOnCl ℂ F (im ⁻¹' Ioo 0 (1 / 2)) ∧
      BddAbove ((norm ∘ F) '' (im ⁻¹' Icc 0 (1 / 2))) ∧
      (∀ t : ℝ, F t = Δ[K]^{-i t} ξ) ∧
      (∀ t : ℝ, F (t + I / 2) = J[K] (Δ[K]^{-i t} ξ)) ∧
      ∀ z ∈ im ⁻¹' Icc 0 (1 / 2), (ξ, F z) ∈ (K.isSelfAdjoint_modular.cpow (-I * z)).graph := by
  set E := K.isSelfAdjoint_modular.pvm
  have hφ : Measurable fun x : ℝ => -Real.log x := Real.measurable_log.neg
  have hsqm : Measurable fun x : ℝ => (Real.sqrt x : ℂ) :=
    Complex.measurable_ofReal.comp Real.continuous_sqrt.measurable
  obtain ⟨w, hw, hwξ⟩ := K.mem_iff_modularConj_sqrt.mp hξ
  rw [IsSelfAdjoint.sqrt, ProjectionValuedMeasure.sqrt,
    ProjectionValuedMeasure.mem_graph_integralPMap] at hw
  have hpos := K.ae_pos_measure_pvm_modular ξ
  have ha : MemLp (fun x : ℝ => Real.exp (-0 * -Real.log x)) 2 (E.measure ξ) := by
    simpa using memLp_const (1 : ℝ)
  have hb : MemLp (fun x : ℝ => Real.exp (-(1 / 2) * -Real.log x)) 2 (E.measure ξ) := by
    refine hw.1.norm.ae_eq (hpos.mono fun x hx => ?_)
    rw [norm_real, Real.norm_of_nonneg (Real.sqrt_nonneg x), Real.sqrt_eq_rpow,
      Real.rpow_def_of_pos hx]
    ring_nf
  have hg : ∀ t : ℝ, Measurable fun s : ℝ => cexp (t * Real.log s * I) := fun t => by fun_prop
  have hgb : ∀ t : ℝ, ∃ C, ∀ s : ℝ, ‖cexp (t * Real.log s * I)‖ ≤ C :=
    fun t => ⟨1, fun s => by rw [← ofReal_mul, norm_exp_ofReal_mul_I]⟩
  refine ⟨_, E.diffContOnCl_integralApply_cexp hφ (by norm_num) ha hb,
    ⟨√(∫ x, Real.exp (-0 * -Real.log x) ^ 2 ∂(E.measure ξ) +
      ∫ x, Real.exp (-(1 / 2) * -Real.log x) ^ 2 ∂(E.measure ξ)), ?_⟩, fun t => ?_, fun t => ?_,
    fun z hz => ?_⟩
  · rintro _ ⟨z, hz, rfl⟩
    exact Real.le_sqrt_of_sq_le (E.norm_integralApply_cexp_sq_le hφ hz ha hb)
  · rw [coe_modularGroup_apply, E.integral_apply (hg _) (hgb _)]
    congr 1
    funext x
    push_cast
    ring_nf
  · -- `Δ_K^{-i(t + i/2)} ξ = Δ_K^{-it} Δ_K^{1/2} ξ = Δ_K^{-it} J_K ξ`
    have hw' : w = J[K] ξ := by rw [← hwξ, modularConj_modularConj]
    have hprod : MemLp ((fun s : ℝ => cexp (↑(-t) * Real.log s * I)) *
        fun x : ℝ => (Real.sqrt x : ℂ)) 2 (E.measure ξ) :=
      hw.1.of_le_mul (c := 1) ((hg _).mul hsqm).aestronglyMeasurable
        (Eventually.of_forall fun x => by
          rw [Pi.mul_apply, norm_mul, ← ofReal_mul, norm_exp_ofReal_mul_I, one_mul])
    rw [K.modularConj_comm_modularGroup, ← hw', ← hw.2, coe_modularGroup_apply,
      E.integral_integralApply hsqm (hg _) (hgb _) hw.1,
      E.integralApply_congr_ae (g := fun x : ℝ => cexp (I * (t + I / 2) * (-Real.log x : ℝ)))
        ((hg _).mul hsqm) (by fun_prop) hprod (hpos.mono fun x hx => ?_)]
    rw [Pi.mul_apply, Real.sqrt_eq_rpow, Real.rpow_def_of_pos hx, ofReal_exp, ← Complex.exp_add]
    congr 1
    push_cast
    ring_nf
    rw [I_sq]
    ring
  · -- `F z = Δ_K^{-iz} ξ`, with `ξ ∈ dom Δ_K^{-iz}` by the bound `|λ^{-iz}| ≤ 1 + λ^{1/2}`
    have hfun : (fun s : ℝ => cexp (-I * z * Real.log s)) =
        fun x => cexp (I * z * ((-Real.log x : ℝ) : ℂ)) := by
      funext x
      push_cast
      ring_nf
    have hbound : ∀ x : ℝ, ‖cexp (I * z * ((-Real.log x : ℝ) : ℂ))‖ ≤
        ‖Real.exp (-0 * -Real.log x) + Real.exp (-(1 / 2) * -Real.log x)‖ := fun x => by
      rw [norm_exp, Real.norm_of_nonneg (by positivity)]
      have hre : (I * z * ((-Real.log x : ℝ) : ℂ)).re = z.im * Real.log x := by
        simp only [mul_re, I_re, I_im, zero_mul, one_mul, zero_sub, ofReal_re, ofReal_im,
          mul_zero, sub_zero]
        ring
      rw [hre]
      rcases le_total 0 (Real.log x) with hL | hL
      · exact (Real.exp_le_exp.mpr (by nlinarith [hz.2])).trans
          (le_add_of_nonneg_left (Real.exp_pos _).le)
      · exact (Real.exp_le_exp.mpr (by nlinarith [hz.1])).trans
          (le_add_of_nonneg_right (Real.exp_pos _).le)
    rw [K.isSelfAdjoint_modular.cpow_eq_integralPMap_exp_log K.isPositive_modular
      K.ker_modular_eq_bot, ProjectionValuedMeasure.mem_graph_integralPMap, hfun]
    exact ⟨(ha.add hb).of_le (by fun_prop : Measurable fun x : ℝ =>
      cexp (I * z * ((-Real.log x : ℝ) : ℂ))).aestronglyMeasurable
      (Eventually.of_forall hbound), rfl⟩

/-! ### Covariance under semilinear isometric equivalences -/

section Covariance

variable {H₁ H₂ : Type*} [NormedAddCommGroup H₁] [InnerProductSpace ℂ H₁]
  [NormedAddCommGroup H₂] [InnerProductSpace ℂ H₂] {K₁ : StandardSubspace H₁}
  {K₂ : StandardSubspace H₂}

/-- `W S_{K₁} ⊆ S_{K₂} W`, pointwise, for a map that is semilinear for a ring endomorphism `σ₀` of
`ℂ` with `σ₀ i = ± i` and maps `K₁` into `K₂`. -/
private lemma mem_graph_tomita_map {F : Type*} [FunLike F H₁ H₂] {σ₀ : ℂ →+* ℂ}
    [SemilinearMapClass F σ₀ H₁ H₂] (hσ₀ : σ₀ I = I ∨ σ₀ I = -I) (W : F)
    (hW : ∀ ξ ∈ K₁, W ξ ∈ K₂) {u v : H₁}
    (h : (u, v) ∈ S[K₁].graphₛₗ) : (W u, W v) ∈ S[K₂].graphₛₗ := by
  obtain ⟨x, hx, y, hy, rfl, rfl⟩ := K₁.mem_graph_tomita.mp h
  rw [mem_graph_tomita]
  rcases hσ₀ with hI | hI
  · exact ⟨W x, hW x hx, W y, hW y hy, by rw [map_add, map_smulₛₗ, hI],
      by rw [map_sub, map_smulₛₗ, hI]⟩
  · refine ⟨W x, hW x hx, -W y, K₂.toClosedSubmodule.toSubmodule.neg_mem (hW y hy), ?_, ?_⟩
    · rw [map_add, map_smulₛₗ, hI, smul_neg, neg_smul]
    · rw [map_sub, map_smulₛₗ, hI, smul_neg, neg_smul]

/-- **`V S_{K₁} ⊆ S_{K₂} V`** for a bounded complex-linear `V` with `V K₁ ⊆ K₂`. -/
lemma compPMap_tomita_le_of_apply_mem (V : H₁ →L[ℂ] H₂) (hV : ∀ ξ ∈ K₁, V ξ ∈ K₂) :
    (V : H₁ →ₗ[ℂ] H₂).compPMap S[K₁] ≤ S[K₂].compNat ((V : H₁ →ₗ[ℂ] H₂).toPMap ⊤) :=
  -- the generating vectors `x + i y` of the domain are mapped one by one
  LinearPMap.compPMap_le_compNat_toPMap_iffₛₗ.mpr fun _ _ h =>
    mem_graph_tomita_map (Or.inl rfl) V hV h

variable {σ σ' : ℂ →+* ℂ} [RingHomInvPair σ σ'] [RingHomInvPair σ' σ] [RingHomIsometric σ]
  (V : H₁ ≃ₛₗᵢ[σ] H₂) (hV : ∀ ξ, V ξ ∈ K₂ ↔ ξ ∈ K₁)
include hV

/-- `S_{K₂} = V S_{K₁} V⁻¹`, pointwise, if a unitary or antiunitary `V` maps `K₁` onto `K₂`. -/
private lemma mem_graph_tomita_map_iff {u v : H₁} :
    (V u, V v) ∈ S[K₂].graphₛₗ ↔ (u, v) ∈ S[K₁].graphₛₗ := by
  obtain ⟨hσ, hσ'⟩ := RingHom.apply_I_of_ringHomIsometric (σ := σ) (σ' := σ')
  refine ⟨fun h => ?_, mem_graph_tomita_map hσ V fun ξ hξ => (hV ξ).mpr hξ⟩
  simpa using mem_graph_tomita_map hσ' V.symm (fun ξ hξ => by rwa [← hV, V.apply_symm_apply]) h

variable [CompleteSpace H₁] [CompleteSpace H₂]

/-- If `V` maps `K₁` onto `K₂`, it maps `K₁'` onto `K₂'`. -/
lemma map_mem_symplComp_iff {ξ : H₁} :
    V ξ ∈ K₂.symplComp ↔ ξ ∈ K₁.symplComp := by
  have him : ∀ z : ℂ, (σ z).im = 0 ↔ z.im = 0 := by
    rcases RingHom.eq_id_or_conj_of_ringHomIsometric (σ := σ) (σ' := σ') with
      ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;> simp
  constructor
  · intro h
    refine mem_symplComp_iff.mpr fun y hy => ?_
    rw [← him, ← V.inner_map_mapₛₗ]
    exact mem_symplComp_iff.mp h _ ((hV y).mpr hy)
  · intro h
    refine mem_symplComp_iff.mpr fun y hy => ?_
    rw [← V.apply_symm_apply y, V.inner_map_mapₛₗ, him]
    exact mem_symplComp_iff.mp h _ ((hV _).mp (by rwa [V.apply_symm_apply]))

/-- `Δ_{K₂} = V Δ_{K₁} V⁻¹`, pointwise, if `V K₁ = K₂`. -/
private lemma mem_graph_modular_map_iff {u v : H₁} :
    (V u, V v) ∈ Δ[K₂].graph ↔ (u, v) ∈ Δ[K₁].graph := by
  have hV' : ∀ ξ, V ξ ∈ K₂.symplComp ↔ ξ ∈ K₁.symplComp :=
    fun _ => map_mem_symplComp_iff V hV
  rw [← LinearPMap.mem_graphₛₗ_iff_mem_graph, ← LinearPMap.mem_graphₛₗ_iff_mem_graph, modular_def,
    modular_def, ← tomita_symplComp, ← tomita_symplComp, LinearPMap.mem_graphₛₗ_compNat,
    LinearPMap.mem_graphₛₗ_compNat]
  constructor
  · rintro ⟨w, h₁, h₂⟩
    refine ⟨V.symm w, ?_, ?_⟩
    · rwa [← mem_graph_tomita_map_iff V hV, V.apply_symm_apply]
    · rwa [← mem_graph_tomita_map_iff V hV', V.apply_symm_apply]
  · rintro ⟨w, h₁, h₂⟩
    exact ⟨V w, (mem_graph_tomita_map_iff V hV).mpr h₁, (mem_graph_tomita_map_iff V hV').mpr h₂⟩

/-- **Covariance of the modular operator**: if `V K₁ = K₂`, then `Δ_{K₂} V = V Δ_{K₁}`. -/
lemma modular_compNat_eq :
    Δ[K₂].compNat ((V : H₁ →ₛₗ[σ] H₂).toPMap ⊤) = (V : H₁ →ₛₗ[σ] H₂).compPMap Δ[K₁] :=
  -- `Δ = S_{K'} S_K` is transported through the graphs of the Tomita operators
  (LinearPMap.compNat_toPMap_eq_compPMap_iff V.toLinearEquiv).mpr fun _ _ =>
    (mem_graph_modular_map_iff V hV).symm

/-- **Covariance of the spectral measure of the modular operator**: if `V K₁ = K₂`, then
`E_{Δ_{K₂}} = V E_{Δ_{K₁}} V⁻¹`. -/
lemma pvm_modular_map :
    K₂.isSelfAdjoint_modular.pvm = K₁.isSelfAdjoint_modular.pvm.transport V :=
  K₁.isSelfAdjoint_modular.pvm_eq_transport K₂.isSelfAdjoint_modular V (modular_compNat_eq V hV)

/-- **Covariance of `Δ^{1/2}`**: if `V K₁ = K₂`, then `Δ_{K₂}^{1/2} V = V Δ_{K₁}^{1/2}`. -/
lemma sqrt_modular_compNat_eq :
    Δ[K₂]^{1/2}.compNat ((V : H₁ →ₛₗ[σ] H₂).toPMap ⊤) = (V : H₁ →ₛₗ[σ] H₂).compPMap Δ[K₁]^{1/2} := by
  have hfun : (fun t : ℝ => σ' (Real.sqrt t : ℂ)) = fun t => (Real.sqrt t : ℂ) := by
    rcases RingHom.eq_id_or_conj_of_ringHomIsometric (σ := σ) (σ' := σ') with
      ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;> simp
  rw [IsSelfAdjoint.sqrt, IsSelfAdjoint.sqrt, ProjectionValuedMeasure.sqrt,
    ProjectionValuedMeasure.sqrt, pvm_modular_map V hV,
    ProjectionValuedMeasure.integralPMap_transport_compNat _ _
      (f := fun t : ℝ => (Real.sqrt t : ℂ))
      (Complex.measurable_ofReal.comp Real.continuous_sqrt.measurable), hfun]

/-- `Δ_{K₂}^{1/2} = V Δ_{K₁}^{1/2} V⁻¹`, pointwise, if `V K₁ = K₂`. -/
private lemma mem_graph_sqrt_modular_map_iff {u v : H₁} :
    (V u, V v) ∈ Δ[K₂]^{1/2}.graph ↔ (u, v) ∈ Δ[K₁]^{1/2}.graph :=
  ((LinearPMap.compNat_toPMap_eq_compPMap_iff V.toLinearEquiv).mp
    (sqrt_modular_compNat_eq V hV) u v).symm

/-- **Covariance of the modular conjugation**: if `V K₁ = K₂`, then `J_{K₂} = V J_{K₁} V⁻¹`. -/
theorem modularConj_map (x : H₁) : J[K₂] (V x) = V (J[K₁] x) := by
  -- `J_{K₂} V J_{K₁} = V` on the dense domain of `Δ_{K₁}^{1/2}`, hence everywhere
  have key : ∀ x, J[K₂] (V (J[K₁] x)) = V x := by
    have hclosed : IsClosed {x : H₁ | J[K₂] (V (J[K₁] x)) = V x} :=
      isClosed_eq (J[K₂].continuous.comp (V.continuous.comp J[K₁].continuous))
        V.continuous
    refine fun x => hclosed.closure_subset_iff.mpr (fun x hx => ?_)
      (K₁.isSelfAdjoint_modular.isSelfAdjoint_sqrt.dense_domain.closure_eq ▸ mem_univ x)
    set u := Δ[K₁]^{1/2} ⟨x, hx⟩
    have hJ := K₁.mem_graph_sqrt_modularConj_iff.mp (Δ[K₁]^{1/2}.mem_graph ⟨x, hx⟩)
    have h₁ : (V (J[K₁] u), J[K₂] (V (J[K₁] x))) ∈ S[K₂].graphₛₗ :=
      K₂.mem_graph_tomita_iff.mpr ⟨_, (mem_graph_sqrt_modular_map_iff V hV).mpr hJ, rfl⟩
    have h₂ : (V (J[K₁] u), V x) ∈ S[K₂].graphₛₗ := by
      rw [mem_graph_tomita_map_iff V hV, K₁.mem_graph_tomita_iff]
      exact ⟨_, hJ, K₁.modularConj_modularConj x⟩
    exact LinearPMap.mem_graphₛₗ_snd_inj h₁ h₂
  simpa using key (J[K₁] x)

/-- Covariance of the modular group: if `V K₁ = K₂`, then `V Δ_{K₁}^{it} V⁻¹ = Δ_{K₂}^{±it}`, with
the sign `(σ i).im`: `+` for a unitary and `-` for an antiunitary `V`. -/
private lemma modularGroup_map_aux (t : ℝ) (x : H₁) :
    (K₂.modularGroup ((σ I).im * t) : H₂ →L[ℂ] H₂) (V x) =
      V (Δ[K₁]^{i t} x) := by
  rw [coe_modularGroup_apply, coe_modularGroup_apply, pvm_modular_map V hV,
    ProjectionValuedMeasure.integral_transport _ _ (by fun_prop)
      ⟨1, fun s => by rw [← ofReal_mul, norm_exp_ofReal_mul_I]⟩]
  simp only [ContinuousLinearMap.comp_apply, LinearIsometry.coe_toContinuousLinearMap,
    LinearIsometryEquiv.coe_toLinearIsometry, LinearIsometryEquiv.symm_apply_apply]
  refine congrArg (fun f => V (K₁.isSelfAdjoint_modular.pvm.integral f x)) (funext fun s => ?_)
  rcases RingHom.eq_id_or_conj_of_ringHomIsometric (σ := σ) (σ' := σ') with
    ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
  · simp
  · rw [← exp_conj]
    simp

end Covariance

section CovarianceGroup

variable {H₁ H₂ : Type*} [NormedAddCommGroup H₁] [InnerProductSpace ℂ H₁] [CompleteSpace H₁]
  [NormedAddCommGroup H₂] [InnerProductSpace ℂ H₂] [CompleteSpace H₂] {K₁ : StandardSubspace H₁}
  {K₂ : StandardSubspace H₂}

/-- **Covariance of the modular group under unitaries**: if a unitary `V` maps `K₁` onto `K₂`, then
`V Δ_{K₁}^{it} V* = Δ_{K₂}^{it}`. -/
theorem modularGroup_map (V : H₁ ≃ₗᵢ[ℂ] H₂)
    (hV : ∀ ξ, V ξ ∈ K₂ ↔ ξ ∈ K₁) (t : ℝ) (x : H₁) :
    Δ[K₂]^{i t} (V x) = V (Δ[K₁]^{i t} x) := by
  simpa using modularGroup_map_aux V hV t x

/-- **Covariance of the modular group under antiunitaries**: if an antiunitary `V` maps `K₁` onto
`K₂`, then `V Δ_{K₁}^{it} V* = Δ_{K₂}^{-it}`. -/
lemma modularGroup_map_of_antiunitary (V : H₁ ≃ₗᵢ⋆[ℂ] H₂)
    (hV : ∀ ξ, V ξ ∈ K₂ ↔ ξ ∈ K₁) (t : ℝ) (x : H₁) :
    Δ[K₂]^{-i t} (V x) = V (Δ[K₁]^{i t} x) := by
  simpa using modularGroup_map_aux V hV t x

end CovarianceGroup

end StandardSubspace
