module

public import QuantumSystem.Algebra.LocalNet.MatrixModel.Net

/-!
# Covariance of the local net generated by a lattice system

A **covariance** of a `SiteIndexSystem` is a permutation `σ` of the sites together with, for each
site, a dimension-matching equivalence `localIdx s ≃ localIdx (σ s)` of the local index types. Such
data reindexes the finite-region matrix algebras and so induces a `*`-isomorphism
`β_a : 𝔄(Λ) ≃⋆ₐ[ℂ] 𝔄(a Λ)` (`localCovariance`), natural with respect to the isotony embeddings
(`localCovariance_includeAlgebra`) — the AQFT covariance axiom `β_a(𝔄(Λ)) = 𝔄(a Λ)` for the
finite-dimensional matrix model.

These per-region `*`-isomorphisms assemble a covariance `toLocalNetCovariance` of the generated
abstract net `toLocalNet`, exhibiting the concrete covariance as an instance of the abstract
`LocalNet.Covariance`. Its covariance action `β_a ⟦⟨Λ, X⟩⟧ = ⟦⟨a Λ, β_a X⟩⟧` on the algebra of local
observables is therefore inherited from the net-level `LocalNet.Covariance.quasiLocalCovariance`,
together with the `*`-automorphism and C⋆-completion structure built there.
-/

@[expose] public section

namespace SiteIndexSystem

/-- Pointwise value of the complement projection of `combineIdx.symm` (holds by `rfl`). -/
@[simp] theorem combineIdx_symm_snd_apply {L : SiteIndexSystem} {Λ Λ_total : Finset L.sites}
    (h : Λ ⊆ Λ_total) (f : L.regionIdx Λ_total) (w : ↥(Λ_total \ Λ)) :
    ((L.combineIdx h).symm f).2 w = f ⟨w.val, (Finset.mem_sdiff.mp w.property).1⟩ := rfl

/-- A covariance datum for a site-index system: a site permutation together with
  dimension-matching equivalences on the local index types. -/
structure Covariance (L : SiteIndexSystem) where
  /-- The underlying permutation of the sites. -/
  σ : L.sites ≃ L.sites
  /-- Dimension-matching equivalence of the local index type at each site. -/
  idx : ∀ s, L.localIdx s ≃ L.localIdx (σ s)

namespace Covariance

variable {L : SiteIndexSystem} (a : L.Covariance)

/-- The image of a region under a covariance. -/
def region (Λ : Finset L.sites) : Finset L.sites := Λ.map a.σ.toEmbedding

variable (L) in
/-- The identity covariance. -/
def id : L.Covariance where
  σ := Equiv.refl _
  idx _ := Equiv.refl _

/-- Composition of covariances: apply `b`, then `a`. The per-site equivalences compose, with the
    intermediate site type aligning definitionally. -/
def comp (a b : L.Covariance) : L.Covariance where
  σ := b.σ.trans a.σ
  idx s := (b.idx s).trans (a.idx (b.σ s))

@[simp] theorem region_id (Λ : Finset L.sites) : (Covariance.id L).region Λ = Λ := by
  simp [region, Covariance.id]

@[simp] theorem region_comp (a b : L.Covariance) (Λ : Finset L.sites) :
    (a.comp b).region Λ = a.region (b.region Λ) := by
  simp [region, comp, Finset.map_map, Equiv.trans_toEmbedding]

/-- Equivalence of region index types induced by the site permutation and the per-site dimension
  equivalences. -/
def regionIdxEquiv (Λ : Finset L.sites) :
    L.regionIdx Λ ≃ L.regionIdx (a.region Λ) :=
  Equiv.piCongr
    (Equiv.subtypeEquiv a.σ (fun _ => (Finset.mem_map' a.σ.toEmbedding).symm))
    (fun s => a.idx s.val)

/-- The **covariance `*`-isomorphism** `β_a : 𝔄(Λ) ≃⋆ₐ[ℂ] 𝔄(a Λ)`, obtained by reindexing the
    matrix algebra along `regionIdxEquiv`. Realises `β_a(𝔄(Λ)) = 𝔄(a Λ)`. -/
noncomputable def localCovariance (Λ : Finset L.sites) :
    L.localAlgebra Λ ≃⋆ₐ[ℂ] L.localAlgebra (a.region Λ) :=
  StarAlgEquiv.ofAlgEquiv (Matrix.reindexAlgEquiv ℂ ℂ (a.regionIdxEquiv Λ))
    (fun X => by
      simp only [Matrix.reindexAlgEquiv_apply, Matrix.star_eq_conjTranspose,
        Matrix.conjTranspose_reindex])

@[simp] theorem localCovariance_apply (Λ : Finset L.sites) (X : L.localAlgebra Λ) :
  a.localCovariance Λ X = Matrix.reindex (a.regionIdxEquiv Λ) (a.regionIdxEquiv Λ) X :=
  rfl

/-- The `Λ`-coordinate of decomposing a transported index equals the corresponding transported
  `aΛ`-coordinate: `regionIdxEquiv` commutes with the isotony split `combineIdx`. Holds
  definitionally. -/
private theorem regionIdxEquiv_symm_combineIdx_fst {Λ Λ' : Finset L.sites} (h : Λ ⊆ Λ')
    (t : L.regionIdx (a.region Λ')) :
  ((L.combineIdx h).symm ((a.regionIdxEquiv Λ').symm t)).1 =
    (a.regionIdxEquiv Λ).symm ((L.combineIdx (Finset.map_subset_map.mpr h)).symm t).1 := by
  funext u
  rfl

/-- **Covariance / naturality**: the covariance `*`-isomorphism intertwines the isotony
    embeddings, so `β_a` is an automorphism of the *net* — `β_a(𝔄(Λ)) = 𝔄(a Λ)` compatibly with
    inclusions (Naaijkens 2012 §3.2 covariance axiom). -/
theorem localCovariance_includeAlgebra {Λ Λ' : Finset L.sites} (h : Λ ⊆ Λ')
    (X : L.localAlgebra Λ) :
    a.localCovariance Λ' (L.includeAlgebra h X) =
      L.includeAlgebra (Finset.map_subset_map.mpr h) (a.localCovariance Λ X) := by
  ext s s'
  simp only [localCovariance_apply, Matrix.reindex_apply, Matrix.submatrix_apply,
    includeAlgebra_apply]
  rw [a.regionIdxEquiv_symm_combineIdx_fst h s, a.regionIdxEquiv_symm_combineIdx_fst h s']
  have key2 : (((L.combineIdx h).symm ((a.regionIdxEquiv Λ').symm s)).2 =
        ((L.combineIdx h).symm ((a.regionIdxEquiv Λ').symm s')).2)
      ↔ (((L.combineIdx (Finset.map_subset_map.mpr h)).symm s).2 =
        ((L.combineIdx (Finset.map_subset_map.mpr h)).symm s').2) := by
    constructor
    · intro H
      funext v
      obtain ⟨vv, hvv⟩ := v
      have hv := Finset.mem_sdiff.mp hvv
      have hΛ' : a.σ.symm vv ∈ Λ' := Finset.mem_map_equiv.mp hv.1
      have hΛ : a.σ.symm vv ∉ Λ := fun hc => hv.2 (Finset.mem_map_equiv.mpr hc)
      have hcong := congrFun H ⟨a.σ.symm vv, Finset.mem_sdiff.mpr ⟨hΛ', hΛ⟩⟩
      simp only [combineIdx_symm_snd_apply, regionIdxEquiv, Equiv.piCongr_symm_apply,
        Equiv.subtypeEquiv_apply, EmbeddingLike.apply_eq_iff_eq] at hcong
      change s ⟨vv, (Finset.mem_sdiff.mp hvv).1⟩ = s' ⟨vv, (Finset.mem_sdiff.mp hvv).1⟩
      convert hcong using 2 <;>
        first
          | exact (a.σ.apply_symm_apply vv).symm
          | exact Subtype.ext (a.σ.apply_symm_apply vv).symm
    · intro H
      funext w
      have hw := Finset.mem_sdiff.mp w.property
      have hv : a.σ w.val ∈ a.region Λ' \ a.region Λ := Finset.mem_sdiff.mpr
        ⟨Finset.mem_map' _ |>.mpr hw.1, fun hc => hw.2 (Finset.mem_map' _ |>.mp hc)⟩
      have hcong := congrFun H ⟨a.σ w.val, hv⟩
      simpa [combineIdx_symm_snd_apply, regionIdxEquiv, Equiv.piCongr_symm_apply,
        Equiv.subtypeEquiv_apply, Equiv.symm_apply_apply,
        EmbeddingLike.apply_eq_iff_eq] using hcong
  by_cases hc : ((L.combineIdx (Finset.map_subset_map.mpr h)).symm s).2 =
      ((L.combineIdx (Finset.map_subset_map.mpr h)).symm s').2
  · rw [if_pos (key2.mpr hc), if_pos hc]
  · rw [if_neg (fun hcc => hc (key2.mp hcc)), if_neg hc]

/-! ### Covariance action on the quasi-local algebra

The per-region covariance `*`-isomorphisms, being natural with respect to isotony
(`localCovariance_includeAlgebra`), assemble a covariance `toLocalNetCovariance` of the abstract net
`toLocalNet`. Its covariance action `β_a ⟦⟨Λ, X⟩⟧ = ⟦⟨a Λ, β_a X⟩⟧` on the algebra of local
observables is therefore inherited from the net-level `LocalNet.Covariance.quasiLocalCovariance`. -/

/-- The covariance of the generated local net `toLocalNet` induced by a lattice covariance: the same
    site permutation, with the local `*`-isomorphisms `localCovariance` as its covariance maps and
    `localCovariance_includeAlgebra` as the isotony naturality. This exhibits the concrete
    covariance as an instance of the abstract `LocalNet.Covariance`. -/
noncomputable def toLocalNetCovariance : L.toLocalNet.Covariance where
  σ := a.σ
  β := a.localCovariance
  β_incl h x := a.localCovariance_includeAlgebra h x

/-- The action of a covariance on the algebra of local observables, as a ring homomorphism:
    `β_a ⟦⟨Λ, X⟩⟧ = ⟦⟨a Λ, β_a X⟩⟧`. Inherited from the abstract net-level covariance action
    `LocalNet.Covariance.quasiLocalCovariance` on `toLocalNet`. -/
noncomputable def quasiLocalCovariance : L.quasiLocalAlgebra →+* L.quasiLocalAlgebra :=
  a.toLocalNetCovariance.quasiLocalCovariance

@[simp] theorem quasiLocalCovariance_mk {Λ : Finset L.sites} (X : L.localAlgebra Λ) :
    a.quasiLocalCovariance (⟦⟨Λ, X⟩⟧ : L.quasiLocalAlgebra) =
      ⟦⟨a.region Λ, a.localCovariance Λ X⟩⟧ :=
  rfl

end Covariance

end SiteIndexSystem
