module

public import Mathlib.Analysis.CStarAlgebra.Matrix
public import QuantumSystem.Algebra.LocalNet.MatrixModel.Locality
public import QuantumSystem.Algebra.LocalNet.QuasiLocal

/-!
# The local net generated by a site-index system

A `SiteIndexSystem` on a (possibly infinite) lattice of sites — the data of a finite local
index type at each site — generates a genuine **local net of C⋆-algebras** (`LocalNet`): the
assignment `Λ ↦ 𝔄(Λ) = ⊗_{x ∈ Λ} M_{n_x}(ℂ)` to each finite region, with the isotony embeddings
`includeAlgebra (h : Λ ⊆ Λ')` (the inclusion `A ↦ A ⊗ I` of `LocalNet.MatrixModel.Isotony`),
functorial (`includeAlgebra_trans_apply`, `includeAlgebra_refl_apply`) and local
(`includeAlgebra_commute_of_disjoint`).

* `instCStarAlgebraLocal` makes each finite-region matrix algebra a C⋆-algebra under the
  `L2Operator` norm; this discharges the C⋆-structure required by `LocalNet`.
* `SiteIndexSystem.toLocalNet` packages the matrix algebras and isotony embeddings into a
  `LocalNet`. The **algebra of local observables** and the **quasi-local C⋆-algebra** are then
  inherited from the abstract net (`LocalNet.quasiLocalAlgebra`, `LocalNet.quasiLocalCStarAlgebra`).
* When each site has a non-empty local index type the embeddings are injective, so the generated
  net is `LocalNet.Faithful` and its quasi-local C⋆-algebra is the AQFT quasi-local algebra
  `𝔄 = ‾⋃_Λ 𝔄(Λ)` (Naaijkens 2012 §1.3, Bratteli–Robinson Vol.2 §6.2).

The site-index-system-level abbreviations `quasiLocalAlgebra` / `ιLocal` / `quasiLocalCStarAlgebra`
below are thin wrappers around the corresponding `LocalNet` constructions on `toLocalNet`. The
concrete covariance of this net and its inherited action live in `LocalNet.MatrixModel.Covariance`.
-/

@[expose] public section

namespace SiteIndexSystem

open scoped Matrix.Norms.L2Operator

variable (S : SiteIndexSystem)

/-- Each finite-region matrix algebra `𝔄(Λ) = Matrix (regionIdx Λ) (regionIdx Λ) ℂ` is a
    (complex) C⋆-algebra under the `L2Operator` norm. Stated for `localAlgebra` so the choice of
    the `L2Operator` norm does not leak to arbitrary matrices. -/
noncomputable instance instCStarAlgebraLocal (Λ : Finset S.sites) :
    CStarAlgebra (S.localAlgebra Λ) where

/-- The **local net generated by the lattice system**: the assignment of matrix algebras to
    finite regions, with the isotony embeddings as connecting maps. This realises the abstract
    Haag–Kastler net `LocalNet` for the finite-dimensional matrix model. -/
noncomputable def toLocalNet : LocalNet S.sites where
  algebra := S.localAlgebra
  incl h := S.includeAlgebra h
  incl_refl x := S.includeAlgebra_refl_apply x
  incl_trans h₁₂ h₂₃ x := S.includeAlgebra_trans_apply h₁₂ h₂₃ x
  locality h₁ h₂ hd x y := S.includeAlgebra_commute_of_disjoint h₁ h₂ hd x y

@[simp] theorem toLocalNet_algebra (Λ : Finset S.sites) :
    S.toLocalNet.algebra Λ = S.localAlgebra Λ := rfl

@[simp] theorem toLocalNet_incl {Λ Λ' : Finset S.sites} (h : Λ ⊆ Λ') :
    S.toLocalNet.incl h = S.includeAlgebra h := rfl

/-- The generated net is **faithful**: if each site has a non-empty local index type, the complementary
    region indices are non-empty, so the isotony embeddings are injective. -/
instance toLocalNet_faithful [∀ s, Nonempty (S.localIdx s)] : S.toLocalNet.Faithful where
  incl_injective h := S.includeAlgebra_injective h

/-! ### Lattice-system-level quasi-local algebra

Thin wrappers exposing the `LocalNet` constructions on `toLocalNet` directly on the lattice system. -/

/-- The **algebra of local observables** of the lattice system: the algebraic inductive limit of the
    finite-region matrix algebras (inherited from `LocalNet.quasiLocalAlgebra` on `toLocalNet`). -/
noncomputable abbrev quasiLocalAlgebra : Type _ := S.toLocalNet.quasiLocalAlgebra

/-- The canonical embedding `𝔄(Λ) ↪ 𝔄_loc` of a local algebra into the algebra of local
    observables (the cocone of the inductive limit). -/
noncomputable def ιLocal (Λ : Finset S.sites) :
    S.localAlgebra Λ →+* S.quasiLocalAlgebra :=
  S.toLocalNet.ιLocal Λ

/-- Compatibility of the cocone with the isotony embeddings. -/
@[simp] theorem ιLocal_includeAlgebra {Λ Λ' : Finset S.sites} (h : Λ ⊆ Λ')
    (X : S.localAlgebra Λ) :
    S.ιLocal Λ' (S.includeAlgebra h X) = S.ιLocal Λ X :=
  S.toLocalNet.ιLocal_incl h X

/-- **Exhaustion**: every element of the algebra of local observables comes from some finite
    region. -/
theorem exists_ιLocal (z : S.quasiLocalAlgebra) :
    ∃ (Λ : Finset S.sites) (X : S.localAlgebra Λ), z = S.ιLocal Λ X :=
  S.toLocalNet.exists_ιLocal z

/-- **Locality**: observables localised in disjoint regions commute inside the algebra of local
    observables. -/
theorem ιLocal_commute_of_disjoint {Λ₁ Λ₂ : Finset S.sites} (hd : Disjoint Λ₁ Λ₂)
    (X : S.localAlgebra Λ₁) (Y : S.localAlgebra Λ₂) :
    Commute (S.ιLocal Λ₁ X) (S.ιLocal Λ₂ Y) :=
  S.toLocalNet.ιLocal_commute_of_disjoint hd X Y

/-- The **quasi-local C⋆-algebra** of the lattice system (assuming non-empty local dimensions): the
    completion of the algebra of local observables, i.e. the AQFT quasi-local algebra
    `𝔄 = ‾⋃_Λ 𝔄(Λ)`. -/
noncomputable abbrev quasiLocalCStarAlgebra [∀ s, Nonempty (S.localIdx s)] : Type _ :=
  S.toLocalNet.quasiLocalCStarAlgebra

end SiteIndexSystem
