/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import QuantumSystem.Analysis.VonNeumannAlgebra.Modular.TomitaAdjoint

/-!
# The relative modular conjugation

Let `M` be a von Neumann algebra on `H` and `η, ξ ∈ H` arbitrary vectors, with relative Tomita
operator `S_{η,ξ}` (`VonNeumannAlgebra.relativeTomita`) and relative modular operator
`Δ_{η,ξ} = S̄_{η,ξ}† S̄_{η,ξ}` (`VonNeumannAlgebra.relativeModular`). This file studies the polar
decomposition `S̄_{η,ξ} = J_{η,ξ} Δ_{η,ξ}^{1/2}` for arbitrary vectors
(`VonNeumannAlgebra.relativeModularConj`). The kernel of `S̄_{η,ξ}` is that of
`s(η) s′(ξ)`, and its range is dense in `s(ξ) s′(η) H`, so `J_{η,ξ}` is a partial isometry from
`s(η) s′(ξ) H` onto `s(ξ) s′(η) H`; `S̄_{ξ,η}` inverts `S̄_{η,ξ}` between these supports, which
by uniqueness of the polar decomposition gives `J_{η,ξ}† = J_{ξ,η}`. With `S† = F̄`, `ξ` cyclic and
`η` separating make `S̄_{η,ξ}` injective, hence `Δ_{η,ξ}` injective and `J_{η,ξ}` isometric, and
for `ξ`, `η` cyclic and separating `J_{η,ξ}` is antiunitary.

## Main definitions

* `VonNeumannAlgebra.relativeModularConj M η ξ` — the **relative modular conjugation** `J_{η,ξ}`,
  the partial isometry of `S̄_{η,ξ} = J_{η,ξ} Δ_{η,ξ}^{1/2}`, a conjugate-linear contraction.
* `VonNeumannAlgebra.relativeModularConjEquiv` — `J_{η,ξ}` as an antiunitary, for `ξ`, `η` cyclic
  and separating.

## Notation

* `J[M]⟦η, ξ⟧` (`open scoped VonNeumannAlgebra`) — `J_{η,ξ}`, with the index order of
  `S_{η,ξ}` and `Δ_{η,ξ}`: Araki's `J_{Φ,Ψ}` with `Φ = η` and `Ψ = ξ`, where
  `S_{Φ,Ψ} x Ψ = x⋆ Φ`.
* `U†` (`open scoped InnerProduct`) — the adjoint of a bounded real-linear `U` for the real inner
  products `re ⟪·, ·⟫`; for the conjugate-linear `J_{η,ξ}` it is the antilinear adjoint
  `⟪J† y, x⟫ = ⟪J x, y⟫` of the literature (`VonNeumannAlgebra.inner_relativeModularConj_left`).

## Main results

* `VonNeumannAlgebra.closure_relativeTomita_compNat_le`, `VonNeumannAlgebra.ker_closure_relativeTomita`,
  `VonNeumannAlgebra.supportProj_compPMap_closure_relativeTomita` — `S̄_{ξ,η} S̄_{η,ξ} ⊆ s(η) s′(ξ)`,
  `ker S̄_{η,ξ} = ker s(η) s′(ξ)` and `ran S̄_{η,ξ} ⊆ s(ξ) s′(η) H` for arbitrary `η, ξ`.
* `VonNeumannAlgebra.ker_closure_relativeTomita_eq_orthogonal`,
  `VonNeumannAlgebra.ker_relativeModular_eq_orthogonal` — for `ξ` cyclic,
  `ker S̄_{η,ξ} = ker Δ_{η,ξ} = [M′ η]ᗮ`.
* `VonNeumannAlgebra.ker_closure_relativeTomita_eq_bot` — for `ξ` cyclic and `η` separating,
  `S̄_{η,ξ}` is injective;
  `VonNeumannAlgebra.dense_range_closure_relativeTomita` — for `ξ` separating and `η` cyclic,
  `S̄_{η,ξ}` has dense range `⊇ M η`.
* `VonNeumannAlgebra.ker_relativeModular_eq_bot`, `VonNeumannAlgebra.relativeModularGroup_eq_unitaryGroup`
  — for `ξ` cyclic and `η` separating, `Δ_{η,ξ}` is injective and `Δ_{η,ξ}^{it}` is the unitary
  group generated by `log Δ_{η,ξ}`.
* `VonNeumannAlgebra.relativeModularConj`, `VonNeumannAlgebra.closure_relativeTomita_eq_compPMap`
  — the relative
  modular conjugation `J_{η,ξ}` (`J[M]⟦η, ξ⟧`) of arbitrary vectors `η, ξ`, the partial isometry of
  the polar decomposition `S̄_{η,ξ} = J_{η,ξ} Δ_{η,ξ}^{1/2}`.
* `VonNeumannAlgebra.adjoint_relativeModularConj`,
  `VonNeumannAlgebra.inner_relativeModularConj_left`,
  `VonNeumannAlgebra.relativeModularConj_comp_relativeModularConj` —
  `J_{ξ,η} = J_{η,ξ}†` for arbitrary `η, ξ`, so `J_{ξ,η} J_{η,ξ} = E_Δ((0, ∞))`, the support
  projection of `Δ_{η,ξ}`.
* `VonNeumannAlgebra.pvm_Ioi_relativeModular`, `VonNeumannAlgebra.range_relativeModularConj` —
  `J_{η,ξ}` is a partial isometry with initial projection `E_Δ((0, ∞)) = s(η) s′(ξ)` and final
  space `s(ξ) s′(η) H`.
* `VonNeumannAlgebra.relativeModularConj_relativeModularConj` — `J_{ξ,η} J_{η,ξ} = 1` for `ξ`
  cyclic and `η` separating.
* `VonNeumannAlgebra.norm_relativeModularConj_apply`, `VonNeumannAlgebra.surjective_relativeModularConj`
  — for `ξ` cyclic and `η` separating `J_{η,ξ}` is isometric, and for `η` cyclic and `ξ`
  separating it is onto.
* `VonNeumannAlgebra.relativeModularConjEquiv`, `VonNeumannAlgebra.relativeModularConjEquiv_symm_apply`
  — `J_{η,ξ}` is antiunitary for `ξ`, `η` cyclic and separating, with inverse `J_{ξ,η}`.
* `VonNeumannAlgebra.relativeModularConj_self` — `J_{Ω,Ω} = J_{H_M}`.

## References

* O. Bratteli, D. W. Robinson, *Operator Algebras and Quantum Statistical Mechanics 1*, Springer
  (1987), Proposition 2.5.11
* H. Araki, *Relative entropy of states of von Neumann algebras*, Publ. RIMS 11 (1976), 809–833
* H. Araki, T. Masuda, *Positive cones and Lp-spaces for von Neumann algebras*, Publ. RIMS 18
  (1982), 339–411, §2
-/
@[expose] public section

open Set Filter Topology Complex ClosedSubmodule MeasureTheory
open scoped InnerProductSpace ComplexConjugate VonNeumannAlgebra LinearPMap StandardSubspace
open scoped InnerProduct
open InnerProductSpace (cyclicSubspace IsCyclicVector IsSeparatingVector)

namespace VonNeumannAlgebra

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  {M : VonNeumannAlgebra H}

/-! ### The relative modular conjugation -/

section RelativeModularConj

variable {η ξ : H}

/-- A set containing the orbit `M η` of a cyclic vector `η` is dense. -/
private lemma dense_of_forall_apply_mem (hc : IsCyclicVector M η) {s : Set H}
    (h : ∀ y ∈ M, y η ∈ s) : Dense s := by
  have hsub := cyclicSubspace_subset (M := M) (ξ := η) isClosed_closure fun y hy =>
    subset_closure (h y hy)
  exact dense_iff_closure_eq.mpr (eq_univ_of_univ_subset fun v _ => hsub (hc.mem v))

/-- For `ξ` separating and `η` cyclic, `S̄_{η,ξ}` has dense range: it contains `M η`. -/
lemma dense_range_closure_relativeTomita (hs : IsSeparatingVector M ξ)
    (hcη : IsCyclicVector M η) : Dense (range (S[M]⟦η, ξ⟧).closure) := by
  have hsupp : M.supportProj ξ = 1 := supportProj_eq_one_iff.mpr hs.isCyclicVector_commutant
  refine dense_of_forall_apply_mem hcη fun y hy => ?_
  have h := mem_graph_closure_relativeTomita (apply_mem_graph_relativeTomita (η := η) (ξ := ξ)
    (star_mem hy))
  rw [hsupp, star_star, one_apply_eq_self] at h
  obtain ⟨p, -, hp⟩ := ((S[M]⟦η, ξ⟧).closure.mem_graph_iff).mp h
  exact ⟨p, hp⟩

variable (M η ξ) in
/-- The **relative modular conjugation** `J_{η,ξ}` of a pair of vectors: the partial isometry of the
polar decomposition `S̄_{η,ξ} = J_{η,ξ} Δ_{η,ξ}^{1/2}`
(`VonNeumannAlgebra.closure_relativeTomita_eq_compPMap`; Araki–Masuda 1982, §2), a conjugate-linear
bounded operator written `J[M]⟦η, ξ⟧`, isometric on `(ker S̄_{η,ξ})ᗮ`
(`IsSelfAdjoint.norm_polarIsometry_apply`). Its adjoint is `J_{ξ,η}`
(`VonNeumannAlgebra.inner_relativeModularConj_left`), so `J_{ξ,η} J_{η,ξ} = E_Δ((0, ∞))`
(`VonNeumannAlgebra.relativeModularConj_comp_relativeModularConj`),
and everywhere for `ξ` cyclic and `η` separating
(`VonNeumannAlgebra.relativeModularConj_relativeModularConj`). For `η = ξ` cyclic and separating
it is the modular conjugation of the standard subspace `H_M`
(`VonNeumannAlgebra.relativeModularConj_self`). -/
noncomputable def relativeModularConj : H →L⋆[ℂ] H :=
  (isSelfAdjoint_relativeModular M η ξ).polarIsometrySL (restrictScalars_relativeModular M η ξ)
    (isClosed_closure_relativeTomita M η ξ) (isSemilinear_closure_relativeTomita M η ξ)

/-- `J[M]⟦η, ξ⟧` is the relative modular conjugation `J_{η,ξ}` of `M`
(`VonNeumannAlgebra.relativeModularConj`). -/
scoped notation "J[" M "]⟦" η ", " ξ "⟧" => VonNeumannAlgebra.relativeModularConj M η ξ

/-- Displays `VonNeumannAlgebra.relativeModularConj M η ξ` as `J[M]⟦η, ξ⟧`. -/
@[scoped app_unexpander VonNeumannAlgebra.relativeModularConj]
meta def relativeModularConjUnexpander : Lean.PrettyPrinter.Unexpander
  | `($_ $M $η $ξ) => `(J[$M]⟦$η, $ξ⟧)
  | _ => throw ()

variable (M η ξ) in
/-- `J_{η,ξ}` is the partial isometry of the polar decomposition of `S̄_{η,ξ}`
(`IsSelfAdjoint.polarIsometry`). -/
lemma relativeModularConj_apply (x : H) :
    J[M]⟦η, ξ⟧ x = (isSelfAdjoint_relativeModular M η ξ).polarIsometry
      (restrictScalars_relativeModular M η ξ) (isClosed_closure_relativeTomita M η ξ) x := rfl

/-- `J_{η,ξ}` is a contraction. -/
lemma norm_relativeModularConj_le : ‖J[M]⟦η, ξ⟧‖ ≤ 1 :=
  (isSelfAdjoint_relativeModular M η ξ).norm_polarIsometrySL_le _ _ _

/-- **Polar decomposition** `S̄_{η,ξ} = J_{η,ξ} Δ_{η,ξ}^{1/2}` for arbitrary `η, ξ`, as real-linear
operators. -/
lemma closure_relativeTomita_eq_compPMap :
    (S[M]⟦η, ξ⟧).closure =
      ((J[M]⟦η, ξ⟧ : H →L[ℝ] H) : H →ₗ[ℝ] H).compPMap (Δ[M]⟦η, ξ⟧^{1/2}.restrictScalars ℝ) :=
  (isSelfAdjoint_relativeModular M η ξ).eq_polarIsometry_compPMap
    (restrictScalars_relativeModular M η ξ) (isClosed_closure_relativeTomita M η ξ)

/-- `S̄_{η,ξ} = J_{η,ξ} Δ_{η,ξ}^{1/2}`, pointwise. -/
private lemma mem_graph_closure_relativeTomita_iff {u v : H} :
    (u, v) ∈ (S[M]⟦η, ξ⟧).closure.graph ↔
      ∃ w, (u, w) ∈ Δ[M]⟦η, ξ⟧^{1/2}.graph ∧ J[M]⟦η, ξ⟧ w = v := by
  have h := closure_relativeTomita_eq_compPMap (M := M) (η := η) (ξ := ξ)
  constructor
  · intro huv
    obtain ⟨w, hw, rfl⟩ := LinearPMap.mem_graph_compPMap.mp (LinearPMap.le_graph_of_le h.le huv)
    exact ⟨w, LinearPMap.mem_graph_restrictScalars.mp hw, rfl⟩
  · rintro ⟨w, hw, rfl⟩
    exact LinearPMap.le_graph_of_le h.ge
      (LinearPMap.mem_graph_compPMap.mpr ⟨w, LinearPMap.mem_graph_restrictScalars.mpr hw, rfl⟩)

/-! #### Supports, and `S̄_{ξ,η}` as the inverse of `S̄_{η,ξ}` -/

/-- `S̄_{ξ,η} S̄_{η,ξ} ⊆ s(η) s′(ξ)`, pointwise: for `(a, b)` in the graph of `S̄_{η,ξ}`,
`(b, s(η) s′(ξ) a)` lies in the graph of `S̄_{ξ,η}`. On `x ξ + ζ` (`x ∈ M`, `ζ ⊥ [M ξ]`) this is
`S_{ξ,η} (s(ξ) x⋆ η) = s(η) x s(ξ) ξ = s(η) x ξ`; the closure is a limit argument. -/
private lemma mem_graph_closure_relativeTomita_swap {a b : H}
    (h : (a, b) ∈ (S[M]⟦η, ξ⟧).closure.graph) :
    (b, M.supportProj η (M′.supportProj ξ a)) ∈ (S[M]⟦ξ, η⟧).closure.graph := by
  have hS : ∀ p ∈ ((S[M]⟦η, ξ⟧).graph : Set (H × H)),
      (p.2, M.supportProj η (M′.supportProj ξ p.1)) ∈ (S[M]⟦ξ, η⟧).graph := by
    intro p hp
    obtain ⟨x, hx, ζ, hζ, rfl⟩ := mem_graph_relativeTomita.mp hp
    have hy : M.supportProj ξ * star x ∈ M := mul_mem (M.supportProj_mem ξ) (star_mem hx)
    have h₁ := apply_mem_graph_relativeTomita (η := ξ) (ξ := η) hy
    have hxξ : M′.supportProj ξ (x ξ) = x ξ := by
      rw [supportProj_commutant, Submodule.starProjection_eq_self_iff]
      exact apply_mem_cyclicSubspace hx (self_mem_cyclicSubspace M ξ)
    have hζ0 : M′.supportProj ξ ζ = 0 := by
      rw [supportProj_commutant]
      exact (Submodule.starProjection_apply_eq_zero_iff _).mpr hζ
    convert h₁ using 2
    · rw [mul_apply_eq_comp]
    · rw [star_mul, star_star, (M.isStarProjection_supportProj ξ).isSelfAdjoint.star_eq,
        mul_apply_eq_comp, supportProj_apply_self, map_add, hxξ, hζ0, add_zero]
  rw [← (isClosable_relativeTomita M η ξ).graph_closure_eq_closure_graph] at h
  rw [← (isClosable_relativeTomita M ξ η).graph_closure_eq_closure_graph]
  rw [← SetLike.mem_coe, Submodule.topologicalClosure_coe] at h ⊢
  have hc : Continuous fun p : H × H => (p.2, M.supportProj η (M′.supportProj ξ p.1)) :=
    continuous_snd.prodMk ((M.supportProj η).continuous.comp
      ((M′.supportProj ξ).continuous.comp continuous_fst))
  exact map_mem_closure (f := fun p : H × H => (p.2, M.supportProj η (M′.supportProj ξ p.1))) hc h hS

/-- `ker S̄_{η,ξ} ⊇ (1 - s(η) s′(ξ)) H`: it contains `[M ξ]ᗮ` and `(1 - s(η)) [M ξ]`, as
`S_{η,ξ} ((1 - s(η)) x ξ) = s(ξ) x⋆ (1 - s(η)) η = 0`; the closure is a limit argument. -/
private lemma mem_graph_closure_relativeTomita_of_supportProj_apply_eq_zero {z : H}
    (hz : M.supportProj η (M′.supportProj ξ z) = 0) :
    (z, 0) ∈ (S[M]⟦η, ξ⟧).closure.graph := by
  set w := M′.supportProj ξ z
  -- `z - w ⊥ [M ξ]`
  have hζ : (z - w, 0) ∈ (S[M]⟦η, ξ⟧).closure.graph := by
    have hmem : z - w ∈ (cyclicSubspace M ξ).toSubmoduleᗮ := by
      simp only [w, supportProj_commutant]
      exact Submodule.sub_starProjection_mem_orthogonal z
    have h := mk_mem_graph_relativeTomita (η := η) (zero_mem M) hmem
    simp only [zero_apply, zero_add, star_zero, map_zero] at h
    exact mem_graph_closure_relativeTomita h
  -- `w ∈ [M ξ]` with `s(η) w = 0` is a limit of the kernel vectors `(1 - s(η)) x ξ`
  have hw : (w, 0) ∈ (S[M]⟦η, ξ⟧).closure.graph := by
    have hφ : Continuous fun v : H => (v - M.supportProj η v, (0 : H)) :=
      (continuous_id.sub (M.supportProj η).continuous).prodMk continuous_const
    have hS : ∀ v ∈ Set.range fun x : M => (x : H →L[ℂ] H) ξ,
        (v - M.supportProj η v, (0 : H)) ∈ (((S[M]⟦η, ξ⟧).closure.graph : Submodule ℝ (H × H)) :
          Set (H × H)) := by
      rintro _ ⟨⟨x, hx⟩, rfl⟩
      have hy : (1 - M.supportProj η) * x ∈ M := mul_mem (sub_mem (one_mem M) (M.supportProj_mem η)) hx
      have h := apply_mem_graph_relativeTomita (η := η) (ξ := ξ) hy
      have h0 : star ((1 - M.supportProj η) * x) η = 0 := by
        rw [star_mul, star_sub, star_one, (M.isStarProjection_supportProj η).isSelfAdjoint.star_eq,
          mul_apply_eq_comp, sub_apply, one_apply_eq_self, supportProj_apply_self, sub_self, map_zero]
      rw [h0, map_zero, mul_apply_eq_comp, sub_apply, one_apply_eq_self] at h
      exact mem_graph_closure_relativeTomita h
    have hwmem : w ∈ closure (Set.range fun x : M => (x : H →L[ℂ] H) ξ) := by
      rw [← coe_cyclicSubspace]
      simp only [w, supportProj_commutant]
      exact Submodule.starProjection_apply_mem _ z
    have h := map_mem_closure hφ hwmem hS
    have hcl : IsClosed (((S[M]⟦η, ξ⟧).closure.graph : Submodule ℝ (H × H)) : Set (H × H)) :=
      isClosed_closure_relativeTomita M η ξ
    rw [hcl.closure_eq] at h
    rwa [hz, sub_zero] at h
  have h := (S[M]⟦η, ξ⟧).closure.graph.add_mem hζ hw
  rwa [Prod.mk_add_mk, sub_add_cancel, add_zero] at h

/-- `ker S̄_{η,ξ} = ker s(η) s′(ξ)`, pointwise. -/
private lemma mem_graph_closure_relativeTomita_zero_iff {x : H} :
    (x, 0) ∈ (S[M]⟦η, ξ⟧).closure.graph ↔ M.supportProj η (M′.supportProj ξ x) = 0 :=
  ⟨fun hx => (S[M]⟦ξ, η⟧).closure.graph_fst_eq_zero_snd
    (mem_graph_closure_relativeTomita_swap hx) rfl,
    mem_graph_closure_relativeTomita_of_supportProj_apply_eq_zero⟩

/-- **`S̄_{ξ,η} S̄_{η,ξ} ⊆ s(η) s′(ξ)`**: `S̄_{ξ,η}` inverts `S̄_{η,ξ}` between the supports. -/
lemma closure_relativeTomita_compNat_le :
    (S[M]⟦ξ, η⟧).closure.compNat (S[M]⟦η, ξ⟧).closure ≤
      (((M.supportProj η * M′.supportProj ξ : H →L[ℂ] H) : H →ₗ[ℂ] H).restrictScalars ℝ).toPMap ⊤ :=
  LinearPMap.le_iff_mem_graph.mpr fun a c hac => by
    -- the graph of `S̄_{ξ,η}` is that of a function
    obtain ⟨b, hab, hbc⟩ := LinearPMap.mem_graph_compNat.mp hac
    obtain rfl : c = M.supportProj η (M′.supportProj ξ a) :=
      sub_eq_zero.mp ((S[M]⟦ξ, η⟧).closure.graph_fst_eq_zero_snd
        ((S[M]⟦ξ, η⟧).closure.graph.sub_mem hbc (mem_graph_closure_relativeTomita_swap hab))
        (sub_self b))
    exact (LinearPMap.mem_graph_iff _).mpr
      ⟨⟨a, Submodule.mem_top⟩, rfl, mul_apply_eq_comp (M.supportProj η) (M′.supportProj ξ) a⟩

/-- **`ker S̄_{η,ξ} = ker s(η) s′(ξ)`** for arbitrary `η, ξ` (Araki–Masuda 1982, §2: the support of
`Δ_{η,ξ}` is `s(η) s′(ξ)`): `S̄_{ξ,η} S̄_{η,ξ} ⊆ s(η) s′(ξ)`
(`VonNeumannAlgebra.closure_relativeTomita_compNat_le`), and conversely `(1 - s(η) s′(ξ)) H` lies
in the kernel, as `S_{η,ξ} ((1 - s(η)) x ξ) = 0` and `S_{η,ξ} [M ξ]ᗮ = 0`. -/
lemma ker_closure_relativeTomita :
    (S[M]⟦η, ξ⟧).closure.ker =
      (LinearMap.ker ((M.supportProj η * M′.supportProj ξ : H →L[ℂ] H) : H →ₗ[ℂ] H)).restrictScalars
        ℝ := by
  ext x
  rw [← LinearPMap.mem_graph_zero_iff_mem_ker, Submodule.restrictScalars_mem, LinearMap.mem_ker,
    ContinuousLinearMap.coe_coe, mul_apply_eq_comp]
  exact mem_graph_closure_relativeTomita_zero_iff

/-- **`ker S̄_{η,ξ} = [M′ η]ᗮ`** for `ξ` cyclic: then `s′(ξ) = 1`, and `s(η)` is the projection
onto `[M′ η]` (`VonNeumannAlgebra.ker_closure_relativeTomita`). -/
lemma ker_closure_relativeTomita_eq_orthogonal (hc : IsCyclicVector M ξ) :
    (S[M]⟦η, ξ⟧).closure.ker = (cyclicSubspace M′ η).toSubmoduleᗮ.restrictScalars ℝ := by
  have hsupp : M′.supportProj ξ = 1 := by
    rw [supportProj_eq_one_iff, commutant_commutant]
    exact hc
  ext x
  rw [ker_closure_relativeTomita, hsupp, mul_one, Submodule.restrictScalars_mem,
    Submodule.restrictScalars_mem, LinearMap.mem_ker, ContinuousLinearMap.coe_coe, supportProj,
    Submodule.starProjection_apply_eq_zero_iff]

/-- For `ξ` cyclic and `η` separating, `S̄_{η,ξ}` is injective: its kernel `[M′ η]ᗮ`
(`VonNeumannAlgebra.ker_closure_relativeTomita_eq_orthogonal`) is `0`. -/
lemma ker_closure_relativeTomita_eq_bot (hc : IsCyclicVector M ξ)
    (hsη : IsSeparatingVector M η) : (S[M]⟦η, ξ⟧).closure.ker = ⊥ := by
  rw [ker_closure_relativeTomita_eq_orthogonal hc, hsη.isCyclicVector_commutant]
  simp

/-- **`ker Δ_{η,ξ} = [M′ η]ᗮ`** for `ξ` cyclic: `ker Δ_{η,ξ} = ker S̄_{η,ξ}`
(`VonNeumannAlgebra.ker_relativeModular`, `VonNeumannAlgebra.ker_closure_relativeTomita_eq_orthogonal`). -/
lemma ker_relativeModular_eq_orthogonal (hc : IsCyclicVector M ξ) :
    (Δ[M]⟦η, ξ⟧).ker.restrictScalars ℝ = (cyclicSubspace M′ η).toSubmoduleᗮ.restrictScalars ℝ :=
  ker_relativeModular.trans (ker_closure_relativeTomita_eq_orthogonal hc)

/-- For `ξ` cyclic and `η` separating, `Δ_{η,ξ}` is injective: `ker Δ_{η,ξ} = ker S̄_{η,ξ}`. -/
lemma ker_relativeModular_eq_bot (hc : IsCyclicVector M ξ) (hsη : IsSeparatingVector M η) :
    (Δ[M]⟦η, ξ⟧).ker = ⊥ :=
  ((isSelfAdjoint_relativeModular M η ξ).ker_eq_bot_iff_of_restrictScalars_eq
    (restrictScalars_relativeModular M η ξ)).mpr (ker_closure_relativeTomita_eq_bot hc hsη)

/-- For `ξ` cyclic and `η` separating, the relative modular group `Δ_{η,ξ}^{it}` is the unitary
group generated by `log Δ_{η,ξ}` (`IsSelfAdjoint.unitaryGroup`). -/
lemma relativeModularGroup_eq_unitaryGroup (hc : IsCyclicVector M ξ) (hsη : IsSeparatingVector M η)
    (t : ℝ) : Δ[M]⟦η, ξ⟧^{i t} =
      ((isSelfAdjoint_relativeModular M η ξ).isSelfAdjoint_logPMap.unitaryGroup t : H →L[ℂ] H) :=
  (isSelfAdjoint_relativeModular M η ξ).imaginaryPower_eq_unitaryGroup
    (isPositive_relativeModular M η ξ) (ker_relativeModular_eq_bot hc hsη) t

/-- `ran S̄_{η,ξ} ⊆ s(ξ) s′(η) H`, pointwise; the closure is a limit argument. -/
private lemma supportProj_apply_supportProj_of_mem_graph_closure {a b : H}
    (h : (a, b) ∈ (S[M]⟦η, ξ⟧).closure.graph) :
    M.supportProj ξ (M′.supportProj η b) = b := by
  have hS : ∀ p ∈ ((S[M]⟦η, ξ⟧).graph : Set (H × H)),
      M.supportProj ξ (M′.supportProj η p.2) = p.2 := by
    intro p hp
    obtain ⟨x, hx, ζ, hζ, rfl⟩ := mem_graph_relativeTomita.mp hp
    have hxη : M′.supportProj η (star x η) = star x η := by
      rw [supportProj_commutant, Submodule.starProjection_eq_self_iff]
      exact apply_mem_cyclicSubspace (star_mem hx) (self_mem_cyclicSubspace M η)
    dsimp only
    rw [← mul_apply_eq_comp (M′.supportProj η), ← (commute_supportProj_supportProj_commutant M ξ η).eq,
      mul_apply_eq_comp, hxη, ← mul_apply_eq_comp (M.supportProj ξ),
      (M.isStarProjection_supportProj ξ).isIdempotentElem.eq]
  have hcl : IsClosed {p : H × H | M.supportProj ξ (M′.supportProj η p.2) = p.2} :=
    isClosed_eq ((M.supportProj ξ).continuous.comp ((M′.supportProj η).continuous.comp
      continuous_snd)) continuous_snd
  rw [← (isClosable_relativeTomita M η ξ).graph_closure_eq_closure_graph, ← SetLike.mem_coe,
    Submodule.topologicalClosure_coe] at h
  have h' : (a, b) ∈ {p : H × H | M.supportProj ξ (M′.supportProj η p.2) = p.2} :=
    closure_minimal (s := ((S[M]⟦η, ξ⟧).graph : Set (H × H))) hS hcl h
  exact h'

/-- **`ran S̄_{η,ξ} ⊆ s(ξ) s′(η) H`**: `s(ξ) s′(η) S̄_{η,ξ} = S̄_{η,ξ}`, since
`S_{η,ξ} (x ξ + ζ) = s(ξ) x⋆ η ∈ s(ξ) [M η]`. -/
lemma supportProj_compPMap_closure_relativeTomita :
    (M.supportProj ξ * M′.supportProj η) ⬝ (S[M]⟦η, ξ⟧).closure = (S[M]⟦η, ξ⟧).closure :=
  LinearPMap.ext rfl fun x hx _ => by
    change (M.supportProj ξ * M′.supportProj η) ((S[M]⟦η, ξ⟧).closure ⟨x, hx⟩) = _
    rw [mul_apply_eq_comp]
    exact supportProj_apply_supportProj_of_mem_graph_closure ((S[M]⟦η, ξ⟧).closure.mem_graph ⟨x, hx⟩)

/-- **`s(ξ) s′(η) H ⊆ closure (ran S̄_{η,ξ})`**: `s(ξ) x η = S_{η,ξ} (x⋆ ξ)` for `x ∈ M`. -/
lemma supportProj_apply_supportProj_mem_closure_range (z : H) :
    M.supportProj ξ (M′.supportProj η z) ∈ closure (Set.range (S[M]⟦η, ξ⟧).closure) := by
  have hS : ∀ v ∈ Set.range fun x : M => (x : H →L[ℂ] H) η,
      M.supportProj ξ v ∈ Set.range (S[M]⟦η, ξ⟧).closure := by
    rintro _ ⟨⟨x, hx⟩, rfl⟩
    have h := mem_graph_closure_relativeTomita (apply_mem_graph_relativeTomita (η := η) (ξ := ξ)
      (star_mem hx))
    rw [star_star] at h
    obtain ⟨p, -, hp⟩ := ((S[M]⟦η, ξ⟧).closure.mem_graph_iff).mp h
    exact ⟨p, hp⟩
  have hmem : M′.supportProj η z ∈ closure (Set.range fun x : M => (x : H →L[ℂ] H) η) := by
    rw [← coe_cyclicSubspace, supportProj_commutant]
    exact Submodule.starProjection_apply_mem _ z
  exact map_mem_closure (M.supportProj ξ).continuous hmem hS

/-- `ran J_{η,ξ} ⊆ s(ξ) s′(η) H`: `J_{η,ξ}` maps into the closure of `ran S̄_{η,ξ}`
(`IsSelfAdjoint.polarIsometry_apply_mem_closure_range`), which `s(ξ) s′(η)` fixes. -/
lemma supportProj_apply_supportProj_relativeModularConj (x : H) :
    M.supportProj ξ (M′.supportProj η (J[M]⟦η, ξ⟧ x)) = J[M]⟦η, ξ⟧ x := by
  have hcl : IsClosed {v : H | M.supportProj ξ (M′.supportProj η v) = v} :=
    isClosed_eq ((M.supportProj ξ).continuous.comp (M′.supportProj η).continuous) continuous_id
  have hsub : Set.range (S[M]⟦η, ξ⟧).closure ⊆
      {v : H | M.supportProj ξ (M′.supportProj η v) = v} := by
    rintro _ ⟨p, rfl⟩
    exact supportProj_apply_supportProj_of_mem_graph_closure ((S[M]⟦η, ξ⟧).closure.mem_graph p)
  exact closure_minimal hsub hcl
    ((isSelfAdjoint_relativeModular M η ξ).polarIsometry_apply_mem_closure_range
      (restrictScalars_relativeModular M η ξ) (isClosed_closure_relativeTomita M η ξ) x)

/-- **`ran J_{η,ξ} = s(ξ) s′(η) H`** for arbitrary `η, ξ` (Araki–Masuda 1982, §2): the final space
of the partial isometry `J_{η,ξ}`. The range of `J_{η,ξ}` is closed and contains `ran S̄_{η,ξ}`,
which is dense in `s(ξ) s′(η) H` (`VonNeumannAlgebra.supportProj_apply_supportProj_mem_closure_range`).
-/
lemma range_relativeModularConj :
    Set.range J[M]⟦η, ξ⟧ = Set.range (M.supportProj ξ * M′.supportProj η) := by
  ext z
  constructor
  · rintro ⟨x, rfl⟩
    refine ⟨J[M]⟦η, ξ⟧ x, ?_⟩
    rw [mul_apply_eq_comp]
    exact supportProj_apply_supportProj_relativeModularConj x
  · rintro ⟨y, rfl⟩
    have h := supportProj_apply_supportProj_mem_closure_range (M := M) (η := η) (ξ := ξ) y
    rw [← mul_apply_eq_comp] at h
    have hA := isSelfAdjoint_relativeModular M η ξ
    have hAT := restrictScalars_relativeModular M η ξ
    have hT := isClosed_closure_relativeTomita M η ξ
    exact (hA.isClosed_range_polarIsometry hAT hT).closure_subset_iff.mpr
      (hA.range_subset_range_polarIsometry hAT hT) h

/-- `J_{η,ξ}† = J_{ξ,η}` for the polar isometries (`adjoint_relativeModularConj`). -/
private lemma adjoint_polarIsometry_relativeModular :
    ((isSelfAdjoint_relativeModular M η ξ).polarIsometry
      (restrictScalars_relativeModular M η ξ) (isClosed_closure_relativeTomita M η ξ))† =
    (isSelfAdjoint_relativeModular M ξ η).polarIsometry (restrictScalars_relativeModular M ξ η)
      (isClosed_closure_relativeTomita M ξ η) := by
  set hA := isSelfAdjoint_relativeModular M η ξ
  set hAT := restrictScalars_relativeModular M η ξ
  set hT := isClosed_closure_relativeTomita M η ξ
  set T := (S[M]⟦η, ξ⟧).closure
  set T' := (S[M]⟦ξ, η⟧).closure
  set J := hA.polarIsometry hAT hT
  set W := J†
  set P := hA.pvm (Ioi 0)
  -- the supports `e = s(ξ) s′(η)` (final space of `J`) and `f = s(η) s′(ξ)` (initial space)
  set e := M.supportProj ξ * M′.supportProj η
  set f := M.supportProj η * M′.supportProj ξ
  have he : IsStarProjection e := (M.isStarProjection_supportProj ξ).mul
    (M′.isStarProjection_supportProj η) (commute_supportProj_supportProj_commutant M ξ η)
  have hf : IsStarProjection f := (M.isStarProjection_supportProj η).mul
    (M′.isStarProjection_supportProj ξ) (commute_supportProj_supportProj_commutant M η ξ)
  have hsym : ∀ {q : H →L[ℂ] H}, IsStarProjection q → ∀ a b, inner ℝ (q a) b = inner ℝ a (q b) :=
    fun hq a b => by
      rw [inner_real_eq_re_inner, inner_real_eq_re_inner, ← ContinuousLinearMap.adjoint_inner_right,
        ← ContinuousLinearMap.star_eq_adjoint, hq.isSelfAdjoint.star_eq]
  have hidem : ∀ {q : H →L[ℂ] H}, IsStarProjection q → ∀ a, q (q a) = q a := fun hq a => by
    rw [← mul_apply_eq_comp, hq.isIdempotentElem.eq]
  have hP : ∀ a b, inner ℝ (P a) b = inner ℝ a (P b) := hsym (hA.pvm.isStarProjection _)
  -- polar decomposition of `T` and the swap
  have hpol : ∀ w v, (w, v) ∈ T.graph ↔ ∃ q, (w, q) ∈ hA.sqrt.graph ∧ J q = v := fun w v =>
    mem_graph_closure_relativeTomita_iff
  have hswap : ∀ y w, (y, w) ∈ T'.graph → (w, e y) ∈ T.graph := fun y w h => by
    simpa only [e, mul_apply_eq_comp] using mem_graph_closure_relativeTomita_swap h
  have hkey : ∀ y w, (y, w) ∈ T'.graph → ∃ q, (w, q) ∈ hA.sqrt.graph ∧ J q = e y :=
    fun y w h => (hpol w (e y)).mp (hswap y w h)
  have hPq : ∀ w q, (w, q) ∈ hA.sqrt.graph → P q = q := fun w q h => by
    -- `E_Δ((0, ∞)) Δ^{1/2} = Δ^{1/2}` at the graph point `(w, q)`
    have h' : (w, P q) ∈ hA.sqrt.graph := by
      rw [← hA.pvm_Ioi_compPMap_sqrt]
      exact LinearPMap.mem_graph_compPMap.mpr ⟨q, h, rfl⟩
    exact sub_eq_zero.mp (hA.sqrt.graph_fst_eq_zero_snd (hA.sqrt.graph.sub_mem h' h) (sub_self w))
  -- `ran J ⊆ e H`
  have hJe : ∀ x, e (J x) = J x := fun x => by
    rw [mul_apply_eq_comp]
    exact supportProj_apply_supportProj_relativeModularConj x
  -- `ran S̄_{ξ,η} ⊆ f H ⊆ E_Δ((0, ∞)) H`
  have hran : ∀ y w, (y, w) ∈ T'.graph → P w = w := fun y w h => by
    have hfw : f w = w := by
      rw [mul_apply_eq_comp]
      exact supportProj_apply_supportProj_of_mem_graph_closure h
    refine hA.pvm_Ioi_apply_eq_self hAT hT ((Submodule.mem_orthogonal _ _).mpr fun k hk => ?_)
    have hfk : f k = 0 := by
      rw [mul_apply_eq_comp]
      exact mem_graph_closure_relativeTomita_zero_iff.mp (LinearPMap.mem_graph_zero_iff_mem_ker.mpr hk)
    rw [← hfw, ← hsym hf, hfk, inner_zero_left]
  have hWJ : ∀ w, W (J w) = P w := hA.adjoint_polarIsometry_apply_polarIsometry hAT hT
  have hJq : ∀ w q, (w, q) ∈ hA.sqrt.graph → ∀ a, inner ℝ (J a) (J q) = inner ℝ a q :=
    fun w q h a => by
      rw [hA.inner_polarIsometry_apply hAT hT, hP, hidem (hA.pvm.isStarProjection _), hPq w q h]
  -- `R = J S̄_{ξ,η}`
  set R : H →ₗ.[ℝ] H := (J : H →ₗ[ℝ] H).compPMap T'
  have hRg : ∀ y v, (y, v) ∈ R.graph ↔ ∃ w, (y, w) ∈ T'.graph ∧ J w = v := fun _ _ =>
    LinearPMap.mem_graph_compPMap
  have hRsemi : LinearPMap.IsSemilinear (RingHom.id ℂ) R := fun c y v h => by
    obtain ⟨w, hw, rfl⟩ := (hRg y v).mp h
    refine (hRg _ _).mpr ⟨_, isSemilinear_closure_relativeTomita M ξ η c y w hw, ?_⟩
    rw [hA.polarIsometry_smul_of_isSemilinear hAT hT (isSemilinear_closure_relativeTomita M η ξ),
      starRingEnd_self_apply, RingHom.id_apply]
  -- `⟪J w, y'⟫ = ⟪w, q'⟫` for `(y', w') ∈ S̄_{ξ,η}`, `Δ^{1/2} w' = q'`
  have hside : ∀ w y' w' q', (y', w') ∈ T'.graph → (w', q') ∈ hA.sqrt.graph → J q' = e y' →
      inner ℝ (J w) y' = inner ℝ w q' := fun w y' w' q' _ hq' hJq' => by
    rw [← hJe w, hsym he, ← hJq', hJq w' q' hq']
  have hRsym : R.IsFormalAdjoint R := LinearPMap.isFormalAdjoint_of_mem_graph
    fun y v y' v' h h' => by
      obtain ⟨w, hw, rfl⟩ := (hRg y v).mp h
      obtain ⟨w', hw', rfl⟩ := (hRg y' v').mp h'
      obtain ⟨q, hq, hJq₁⟩ := hkey y w hw
      obtain ⟨q', hq', hJq₂⟩ := hkey y' w' hw'
      rw [hside w y' w' q' hw' hq' hJq₂, real_inner_comm (J w') y, hside w' y w q hw hq hJq₁,
        inner_real_eq_re_inner, inner_real_eq_re_inner,
        ← hA.isSelfAdjoint_sqrt.isFormalAdjoint.inner_eq_of_mem_graph hq hq', ← inner_conj_symm,
        conj_re]
  have hRpos : R.IsPositive := by
    refine ⟨hRsym, fun x => ?_⟩
    obtain ⟨w, hw, hJw⟩ := (hRg x (R x)).mp (R.mem_graph x)
    obtain ⟨q, hq, hJq₁⟩ := hkey x w hw
    obtain ⟨⟨w₀, hw₀⟩, rfl, rfl⟩ := (LinearPMap.mem_graph_iff _).mp hq
    have h := hA.isPositive_sqrt.re_inner_nonneg_left ⟨w₀, hw₀⟩
    rw [RCLike.re_to_real, ← hJw, hside _ _ _ _ hw (hA.sqrt.mem_graph ⟨w₀, hw₀⟩) hJq₁,
      inner_real_eq_re_inner, ← inner_conj_symm, conj_re]
    exact h
  -- `ran (R + 1) = H`
  have hrange : ∀ z, ∃ y v, (y, v) ∈ R.graph ∧ v + y = z := by
    intro z
    have hez : e z ∈ Set.range J :=
      (range_relativeModularConj (M := M) (η := η) (ξ := ξ)).ge ⟨z, rfl⟩
    obtain ⟨p₀, hp₀⟩ := hez
    have hres := LinearPMap.IsPositive.mem_resolventSet hA.isSelfAdjoint_sqrt hA.isPositive_sqrt
      (z := (-1 : ℂ)) (by simp)
    have hr := hA.sqrt.graph.neg_mem (LinearPMap.resolvent_mem_graph hres p₀)
    set a := -hA.sqrt.resolvent (-1) p₀
    set c := -((-1 : ℂ) • hA.sqrt.resolvent (-1) p₀ - p₀)
    have hac : a + c = p₀ := by
      simp only [a, c, neg_smul, one_smul, neg_sub, sub_neg_eq_add]
      abel
    have h₁ : (a, J c) ∈ T.graph := (hpol _ _).mpr ⟨c, hr, rfl⟩
    have h₂ := mem_graph_closure_relativeTomita_swap h₁
    rw [← mul_apply_eq_comp] at h₂
    have hJfa : J (f a) = J a := by
      have hk : (a - f a, 0) ∈ T.graph := by
        refine mem_graph_closure_relativeTomita_of_supportProj_apply_eq_zero ?_
        rw [← mul_apply_eq_comp, map_sub, hidem hf, sub_self]
      have hk0 : hA.pvm (Ioi 0) (a - f a) = 0 :=
        hA.ker_le_ker_pvm_Ioi hAT hT (LinearPMap.mem_graph_zero_iff_mem_ker.mp hk)
      have hJk : J (a - f a) = 0 := norm_eq_zero.mp (by
        rw [hA.norm_polarIsometry_apply hAT hT, hk0, norm_zero])
      rw [map_sub, sub_eq_zero] at hJk
      exact hJk.symm
    have h₃ : (z - e z, 0) ∈ T'.graph := by
      refine mem_graph_closure_relativeTomita_of_supportProj_apply_eq_zero ?_
      rw [← mul_apply_eq_comp, map_sub, hidem he, sub_self]
    refine ⟨J c + (z - e z), J a + 0, (hRg _ _).mpr ⟨f a + 0, T'.graph.add_mem h₂ h₃, ?_⟩, ?_⟩
    · rw [add_zero, add_zero, hJfa]
    · rw [add_zero, ← add_assoc, ← map_add, hac, hp₀, add_sub_cancel]
  have hRsa : IsSelfAdjoint R := hRsym.isSelfAdjoint_of_surjective 1
    (LinearPMap.surjective_vadd_iff.mpr fun z => by
      obtain ⟨y, v, h, hvy⟩ := hrange z
      exact ⟨y, v, h, by rw [← hvy, add_comm, LinearMap.smul_apply, LinearMap.id_apply,
        RCLike.ofReal_one, one_smul]⟩)
  have hBg : ∀ y v, (y, v) ∈ hRsemi.toLinearPMap.graph ↔ (y, v) ∈ R.graph := fun _ _ =>
    hRsemi.mem_graph_toLinearPMap
  refine (isSelfAdjoint_relativeModular M ξ η).eq_polarIsometry_of_eq_compPMap
    (restrictScalars_relativeModular M ξ η) (isClosed_closure_relativeTomita M ξ η)
    (hRsemi.isSelfAdjoint_toLinearPMap hRsa) (hRsemi.isPositive_toLinearPMap hRpos) W
    (fun y hy => ?_) (fun x hx => ?_) ?_
  · obtain ⟨x, h⟩ := LinearPMap.mem_range_iff.mp hy
    obtain ⟨w, -, rfl⟩ := (hRg x y).mp ((hBg x y).mp h)
    rw [hWJ, hA.norm_polarIsometry_apply hAT hT]
  · have h := LinearPMap.mem_graph_zero_iff_mem_ker.mpr hx
    change W x = 0
    obtain ⟨w, hw, hJw⟩ := (hRg x 0).mp ((hBg x 0).mp h)
    obtain ⟨q, hq, hJq₁⟩ := hkey x w hw
    have hPw : P w = 0 := by
      rw [← norm_eq_zero, ← hA.norm_polarIsometry_apply hAT hT, hJw, norm_zero]
    have hq0 : q = 0 := by
      have h' := LinearPMap.compPMap_le_compNat_toPMap_iff.mp
        (hA.pvm_compPMap_sqrt_le (measurableSet_Ioi (a := (0 : ℝ)))) hq
      simp only [ContinuousLinearMap.coe_coe] at h'
      rw [hPw, hPq w q hq] at h'
      exact hA.sqrt.graph_fst_eq_zero_snd h' rfl
    have hex : e x = 0 := by rw [← hJq₁, hq0, map_zero]
    refine hA.adjoint_polarIsometry_apply_eq_zero hAT hT fun v => ?_
    rw [← hJe v, ← hsym he, hex, inner_zero_left]
  · rw [hRsemi.restrictScalars_toLinearPMap]
    refine LinearPMap.eq_of_eq_graph (Submodule.ext fun ⟨y, v⟩ => ?_)
    rw [LinearPMap.mem_graph_compPMap]
    constructor
    · intro h
      exact ⟨J v, (hRg _ _).mpr ⟨v, h, rfl⟩, by rw [ContinuousLinearMap.coe_coe, hWJ, hran y v h]⟩
    · rintro ⟨u, hu, rfl⟩
      obtain ⟨w, hw, rfl⟩ := (hRg _ _).mp hu
      rw [ContinuousLinearMap.coe_coe, hWJ, hran y w hw]
      exact hw

/-- **`J_{η,ξ}† = J_{ξ,η}`** for arbitrary `η, ξ` (Araki–Masuda 1982, §2): the real adjoint `J†` of
the polar isometry `J = J_{η,ξ}` of `S̄_{η,ξ}` is the polar isometry of `S̄_{ξ,η}`; in complex form,
`⟪J_{ξ,η} x, y⟫ = ⟪J_{η,ξ} y, x⟫` (`VonNeumannAlgebra.inner_relativeModularConj_left`).

The proof is the uniqueness of the polar decomposition
(`IsSelfAdjoint.eq_polarIsometry_of_eq_compPMap`). `S̄_{ξ,η}` inverts `S̄_{η,ξ}` between the supports
(`VonNeumannAlgebra.closure_relativeTomita_compNat_le`), so on the supports
`S̄_{ξ,η} = S̄_{η,ξ}⁻¹ = Δ_{η,ξ}^{-1/2} J†`, and `R = J S̄_{ξ,η}`, which is `J Δ_{η,ξ}^{-1/2} J†`
there, is positive and self-adjoint (`LinearPMap.IsFormalAdjoint.isSelfAdjoint_of_surjective`); then
`S̄_{ξ,η} = J† R` is a polar decomposition of `S̄_{ξ,η}`.

TODO: the same computation gives `Δ_{ξ,η} = J_{η,ξ} Δ_{η,ξ}^{-1} J_{η,ξ}†` and
`Δ_{ξ,η}^{it} = J_{η,ξ} Δ_{η,ξ}^{it} J_{η,ξ}†`. With it the boundary value
`Δ_{η₂,Ω₂}^{-it} J_{Ω₂,η₂} V J_{η₁,Ω₁} Δ_{η₁,Ω₁}^{it}` of the relative Theorem A
(`VonNeumannAlgebra.exists_relativeModularGroup_continuation`) becomes
`J_{Ω₂,η₂} Ṽ(t) J_{η₁,Ω₁}` with `Ṽ(t) = Δ_{Ω₂,η₂}^{-it} V Δ_{Ω₁,η₁}^{it}`, the continuation for the
swapped pairs; it is Borchers' form `J V(t) J` only for `ηᵢ = Ωᵢ`. -/
lemma adjoint_relativeModularConj : ((J[M]⟦η, ξ⟧ : H →L[ℝ] H)†) = J[M]⟦ξ, η⟧ :=
  adjoint_polarIsometry_relativeModular

/-- **`J_{ξ,η} J_{η,ξ} = E_Δ((0, ∞))`**, the support projection of `Δ_{η,ξ}`, for arbitrary `η, ξ`
(Araki–Masuda 1982, §2, where `J_{η,ξ}† = J_{ξ,η}`): `J_{η,ξ}` is a partial isometry with initial
space `E_Δ((0, ∞)) H`, so `J_{ξ,η} J_{η,ξ} Δ_{η,ξ}^{1/2} = Δ_{η,ξ}^{1/2}`
(`IsSelfAdjoint.pvm_Ioi_compPMap_sqrt`). -/
lemma relativeModularConj_comp_relativeModularConj :
    (J[M]⟦ξ, η⟧.comp J[M]⟦η, ξ⟧ : H →L[ℂ] H) = E_Δ[M]⟦η, ξ⟧ (Ioi 0) := by
  ext u
  change J[M]⟦ξ, η⟧ (J[M]⟦η, ξ⟧ u) = _
  rw [relativeModularConj_apply, relativeModularConj_apply, ← adjoint_polarIsometry_relativeModular,
    IsSelfAdjoint.adjoint_polarIsometry_apply_polarIsometry]

/-- **The initial projection of `J_{η,ξ}`**: the support projection `E_Δ((0, ∞))` of `Δ_{η,ξ}` is
`s(η) s′(ξ)` for arbitrary `η, ξ` (Araki–Masuda 1982, §2), since `E_Δ((0, ∞))` projects onto
`(ker Δ_{η,ξ})ᗮ` (`IsSelfAdjoint.pvm_Ioi_eq_starProjection_orthogonal`) and
`ker Δ_{η,ξ} = ker S̄_{η,ξ} = ker s(η) s′(ξ)` (`VonNeumannAlgebra.ker_relativeModular`,
`VonNeumannAlgebra.ker_closure_relativeTomita`). -/
lemma pvm_Ioi_relativeModular :
    E_Δ[M]⟦η, ξ⟧ (Ioi 0) = M.supportProj η * M′.supportProj ξ := by
  have hf : IsStarProjection (M.supportProj η * M′.supportProj ξ) :=
    (M.isStarProjection_supportProj η).mul (M′.isStarProjection_supportProj ξ)
      (commute_supportProj_supportProj_commutant M η ξ)
  obtain ⟨K, hK, hfK⟩ := isStarProjection_iff_eq_starProjection.mp hf
  have hker : (Δ[M]⟦η, ξ⟧).ker = Kᗮ := by
    apply Submodule.restrictScalars_injective ℝ
    rw [ker_relativeModular, ker_closure_relativeTomita, hfK, Submodule.ker_starProjection]
  rw [(isSelfAdjoint_relativeModular M η ξ).pvm_Ioi_eq_starProjection_orthogonal
    (isPositive_relativeModular M η ξ), hfK]
  have h : (Δ[M]⟦η, ξ⟧).kerᗮ = K := by rw [hker, Submodule.orthogonal_orthogonal]
  subst h
  rfl

/-- **The modular conjugation of `(M, Ω)`**: for a cyclic and separating `Ω`, `J_{Ω,Ω}` is the
modular conjugation `J_{H_M}` of the standard subspace `H_M`. Both are the isometric part of the
polar decomposition of `S̄_{Ω,Ω} = S_{H_M}` (`VonNeumannAlgebra.closure_relativeTomita_self_eq_tomita`),
which is unique (`IsSelfAdjoint.eq_polarIsometry_of_eq_compPMap`). -/
lemma relativeModularConj_self {Ω : H} (hc : IsCyclicVector M Ω) (hs : IsSeparatingVector M Ω) :
    J[M]⟦Ω, Ω⟧ = (J[H[M, Ω]] : H →L⋆[ℂ] H) := by
  refine ContinuousLinearMap.ext fun x => ?_
  set K := H[M, Ω]
  set Jr := K.isSelfAdjoint_modular.polarIsometry K.restrictScalars_modular K.isClosed_tomita
  have hJr : ∀ y, J[K] y = Jr y := fun _ => rfl
  have hT : (S[M]⟦Ω, Ω⟧).closure =
      (Jr : H →ₗ[ℝ] H).compPMap (Δ[K]^{1/2}.restrictScalars ℝ) := by
    rw [closure_relativeTomita_self_eq_tomita hc hs]
    exact K.tomita_eq_modularConj_compPMap
  have h := (isSelfAdjoint_relativeModular M Ω Ω).eq_polarIsometry_of_eq_compPMap
    (restrictScalars_relativeModular M Ω Ω) (isClosed_closure_relativeTomita M Ω Ω)
    K.isSelfAdjoint_modular.isSelfAdjoint_sqrt K.isSelfAdjoint_modular.isPositive_sqrt Jr
    (fun y _ => K.isSelfAdjoint_modular.norm_polarIsometry_of_ker_eq_bot K.restrictScalars_modular
      K.isClosed_tomita K.ker_tomita_eq_bot y)
    (by rw [K.ker_sqrt_modular_eq_bot, Submodule.restrictScalars_bot]; exact bot_le) hT
  change J[M]⟦Ω, Ω⟧ x = J[K] x
  rw [relativeModularConj_apply, hJr, h]

/-- **`J_{ξ,η} = J_{η,ξ}†`** for arbitrary `η, ξ` (Araki–Masuda 1982, §2):
`⟪J_{ξ,η} x, y⟫ = ⟪J_{η,ξ} y, x⟫`, the adjoint relation of conjugate-linear operators. -/
lemma inner_relativeModularConj_left (x y : H) :
    ⟪J[M]⟦ξ, η⟧ x, y⟫_ℂ = ⟪J[M]⟦η, ξ⟧ y, x⟫_ℂ := by
  have hre : ∀ x, re ⟪J[M]⟦ξ, η⟧ x, y⟫_ℂ = re ⟪x, J[M]⟦η, ξ⟧ y⟫_ℂ := fun x => by
    rw [← inner_real_eq_re_inner, ← inner_real_eq_re_inner, relativeModularConj_apply,
      relativeModularConj_apply, ← adjoint_polarIsometry_relativeModular,
      ContinuousLinearMap.adjoint_inner_left]
  have h₁ := hre x
  have h₂ := hre (I • x)
  rw [map_smulₛₗ, inner_smul_left, inner_smul_left, starRingEnd_self_apply, conj_I] at h₂
  simp only [mul_re, I_re, I_im, zero_mul, one_mul, zero_sub, neg_re, neg_mul] at h₂
  refine Complex.ext ?_ ?_
  · rw [h₁, ← inner_conj_symm, conj_re]
  · rw [← inner_conj_symm (J[M]⟦η, ξ⟧ y), conj_im]
    linarith

/-- **`J_{ξ,η} J_{η,ξ} = 1`** for `ξ` cyclic and `η` separating: then `S̄_{η,ξ}` is injective
(`VonNeumannAlgebra.ker_closure_relativeTomita_eq_bot`), so `J_{η,ξ}` is isometric and
`J_{ξ,η} = J_{η,ξ}†` (`VonNeumannAlgebra.inner_relativeModularConj_left`) is a left inverse. -/
lemma relativeModularConj_relativeModularConj (hc : IsCyclicVector M ξ)
    (hsη : IsSeparatingVector M η) (x : H) : J[M]⟦ξ, η⟧ (J[M]⟦η, ξ⟧ x) = x := by
  rw [relativeModularConj_apply, relativeModularConj_apply, ← adjoint_polarIsometry_relativeModular,
    IsSelfAdjoint.adjoint_polarIsometry_apply_polarIsometry,
    IsSelfAdjoint.pvm_Ioi_eq_one_of_ker_eq_bot _ (restrictScalars_relativeModular M η ξ)
      (ker_closure_relativeTomita_eq_bot hc hsη), one_apply_eq_self]

/-- For `ξ` cyclic and `η` separating, `J_{η,ξ}` is isometric, since `S̄_{η,ξ}` is injective. -/
lemma norm_relativeModularConj_apply (hc : IsCyclicVector M ξ) (hsη : IsSeparatingVector M η)
    (x : H) : ‖J[M]⟦η, ξ⟧ x‖ = ‖x‖ := by
  rw [relativeModularConj_apply]
  exact (isSelfAdjoint_relativeModular M η ξ).norm_polarIsometry_of_ker_eq_bot
    (restrictScalars_relativeModular M η ξ) (isClosed_closure_relativeTomita M η ξ)
    (ker_closure_relativeTomita_eq_bot hc hsη) x

/-- For `η` cyclic and `ξ` separating, `J_{η,ξ}` is onto, with right inverse `J_{ξ,η}`. Together
with `VonNeumannAlgebra.norm_relativeModularConj_apply`, `J_{η,ξ}` is **antiunitary** for `ξ`, `η`
cyclic and separating (`VonNeumannAlgebra.relativeModularConjEquiv`). -/
lemma surjective_relativeModularConj (hcη : IsCyclicVector M η) (hs : IsSeparatingVector M ξ) :
    Function.Surjective J[M]⟦η, ξ⟧ := fun x =>
  ⟨J[M]⟦ξ, η⟧ x, relativeModularConj_relativeModularConj hcη hs x⟩

/-- **The relative modular conjugation is antiunitary** for `ξ`, `η` cyclic and separating:
`J_{η,ξ}` as a conjugate-linear isometric equivalence, the isometric part
(`IsSelfAdjoint.polarIsometryEquiv`) of `S̄_{η,ξ} = J_{η,ξ} Δ_{η,ξ}^{1/2}`, which is injective
(`VonNeumannAlgebra.ker_closure_relativeTomita_eq_bot`) with dense range
(`VonNeumannAlgebra.dense_range_closure_relativeTomita`). Its inverse is `J_{ξ,η}`
(`VonNeumannAlgebra.relativeModularConjEquiv_symm_apply`). -/
noncomputable def relativeModularConjEquiv (hc : IsCyclicVector M ξ)
    (hs : IsSeparatingVector M ξ) (hcη : IsCyclicVector M η) (hsη : IsSeparatingVector M η) :
    H ≃ₗᵢ⋆[ℂ] H :=
  (isSelfAdjoint_relativeModular M η ξ).polarIsometryEquiv (restrictScalars_relativeModular M η ξ)
    (isClosed_closure_relativeTomita M η ξ) (ker_closure_relativeTomita_eq_bot hc hsη)
    (dense_range_closure_relativeTomita hs hcη) (isSemilinear_closure_relativeTomita M η ξ)

section Equiv

variable (hc : IsCyclicVector M ξ) (hs : IsSeparatingVector M ξ) (hcη : IsCyclicVector M η)
  (hsη : IsSeparatingVector M η)

/-- The antiunitary `relativeModularConjEquiv` is `J_{η,ξ}`. -/
@[simp]
lemma relativeModularConjEquiv_apply (x : H) :
    relativeModularConjEquiv hc hs hcη hsη x = J[M]⟦η, ξ⟧ x := rfl

/-- The inverse of the antiunitary `J_{η,ξ}` is `J_{ξ,η}`. -/
@[simp]
lemma relativeModularConjEquiv_symm_apply (x : H) :
    (relativeModularConjEquiv hc hs hcη hsη).symm x = J[M]⟦ξ, η⟧ x :=
  (LinearIsometryEquiv.symm_apply_eq _).mpr
    (relativeModularConj_relativeModularConj hcη hs x).symm

end Equiv

end RelativeModularConj

end VonNeumannAlgebra
