/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import Mathlib.Analysis.InnerProductSpace.Adjoint

/-!
# Displaying the adjoint as `A†`

Mathlib writes the adjoint of a bounded operator `A : E →L[𝕜] F` between inner product spaces as
`A†` (`open scoped InnerProduct`, `ContinuousLinearMap.adjoint`), but the notation is never shown
in goals: `ContinuousLinearMap.adjoint` is a bundled conjugate-linear isometric equivalence, and
`A†` elaborates to its coercion to a function applied to `A`, which the unexpander generated by
the `postfix` declaration does not match. The delaborator here displays that application as `A†`
in the same scope, so goals read `(V†) x` and `V ∘L A ∘L V†`.

The delaborator is an **approved exception (2026-10-10)** to the project rule that display is
achieved by shaping definitions rather than by metaprogramming (see the *Prohibited Tokens* section
of `.claude/skills/lint-fix/references/rules.md`). It compensates for Mathlib's own `†` notation
not being displayed: `ContinuousLinearMap.adjoint` is a bundled equivalence owned by Mathlib, so no
proof-free definition in this repository can make the `postfix` unexpander fire without bridging
two spellings of the adjoint.

The notation coexists with the `T†` of `LinearPMap.adjoint` (`open scoped LinearPMap`): with both
scopes open the overloaded `†` elaborates by the type of `T`. The bounded `†` has precedence `1000`,
below that of a function argument, so with both scopes open an adjoint applied to an argument is
written `(T†) x` for either kind; `T† x` (which `LinearPMap` alone accepts) no longer parses.

## Conventions

The adjoint `A†` is used for operators between two spaces. For an element of the C⋆-algebra
`E →L[𝕜] E` the star `A⋆` (`star A`) is used, as for any C⋆-algebra; the two agree by
`ContinuousLinearMap.star_eq_adjoint`. The adjoint of a conjugate-linear map, such as a modular
conjugation `J : H →L⋆[ℂ] H`, lies outside `ContinuousLinearMap.adjoint`; it is the semilinear
adjoint `J.adjointₛₗ` (`ContinuousLinearMap.adjointₛₗ`), which has no `†` notation.
-/

@[expose] public section

namespace InnerProduct

open Lean PrettyPrinter Delaborator SubExpr in
/-- Delaborator displaying `ContinuousLinearMap.adjoint A` (the coercion of the bundled adjoint
applied to `A`) as `A†`. It is an approved exception (2026-10-10) to the ban on metaprogramming:
Mathlib's `†` notation for the bundled equivalence `ContinuousLinearMap.adjoint` is otherwise never
displayed. -/
@[scoped delab app.DFunLike.coe]
meta def delabAdjoint : Delab := do
  let e ← getExpr
  guard <| e.isAppOfArity ``DFunLike.coe 6
  guard <| (e.getArg! 4).isAppOf ``ContinuousLinearMap.adjoint
  let A ← withAppArg delab
  `($A†)

end InnerProduct
