/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import Mathlib.Analysis.InnerProductSpace.Adjoint

/-!
# Displaying the adjoint as `A†`

Mathlib writes the adjoint of a bounded operator `A : E →L[𝕜] F` between inner product spaces as
`A†` (`open scoped InnerProduct`, `ContinuousLinearMap.adjoint`), but the notation is never shown
in goals: `ContinuousLinearMap.adjoint` is a bundled conjugate-linear isometric equivalence, and
`A†` elaborates to its coercion to a function applied to `A`, which the unexpander generated by
the `postfix` declaration does not match. The delaborator here displays that application as `A†`
in the same scope, so goals read `(V†) x` and `V ∘L A ∘L V†`.

The notation coexists with the `T†` of `LinearPMap.adjoint` (`open scoped LinearPMap`): with both
scopes open the overloaded `†` elaborates by the type of `T`. The bounded `†` has precedence `1000`,
below that of a function argument, so with both scopes open an adjoint applied to an argument is
written `(T†) x` for either kind; `T† x` (which `LinearPMap` alone accepts) no longer parses.

## Conventions

The adjoint `A†` is used for operators between two spaces. For an element of the C⋆-algebra
`E →L[𝕜] E` the star `A⋆` (`star A`) is used, as for any C⋆-algebra; the two agree by
`ContinuousLinearMap.star_eq_adjoint`. The real adjoint of a real-linear map on a complex Hilbert
space, for the real inner product `re ⟪·, ·⟫`, is written `A†` even on one space, as for the
modular conjugation `(J : H →L[ℝ] H)†`, since the real inner product is only a scoped instance
(`ClosedSubmodule.instInnerProductSpaceReal`).
-/

@[expose] public section

namespace InnerProduct

open Lean PrettyPrinter Delaborator SubExpr in
/-- Delaborator displaying `ContinuousLinearMap.adjoint A` (the coercion of the bundled adjoint
applied to `A`) as `A†`. -/
@[scoped delab app.DFunLike.coe]
meta def delabAdjoint : Delab := do
  let e ← getExpr
  guard <| e.isAppOfArity ``DFunLike.coe 6
  guard <| (e.getArg! 4).isAppOf ``ContinuousLinearMap.adjoint
  let A ← withAppArg delab
  `($A†)

end InnerProduct
