/-
Copyright (c) 2025 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Basic
public import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Commute
public import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap

/-!
# Reducing subspaces for sets of bounded operators

This file provides a minimal API for invariant / reducing subspaces for a set of operators
`S : Set (H →L[ℂ] H)` on a Hilbert space `H`.  Invariance of `K` under a single operator `T` is
Mathlib's `K ∈ Module.End.invtSubmodule T`.

## Main definitions

* `IsReducing S K`: `K` is reducing for `S` if `K` is invariant under `T` and `T†` for all `T ∈ S`.
* `cyclicSubspace S x`: the closed subspace `[S x]` generated by the orbit `{a x | a ∈ S}`.
* `IsCyclicVector S x`, `IsSeparatingVector S x`: `[S x] = H`, and `a x = 0` forces `a = 0` for
  `a ∈ S` (Bratteli–Robinson, Definition 2.5.2).

## Main results

* `commutes_starProjection_of_mem_invtSubmodule`: if `K` and `Kᗮ` are both invariant under `T`,
  then `T` commutes with the orthogonal projection onto `K`.
* `mem_invtSubmodule_of_commutes_starProjection`: conversely, if `T` commutes with
  `K.starProjection`, then `K` is invariant under `T`.
* `orthogonal_mem_invtSubmodule_of_commutes_starProjection`: if `T` commutes with
  `K.starProjection`, then `Kᗮ` is invariant under `T`.
* `orthogonal_mem_invtSubmodule_of_adjoint`: if `K` is invariant under `T†`, then
  `Kᗮ` is invariant under `T`.
* `subset_cyclicSubspace`, `apply_mem_cyclicSubspace`, `cyclicSubspace_le`: `[S x]` is the
  smallest closed subspace containing the orbit; `mem_orthogonal_cyclicSubspace_iff`: its
  orthogonal complement is that of the orbit; `cyclicSubspace_smul`: `[S (c x)] = [S x]`, `c ≠ 0`.
* `apply_mem_cyclicSubspace_of_mem`: for a subalgebra `A`, `[A x]` is invariant under `A`;
  `coe_cyclicSubspace_of_submodule`: for a linear subspace `P` of operators, `[P x]` is the closure
  of the orbit itself, with no span needed.
* `starProjection_mem_centralizer_of_isReducing`: if `K` is reducing for `S`, then
  `K.starProjection ∈ Set.centralizer S`.
* `ActsNondegenerately S`: no nonzero vector is annihilated by every element of `S`; the
  hypothesis of the non-unital double commutant theorem.
* `IsTopologicallyIrreducible S`: the only closed `S`-invariant subspaces are `⊥` and `⊤`.
* `centralizer_eq_scalars_iff`: **Schur's lemma** for a `⋆`-closed set `S` of bounded operators —
  the commutant `Set.centralizer S` is `ℂ1` iff `S` is topologically irreducible. This is the
  topological form, for closed invariant subspaces of a possibly infinite-dimensional Hilbert
  space; Mathlib's algebraic Schur lemmas
  (`LinearMap.bijective_or_eq_zero` for simple modules, `FDRep.finrank_hom_simple_simple` in
  finite dimension) do not apply to it, and the proof goes through the continuous functional
  calculus instead.
-/

@[expose] public section

namespace InnerProductSpace

open scoped InnerProduct ComplexInnerProductSpace

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]

section NonComplete

/-- If `K` and `Kᗮ` are both invariant under `T`, then `T` commutes with the orthogonal projection
onto `K` (as `K.starProjection`). -/
lemma commutes_starProjection_of_mem_invtSubmodule
    {T : H →L[ℂ] H} {K : Submodule ℂ H} [K.HasOrthogonalProjection]
    (hK : K ∈ Module.End.invtSubmodule (T : Module.End ℂ H))
    (hKorth : Kᗮ ∈ Module.End.invtSubmodule (T : Module.End ℂ H)) :
    T * K.starProjection = K.starProjection * T := by
  ext x
  -- Unfold multiplication as composition.
  -- After this, the goal is `T (P x) = P (T x)`.
  simp only [mul_apply_eq_comp]
  have hxK : K.starProjection x ∈ K := Submodule.starProjection_apply_mem (U := K) x
  have hxKorth : x - K.starProjection x ∈ Kᗮ := Submodule.sub_starProjection_mem_orthogonal (K := K) x
  have hTxK : T (K.starProjection x) ∈ K :=
    (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).1 hK _ hxK
  have hTxKorth : T (x - K.starProjection x) ∈ Kᗮ :=
    (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).1 hKorth _ hxKorth
  have h1 : K.starProjection (T (K.starProjection x)) = T (K.starProjection x) :=
    (Submodule.starProjection_eq_self_iff (K := K)).2 hTxK
  have h2 : K.starProjection (T (x - K.starProjection x)) = 0 :=
    (Submodule.starProjection_apply_eq_zero_iff (K := K)).2 hTxKorth
  have hxDecomp : K.starProjection x + (x - K.starProjection x) = x := by
    simp [sub_eq_add_neg]
  -- Rewrite `T x` as `T (P x + (x - P x))` and project.
  have hproj : K.starProjection (T x) = T (K.starProjection x) := by
    have hx1 :
        K.starProjection (T x) = K.starProjection (T (K.starProjection x + (x - K.starProjection x))) :=
      congrArg (fun z => K.starProjection (T z)) hxDecomp.symm
    calc
      K.starProjection (T x)
          = K.starProjection (T (K.starProjection x + (x - K.starProjection x))) := hx1
      _ = K.starProjection (T (K.starProjection x) + T (x - K.starProjection x)) := by
          exact
            congrArg (fun w => K.starProjection w)
              (T.map_add (K.starProjection x) (x - K.starProjection x))
      _ = K.starProjection (T (K.starProjection x)) + K.starProjection (T (x - K.starProjection x)) := by
          exact
            (K.starProjection.map_add (T (K.starProjection x)) (T (x - K.starProjection x)))
      _ = T (K.starProjection x) + K.starProjection (T (x - K.starProjection x)) := by
          simp [h1]
      _ = T (K.starProjection x) + 0 := by
          rw [h2]
      _ = T (K.starProjection x) := by
          simp
  exact hproj.symm

/-- If `T` commutes with the orthogonal projection onto `K`, then `K` is invariant under `T`. -/
lemma mem_invtSubmodule_of_commutes_starProjection
    {T : H →L[ℂ] H} {K : Submodule ℂ H} [K.HasOrthogonalProjection]
    (hcomm : K.starProjection * T = T * K.starProjection) :
    K ∈ Module.End.invtSubmodule (T : Module.End ℂ H) := by
  refine (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).2 ?_
  intro x hx
  have hxPx : K.starProjection x = x :=
    (Submodule.starProjection_eq_self_iff (K := K)).2 hx
  have hcomm_apply : (K.starProjection * T) x = (T * K.starProjection) x :=
    congrArg (fun f => f x) hcomm
  have hxTx : K.starProjection (T x) = T x := by
    simpa [mul_apply_eq_comp, hxPx] using hcomm_apply
  exact (Submodule.starProjection_eq_self_iff (K := K)).1 hxTx

/-- If `T` commutes with the orthogonal projection onto `K`, then `Kᗮ` is invariant under `T`. -/
lemma orthogonal_mem_invtSubmodule_of_commutes_starProjection
    {T : H →L[ℂ] H} {K : Submodule ℂ H} [K.HasOrthogonalProjection]
    (hcomm : K.starProjection * T = T * K.starProjection) :
    Kᗮ ∈ Module.End.invtSubmodule (T : Module.End ℂ H) := by
  refine (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).2 ?_
  intro y hy
  have hyPy : K.starProjection y = 0 :=
    (Submodule.starProjection_apply_eq_zero_iff (K := K)).2 hy
  have hcomm_apply : (K.starProjection * T) y = (T * K.starProjection) y :=
    congrArg (fun f => f y) hcomm
  have hyTy : K.starProjection (T y) = 0 := by
    simpa [mul_apply_eq_comp, hyPy] using hcomm_apply
  exact (Submodule.starProjection_apply_eq_zero_iff (K := K)).1 hyTy

end NonComplete

section WithComplete

variable [CompleteSpace H]

/-- A subspace `K` is reducing for a set of operators `S` if it is invariant under every operator
in `S` and also invariant under every adjoint operator. -/
def IsReducing (S : Set (H →L[ℂ] H)) (K : Submodule ℂ H) : Prop :=
  ∀ T ∈ S, K ∈ Module.End.invtSubmodule (T : Module.End ℂ H) ∧
    K ∈ Module.End.invtSubmodule ((T†) : Module.End ℂ H)

/-- If `K` is invariant under `T†`, then `Kᗮ` is invariant under `T`. -/
lemma orthogonal_mem_invtSubmodule_of_adjoint
    {T : H →L[ℂ] H} {K : Submodule ℂ H}
    (hK : K ∈ Module.End.invtSubmodule ((T†) : Module.End ℂ H)) :
    Kᗮ ∈ Module.End.invtSubmodule (T : Module.End ℂ H) := by
  -- Unfold to the pointwise characterization.
  refine (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).2 ?_
  intro y hy
  -- Show `T y ∈ Kᗮ` via the inner-product characterization.
  refine (K.mem_orthogonal (T y)).2 ?_
  intro x hx
  have hx' : (T†) x ∈ K :=
    (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).1 hK x hx
  -- `y ∈ Kᗮ` implies `⟪(T†) x, y⟫ = 0`, hence also `⟪x, T y⟫ = 0`.
  have hy0 : ⟪(T†) x, y⟫ = 0 :=
    (K.mem_orthogonal y).1 hy ((T†) x) hx'
  -- Use adjointness: `⟪(T†) x, y⟫ = ⟪x, T y⟫`.
  have hAdj : ⟪x, T y⟫ = ⟪(T†) x, y⟫ := by
    -- `adjoint_inner_left` is: `⟪(T†) y, x⟫ = ⟪y, T x⟫`.
    simpa using (ContinuousLinearMap.adjoint_inner_left (A := T) (x := y) (y := x)).symm
  exact hAdj.trans hy0

/-- If `K` is reducing for `S`, then the orthogonal projection onto `K` lies in the commutant
(`Set.centralizer S`). -/
lemma starProjection_mem_centralizer_of_isReducing
    (S : Set (H →L[ℂ] H)) (K : Submodule ℂ H) [K.HasOrthogonalProjection]
    (hK : IsReducing S K) : K.starProjection ∈ Set.centralizer S := by
  intro T hT
  have hInv : K ∈ Module.End.invtSubmodule (T : Module.End ℂ H) := (hK T hT).1
  have hInvAdj : K ∈ Module.End.invtSubmodule ((T†) : Module.End ℂ H) := (hK T hT).2
  have hInvOrth : Kᗮ ∈ Module.End.invtSubmodule (T : Module.End ℂ H) :=
    orthogonal_mem_invtSubmodule_of_adjoint (T := T) hInvAdj
  exact commutes_starProjection_of_mem_invtSubmodule (T := T) (K := K) hInv hInvOrth

end WithComplete

section Nondegenerate

/-- A set of operators `S` *acts non-degenerately* on `H` if the only vector annihilated by
every element of `S` is `0`.

This is the *joint-kernel* form of non-degeneracy. The operator-algebra literature usually states
it as "the span of `S • H` is dense in `H`"; the two agree when `S` is closed under `star`, and
only then. Without self-adjointness they come apart: `span {e₁₁, e₁₂} ⊆ M₂(ℂ)` has trivial joint
kernel but its range `ℂ • e₁` is not dense. Every
use in this development supplies a `NonUnitalStarSubalgebra`, where the readings coincide.

This is strictly weaker than `1 ∈ S` (see `actsNondegenerately_of_one_mem`): for example the
compact operators act non-degenerately on an infinite-dimensional `H` without containing `1`.
It is the hypothesis under which the double commutant theorem holds for a possibly non-unital
`*`-subalgebra. -/
def ActsNondegenerately (S : Set (H →L[ℂ] H)) : Prop :=
  ∀ x : H, (∀ T ∈ S, T x = 0) → x = 0

/-- A set of operators containing the identity acts non-degenerately. -/
lemma actsNondegenerately_of_one_mem {S : Set (H →L[ℂ] H)}
    (h : (1 : H →L[ℂ] H) ∈ S) : ActsNondegenerately S := by
  intro x hx
  simpa using hx 1 h

/-- Non-degeneracy is monotone: it passes from a set to any superset. -/
lemma ActsNondegenerately.mono {S S' : Set (H →L[ℂ] H)} (hSS' : S ⊆ S')
    (hS : ActsNondegenerately S) : ActsNondegenerately S' := by
  intro x hx
  exact hS x fun T hT => hx T (hSS' hT)

end Nondegenerate

section Cyclic

/-- The **cyclic subspace** `[S x]`: the closed subspace generated by the orbit
`{a x | a ∈ S}` of a vector `x` under a set `S` of operators, i.e. the closure of its span. -/
noncomputable def cyclicSubspace (S : Set (H →L[ℂ] H)) (x : H) : ClosedSubmodule ℂ H :=
  (Submodule.span ℂ (Set.range fun a : S => (a : H →L[ℂ] H) x)).closure

/-- The orbit `{a x | a ∈ S}` is contained in the cyclic subspace. -/
lemma subset_cyclicSubspace (S : Set (H →L[ℂ] H)) (x : H) :
    (Set.range fun a : S => (a : H →L[ℂ] H) x) ⊆ cyclicSubspace S x := fun _ hy =>
  Submodule.le_topologicalClosure _ (Submodule.subset_span hy)

/-- `a x ∈ [S x]` for `a ∈ S`. -/
lemma apply_mem_cyclicSubspace {S : Set (H →L[ℂ] H)} (x : H) {a : H →L[ℂ] H} (ha : a ∈ S) :
    a x ∈ cyclicSubspace S x :=
  subset_cyclicSubspace S x ⟨⟨a, ha⟩, rfl⟩

/-- `[S x]` is the smallest closed subspace containing the orbit `{a x | a ∈ S}`. -/
lemma cyclicSubspace_le {S : Set (H →L[ℂ] H)} {x : H} {K : ClosedSubmodule ℂ H}
    (h : ∀ a ∈ S, a x ∈ K) : cyclicSubspace S x ≤ K :=
  Submodule.closure_le.mpr (Submodule.span_le.mpr (by rintro _ ⟨⟨a, ha⟩, rfl⟩; exact h a ha))

/-- `[S (c x)] = [S x]` for `c ≠ 0`. -/
lemma cyclicSubspace_smul (S : Set (H →L[ℂ] H)) (x : H) {c : ℂ} (hc : c ≠ 0) :
    cyclicSubspace S (c • x) = cyclicSubspace S x := by
  refine le_antisymm (cyclicSubspace_le fun a ha => ?_) (cyclicSubspace_le fun a ha => ?_)
  · rw [map_smul]
    exact Submodule.smul_mem _ c (apply_mem_cyclicSubspace x ha)
  · rw [show a x = c⁻¹ • a (c • x) by rw [map_smul, inv_smul_smul₀ hc]]
    exact Submodule.smul_mem _ c⁻¹ (apply_mem_cyclicSubspace (c • x) ha)

/-- A vector is orthogonal to `[S x]` iff it is orthogonal to every `a x`, `a ∈ S`. -/
lemma mem_orthogonal_cyclicSubspace_iff {S : Set (H →L[ℂ] H)} {x v : H} :
    v ∈ (cyclicSubspace S x).toSubmoduleᗮ ↔ ∀ a ∈ S, ⟪a x, v⟫ = 0 := by
  refine ⟨fun hv a ha => (Submodule.mem_orthogonal _ v).mp hv _ (apply_mem_cyclicSubspace x ha),
    fun h => (Submodule.mem_orthogonal _ v).mpr fun w hw => ?_⟩
  let K : ClosedSubmodule ℂ H := ⟨LinearMap.ker (innerSL ℂ v : H →ₗ[ℂ] ℂ), (innerSL ℂ v).isClosed_ker⟩
  have hle : cyclicSubspace S x ≤ K := cyclicSubspace_le fun a ha => by
    change ⟪v, a x⟫ = 0
    rw [inner_eq_zero_symm]
    exact h a ha
  rw [inner_eq_zero_symm]
  exact hle hw

/-- For a linear subspace `P` of operators, the orbit `{a x | a ∈ P}` is already a subspace, so
`[P x]` is its closure. -/
lemma coe_cyclicSubspace_of_submodule (P : Submodule ℂ (H →L[ℂ] H)) (x : H) :
    (cyclicSubspace P x : Set H) =
      closure (Set.range fun a : P => (a : H →L[ℂ] H) x) := by
  have : (Submodule.span ℂ (Set.range fun a : (P : Set (H →L[ℂ] H)) => (a : H →L[ℂ] H) x) :
      Set H) = Set.range fun a : P => (a : H →L[ℂ] H) x := by
    have hmap : (Set.range fun a : P => (a : H →L[ℂ] H) x) =
        (P.map (ContinuousLinearMap.apply ℂ H x : (H →L[ℂ] H) →ₗ[ℂ] H) : Set H) := by
      ext v
      simp [eq_comm]
    rw [show (Set.range fun a : (P : Set (H →L[ℂ] H)) => (a : H →L[ℂ] H) x) =
      Set.range fun a : P => (a : H →L[ℂ] H) x from rfl, hmap, Submodule.span_eq]
  exact (Submodule.topologicalClosure_coe _).trans (congrArg closure this)

/-- A closed set containing the orbit of `x` under a linear subspace `P` of operators contains
`[P x]`. -/
lemma cyclicSubspace_subset_of_submodule (P : Submodule ℂ (H →L[ℂ] H)) {x : H} {s : Set H}
    (hs : IsClosed s) (h : ∀ a ∈ P, a x ∈ s) :
    (cyclicSubspace P x : Set H) ⊆ s := by
  rw [coe_cyclicSubspace_of_submodule]
  exact closure_minimal (by rintro _ ⟨⟨a, ha⟩, rfl⟩; exact h a ha) hs

/-- For a subalgebra `A`, the cyclic subspace `[A x]` is invariant under `A`. -/
lemma apply_mem_cyclicSubspace_of_mem (A : NonUnitalSubalgebra ℂ (H →L[ℂ] H)) {x y : H}
    {a : H →L[ℂ] H} (ha : a ∈ A) (hy : y ∈ cyclicSubspace A x) :
    a y ∈ cyclicSubspace A x := by
  have hy' : y ∈ (cyclicSubspace A.toSubmodule x : Set H) := hy
  change a y ∈ (cyclicSubspace A.toSubmodule x : Set H)
  rw [coe_cyclicSubspace_of_submodule] at hy' ⊢
  exact map_mem_closure a.continuous hy' fun _ ⟨b, hb⟩ =>
    ⟨⟨a * b, (A.mul_mem ha (show (b : H →L[ℂ] H) ∈ A from b.2) : a * (b : H →L[ℂ] H) ∈ A)⟩,
      by rw [← hb]; rfl⟩

/-- `x` is a **cyclic vector** for `S`: the cyclic subspace `[S x]` is all of `H`. -/
def IsCyclicVector (S : Set (H →L[ℂ] H)) (x : H) : Prop := cyclicSubspace S x = ⊤

/-- `x` is cyclic for `S` iff `[S x] = ⊤`. -/
lemma isCyclicVector_iff {S : Set (H →L[ℂ] H)} {x : H} :
    IsCyclicVector S x ↔ cyclicSubspace S x = ⊤ :=
  Iff.rfl

/-- Every vector lies in the cyclic subspace of a cyclic vector. -/
lemma IsCyclicVector.mem {S : Set (H →L[ℂ] H)} {x : H} (h : IsCyclicVector S x) (v : H) :
    v ∈ cyclicSubspace S x := by
  rw [isCyclicVector_iff.mp h]
  trivial

/-- `x` is a **separating vector** for `S`: `a x = 0` forces `a = 0` for `a ∈ S`. -/
def IsSeparatingVector (S : Set (H →L[ℂ] H)) (x : H) : Prop := ∀ a ∈ S, a x = 0 → a = 0

end Cyclic

section Schur

/-! ### Schur's lemma -/

variable [CompleteSpace H]

open scoped ComplexStarModule

omit [CompleteSpace H] in
/-- A set of operators `S` is *topologically irreducible* if the only closed `S`-invariant
subspaces are `⊥` and `⊤` (Murphy, *C\*-algebras and Operator Theory*, §5.1). This is the
hypothesis of Schur's lemma (`centralizer_eq_scalars_iff`) and the irreducibility condition of a
representation (`CStarRep.IsIrreducible`). -/
def IsTopologicallyIrreducible (S : Set (H →L[ℂ] H)) : Prop :=
  ∀ K : ClosedSubmodule ℂ H,
    (∀ T ∈ S, K.toSubmodule ∈ Module.End.invtSubmodule (T : Module.End ℂ H)) → K = ⊥ ∨ K = ⊤

omit [CompleteSpace H] in
/-- The kernel of an operator commuting with `T` is invariant under `T`. -/
lemma ker_mem_invtSubmodule_of_commute {G T : H →L[ℂ] H} (h : Commute G T) :
    G.ker ∈ Module.End.invtSubmodule (T : Module.End ℂ H) := by
  refine (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem _).2 fun x hx => ?_
  have hx' : G x = 0 := hx
  change G (T x) = 0
  rw [← mul_apply_eq_comp, h.eq, mul_apply_eq_comp, hx', map_zero]

/-- If the only closed `S`-invariant subspaces are `⊥` and `⊤`, a self-adjoint operator commuting
with every element of `S` is a real scalar. Two distinct points `r ≠ s` of its spectrum would give,
through the continuous functional calculus, nonzero operators `F`, `G` commuting with `S` with
`G F = 0`; the kernel of `G` would then be a closed invariant subspace that is neither `⊥` (it
contains the range of `F`) nor `⊤` (as `G ≠ 0`). -/
lemma exists_eq_algebraMap_of_isSelfAdjoint_of_commute {S : Set (H →L[ℂ] H)}
    (hS : IsTopologicallyIrreducible S)
    {y : H →L[ℂ] H} (hy : IsSelfAdjoint y) (hcomm : ∀ T ∈ S, Commute y T) :
    ∃ r : ℝ, y = algebraMap ℝ (H →L[ℂ] H) r := by
  rcases subsingleton_or_nontrivial H with hH | hH
  · exact ⟨0, ContinuousLinearMap.ext fun x => Subsingleton.elim _ _⟩
  obtain ⟨r, hr⟩ := ContinuousFunctionalCalculus.spectrum_nonempty (R := ℝ) y hy
  refine ⟨r, CFC.eq_algebraMap_of_spectrum_subset_singleton y r fun s hs => ?_⟩
  by_contra hsr
  rw [Set.mem_singleton_iff] at hsr
  set ε := |s - r| / 2 with hε_def
  have hε : 0 < ε := half_pos (abs_pos.mpr (sub_ne_zero.mpr hsr))
  -- Bumps of height `ε` at `r` and at `s` with disjoint supports.
  set f : ℝ → ℝ := fun t => max 0 (ε - |t - r|) with hf_def
  set g : ℝ → ℝ := fun t => max 0 (ε - |t - s|) with hg_def
  have hgf : (fun t => g t * f t) = (0 : ℝ → ℝ) := by
    funext t
    have htri : |s - r| ≤ |t - r| + |t - s| := by
      calc |s - r| = |(t - r) - (t - s)| := by ring_nf
        _ ≤ |t - r| + |t - s| := abs_sub _ _
    rcases le_total (ε - |t - r|) 0 with h1 | h1
    · simp [f, max_eq_left h1]
    · have h2 : ε - |t - s| ≤ 0 := by linarith
      simp [g, max_eq_left h2]
  have hF : cfc f y ≠ 0 := by
    intro h0
    have := ((cfc_eq_cfc_iff_eqOn (a := y) (f := f) (g := 0)).mp
      (h0.trans (cfc_zero (R := ℝ) (a := y)).symm)) hr
    simp only [f, sub_self, abs_zero, sub_zero, Pi.zero_apply] at this
    linarith [le_of_max_le_right this.le]
  have hG : cfc g y ≠ 0 := by
    intro h0
    have := ((cfc_eq_cfc_iff_eqOn (a := y) (f := g) (g := 0)).mp
      (h0.trans (cfc_zero (R := ℝ) (a := y)).symm)) hs
    simp only [g, sub_self, abs_zero, sub_zero, Pi.zero_apply] at this
    linarith [le_of_max_le_right this.le]
  have hGF : cfc g y * cfc f y = 0 := by rw [← cfc_mul g f y, hgf, cfc_zero]
  rcases hS ⟨(cfc g y).ker, (cfc g y).isClosed_ker⟩
      (fun T hT => ker_mem_invtSubmodule_of_commute ((hcomm T hT).cfc_real g)) with hb | ht
  · refine hF (ContinuousLinearMap.ext fun x => ?_)
    have hx : cfc f y x ∈ (⟨(cfc g y).ker, (cfc g y).isClosed_ker⟩ : ClosedSubmodule ℂ H) := by
      change cfc g y (cfc f y x) = 0
      rw [← mul_apply_eq_comp, hGF, zero_apply]
    rw [hb] at hx
    simpa using hx
  · refine hG (ContinuousLinearMap.ext fun x => ?_)
    have hx : x ∈ (⟨(cfc g y).ker, (cfc g y).isClosed_ker⟩ : ClosedSubmodule ℂ H) := by
      rw [ht]; trivial
    simpa using hx

/-- **Schur's lemma** for a `⋆`-closed set `S` of bounded operators: the commutant
`Set.centralizer S` consists of the scalars `ℂ1` iff the only closed `S`-invariant subspaces are
`⊥` and `⊤` (Murphy, *C\*-algebras and Operator Theory*, Thm. 5.1.1 and its converse;
Bratteli–Robinson, Prop. 2.3.8).

Forward: the orthogonal projection onto a closed invariant subspace commutes with `S`, since its
orthogonal complement is invariant too (`S` is `⋆`-closed), so it is an idempotent scalar, `0` or
`1`. Backward: an operator in the commutant splits into self-adjoint real and imaginary parts that
still commute with `S`, and each is a real scalar by
`exists_eq_algebraMap_of_isSelfAdjoint_of_commute`. -/
theorem centralizer_eq_scalars_iff {S : Set (H →L[ℂ] H)} (hS : ∀ T ∈ S, star T ∈ S) :
    (∀ x ∈ Set.centralizer S, ∃ c : ℂ, x = c • (1 : H →L[ℂ] H)) ↔ IsTopologicallyIrreducible S := by
  constructor
  · intro hsc K hK
    rcases subsingleton_or_nontrivial H with hH | hH
    · exact Or.inl (ClosedSubmodule.toSubmodule_injective (Subsingleton.elim _ _))
    have : CompleteSpace K.toSubmodule := K.isClosed.completeSpace_coe
    have hP : K.toSubmodule.starProjection ∈ Set.centralizer S := fun T hT =>
      commutes_starProjection_of_mem_invtSubmodule (hK T hT)
        (orthogonal_mem_invtSubmodule_of_adjoint (by
          rw [← ContinuousLinearMap.star_eq_adjoint]
          exact hK _ (hS T hT)))
    obtain ⟨c, hc⟩ := hsc _ hP
    have hcc : c * c = c := by
      have hidem := (Submodule.isIdempotentElem_starProjection (K := K.toSubmodule)).eq
      rw [hc, smul_mul_smul_comm, one_mul] at hidem
      exact smul_left_injective ℂ one_ne_zero hidem
    have hc01 : c * (c - 1) = 0 := by rw [mul_sub, hcc, mul_one, sub_self]
    rcases mul_eq_zero.mp hc01 with rfl | hc1
    · refine Or.inl (ClosedSubmodule.toSubmodule_injective (Submodule.eq_bot_iff _ |>.mpr ?_))
      intro x hx
      rw [← Submodule.starProjection_eq_self_iff.mpr hx, hc, zero_smul, zero_apply]
    · obtain rfl : c = 1 := sub_eq_zero.mp hc1
      refine Or.inr (ClosedSubmodule.toSubmodule_injective (Submodule.eq_top_iff'.mpr ?_))
      intro x
      rw [← Submodule.starProjection_eq_self_iff, hc, one_smul, one_apply_eq_self]
  · intro hirr x hx
    have hx' : ∀ T ∈ S, Commute x T := fun T hT => (hx T hT).symm
    have hxs : ∀ T ∈ S, Commute (star x) T := fun T hT => by
      have := (hx' _ (hS T hT)).star_star
      rwa [star_star] at this
    obtain ⟨r₁, hr₁⟩ := exists_eq_algebraMap_of_isSelfAdjoint_of_commute hirr (ℜ x).2
      fun T hT => by
        rw [realPart_apply_coe]
        exact ((hx' T hT).add_left (hxs T hT)).smul_left _
    obtain ⟨r₂, hr₂⟩ := exists_eq_algebraMap_of_isSelfAdjoint_of_commute hirr (ℑ x).2
      fun T hT => by
        rw [imaginaryPart_apply_coe]
        exact (((hx' T hT).sub_left (hxs T hT)).smul_left _).smul_left _
    refine ⟨r₁ + Complex.I * r₂, ?_⟩
    conv_lhs => rw [← realPart_add_I_smul_imaginaryPart x, hr₁, hr₂]
    rw [Algebra.algebraMap_eq_smul_one, Algebra.algebraMap_eq_smul_one, ← Complex.coe_smul,
      ← Complex.coe_smul, smul_smul, ← add_smul]

end Schur

end InnerProductSpace
