/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import Mathlib.MeasureTheory.Function.AEEqOfIntegral
public import Mathlib.MeasureTheory.Integral.Bochner.SumMeasure
public import Mathlib.MeasureTheory.Measure.Decomposition.IntegralRNDeriv
public import Mathlib.MeasureTheory.Measure.Decomposition.RadonNikodym
public import QuantumSystem.Analysis.VonNeumannAlgebra.NormalFunctional
public import QuantumSystem.ForMathlib.Analysis.VonNeumannAlgebra.Commutant
public import QuantumSystem.ForMathlib.MeasureTheory.Function.LpSpace.Linfty

/-!
# The multiplication von Neumann algebra on `L²(μ)`

For a measure `μ`, the **multiplication algebra** on `L²(μ)` is the von Neumann algebra
`{M_f}″` generated by the multiplication operators `M_f`, `f ∈ L∞(μ)`
(`MeasureTheory.Linfty.mulL2`). The multiplication operators commute with each other, so the
algebra is abelian: it lies in its commutant `{M_f}′`
(`VonNeumannAlgebra.multiplicationAlgebra_le_commutant`), and every member commutes with every
multiplication operator.

For σ-finite `μ` the commutant consists exactly of the multiplication operators, so the algebra is
`{M_f}` itself and is **maximal abelian**: it equals its own commutant. The proof tests an operator
`T` commuting with every `M_f` on the vector `ω = √w`, for a strictly positive integrable weight
`w`: the multiplier is `Tω / ω`, bounded by `‖T‖` because `‖T(1_S ω)‖ ≤ ‖T‖ ‖1_S ω‖` for every
measurable `S`, and the vectors `1_S ω` span a dense subspace.

σ-finiteness is the hypothesis under which this is usually stated; it is not a proof convenience,
since without some such hypothesis the commutant can be larger. For counting measure on the Borel
sets of `[0, 1]`, `L²(μ) = ℓ²([0, 1])` and only `∅` is null, so the diagonal operator `1_A` of a
non-Borel set `A` commutes with every `M_f` but is no `M_f`. The sharp condition is Segal's
*localizability* (Segal, *Equivalences of measure spaces*, 1951), which is weaker than σ-finiteness
and is not formalised here.

Every normal positive functional `ψ` is a series `Σₙ ω_{ξₙ}` of vector functionals with
`Σₙ ‖ξₙ‖² < ∞`, so `ψ(M_f) = ∫ f dP` for the finite measure `P = Σₙ |ξₙ|² μ ≪ μ`. For σ-finite `μ`,
where every member of the algebra is some `M_f`, each finite measure `P ≪ μ` defines the normal
functional `ω_P : M_f ↦ ∫ f dP`, which is the vector functional of `ξ_P = √(dP/dμ)`; so
`P ↦ ω_P` is a bijection from the finite measures `P ≪ μ` onto the normal positive functionals.

## Main definitions

* `VonNeumannAlgebra.multiplicationAlgebra μ` — the multiplication algebra `{M_f}″` on `L²(μ)`.
* `VonNeumannAlgebra.densityFun P μ`, `VonNeumannAlgebra.densityVec P μ` — the density
  `dP/dμ` as a real function, and the vector `√(dP/dμ)` of `L²(μ)`.
* `VonNeumannAlgebra.multiplier x` — for σ-finite `μ`, a function `f ∈ L∞(μ)` with `x = M_f`.
* `VonNeumannAlgebra.NormalFunctional.ofMeasure P hP` — for σ-finite `μ`, the normal functional
  `ω_P : M_f ↦ ∫ f dP` of a finite measure `P ≪ μ`.

## Main results

* `VonNeumannAlgebra.mulL2_mem_multiplicationAlgebra`,
  `VonNeumannAlgebra.mulL2_mem_commutant_multiplicationAlgebra` — `M_f` lies in the algebra and in
  its commutant.
* `VonNeumannAlgebra.commute_mulL2_of_mem`, `VonNeumannAlgebra.commute_mulL2_of_mem_commutant` —
  members of the algebra and of its commutant commute with every `M_f`.
* `VonNeumannAlgebra.multiplicationAlgebra_le_commutant` — the algebra is abelian.
* `VonNeumannAlgebra.mem_commutant_multiplicationAlgebra_iff`,
  `VonNeumannAlgebra.mem_multiplicationAlgebra_iff` — for σ-finite `μ`, the members of the
  commutant, and of the algebra, are exactly the multiplication operators `M_f`, `f ∈ L∞(μ)`.
* `VonNeumannAlgebra.commutant_multiplicationAlgebra` — for σ-finite `μ`, the algebra is maximal
  abelian.
* `VonNeumannAlgebra.inner_densityVec_mulL2` — the vector `ξ_P = √(dP/dμ)` represents a finite
  measure `P ≪ μ`: `⟪ξ_P, M_f ξ_P⟫ = ∫ f dP`.
* `VonNeumannAlgebra.exists_measure_of_normalFunctional` — every normal positive functional on the
  algebra is `M_f ↦ ∫ f dP` for a finite measure `P ≪ μ`.
* `VonNeumannAlgebra.NormalFunctional.ofMeasure_apply` — `ω_P(M_f) = ∫ f dP`;
  `VonNeumannAlgebra.NormalFunctional.ofMeasure_eq_ofVector` — `ω_P = ω_{ξ_P}`;
  `VonNeumannAlgebra.NormalFunctional.ofMeasure_apply_one` — `ω_P(1) = P(α)`.
* `VonNeumannAlgebra.NormalFunctional.ofMeasure_inj` — `ω_P = ω_Q ↔ P = Q`.
* `VonNeumannAlgebra.eq_ofMeasure_of_apply` — a normal functional `M_f ↦ ∫ f dP` is `ω_P`;
  `VonNeumannAlgebra.existsUnique_eq_ofMeasure` — every normal positive functional is `ω_P` for a
  unique finite measure `P ≪ μ`.
-/

@[expose] public section

open MeasureTheory Linfty Filter
open scoped ENNReal NNReal VonNeumannAlgebra InnerProductSpace ComplexOrder

namespace VonNeumannAlgebra

variable {α : Type*} [MeasurableSpace α] (μ : Measure α)

/-- The **multiplication algebra** on `L²(μ)`: the von Neumann algebra `{M_f}″` generated by the
multiplication operators `M_f`, `f ∈ L∞(μ)`. -/
noncomputable def multiplicationAlgebra : VonNeumannAlgebra (Lp ℂ 2 μ) :=
  generated (Set.range (mulL2 (μ := μ)))

variable {μ}

/-- The commutant of the multiplication algebra is the commutant `{M_f}′` of the multiplication
operators. -/
lemma commutant_multiplicationAlgebra_eq :
    (multiplicationAlgebra μ)′ = commutantSet (Set.range (mulL2 (μ := μ))) :=
  commutant_generated _

/-- Multiplication operators lie in the commutant of the multiplication algebra. -/
lemma mulL2_mem_commutant_multiplicationAlgebra (f : Lp ℂ ∞ μ) :
    mulL2 f ∈ (multiplicationAlgebra μ)′ := by
  rw [commutant_multiplicationAlgebra_eq, mem_commutantSet_iff]
  rintro _ ⟨g, rfl⟩
  refine ⟨by rw [← map_mul, ← map_mul, mul_comm], ?_⟩
  rw [← map_star, ← map_mul, ← map_mul, mul_comm]

/-- An operator in the commutant of the multiplication algebra commutes with every multiplication
operator. -/
lemma commute_mulL2_of_mem_commutant {T : Lp ℂ 2 μ →L[ℂ] Lp ℂ 2 μ}
    (hT : T ∈ (multiplicationAlgebra μ)′) (f : Lp ℂ ∞ μ) : mulL2 f * T = T * mulL2 f := by
  rw [commutant_multiplicationAlgebra_eq, mem_commutantSet_iff] at hT
  exact (hT _ ⟨f, rfl⟩).1

/-- A member of the multiplication algebra commutes with every multiplication operator. -/
lemma commute_mulL2_of_mem {T : Lp ℂ 2 μ →L[ℂ] Lp ℂ 2 μ} (hT : T ∈ multiplicationAlgebra μ)
    (f : Lp ℂ ∞ μ) : mulL2 f * T = T * mulL2 f :=
  (mem_commutant_iff.mp (mulL2_mem_commutant_multiplicationAlgebra f) T hT).symm

/-- Multiplication operators lie in the multiplication algebra. -/
lemma mulL2_mem_multiplicationAlgebra (f : Lp ℂ ∞ μ) : mulL2 f ∈ multiplicationAlgebra μ :=
  mem_generated_of_mem ⟨f, rfl⟩

/-- The multiplication algebra is abelian: it lies in its commutant. -/
lemma multiplicationAlgebra_le_commutant : multiplicationAlgebra μ ≤ (multiplicationAlgebra μ)′ := by
  refine generated_le ?_
  rintro _ ⟨f, rfl⟩
  exact mulL2_mem_commutant_multiplicationAlgebra f

/-- **`M_{1_S}` is not a scalar** when `S` and `Sᶜ` both have finite nonzero measure: it is the
identity on `1_S` and zero on `1_{Sᶜ}`. -/
lemma mulL2_indicatorConst_ne_smul_one {S : Set α} (hS : MeasurableSet S) (h0 : μ S ≠ 0)
    (htop : μ S ≠ ∞) (h0' : μ Sᶜ ≠ 0) (htop' : μ Sᶜ ≠ ∞) (c : ℂ) :
    mulL2 (indicatorConst (μ := μ) hS (1 : ℂ)) ≠ c • 1 := by
  intro hc
  -- testing on `1_T` shows `1_S = c` almost everywhere on `T`
  have hval : ∀ {T : Set α} (hT : MeasurableSet T) (hTtop : μ T ≠ ∞),
      ∀ᵐ x ∂μ, x ∈ T → S.indicator (fun _ => (1 : ℂ)) x = c := by
    intro T hT hTtop
    have h : ⇑(mulL2 (indicatorConst hS (1 : ℂ)) (indicatorConstLp 2 hT hTtop (1 : ℂ))) =ᵐ[μ]
        ⇑(c • indicatorConstLp 2 hT hTtop (1 : ℂ)) := by
      rw [hc, smul_apply, one_apply_eq_self]
    filter_upwards [h, coeFn_mulL2 (indicatorConst hS (1 : ℂ)) (indicatorConstLp 2 hT hTtop (1 : ℂ)),
      coeFn_indicatorConst (μ := μ) hS (1 : ℂ), indicatorConstLp_coeFn (p := 2) (hs := hT)
        (hμs := hTtop) (c := (1 : ℂ)), Lp.coeFn_smul c (indicatorConstLp 2 hT hTtop (1 : ℂ))]
      with x h₁ h₂ h₃ h₄ h₅ hx
    rw [h₂, Pi.mul_apply, h₃, h₄, Set.indicator_of_mem hx, mul_one] at h₁
    rw [h₁, h₅, Pi.smul_apply, h₄, Set.indicator_of_mem hx, smul_eq_mul, mul_one]
  have h1 : c = 1 := by
    by_contra hne
    refine h0 (measure_eq_zero_iff_ae_notMem.mpr ?_)
    filter_upwards [hval hS htop] with x hx hxS
    exact hne ((hx hxS).symm.trans (Set.indicator_of_mem hxS _))
  have h2 : c = 0 := by
    by_contra hne
    refine h0' (measure_eq_zero_iff_ae_notMem.mpr ?_)
    filter_upwards [hval hS.compl htop'] with x hx hxS
    exact hne ((hx hxS).symm.trans (Set.indicator_of_notMem hxS _))
  exact one_ne_zero (h1.symm.trans h2)

/-- **The multiplication algebra is not a factor** when `μ` splits: if some measurable `S` and its
complement both have finite nonzero measure, `M_{1_S}` lies in the centre and is not a scalar. -/
theorem not_isFactor_multiplicationAlgebra {S : Set α} (hS : MeasurableSet S) (h0 : μ S ≠ 0)
    (htop : μ S ≠ ∞) (h0' : μ Sᶜ ≠ 0) (htop' : μ Sᶜ ≠ ∞) :
    ¬ IsFactor (multiplicationAlgebra μ) := fun h =>
  let ⟨c, hc⟩ := h _ (mulL2_mem_multiplicationAlgebra (indicatorConst hS (1 : ℂ)))
    (mulL2_mem_commutant_multiplicationAlgebra _)
  mulL2_indicatorConst_ne_smul_one hS h0 htop h0' htop' c hc

/-- A vector orthogonal to every `1_S ω`, for an almost everywhere nonvanishing `ω ∈ L²`, is `0`. -/
lemma eq_zero_of_forall_inner_mulL2_indicatorConst {ω v : Lp ℂ 2 μ} (hω : ∀ᵐ x ∂μ, ω x ≠ 0)
    (h : ∀ S (hS : MeasurableSet S), ⟪mulL2 (indicatorConst hS (1 : ℂ)) ω, v⟫_ℂ = 0) : v = 0 := by
  have hzero : (fun x => ⟪ω x, v x⟫_ℂ) =ᵐ[μ] 0 := by
    refine (MeasureTheory.L2.integrable_inner (𝕜 := ℂ) ω v).ae_eq_zero_of_forall_setIntegral_eq_zero
      fun S hS _ => ?_
    rw [← h S hS, MeasureTheory.L2.inner_def, ← integral_indicator hS]
    refine integral_congr_ae ?_
    filter_upwards [coeFn_mulL2 (indicatorConst hS (1 : ℂ)) ω,
      coeFn_indicatorConst (μ := μ) hS (1 : ℂ)] with x h₁ h₂
    rw [h₁, Pi.mul_apply, h₂]
    by_cases hx : x ∈ S <;> simp [hx]
  refine Lp.ext ?_
  filter_upwards [hzero, hω, Lp.coeFn_zero ℂ 2 μ] with x h₁ h₂ h₃
  rw [h₃]
  simpa [h₂] using h₁

variable [SigmaFinite μ]

/-- **The commutant of the multiplication operators** (σ-finite `μ`): an operator commuting with
every `M_f` is `M_h` for some `h ∈ L∞(μ)`. -/
lemma mem_commutant_multiplicationAlgebra_iff {T : Lp ℂ 2 μ →L[ℂ] Lp ℂ 2 μ} :
    T ∈ (multiplicationAlgebra μ)′ ↔ ∃ f : Lp ℂ ∞ μ, T = mulL2 f := by
  refine ⟨fun hT => ?_, by rintro ⟨f, rfl⟩; exact mulL2_mem_commutant_multiplicationAlgebra f⟩
  -- an almost everywhere nonvanishing vector `ω`, cyclic for the multiplication operators
  obtain ⟨ω, hωne⟩ := L2.exists_ae_ne_zero (μ := μ)
  set k := T ω
  set C := ‖T‖
  -- `|Tω| ≤ ‖T‖ |ω|` almost everywhere, by testing on indicators
  have hbound : ∀ᵐ x ∂μ, ‖k x‖ ≤ C * ‖ω x‖ := by
    have hle : (fun x => ‖k x‖ₑ ^ 2) ≤ᵐ[μ] fun x => ENNReal.ofReal C ^ 2 * ‖ω x‖ₑ ^ 2 := by
      refine ae_le_of_forall_setLIntegral_le_of_sigmaFinite (measurable_enorm_sq k) fun s hs _ => ?_
      rw [lintegral_const_mul _ (measurable_enorm_sq ω), ← withDensity_apply _ hs,
        ← withDensity_apply _ hs, ← ofReal_measureReal (measure_ne_top _ _),
        ← ofReal_measureReal (measure_ne_top _ _), ← norm_mulL2_indicatorConst_sq k hs,
        ← norm_mulL2_indicatorConst_sq ω hs, ← ENNReal.ofReal_pow (norm_nonneg _),
        ← ENNReal.ofReal_mul (by positivity)]
      refine ENNReal.ofReal_le_ofReal ?_
      rw [← mul_pow]
      refine pow_le_pow_left₀ (norm_nonneg _) ?_ 2
      rw [← _root_.mul_apply_eq_comp, commute_mulL2_of_mem_commutant hT, _root_.mul_apply_eq_comp]
      exact T.le_opNorm _
    filter_upwards [hle] with x hx
    rw [← mul_pow, ENNReal.pow_le_pow_left_iff two_ne_zero, ← ofReal_norm, ← ofReal_norm,
      ← ENNReal.ofReal_mul (norm_nonneg _)] at hx
    exact (ENNReal.ofReal_le_ofReal_iff (by positivity)).mp hx
  -- the multiplier `h = Tω / ω`
  set F₀ : α → ℂ := fun x => k x / ω x
  have hF : MemLp F₀ ∞ μ := by
    refine memLp_top_of_bound ((Lp.stronglyMeasurable k).measurable.div
      (Lp.stronglyMeasurable ω).measurable).aestronglyMeasurable C ?_
    filter_upwards [hbound, hωne] with x h₁ h₂
    rw [norm_div, div_le_iff₀ (norm_pos_iff.mpr h₂)]
    exact h₁
  refine ⟨hF.toLp F₀, ?_⟩
  set A := T - mulL2 (hF.toLp F₀)
  have hAω : A ω = 0 := by
    refine Lp.ext ?_
    filter_upwards [Lp.coeFn_sub (T ω) (mulL2 (hF.toLp F₀) ω), coeFn_mulL2 (hF.toLp F₀) ω,
      hF.coeFn_toLp, hωne, Lp.coeFn_zero ℂ 2 μ] with x h₁ h₂ h₃ h₄ h₅
    rw [_root_.sub_apply, h₁, Pi.sub_apply, h₂, Pi.mul_apply, h₃, h₅]
    simp [F₀, k, h₄]
  have hAcomm : ∀ f, mulL2 f * A = A * mulL2 f := fun f => by
    rw [mul_sub, sub_mul, commute_mulL2_of_mem_commutant hT f, ← map_mul, ← map_mul, mul_comm]
  have hA : star A = 0 := by
    ext1 v
    refine eq_zero_of_forall_inner_mulL2_indicatorConst hωne fun S hS => ?_
    rw [ContinuousLinearMap.star_eq_adjoint, ContinuousLinearMap.adjoint_inner_right,
      ← _root_.mul_apply_eq_comp, ← hAcomm, _root_.mul_apply_eq_comp,
      hAω, map_zero, inner_zero_left]
  exact sub_eq_zero.mp (star_eq_zero.mp hA)

/-- **The multiplication algebra consists of multiplication operators** (σ-finite `μ`): its
members are exactly the `M_f`, `f ∈ L∞(μ)`. -/
lemma mem_multiplicationAlgebra_iff {T : Lp ℂ 2 μ →L[ℂ] Lp ℂ 2 μ} :
    T ∈ multiplicationAlgebra μ ↔ ∃ f : Lp ℂ ∞ μ, T = mulL2 f :=
  ⟨fun hT => mem_commutant_multiplicationAlgebra_iff.mp (multiplicationAlgebra_le_commutant hT),
    by rintro ⟨f, rfl⟩; exact mulL2_mem_multiplicationAlgebra f⟩

/-- **The multiplication algebra is maximal abelian** (σ-finite `μ`): it is its own commutant. -/
theorem commutant_multiplicationAlgebra :
    (multiplicationAlgebra μ)′ = multiplicationAlgebra μ := by
  refine le_antisymm (fun T hT => ?_) multiplicationAlgebra_le_commutant
  obtain ⟨f, rfl⟩ := mem_commutant_multiplicationAlgebra_iff.mp hT
  exact mulL2_mem_multiplicationAlgebra f

/-! ### Density vectors and normal functionals -/

/-- The density `p = dP/dμ` as a real function. -/
noncomputable abbrev densityFun (P : Measure α) (μ : Measure α) (x : α) : ℝ :=
  (P.rnDeriv μ x).toReal

/-- The density `dP/dμ`, as a real function, is measurable. -/
lemma measurable_densityFun (P μ : Measure α) : Measurable (densityFun P μ) :=
  (Measure.measurable_rnDeriv P μ).ennreal_toReal

/-- The vector `ξ_P = √(dP/dμ)` of `L²(μ)` representing a finite measure `P`. It sees only the
part of `P` absolutely continuous with respect to `μ`, so it represents `P` itself when `P ≪ μ`
(`VonNeumannAlgebra.inner_densityVec_mulL2`). -/
noncomputable def densityVec (P : Measure α) [IsFiniteMeasure P] (μ : Measure α) : Lp ℂ 2 μ :=
  MemLp.toLp (fun x => ((Real.sqrt (densityFun P μ x) : ℝ) : ℂ)) (by
    rw [memLp_two_iff_integrable_sq_norm
      (measurable_densityFun P μ).sqrt.complex_ofReal.aestronglyMeasurable]
    refine (Measure.integrable_toReal_rnDeriv (μ := P) (ν := μ)).congr
      (Eventually.of_forall fun x => ?_)
    simp [Real.sq_sqrt ENNReal.toReal_nonneg])

/-- Almost everywhere, `densityVec P μ` is the function `√(dP/dμ)` (as a complex number). -/
lemma coeFn_densityVec (P : Measure α) [IsFiniteMeasure P] (μ : Measure α) :
    ⇑(densityVec P μ) =ᵐ[μ] fun x => ((Real.sqrt (densityFun P μ x) : ℝ) : ℂ) :=
  MemLp.coeFn_toLp _

omit [SigmaFinite μ] in
/-- `|ξ_P|² μ = P` for `P ≪ μ`, whenever `P` has a Lebesgue decomposition with respect to `μ`
(automatic for σ-finite `μ`). -/
lemma withDensity_enorm_sq_densityVec (P : Measure α) [IsFiniteMeasure P]
    [P.HaveLebesgueDecomposition μ] (hP : P ≪ μ) :
    μ.withDensity (fun x => ‖densityVec P μ x‖ₑ ^ 2) = P := by
  calc μ.withDensity (fun x => ‖densityVec P μ x‖ₑ ^ 2) = μ.withDensity (P.rnDeriv μ) :=
        withDensity_congr_ae ?_
    _ = P := Measure.withDensity_rnDeriv_eq P μ hP
  filter_upwards [coeFn_densityVec P μ, Measure.rnDeriv_lt_top P μ] with x h₁ h₂
  rw [h₁, ← ofReal_norm, Complex.norm_real, Real.norm_of_nonneg (Real.sqrt_nonneg _),
    ← ENNReal.ofReal_pow (Real.sqrt_nonneg _), Real.sq_sqrt ENNReal.toReal_nonneg,
    ENNReal.ofReal_toReal h₂.ne]

omit [SigmaFinite μ] in
/-- **`ξ_P` represents `P`**: for `P ≪ μ`, `⟪ξ_P, M_f ξ_P⟫ = ∫ f dP` for every `f ∈ L∞(μ)`,
whenever `P` has a Lebesgue decomposition with respect to `μ` (automatic for σ-finite `μ`). -/
lemma inner_densityVec_mulL2 (P : Measure α) [IsFiniteMeasure P] [P.HaveLebesgueDecomposition μ]
    (hP : P ≪ μ) (f : Lp ℂ ∞ μ) :
    ⟪densityVec P μ, mulL2 f (densityVec P μ)⟫_ℂ = ∫ x, f x ∂P := by
  rw [inner_mulL2_self_eq_integral, withDensity_enorm_sq_densityVec P hP]

omit [SigmaFinite μ] in
/-- **Normal functionals of the multiplication algebra are finite measures**: every normal
positive functional `ψ` on `L∞(μ)` is `M_f ↦ ∫ f dP` for a finite measure `P ≪ μ`. Writing
`ψ = Σₙ ω_{ξₙ}` with `Σₙ ‖ξₙ‖² < ∞`, the measure is `P = Σₙ |ξₙ|² μ`. -/
lemma exists_measure_of_normalFunctional (ψ : (multiplicationAlgebra μ).NormalFunctional) :
    ∃ (P : Measure α) (_ : IsFiniteMeasure P), P ≪ μ ∧
      ∀ f : Lp ℂ ∞ μ, ψ.1 ⟨mulL2 f, mulL2_mem_multiplicationAlgebra f⟩ = ∫ x, f x ∂P := by
  obtain ⟨ξ, hξ⟩ := isNormal_iff_exists_lp.mp ψ.2
  set ν : ℕ → Measure α := fun n => μ.withDensity fun x => ‖ξ n x‖ₑ ^ 2
  have hone : mulL2 (indicatorConst (μ := μ) MeasurableSet.univ (1 : ℂ)) = 1 := by
    rw [← map_one mulL2]
    congr 1
    refine Lp.ext ?_
    filter_upwards [coeFn_indicatorConst (μ := μ) MeasurableSet.univ (1 : ℂ), coeFn_one (R := ℂ)]
      with x h₁ h₂
    rw [h₁, h₂, Set.indicator_univ, Pi.one_apply]
  have hν : ∀ n, ν n Set.univ = ENNReal.ofReal (‖ξ n‖ ^ 2) := fun n => by
    rw [← ofReal_measureReal (measure_ne_top _ _), ← norm_mulL2_indicatorConst_sq _ MeasurableSet.univ,
      hone]
    rfl
  have hsum := lp.hasSum_norm (p := 2) (by norm_num) ξ
  simp only [ENNReal.toReal_ofNat, Real.rpow_two] at hsum
  have hfin : Measure.sum ν Set.univ ≠ ⊤ := by
    rw [Measure.sum_apply _ MeasurableSet.univ, funext hν,
      ← ENNReal.ofReal_tsum_of_nonneg (fun n => by positivity) hsum.summable]
    exact ENNReal.ofReal_ne_top
  have : IsFiniteMeasure (Measure.sum ν) := ⟨hfin.lt_top⟩
  refine ⟨Measure.sum ν, inferInstance,
    Measure.absolutelyContinuous_sum_left fun n => withDensity_absolutelyContinuous _ _, fun f => ?_⟩
  have hint : Integrable (⇑f) (Measure.sum ν) :=
    Integrable.of_bound (Lp.stronglyMeasurable f).aestronglyMeasurable ‖f‖
      ((Measure.absolutelyContinuous_sum_left fun n => withDensity_absolutelyContinuous _ _).ae_le
        (ae_norm_le_norm f))
  refine (hξ ⟨mulL2 f, mulL2_mem_multiplicationAlgebra f⟩).unique ?_
  simp only [inner_mulL2_self_eq_integral]
  exact hasSum_integral_measure hint

/-! ### The normal functional of a finite measure -/

/-- The **multiplier** of a member `x` of the multiplication algebra of a σ-finite `μ`: a function
`f ∈ L∞(μ)` with `x = M_f` (`VonNeumannAlgebra.mulL2_multiplier`), which exists by
`VonNeumannAlgebra.mem_multiplicationAlgebra_iff`. -/
noncomputable def multiplier (x : multiplicationAlgebra μ) : Lp ℂ ∞ μ :=
  (mem_multiplicationAlgebra_iff.mp x.2).choose

/-- A member `x` of the multiplication algebra is multiplication by its multiplier. -/
lemma mulL2_multiplier (x : multiplicationAlgebra μ) : mulL2 (multiplier x) = x :=
  (mem_multiplicationAlgebra_iff.mp x.2).choose_spec.symm

/-- Integrating the multiplier of `x` against `P ≪ μ` gives `⟪ξ_P, x ξ_P⟫`. -/
lemma integral_multiplier_eq_inner (P : Measure α) [IsFiniteMeasure P] (hP : P ≪ μ)
    (x : multiplicationAlgebra μ) :
    ∫ a, multiplier x a ∂P = ⟪densityVec P μ, (x : Lp ℂ 2 μ →L[ℂ] Lp ℂ 2 μ) (densityVec P μ)⟫_ℂ := by
  rw [← inner_densityVec_mulL2 P hP, mulL2_multiplier]

/-- The **normal functional of a finite measure** `P ≪ μ` on the multiplication algebra of a
σ-finite `μ`: `ω_P(M_f) = ∫ f dP` (`VonNeumannAlgebra.NormalFunctional.ofMeasure_apply`). Every
member of the algebra is some `M_f` (`VonNeumannAlgebra.mem_multiplicationAlgebra_iff`), and since
`P ≪ μ` the integral depends only on the class `f ∈ L∞(μ)`. The functional is positive and normal
because it agrees with the vector functional of `ξ_P = √(dP/dμ)`
(`VonNeumannAlgebra.NormalFunctional.ofMeasure_eq_ofVector`). -/
noncomputable def NormalFunctional.ofMeasure (P : Measure α) [IsFiniteMeasure P] (hP : P ≪ μ) :
    (multiplicationAlgebra μ).NormalFunctional :=
  ⟨PositiveLinearMap.mk₀
    { toFun := fun x => ∫ a, multiplier x a ∂P
      map_add' := fun x y => by
        simp only [integral_multiplier_eq_inner P hP]
        exact map_add ((multiplicationAlgebra μ).vectorFunctional (densityVec P μ)) x y
      map_smul' := fun c x => by
        simp only [integral_multiplier_eq_inner P hP]
        exact map_smul ((multiplicationAlgebra μ).vectorFunctional (densityVec P μ)) c x }
    fun x hx => by
      simp only [LinearMap.coe_mk, AddHom.coe_mk, integral_multiplier_eq_inner P hP]
      exact map_nonneg ((multiplicationAlgebra μ).vectorFunctional (densityVec P μ)) hx,
    ((multiplicationAlgebra μ).isNormal_vectorFunctional (densityVec P μ)).congr fun T =>
      (integral_multiplier_eq_inner P hP _).symm⟩

namespace NormalFunctional

variable (P : Measure α) [IsFiniteMeasure P] (hP : P ≪ μ)

/-- **`ω_P` integrates against `P`**: `ω_P(M_f) = ∫ f dP` for every `f ∈ L∞(μ)`. -/
lemma ofMeasure_apply (f : Lp ℂ ∞ μ) :
    (ofMeasure P hP).1 ⟨mulL2 f, mulL2_mem_multiplicationAlgebra f⟩ = ∫ x, f x ∂P :=
  (integral_multiplier_eq_inner P hP _).trans (inner_densityVec_mulL2 P hP f)

/-- **`ω_P` is a vector functional**: `ω_P = ω_{ξ_P}` for `ξ_P = √(dP/dμ)`. -/
lemma ofMeasure_eq_ofVector : ofMeasure P hP = ofVector _ (densityVec P μ) :=
  Subtype.ext (PositiveLinearMap.ext fun x => integral_multiplier_eq_inner P hP x)

/-- The mass of `ω_P` is the mass of `P`: `ω_P(1) = P(α)`. -/
lemma ofMeasure_apply_one : (ofMeasure P hP).1 1 = (P.real Set.univ : ℂ) := by
  have h1 : (1 : multiplicationAlgebra μ) = ⟨mulL2 1, mulL2_mem_multiplicationAlgebra 1⟩ :=
    Subtype.ext (map_one mulL2).symm
  rw [h1, ofMeasure_apply, integral_congr_ae (hP.ae_le coeFn_one)]
  simp

variable {P hP} in
/-- **Measures are determined by their normal functionals**: for finite `P, Q ≪ μ`,
`ω_P = ω_Q ↔ P = Q`. -/
lemma ofMeasure_inj {Q : Measure α} [IsFiniteMeasure Q] {hQ : Q ≪ μ} :
    ofMeasure P hP = ofMeasure Q hQ ↔ P = Q := by
  refine ⟨fun h => Measure.ext fun s hs => ?_, fun h => by subst h; rfl⟩
  have hint : ∀ (R : Measure α) [IsFiniteMeasure R] (hR : R ≪ μ),
      (ofMeasure R hR).1 ⟨mulL2 (indicatorConst hs (1 : ℂ)), mulL2_mem_multiplicationAlgebra _⟩ =
        (R.real s : ℂ) := fun R _ hR => by
    rw [ofMeasure_apply, integral_congr_ae (hR.ae_le (coeFn_indicatorConst hs (1 : ℂ))),
      integral_indicator_const _ hs]
    simp
  have hs' := hint P hP
  rw [h, hint Q hQ, Complex.ofReal_inj, measureReal_def, measureReal_def] at hs'
  exact (ENNReal.toReal_eq_toReal_iff' (measure_ne_top P s) (measure_ne_top Q s)).mp hs'.symm

end NormalFunctional

/-- **A normal functional with the values of `P` is `ω_P`**: if `ψ(M_f) = ∫ f dP` for every
`f ∈ L∞(μ)`, for a finite measure `P ≪ μ`, then `ψ = ω_P`. -/
lemma eq_ofMeasure_of_apply {ψ : (multiplicationAlgebra μ).NormalFunctional}
    {P : Measure α} [IsFiniteMeasure P] (hP : P ≪ μ)
    (hψ : ∀ f : Lp ℂ ∞ μ, ψ.1 ⟨mulL2 f, mulL2_mem_multiplicationAlgebra f⟩ = ∫ x, f x ∂P) :
    ψ = NormalFunctional.ofMeasure P hP := by
  refine Subtype.ext (PositiveLinearMap.ext fun x => ?_)
  obtain ⟨f, hf⟩ := mem_multiplicationAlgebra_iff.mp x.2
  obtain rfl : x = ⟨mulL2 f, mulL2_mem_multiplicationAlgebra f⟩ := Subtype.ext hf
  exact (hψ f).trans (NormalFunctional.ofMeasure_apply P hP f).symm

/-- **Normal functionals of the multiplication algebra are measures**: every normal positive
functional is `ψ = ω_P` for a unique finite measure `P ≪ μ`. -/
theorem existsUnique_eq_ofMeasure (ψ : (multiplicationAlgebra μ).NormalFunctional) :
    ∃! P : Measure α, ∃ (_ : IsFiniteMeasure P) (hP : P ≪ μ), ψ = NormalFunctional.ofMeasure P hP := by
  obtain ⟨P, _, hP, hψ⟩ := exists_measure_of_normalFunctional ψ
  refine ⟨P, ⟨inferInstance, hP, eq_ofMeasure_of_apply hP hψ⟩, ?_⟩
  rintro Q ⟨_, hQ, rfl⟩
  exact NormalFunctional.ofMeasure_inj.mp (eq_ofMeasure_of_apply hP hψ)

end VonNeumannAlgebra
