module

public import Mathlib.Analysis.CStarAlgebra.Classes
public import Mathlib.Order.DirectedInverseSystem

/-!
# Local nets of C⋆-algebras

This file contains the abstract **local net** data in Haag–Kastler form: the regions form an
abstract *causal index set* — a partially ordered set `K` (in the literature, the open bounded
regions of spacetime ordered by inclusion) equipped with a causal orthogonality relation
`O₁ ⟂ O₂` (`CausalOrthogonality`, abstracting spacelike separation) — and each region is assigned
a local C⋆-algebra, with functorial isotony embeddings and locality. Lattice (quantum spin system)
nets are the instance `K = Finset sites` with `⟂ = Disjoint`; nothing in this file assumes
directedness, so non-directed index sets (wedges, spacelike cones) are also in scope.

The file deliberately stops at the net-level axioms; in particular, additivity/generation axioms
(e.g. `𝔄(O₁ ⊔ O₂)` being generated by the images of `𝔄(O₁)` and `𝔄(O₂)`, as in tensor-product
spin-system nets) are intentionally out of scope here and belong to concrete instantiations.

The quasi-local algebra built from a net lives in `LocalNet.QuasiLocalAlgebra` (and requires the
index set to be directed); covariance data and its action live in `LocalNet.Covariance` /
`LocalNet.QuasiLocalAlgebra`.
-/

@[expose] public section

/-! ### Causal index sets -/

/-- A **causal orthogonality relation** on an index set of regions: `O₁ ⟂ O₂` abstracts causal
    (spacelike) disjointness of regions, the relation under which the Haag–Kastler locality axiom
    applies. It is symmetric and hereditary under shrinking regions.

    Of the causal-index-set axiomatizations in the literature (Roberts; Guido–Longo–Roberts–Verch)
    this class keeps only symmetry and heredity — the minimal core needed for locality, the
    quasi-local algebra, and the split property. The existence of causal complements
    (`∀ O₁, ∃ O₂, O₁ ⟂ O₂`), needed for DHR sector theory, is intentionally not required.

    The relation is *not* required to be irreflexive: `O ⟂ O` legitimately holds for degenerate
    regions (e.g. the empty lattice region) and forces `𝔄(O)` to be commutative. For Minkowski
    double cones one instantiates `⟂` with spacelike separation — note this is *not* set
    disjointness (disjoint timelike-separated regions are not causally orthogonal), which is why
    the relation is carried as data rather than derived from the order. -/
class CausalOrthogonality (K : Type*) [Preorder K] where
  /-- The causal orthogonality relation `O₁ ⟂ O₂` on regions. -/
  Orthogonal : K → K → Prop
  /-- Causal orthogonality is symmetric. -/
  orthogonal_symm : ∀ ⦃O₁ O₂ : K⦄, Orthogonal O₁ O₂ → Orthogonal O₂ O₁
  /-- Causal orthogonality is hereditary under shrinking the left region. -/
  orthogonal_mono_left : ∀ ⦃O₀ O₁ O₂ : K⦄, O₀ ≤ O₁ → Orthogonal O₁ O₂ → Orthogonal O₀ O₂

namespace CausalOrthogonality

/-- `O₁ ⟂ O₂` : the regions `O₁` and `O₂` are causally orthogonal (spacelike separated).

    The token `⟂` is also used globally by Mathlib for `Submodule.IsOrtho` at precedence 50;
    this scoped notation is declared at the same precedence so that the two coexist by
    type-directed disambiguation. -/
scoped infixl:50 " ⟂ " => CausalOrthogonality.Orthogonal

variable {K : Type*} [Preorder K] [CausalOrthogonality K]

/-- Causal orthogonality is symmetric (dot-notation form). -/
theorem Orthogonal.symm {O₁ O₂ : K} (h : O₁ ⟂ O₂) : O₂ ⟂ O₁ :=
  orthogonal_symm h

/-- Causal orthogonality is hereditary under shrinking the left region. -/
theorem Orthogonal.mono_left {O₀ O₁ O₂ : K} (h₀ : O₀ ≤ O₁) (h : O₁ ⟂ O₂) : O₀ ⟂ O₂ :=
  orthogonal_mono_left h₀ h

/-- Causal orthogonality is hereditary under shrinking the right region. -/
theorem Orthogonal.mono_right {O₁ O₂ O₃ : K} (h₀ : O₃ ≤ O₂) (h : O₁ ⟂ O₂) : O₁ ⟂ O₃ :=
  (h.symm.mono_left h₀).symm

/-- Causal orthogonality is hereditary under shrinking both regions. -/
theorem Orthogonal.mono {O₁' O₁ O₂' O₂ : K} (h₁ : O₁' ≤ O₁) (h₂ : O₂' ≤ O₂) (h : O₁ ⟂ O₂) :
    O₁' ⟂ O₂' :=
  (h.mono_left h₁).mono_right h₂

end CausalOrthogonality

open scoped CausalOrthogonality

/-- On the finite regions of a lattice of sites, causal orthogonality is plain set disjointness:
    a lattice net is kinematical (equal-time), so "spacelike separated" degenerates to "disjoint in
    space" (Naaijkens 2012 §3.4). -/
instance {α : Type*} : CausalOrthogonality (Finset α) where
  Orthogonal := Disjoint
  orthogonal_symm _ _ h := h.symm
  orthogonal_mono_left _ _ _ h₀ h := h.mono_left h₀

/-- A **local net of C⋆-algebras** over a causal index set `K` — a partially ordered set of
    regions with a causal orthogonality relation `⟂` (`CausalOrthogonality`): the assignment
    `O ↦ 𝔄(O)` together with isotony embeddings `incl : 𝔄(O) →⋆ₐ[ℂ] 𝔄(O')` for `O ≤ O'`,
    functorial (`incl_refl`/`incl_trans`) and local (`locality`). This is the Haag–Kastler net
    structure over an abstract index set, *without* the injectivity requirement on the isotony
    embeddings; the literature's net (Naaijkens 2012 §3.4) is `LocalNet` together with the
    `Faithful` class, which carries that requirement. Lattice nets are the instance
    `K = Finset sites` with `⟂ = Disjoint`. -/
structure LocalNet (K : Type*) [PartialOrder K] [CausalOrthogonality K] where
  /-- The local C⋆-algebra `𝔄(O)` assigned to a region. For any self-orthogonal region `O ⟂ O`
      (e.g. the empty lattice region) the axioms force `𝔄(O)` to be commutative (instantiate
      `locality` at `O₁ = O₂ = O`) but do *not* force it to be trivial: the literature's
      `𝔄(∅) = ℂ·1` is not required and must be imposed by a concrete instantiation when needed. -/
  algebra : K → Type*
  /-- Each local algebra is a (complex) C⋆-algebra. -/
  [algebraCStar : ∀ O, CStarAlgebra (algebra O)]
  /-- **Isotony**: for `O ≤ O'` an inclusion of local algebras as a unital `*`-homomorphism. -/
  incl : ∀ {O O' : K}, O ≤ O' → (algebra O →⋆ₐ[ℂ] algebra O')
  /-- The identity inclusion `O ≤ O` acts as the identity. -/
  incl_refl : ∀ {O : K} (x : algebra O), incl (le_refl O) x = x
  /-- **Functoriality**: the inclusions compose, so the net is a directed system. -/
  incl_trans : ∀ {O₁ O₂ O₃ : K} (h₁₂ : O₁ ≤ O₂) (h₂₃ : O₂ ≤ O₃) (x : algebra O₁),
      incl h₂₃ (incl h₁₂ x) = incl (h₁₂.trans h₂₃) x
  /-- **Locality** (microcausality, Einstein causality): observables localised in causally
      orthogonal regions commute inside any common larger region. -/
  locality : ∀ {O₁ O₂ O : K} (h₁ : O₁ ≤ O) (h₂ : O₂ ≤ O), O₁ ⟂ O₂ →
      ∀ (x : algebra O₁) (y : algebra O₂), Commute (incl h₁ x) (incl h₂ y)

namespace LocalNet

attribute [instance] algebraCStar

section SemilatticeSup

variable {K : Type*} [SemilatticeSup K] [CausalOrthogonality K]

/-- Smart constructor for `LocalNet` over a join-semilattice of regions, taking locality only
    inside the canonical join region `O₁ ⊔ O₂`: given `incl_trans`, commutation there pushes
    forward along `incl : 𝔄(O₁ ⊔ O₂) →⋆ₐ[ℂ] 𝔄(O)` to any common superregion `O`, so the join case
    is equivalent to the general `locality` field. For lattice nets (`K = Finset sites`) the join
    is the union of regions. -/
def mk' (algebra : K → Type*) [algebraCStar : ∀ O, CStarAlgebra (algebra O)]
    (incl : ∀ {O O' : K}, O ≤ O' → (algebra O →⋆ₐ[ℂ] algebra O'))
    (incl_refl : ∀ {O : K} (x : algebra O), incl (le_refl O) x = x)
    (incl_trans : ∀ {O₁ O₂ O₃ : K} (h₁₂ : O₁ ≤ O₂) (h₂₃ : O₂ ≤ O₃) (x : algebra O₁),
      incl h₂₃ (incl h₁₂ x) = incl (h₁₂.trans h₂₃) x)
    (locality_sup : ∀ {O₁ O₂ : K}, O₁ ⟂ O₂ →
      ∀ (x : algebra O₁) (y : algebra O₂),
        Commute (incl le_sup_left x) (incl le_sup_right y)) :
    LocalNet K where
  algebra := algebra
  incl := incl
  incl_refl := incl_refl
  incl_trans := incl_trans
  locality h₁ h₂ hortho x y := by
    have h := (locality_sup hortho x y).map (incl (sup_le h₁ h₂))
    rwa [incl_trans, incl_trans] at h

end SemilatticeSup

variable {K : Type*} [PartialOrder K] [CausalOrthogonality K] (N : LocalNet K)

/-- The net forms a directed system of `*`-algebras: the isotony embeddings compose and the
    identity inclusion is the identity. -/
instance directedSystem :
    DirectedSystem N.algebra (fun _ _ h => ⇑(N.incl h)) where
  map_self _ x := N.incl_refl x
  map_map _ _ _ hij hjk x := N.incl_trans hij hjk x

/-! ### Faithful nets

A net is *faithful* when its isotony embeddings are injective (the standard AQFT
non-degeneracy condition). The quasi-local C⋆-norm built from this hypothesis lives in
`LocalNet.QuasiLocalAlgebra`.
-/

/-- A local net is **faithful** when all its isotony embeddings are injective. In the standard
    AQFT definition the isotony embeddings are *injective* unital `*`-homomorphisms (Naaijkens 2012
    §3.4), so a faithful local net — `LocalNet` together with `Faithful` — is the literature's net.
    Carried as a typeclass rather than a structure field so algebraic constructions can state the
    non-degeneracy hypothesis only where they need it. -/
class Faithful {K : Type*} [PartialOrder K] [CausalOrthogonality K] (N : LocalNet K) : Prop where
  /-- Every isotony embedding of the net is injective. -/
  incl_injective : ∀ {O O' : K} (h : O ≤ O'), Function.Injective (N.incl h)

/-! ### Region-equality transport -/

/-- Transport a local algebra along an equality of regions, as a `*`-isomorphism. Used to identify
    local algebras whose regions are propositionally equal. -/
def algebraCongr {O O' : K} (h : O = O') : N.algebra O ≃⋆ₐ[ℂ] N.algebra O' := by
  subst h; exact StarAlgEquiv.refl

/-- The isotony embeddings are natural with respect to the region-equality transport. -/
lemma incl_algebraCongr {O₁ O₂ O₁' O₂' : K} (e₁ : O₁ = O₁') (e₂ : O₂ = O₂')
    (h : O₁ ≤ O₂) (h' : O₁' ≤ O₂') (x : N.algebra O₁) :
    N.algebraCongr e₂ (N.incl h x) = N.incl h' (N.algebraCongr e₁ x) := by
  subst e₁; subst e₂; rfl

/-- Transports along composable region equalities compose. -/
@[simp] lemma algebraCongr_trans {O₁ O₂ O₃ : K} (h₁ : O₁ = O₂) (h₂ : O₂ = O₃)
    (x : N.algebra O₁) :
    N.algebraCongr h₂ (N.algebraCongr h₁ x) = N.algebraCongr (h₁.trans h₂) x := by
  subst h₁; subst h₂; rfl

/-- A transport along a reflexive region equality is the identity. -/
@[simp] lemma algebraCongr_self {O : K} (h : O = O) (x : N.algebra O) :
    N.algebraCongr h x = x := by
  rw [Subsingleton.elim h rfl]; rfl

/-- Cancelling a transport against a target value moves it to the other side. -/
lemma algebraCongr_eq_iff {O O' : K} (h : O = O') (x : N.algebra O)
    (y : N.algebra O') : N.algebraCongr h x = y ↔ x = N.algebraCongr h.symm y := by
  subst h; simp

end LocalNet
