module

public import Mathlib.Analysis.CStarAlgebra.Classes
public import Mathlib.Order.DirectedInverseSystem

/-!
# Local nets of C⋆-algebras

This file contains the abstract **local net** data in Haag–Kastler form: the regions form an
abstract *causal index set* — an ordered set `K` of regions (in the literature, the open bounded
regions of spacetime ordered by inclusion) equipped with a causal orthogonality relation
`O₁ ⟂ O₂` (`CausalOrthogonality`, abstracting spacelike separation) — and each region is assigned
a local C⋆-algebra, with functorial isotony embeddings and locality. Lattice (quantum spin system)
nets are the instance `K = Finset sites` with `⟂ = Disjoint`. The literature's third axiom on the
index set — every region admits a causally disjoint one — is the mixin `CausalIndexSet`, kept
separate because not every index family of the corpus satisfies it.

The order is carried as a `Preorder` throughout, not a `PartialOrder`: the literature's index sets
are ordered by inclusion and so are partial orders, but antisymmetry is used nowhere in this
development — not by the net axioms, not by the quasi-local algebra, not by the split property — so
demanding it would restrict the interface without buying anything. A concrete index set that is a
partial order is of course still an instance.

**Directedness, and what locality means without it.** No definition in this file assumes the index
set directed, so a non-directed `K` — the proper intervals of the circle, wedges — carries the data
of a `LocalNet` perfectly well. The *locality axiom*, however, is weaker there than its name
suggests: commutation of `𝔄(O₁)` with `𝔄(O₂)` has to be stated inside an algebra containing both,
so the axiom binds a common upper bound of the two regions and therefore constrains only the
causally orthogonal pairs that have one. That is Guido–Longo–Roberts–Verch's derived relation `⊥̂`
(`CausalOrthogonality.OrthogonalHat`), which collapses onto `⟂` whenever `K` is directed
(`CausalOrthogonality.orthogonalHat_iff`). The converse fails for a *fixed* orthogonality
relation — an empty `⟂` collapses on every preorder — and becomes true once the relation is
quantified over: directedness of `K` is equivalent to `⊥̂ = ⟂` holding for *every*
`CausalOrthogonality K` (`CausalOrthogonality.isDirectedOrder_iff_forall_orthogonalHat_iff`).
The dichotomy is spelled out at
`LocalNet.exists_locality_of_orthogonalHat` and `LocalNet.exists_locality_of_orthogonal`, and the
regions carrying the interesting statements are precisely the ones it bites on: a region and its
causal complement typically have no common upper bound in the index set — on the circle their
union misses only two points and so is neither connected nor non-dense, hence not a region. A net
over such an index set needing locality for `⟂` itself must be taken as a `VonNeumannNet`
(`QuantumSystem.Algebra.LocalNet.SplitProperty`), where the ambient `𝓑(H)` removes the obstruction.

The file deliberately stops at the net-level axioms; in particular, additivity/generation axioms
(e.g. `𝔄(O₁ ⊔ O₂)` being generated by the images of `𝔄(O₁)` and `𝔄(O₂)`, as in tensor-product
spin-system nets) are intentionally out of scope here and belong to concrete instantiations.

The quasi-local algebra built from a net lives in `LocalNet.QuasiLocalAlgebra` (and requires the
index set to be directed); covariance data and its action live in `LocalNet.Covariance` /
`LocalNet.QuasiLocalAlgebra`.

## Notation

`𝔄(O)` in the prose above is documentation shorthand, following the AQFT literature, for the local
C⋆-algebra `N.algebra O` of a region; where a representation is in play, `𝓡(O)` abbreviates the
local von Neumann algebra `N.localVonNeumannAlgebra R O`. Neither is a Lean notation, and
deliberately so: both objects carry the net `N` — and `𝓡(O)` also the representation `R` — as
parameters that a bare `𝔄(O)` could not capture, so a faithful notation would have to spell them
out anyway. The symbols stay in the prose; the code writes the projections.
-/

@[expose] public section

/-! ### Causal index sets -/

/-- A **causal orthogonality relation** on an index set of regions: `O₁ ⟂ O₂` abstracts causal
    (spacelike) disjointness of regions, the relation under which the Haag–Kastler locality axiom
    applies. It is symmetric and hereditary under shrinking regions.

    The literature's axiomatization (Guido–Longo–Roberts–Verch §3.1, the only abstract one in the
    sources behind `docs/math/causal-index-set.md`) asks for three conditions: symmetry, heredity,
    and the existence of causal complements (`∀ O₁, ∃ O₂, O₁ ⟂ O₂`). This class carries the first
    two, which are properties of the relation itself; the third is a property of the *index set*
    and is carried separately, as the mixin `CausalIndexSet` below. Splitting it off keeps this
    class available where the third condition is absent or in doubt: the corpus secures it in
    three different ways — through a membership condition (Guido–Longo–Roberts–Verch's regular
    diamonds and Köster's proper intervals demand a non-void causal complement to *be* a region),
    by admitting the empty region (lattice regions, where `∅` is disjoint from everything), or not
    at all (Halvorson–Müger's double cones state no such clause) — and on a time-slab around a
    compact Cauchy surface it fails under the reading of Brunetti–Fredenhagen–Verch that their own
    category of spacetimes forces, though read literally their index set contains `∅` and the
    condition then holds vacuously. A class demanding the condition could not carry such an index
    set at all.

    What the third condition buys — on a *directed* index set, through heredity — is that causal
    orthogonality refines the *other* derived relation of Guido–Longo–Roberts–Verch (`⊥̃`, a common
    orthogonal partner rather than a common upper bound), and through it the duality theory of the
    dual net and the DHR selection criterion; without directedness it has no order-theoretic
    consequence at all, since adjoining a bottom element related to everything satisfies all three
    conditions on any poset. None of that is used here.

    The relation is *not* required to be irreflexive: `O ⟂ O` legitimately holds for degenerate
    regions (e.g. the empty lattice region) and forces `𝔄(O)` to be commutative. For Minkowski
    double cones one instantiates `⟂` with spacelike separation — note this is *not* set
    disjointness (disjoint timelike-separated regions are not causally orthogonal), which is why
    the relation is carried as data rather than derived from the order. -/
class CausalOrthogonality (K : Type*) [Preorder K] where
  /-- The causal orthogonality relation `O₁ ⟂ O₂` on regions. -/
  Orthogonal : K → K → Prop
  /-- Causal orthogonality is symmetric. -/
  orthogonal_symm : ∀ ⦃O₁ O₂ : K⦄, Orthogonal O₁ O₂ → Orthogonal O₂ O₁
  /-- Causal orthogonality is hereditary under shrinking the left region. -/
  orthogonal_mono_left : ∀ ⦃O₀ O₁ O₂ : K⦄, O₀ ≤ O₁ → Orthogonal O₁ O₂ → Orthogonal O₀ O₂

namespace CausalOrthogonality

/-- `O₁ ⟂ O₂` : the regions `O₁` and `O₂` are causally orthogonal (spacelike separated).

    The token `⟂` is also used globally by Mathlib for `Submodule.IsOrtho` at precedence 50;
    this scoped notation is declared at the same precedence so that the two coexist by
    type-directed disambiguation. -/
scoped infixl:50 " ⟂ " => CausalOrthogonality.Orthogonal

variable {K : Type*} [Preorder K] [CausalOrthogonality K]

/-- Causal orthogonality is symmetric (dot-notation form). -/
theorem Orthogonal.symm {O₁ O₂ : K} (h : O₁ ⟂ O₂) : O₂ ⟂ O₁ :=
  orthogonal_symm h

/-- Causal orthogonality is hereditary under shrinking the left region. -/
theorem Orthogonal.mono_left {O₀ O₁ O₂ : K} (h₀ : O₀ ≤ O₁) (h : O₁ ⟂ O₂) : O₀ ⟂ O₂ :=
  orthogonal_mono_left h₀ h

/-- Causal orthogonality is hereditary under shrinking the right region. -/
theorem Orthogonal.mono_right {O₁ O₂ O₃ : K} (h₀ : O₃ ≤ O₂) (h : O₁ ⟂ O₂) : O₁ ⟂ O₃ :=
  (h.symm.mono_left h₀).symm

/-- Causal orthogonality is hereditary under shrinking both regions. -/
theorem Orthogonal.mono {O₁' O₁ O₂' O₂ : K} (h₁ : O₁' ≤ O₁) (h₂ : O₂' ≤ O₂)
    (h : O₁ ⟂ O₂) : O₁' ⟂ O₂' :=
  (h.mono_left h₁).mono_right h₂

/-! ### The derived relation `⊥̂`

Guido–Longo–Roberts–Verch derive from `⟂` a relation written `⊥̂`, obtained by supplementing
`O₁ ⟂ O₂` with the demand that `O₁` and `O₂` have a **common upper bound** in the index set. It is
purely order- and `⟂`-theoretic — no topology, no closures — so it is available over
`CausalOrthogonality` exactly as that class stands. On a directed index set it collapses back onto
`⟂` (`orthogonalHat_iff`); off one it *can* be strictly weaker, though whether it is depends on the
relation — the collapse characterises directedness only after quantifying over all causal
orthogonality relations on the index set (`isDirectedOrder_iff_forall_orthogonalHat_iff`). The whole
`⟂` / `⊥̂` distinction is the price of dropping directedness.

It is carried here because it, and not `⟂`, is what the locality axiom of `LocalNet` below
actually constrains: see `LocalNet.locality` and `LocalNet.exists_locality_of_orthogonalHat`.

No notation is introduced for it: the literature's `⊥̂` needs a combining accent, and the relation
appears rarely enough that the spelled-out name reads better than a near-collision with `⟂`.
-/

/-- The **derived orthogonality relation `⊥̂`** of Guido–Longo–Roberts–Verch: `O₁` and `O₂` are
    causally orthogonal *and* admit a common upper bound in the index set.

    This is the relation on which the locality axiom of a `LocalNet` bites, since commutation of
    `𝔄(O₁)` with `𝔄(O₂)` can only be *stated* inside an algebra containing both. On a directed
    index set it is `⟂` itself (`orthogonalHat_iff`). -/
def OrthogonalHat (O₁ O₂ : K) : Prop :=
  O₁ ⟂ O₂ ∧ ∃ O₃, O₁ ≤ O₃ ∧ O₂ ≤ O₃

/-- The derived relation refines causal orthogonality. -/
theorem OrthogonalHat.orthogonal {O₁ O₂ : K} (h : OrthogonalHat O₁ O₂) : O₁ ⟂ O₂ :=
  h.1

/-- A common upper bound of a pair related by the derived relation. -/
theorem OrthogonalHat.exists_upperBound {O₁ O₂ : K} (h : OrthogonalHat O₁ O₂) :
    ∃ O₃, O₁ ≤ O₃ ∧ O₂ ≤ O₃ :=
  h.2

/-- The derived relation is symmetric. Symmetry of `⟂` is what is used on the first component;
    a common upper bound is symmetric on the nose. -/
theorem OrthogonalHat.symm {O₁ O₂ : K} (h : OrthogonalHat O₁ O₂) : OrthogonalHat O₂ O₁ :=
  ⟨h.1.symm, h.2.imp fun _ hO => ⟨hO.2, hO.1⟩⟩

/-- The derived relation is hereditary under shrinking the left region: heredity of `⟂` handles
    the first component and transitivity of `≤` the upper bound. -/
theorem OrthogonalHat.mono_left {O₀ O₁ O₂ : K} (h₀ : O₀ ≤ O₁) (h : OrthogonalHat O₁ O₂) :
    OrthogonalHat O₀ O₂ :=
  ⟨h.1.mono_left h₀, h.2.imp fun _ hO => ⟨h₀.trans hO.1, hO.2⟩⟩

/-- The derived relation is hereditary under shrinking the right region. -/
theorem OrthogonalHat.mono_right {O₁ O₂ O₃ : K} (h₀ : O₃ ≤ O₂) (h : OrthogonalHat O₁ O₂) :
    OrthogonalHat O₁ O₃ :=
  (h.symm.mono_left h₀).symm

/-- The derived relation is hereditary under shrinking both regions. -/
theorem OrthogonalHat.mono {O₁' O₁ O₂' O₂ : K} (h₁ : O₁' ≤ O₁) (h₂ : O₂' ≤ O₂)
    (h : OrthogonalHat O₁ O₂) : OrthogonalHat O₁' O₂' :=
  (h.mono_left h₁).mono_right h₂

/-- **Passing to the derived relation is idempotent**: supplementing `⊥̂` with the demand for a
    common upper bound asks for nothing new, since `⊥̂` already carries one. No axiom of
    `CausalOrthogonality` is used. -/
theorem orthogonalHat_and_exists_upperBound_iff {O₁ O₂ : K} :
    (OrthogonalHat O₁ O₂ ∧ ∃ O₃, O₁ ≤ O₃ ∧ O₂ ≤ O₃) ↔ OrthogonalHat O₁ O₂ :=
  ⟨And.left, fun h => ⟨h, h.2⟩⟩

/-- **On a directed index set the derived relation is causal orthogonality itself.** Directedness
    supplies the common upper bound, and no axiom of `CausalOrthogonality` is needed.

    Only this implication holds for a *fixed* orthogonality relation: off a directed index set the
    two need not differ, since an empty `⟂` collapses onto `⊥̂` on any preorder. The sharp converse
    quantifies over the relation (`isDirectedOrder_iff_forall_orthogonalHat_iff`). Where they do
    differ it is `⊥̂` that the locality axiom of a `LocalNet` constrains: on the two-element
    antichain `{O₁, O₂}` with `O₁ ⟂ O₂` there is no common upper bound at all, so `⊥̂` is empty
    there while `⟂` is not. -/
theorem orthogonalHat_iff [IsDirectedOrder K] {O₁ O₂ : K} :
    OrthogonalHat O₁ O₂ ↔ O₁ ⟂ O₂ :=
  ⟨OrthogonalHat.orthogonal, fun h => ⟨h, directed_of (· ≤ ·) O₁ O₂⟩⟩

/-- **Directedness is exactly the coincidence of `⊥̂` with `⟂`, quantified over the relation.**
    For one fixed `CausalOrthogonality K` the coincidence is strictly weaker than directedness —
    the empty relation collapses on every preorder — so the literature's "`⊥̂ = ⟂` precisely on
    directed index sets" is a statement about the index set, not about a single net's causal
    structure. Read that way it is true: the forward direction is `orthogonalHat_iff`, and the
    converse tests directedness against the *total* relation, in which every pair is causally
    orthogonal and `⊥̂` therefore records nothing but the existence of a common upper bound. -/
theorem isDirectedOrder_iff_forall_orthogonalHat_iff (K : Type*) [Preorder K] :
    IsDirectedOrder K ↔
      ∀ [CausalOrthogonality K] (O₁ O₂ : K), OrthogonalHat O₁ O₂ ↔ O₁ ⟂ O₂ := by
  constructor
  · intro _ _ _ _
    exact orthogonalHat_iff
  · intro h
    refine ⟨fun O₁ O₂ => ?_⟩
    letI : CausalOrthogonality K :=
      { Orthogonal := fun _ _ => True
        orthogonal_symm := fun _ _ _ => trivial
        orthogonal_mono_left := fun _ _ _ _ _ => trivial }
    exact ((h O₁ O₂).2 trivial).2

end CausalOrthogonality

open scoped CausalOrthogonality

/-- A **causal index set** in the full sense of Guido–Longo–Roberts–Verch §3.1: on top of the
    symmetry and heredity carried by `CausalOrthogonality`, the third condition of the
    axiomatization — the **existence of causal complements**, every region admitting a causally
    disjoint one. An ordered `K` with `[CausalOrthogonality K]` and this mixin is exactly the
    adopted general form of the extraction note `docs/math/causal-index-set.md`.

    Carried as a mixin rather than folded into `CausalOrthogonality`, because unlike symmetry and
    heredity this condition is a property of the index set rather than of the relation, and the
    corpus's index families do not all satisfy it (see the docstring of `CausalOrthogonality`).
    It is genuinely model-dependent input: what this development draws from it is
    `CausalIndexSet.exists_orthogonalHat` — on a directed index set the locality axiom of a
    `LocalNet` bites at every region — while the duality theory it really feeds (the dual net, the
    DHR selection criterion) is not formalized here; the literature's causal index set is not
    expressible without it. -/
class CausalIndexSet (K : Type*) [Preorder K] [CausalOrthogonality K] : Prop where
  /-- Every region admits a causally disjoint region — axiom c) of the
      Guido–Longo–Roberts–Verch axiomatization. -/
  exists_orthogonal : ∀ O₁ : K, ∃ O₂, O₁ ⟂ O₂

/-- **On a directed causal index set every region has a `⊥̂`-orthogonal partner**: directedness
    upgrades the causal complement supplied by `exists_orthogonal` to the derived relation `⊥̂`
    (`CausalOrthogonality.orthogonalHat_iff`), which is the relation the locality axiom of a
    `LocalNet` actually constrains. So the locality axiom is nowhere vacuous on such an index set:
    `LocalNet.exists_locality_of_orthogonalHat` applies at every region. -/
theorem CausalIndexSet.exists_orthogonalHat {K : Type*} [Preorder K] [CausalOrthogonality K]
    [IsDirectedOrder K] [CausalIndexSet K] (O : K) :
    ∃ O', CausalOrthogonality.OrthogonalHat O O' :=
  let ⟨O', h⟩ := CausalIndexSet.exists_orthogonal O
  ⟨O', CausalOrthogonality.orthogonalHat_iff.2 h⟩

/-- On the finite regions of a lattice of sites, causal orthogonality is plain set disjointness:
    a lattice net is kinematical (equal-time), so "spacelike separated" degenerates to "disjoint in
    space" (Naaijkens, *Anyons in Infinite Quantum Systems*, 2012, §3.4). -/
instance {α : Type*} : CausalOrthogonality (Finset α) where
  Orthogonal := Disjoint
  orthogonal_symm _ _ h := h.symm
  orthogonal_mono_left _ _ _ h₀ h := h.mono_left h₀

/-- The lattice regions form a causal index set in the full sense: the **empty region** is
    disjoint from every region, so causal complements exist for free. This is how the literature's
    lattice index set secures the condition — through `∅ ∈ 𝒦` rather than through a membership
    clause — at the price of `⟂` being reflexive at `∅`. -/
instance {α : Type*} : CausalIndexSet (Finset α) :=
  ⟨fun Λ => ⟨∅, Finset.disjoint_empty_right Λ⟩⟩

/-- A **local net of C⋆-algebras** over a causal index set `K` — an ordered set of
    regions with a causal orthogonality relation `⟂` (`CausalOrthogonality`): the assignment
    `O ↦ 𝔄(O)` together with isotony embeddings `incl : 𝔄(O) →⋆ₐ[ℂ] 𝔄(O')` for `O ≤ O'`,
    functorial (`incl_refl`/`incl_trans`) and local (`locality`). This is the Haag–Kastler net
    structure over an abstract index set, *without* the injectivity requirement on the isotony
    embeddings; the literature's net (Naaijkens, *Anyons in Infinite Quantum Systems*, 2012, §3.4)
    is `LocalNet` together with the `Faithful` class, which carries that requirement. Lattice nets are the instance
    `K = Finset sites` with `⟂ = Disjoint`. -/
structure LocalNet (K : Type*) [Preorder K] [CausalOrthogonality K] where
  /-- The local C⋆-algebra `𝔄(O)` assigned to a region. For any self-orthogonal region `O ⟂ O`
      (e.g. the empty lattice region) the axioms force `𝔄(O)` to be commutative (instantiate
      `locality` at `O₁ = O₂ = O`) but do *not* force it to be trivial: the literature's
      `𝔄(∅) = ℂ·1` is not required and must be imposed by a concrete instantiation when needed. -/
  algebra : K → Type*
  /-- Each local algebra is a (complex) C⋆-algebra. -/
  [algebraCStar : ∀ O, CStarAlgebra (algebra O)]
  /-- **Isotony**: for `O ≤ O'` an inclusion of local algebras as a unital `*`-homomorphism. -/
  incl : ∀ {O O' : K}, O ≤ O' → (algebra O →⋆ₐ[ℂ] algebra O')
  /-- The identity inclusion `O ≤ O` acts as the identity. -/
  incl_refl : ∀ {O : K} (x : algebra O), incl (le_refl O) x = x
  /-- **Functoriality**: the inclusions compose, so the net is a directed system. -/
  incl_trans : ∀ {O₁ O₂ O₃ : K} (h₁₂ : O₁ ≤ O₂) (h₂₃ : O₂ ≤ O₃) (x : algebra O₁),
      incl h₂₃ (incl h₁₂ x) = incl (h₁₂.trans h₂₃) x
  /-- **Locality** (microcausality, Einstein causality): observables localised in causally
      orthogonal regions commute inside any common larger region.

      The common region `O` is bound *before* the orthogonality hypothesis, and that is not an
      accident of phrasing: `Commute x y` for `x : 𝔄(O₁)` and `y : 𝔄(O₂)` is not even typeable
      without an algebra containing both, and over a non-directed index set there need be no such
      region — nor any quasi-local algebra to fall back on. So the pairs this field constrains are
      exactly those causally orthogonal pairs that admit a common upper bound, which is the derived
      relation `CausalOrthogonality.OrthogonalHat` (`⊥̂`) rather than `⟂` itself. The two coincide
      on directed index sets (`CausalOrthogonality.orthogonalHat_iff`) — and, once the orthogonality
      relation is quantified over, only there
      (`CausalOrthogonality.isDirectedOrder_iff_forall_orthogonalHat_iff`) — which is where every
      consumer of this field lives.

      A net over a genuinely non-directed index set that needs locality for `⟂` itself must be
      taken as a `VonNeumannNet` (`QuantumSystem.Algebra.LocalNet.SplitProperty`), whose ambient
      `𝓑(H)` lets `algebra_le_commutant_of_orthogonal` state locality with no upper bound. -/
  locality : ∀ {O₁ O₂ O : K} (h₁ : O₁ ≤ O) (h₂ : O₂ ≤ O), O₁ ⟂ O₂ →
      ∀ (x : algebra O₁) (y : algebra O₂), Commute (incl h₁ x) (incl h₂ y)

namespace LocalNet

attribute [instance] algebraCStar

section SemilatticeSup

variable {K : Type*} [SemilatticeSup K] [CausalOrthogonality K]

/-- Smart constructor for `LocalNet` over a join-semilattice of regions, taking locality only
    inside the canonical join region `O₁ ⊔ O₂`: given `incl_trans`, commutation there pushes
    forward along `incl : 𝔄(O₁ ⊔ O₂) →⋆ₐ[ℂ] 𝔄(O)` to any common superregion `O`, so the join case
    is equivalent to the general `locality` field. For lattice nets (`K = Finset sites`) the join
    is the union of regions. -/
def mk' (algebra : K → Type*) [algebraCStar : ∀ O, CStarAlgebra (algebra O)]
    (incl : ∀ {O O' : K}, O ≤ O' → (algebra O →⋆ₐ[ℂ] algebra O'))
    (incl_refl : ∀ {O : K} (x : algebra O), incl (le_refl O) x = x)
    (incl_trans : ∀ {O₁ O₂ O₃ : K} (h₁₂ : O₁ ≤ O₂) (h₂₃ : O₂ ≤ O₃) (x : algebra O₁),
      incl h₂₃ (incl h₁₂ x) = incl (h₁₂.trans h₂₃) x)
    (locality_sup : ∀ {O₁ O₂ : K}, O₁ ⟂ O₂ →
      ∀ (x : algebra O₁) (y : algebra O₂),
        Commute (incl le_sup_left x) (incl le_sup_right y)) :
    LocalNet K where
  algebra := algebra
  incl := incl
  incl_refl := incl_refl
  incl_trans := incl_trans
  locality h₁ h₂ hortho x y := by
    have h := (locality_sup hortho x y).map (incl (sup_le h₁ h₂))
    rwa [incl_trans, incl_trans] at h

end SemilatticeSup

variable {K : Type*} [Preorder K] [CausalOrthogonality K] (N : LocalNet K)

/-- The net forms a directed system of `*`-algebras: the isotony embeddings compose and the
    identity inclusion is the identity. -/
instance directedSystem :
    DirectedSystem N.algebra (fun _ _ h => ⇑(N.incl h)) where
  map_self _ x := N.incl_refl x
  map_map _ _ _ hij hjk x := N.incl_trans hij hjk x

/-! ### What locality constrains

The `locality` field quantifies over a common upper bound of the two regions, so the pairs it
constrains are exactly those related by the derived relation `⊥̂` of
`CausalOrthogonality.OrthogonalHat`. The two lemmas below say this in both directions of the
directedness dichotomy: `⊥̂`-related pairs always get commutation somewhere, and on a directed
index set that is every causally orthogonal pair.
-/

/-- **Locality is locality for the derived relation `⊥̂`**: a causally orthogonal pair admitting a
    common upper bound commutes inside one. This is the whole content of the `locality` field —
    for a causally orthogonal pair with *no* common upper bound the field says nothing, and cannot,
    since the commutation has nowhere to be stated. -/
theorem exists_locality_of_orthogonalHat {O₁ O₂ : K}
    (h : CausalOrthogonality.OrthogonalHat O₁ O₂) :
    ∃ (O : K) (h₁ : O₁ ≤ O) (h₂ : O₂ ≤ O),
      ∀ (x : N.algebra O₁) (y : N.algebra O₂), Commute (N.incl h₁ x) (N.incl h₂ y) :=
  let ⟨O, h₁, h₂⟩ := h.exists_upperBound
  ⟨O, h₁, h₂, N.locality h₁ h₂ h.orthogonal⟩

/-- **On a directed index set locality is locality for `⟂` itself**: directedness supplies the
    common upper bound, so every causally orthogonal pair commutes inside some region. This is the
    setting of every consumer of the `locality` field — in particular of
    `LocalNet.ιLocal_commute_of_orthogonal`, where the quasi-local algebra provides the ambient
    algebra in which the commutation is finally stated for all pairs at once. -/
theorem exists_locality_of_orthogonal [IsDirectedOrder K] {O₁ O₂ : K} (h : O₁ ⟂ O₂) :
    ∃ (O : K) (h₁ : O₁ ≤ O) (h₂ : O₂ ≤ O),
      ∀ (x : N.algebra O₁) (y : N.algebra O₂), Commute (N.incl h₁ x) (N.incl h₂ y) :=
  N.exists_locality_of_orthogonalHat (CausalOrthogonality.orthogonalHat_iff.2 h)

/-! ### Faithful nets

A net is *faithful* when its isotony embeddings are injective (the standard AQFT
non-degeneracy condition). The quasi-local C⋆-norm built from this hypothesis lives in
`LocalNet.QuasiLocalAlgebra`.
-/

/-- A local net is **faithful** when all its isotony embeddings are injective. In the standard
    AQFT definition the isotony embeddings are *injective* unital `*`-homomorphisms (Naaijkens,
    *Anyons in Infinite Quantum Systems*, 2012, §3.4), so a faithful local net — `LocalNet`
    together with `Faithful` — is the literature's net.
    Carried as a typeclass rather than a structure field so algebraic constructions can state the
    non-degeneracy hypothesis only where they need it. -/
class Faithful {K : Type*} [Preorder K] [CausalOrthogonality K] (N : LocalNet K) : Prop where
  /-- Every isotony embedding of the net is injective. -/
  incl_injective : ∀ {O O' : K} (h : O ≤ O'), Function.Injective (N.incl h)

/-! ### Region-equality transport -/

/-- Transport a local algebra along an equality of regions, as a `*`-isomorphism. Used to identify
    local algebras whose regions are propositionally equal. -/
def algebraCongr {O O' : K} (h : O = O') : N.algebra O ≃⋆ₐ[ℂ] N.algebra O' := by
  subst h; exact StarAlgEquiv.refl

/-- The isotony embeddings are natural with respect to the region-equality transport. -/
lemma incl_algebraCongr {O₁ O₂ O₁' O₂' : K} (e₁ : O₁ = O₁') (e₂ : O₂ = O₂')
    (h : O₁ ≤ O₂) (h' : O₁' ≤ O₂') (x : N.algebra O₁) :
    N.algebraCongr e₂ (N.incl h x) = N.incl h' (N.algebraCongr e₁ x) := by
  subst e₁; subst e₂; rfl

/-- Transports along composable region equalities compose. -/
@[simp] lemma algebraCongr_trans {O₁ O₂ O₃ : K} (h₁ : O₁ = O₂) (h₂ : O₂ = O₃)
    (x : N.algebra O₁) :
    N.algebraCongr h₂ (N.algebraCongr h₁ x) = N.algebraCongr (h₁.trans h₂) x := by
  subst h₁; subst h₂; rfl

/-- A transport along a reflexive region equality is the identity. -/
@[simp] lemma algebraCongr_self {O : K} (h : O = O) (x : N.algebra O) :
    N.algebraCongr h x = x := by
  rw [Subsingleton.elim h rfl]; rfl

/-- Cancelling a transport against a target value moves it to the other side. -/
lemma algebraCongr_eq_iff {O O' : K} (h : O = O') (x : N.algebra O)
    (y : N.algebra O') : N.algebraCongr h x = y ↔ x = N.algebraCongr h.symm y := by
  subst h; simp

end LocalNet
