/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import QuantumSystem.Algebra.CStarAlgebra.Representation.Conjugation
public import QuantumSystem.Algebra.LocalNet.QuasiLocalAlgebra

/-!
# The DHR selection criterion

Doplicher–Haag–Roberts superselection theory singles out, among the representations of the
quasi-local C⋆-algebra `𝔄` of a local net, those that are indistinguishable from a reference
representation `π₀` (the vacuum representation) by measurements far away: a representation `R`
satisfies the **DHR selection criterion** if for every region `O` the restrictions of `R` and `π₀`
to the observables `𝔄(O')` localised in the causal complement of `O` are unitarily equivalent.
Here `𝔄(O')` is generated by the local algebras `𝔄(O₁)` of the regions `O₁ ⟂ O`, so the
equivalence is stated region by region on those local algebras.

The reference representation is an arbitrary `CStarRep` of `𝔄`: the vacuum representation is the
case the literature treats, but the criterion uses nothing about it.

Conjugating `R` by a unitary `U` witnessing the criterion at `O` gives a representation
`R.conjBy U` on the Hilbert space of `π₀` itself, and it *coincides* with `π₀` on every observable
localised outside `O` (`LocalNet.conjBy_π_ιLocalCStar_eq_of_isDHRIntertwiner`). This is the step
from which, in the presence of Haag duality, one reads off an endomorphism of `𝔄` localised in `O`
(Naaijkens, §3.2); Haag duality and the localised endomorphisms are not formalised here.

## Main definitions

* `LocalNet.IsDHRIntertwiner` — `U : R.H ≃ₗᵢ[ℂ] π₀.H` intertwines `R` and `π₀` on every
  observable localised in a region causally orthogonal to `O`.
* `LocalNet.SatisfiesDHR` — the DHR selection criterion: such a `U` exists for every region `O`.

## Main results

* `LocalNet.conjBy_π_ιLocalCStar_eq_of_isDHRIntertwiner` — **the conjugated representation acts
  as `π₀` outside the localisation region**.
* `LocalNet.satisfiesDHR_refl` — the reference representation satisfies the criterion.

## References

* S. Doplicher, R. Haag, J. E. Roberts, *Local observables and particle statistics I*,
  Comm. Math. Phys. 23 (1971), 199–230
* P. Naaijkens, *Anyons in Infinite Quantum Systems*, PhD thesis, Radboud University Nijmegen
  (2012), §3.2
-/

@[expose] public section

namespace LocalNet

open scoped CausalOrthogonality

variable {K : Type*} [Preorder K] [CausalOrthogonality K] [IsDirectedOrder K] [Nonempty K]
variable (N : LocalNet K) [N.Faithful]

/-- `U : R.H ≃ₗᵢ[ℂ] π₀.H` is a **DHR intertwiner for the region `O`**: it intertwines `R` with the
    reference representation `π₀` on every observable localised in a region `O₁ ⟂ O`, that is,
    `U R(X) = π₀(X) U` for `X ∈ 𝔄(O₁)`. -/
def IsDHRIntertwiner (π₀ R : CStarRep N.quasiLocalCStarAlgebra) (O : K)
    (U : R.H ≃ₗᵢ[ℂ] π₀.H) : Prop :=
  ∀ ⦃O₁ : K⦄, O₁ ⟂ O → ∀ X : N.algebra O₁,
    (U : R.H →L[ℂ] π₀.H) ∘L R.π (N.ιLocalCStar O₁ X) =
      π₀.π (N.ιLocalCStar O₁ X) ∘L (U : R.H →L[ℂ] π₀.H)

/-- The **DHR selection criterion** (Doplicher–Haag–Roberts): for every region `O`, the
    representation `R` is unitarily equivalent to the reference representation `π₀` on the
    observables localised in the causal complement of `O`. -/
def SatisfiesDHR (π₀ R : CStarRep N.quasiLocalCStarAlgebra) : Prop :=
  ∀ O : K, ∃ U : R.H ≃ₗᵢ[ℂ] π₀.H, N.IsDHRIntertwiner π₀ R O U

variable {N}

/-- **The conjugated representation acts as `π₀` outside the localisation region**: if `U` is a
    DHR intertwiner for `O`, then `R.conjBy U`, a representation on the Hilbert space of `π₀`,
    agrees with `π₀` on every observable localised in a region `O₁ ⟂ O`. -/
theorem conjBy_π_ιLocalCStar_eq_of_isDHRIntertwiner {π₀ R : CStarRep N.quasiLocalCStarAlgebra}
    {O : K} {U : R.H ≃ₗᵢ[ℂ] π₀.H} (hU : N.IsDHRIntertwiner π₀ R O U) {O₁ : K} (hO₁ : O₁ ⟂ O)
    (X : N.algebra O₁) :
    (R.conjBy U).π (N.ιLocalCStar O₁ X) = π₀.π (N.ιLocalCStar O₁ X) :=
  CStarRep.conjBy_π_eq_of_intertwined U (hU hO₁ X)

/-- Under the DHR selection criterion, for every region `O` some conjugate of `R` on the Hilbert
    space of `π₀` agrees with `π₀` on every observable localised in a region `O₁ ⟂ O`. -/
lemma exists_conjBy_π_ιLocalCStar_eq_of_satisfiesDHR {π₀ R : CStarRep N.quasiLocalCStarAlgebra}
    (h : N.SatisfiesDHR π₀ R) (O : K) :
    ∃ U : R.H ≃ₗᵢ[ℂ] π₀.H, ∀ ⦃O₁ : K⦄, O₁ ⟂ O → ∀ X : N.algebra O₁,
      (R.conjBy U).π (N.ιLocalCStar O₁ X) = π₀.π (N.ιLocalCStar O₁ X) :=
  (h O).imp fun _ hU _ hO₁ X => conjBy_π_ιLocalCStar_eq_of_isDHRIntertwiner hU hO₁ X

variable (N) in
/-- The identity is a DHR intertwiner of the reference representation with itself, for every
    region. -/
lemma isDHRIntertwiner_refl (π₀ : CStarRep N.quasiLocalCStarAlgebra) (O : K) :
    N.IsDHRIntertwiner π₀ π₀ O (LinearIsometryEquiv.refl ℂ π₀.H) := fun _ _ _ => by
  ext
  rfl

variable (N) in
/-- The reference representation satisfies the DHR selection criterion. -/
lemma satisfiesDHR_refl (π₀ : CStarRep N.quasiLocalCStarAlgebra) : N.SatisfiesDHR π₀ π₀ :=
  fun O => ⟨_, N.isDHRIntertwiner_refl π₀ O⟩

end LocalNet
