module

public import Mathlib.Analysis.VonNeumannAlgebra.Basic
public import QuantumSystem.Algebra.CStarAlgebra.GNS.Construction
public import QuantumSystem.Algebra.Star.DoubleCommutant.SOTClosedSubAlgebra

@[expose] public section

/-!
# Weak-operator-topology and strong-operator-topology von Neumann algebras

Mathlib defines the concrete notion `VonNeumannAlgebra H` via the double commutant.

For many arguments, one instead wants the alternative characterization: a *-subalgebra of
`𝓑(H)` that is **closed in the weak operator topology (WOT)** or the **strong operator
topology (SOT)**. The equivalence between these characterizations and the double commutant
is the von Neumann double commutant theorem.

This file sets up:

## Main definitions

* `VonNeumannAlgebraWOT`: a WOT-closed `StarSubalgebra` of `H →L[ℂ] H`.
* `VonNeumannAlgebraSOT`: a SOT-closed `StarSubalgebra` of `H →L[ℂ] H`.
* `GNS.Construction.vonNeumannAlgebraGenerated`: the double commutant of a set of operators.
* `GNS.Construction.gnsVonNeumannAlgebra`: the von Neumann algebra generated by the GNS
  representation.

## Main results

* `VonNeumannAlgebra.isWOTClosed`: any `VonNeumannAlgebra` (double-commutant) is WOT-closed.
* `VonNeumannAlgebra.isSOTClosed`: any `VonNeumannAlgebra` (double-commutant) is SOT-closed.
* `isWOTClosed_iff_doubleCommutant`: a *-subalgebra is WOT-closed iff it equals its double
  commutant.
* `isSOTClosed_iff_doubleCommutant`: a *-subalgebra is SOT-closed iff it equals its double
  commutant.
* `VonNeumannAlgebraWOT.coe_coe_eq`: the two notions of von Neumann algebra (WOT and
  double-commutant) are carrier-equivalent.
* `VonNeumannAlgebraSOT.coe_coe_eq`: the two notions of von Neumann algebra (SOT and
  double-commutant) are carrier-equivalent.
* `VonNeumannAlgebra.coe_coe_eq_wot`, `VonNeumannAlgebra.coe_coe_eq_sot`: round-trip
  equivalences.
* `GNS.Construction.gnsVonNeumannAlgebra_contains_πω`: the GNS operators lie in the generated
  von Neumann algebra.
-/

section WOTClosed

open WeakOperatorTopology

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- A concrete von Neumann algebra defined as a WOT-closed *-subalgebra of `𝓑(H)`.

This is the standard alternative definition in functional analysis.
-/
structure VonNeumannAlgebraWOT (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] extends StarSubalgebra ℂ (H →L[ℂ] H) where
  /-- The carrier is closed in the weak operator topology (via the WOT type-copy). -/
  wot_closed' : IsWOTClosed (H := H) (carrier : Set (H →L[ℂ] H))

namespace VonNeumannAlgebraWOT

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- Coercion to `VonNeumannAlgebra` via double commutant. Always valid (no hard half needed). -/
noncomputable instance : CoeOut (VonNeumannAlgebraWOT H) (VonNeumannAlgebra H) where
  coe S := {
    toStarSubalgebra :=
      StarSubalgebra.centralizer ℂ (Set.centralizer (S.toStarSubalgebra : Set (H →L[ℂ] H)))
    centralizer_centralizer' := by
      classical
      let sset : Set (H →L[ℂ] H) := (S.toStarSubalgebra : Set (H →L[ℂ] H))
      have hsstar : star sset = sset := by simp [sset]
      have hcommstar : star (Set.centralizer sset) = Set.centralizer sset := by
        simp [Set.star_centralizer, hsstar]
      simp [StarSubalgebra.coe_centralizer, sset, hcommstar]
  }

end VonNeumannAlgebraWOT

/-- Any `VonNeumannAlgebra` (double-commutant) is WOT-closed. -/
theorem VonNeumannAlgebra.isWOTClosed (S : VonNeumannAlgebra H) :
    IsWOTClosed (H := H) (S : Set (H →L[ℂ] H)) := by
  simpa [S.centralizer_centralizer] using
    isWOTClosed_centralizer_centralizer (H := H) (S := (S : Set (H →L[ℂ] H)))

/-- Any `VonNeumannAlgebra` can be viewed as a WOT-closed *-subalgebra. -/
noncomputable instance : CoeOut (VonNeumannAlgebra H) (VonNeumannAlgebraWOT H) where
  coe S := ⟨S.toStarSubalgebra, S.isWOTClosed⟩

/-! ### Equivalence of the two definitions -/

/-- The double commutant theorem for WOT-closed *-subalgebras: closedness ↔ equals double commutant.
-/
theorem isWOTClosed_iff_doubleCommutant (S : StarSubalgebra ℂ (H →L[ℂ] H)) :
    IsWOTClosed (H := H) (S : Set (H →L[ℂ] H)) ↔
      Set.centralizer (Set.centralizer (S : Set (H →L[ℂ] H))) = (S : Set (H →L[ℂ] H)) :=
  ⟨WOTClosedSubalgebra.doubleCommutant_eq_of_isWOTClosed (H := H) S, fun hcc => by
    simpa [hcc] using isWOTClosed_centralizer_centralizer (H := H) (S := (S : Set (H →L[ℂ] H)))⟩

/-- The two notions of von Neumann algebra are carrier-equivalent. -/
theorem VonNeumannAlgebraWOT.coe_coe_eq (S : VonNeumannAlgebraWOT H) :
    ((S : VonNeumannAlgebra H) : Set (H →L[ℂ] H)) = (S.toStarSubalgebra : Set (H →L[ℂ] H)) := by
  classical
  let sset : Set (H →L[ℂ] H) := (S.toStarSubalgebra : Set (H →L[ℂ] H))
  have hsstar : star sset = sset := by simp [sset]
  have hcommstar : star (Set.centralizer sset) = Set.centralizer sset := by
    simp [Set.star_centralizer, hsstar]
  have hcc := (isWOTClosed_iff_doubleCommutant S.toStarSubalgebra).1 S.wot_closed'
  simp [StarSubalgebra.coe_centralizer, hcommstar, hcc, sset]

/-- Round-trip: `VonNeumannAlgebra → WOT → VonNeumannAlgebra` gives carrier equality. -/
theorem VonNeumannAlgebra.coe_coe_eq_wot (S : VonNeumannAlgebra H) :
    ((S : VonNeumannAlgebraWOT H) : VonNeumannAlgebra H) = S := by
  have h : ((S : VonNeumannAlgebraWOT H) : VonNeumannAlgebra H).toStarSubalgebra.carrier =
           S.toStarSubalgebra.carrier := by
    have := VonNeumannAlgebraWOT.coe_coe_eq (S : VonNeumannAlgebraWOT H)
    simp only [VonNeumannAlgebra.coe_toStarSubalgebra] at this
    exact this
  ext x
  exact Set.ext_iff.1 h x

end WOTClosed

/-!
## Strong-operator-topology von Neumann algebras

Parallel to the WOT characterization, we define SOT-closed *-subalgebras and prove that
double commutants are SOT-closed.
-/

section SOTClosed

open StrongOperatorTopology WeakOperatorTopology

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- A concrete von Neumann algebra defined as a SOT-closed *-subalgebra of `𝓑(H)`.

This is equivalent to WOT-closedness for *-subalgebras (by the double commutant theorem).
-/
structure VonNeumannAlgebraSOT (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] extends StarSubalgebra ℂ (H →L[ℂ] H) where
  /-- The carrier is closed in the strong operator topology. -/
  sot_closed' : IsSOTClosed (H := H) (carrier : Set (H →L[ℂ] H))

namespace VonNeumannAlgebraSOT

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- Coercion to `VonNeumannAlgebra` via double commutant. Always valid (no hard half needed). -/
noncomputable instance : CoeOut (VonNeumannAlgebraSOT H) (VonNeumannAlgebra H) where
  coe S := {
    toStarSubalgebra :=
      StarSubalgebra.centralizer ℂ (Set.centralizer (S.toStarSubalgebra : Set (H →L[ℂ] H)))
    centralizer_centralizer' := by
      classical
      let sset : Set (H →L[ℂ] H) := (S.toStarSubalgebra : Set (H →L[ℂ] H))
      have hsstar : star sset = sset := by simp [sset]
      have hcommstar : star (Set.centralizer sset) = Set.centralizer sset := by
        simp [Set.star_centralizer, hsstar]
      simp [StarSubalgebra.coe_centralizer, sset, hcommstar]
  }

end VonNeumannAlgebraSOT

/-- Any `VonNeumannAlgebra` (double-commutant) is SOT-closed. -/
theorem VonNeumannAlgebra.isSOTClosed (S : VonNeumannAlgebra H) :
    IsSOTClosed (H := H) (S : Set (H →L[ℂ] H)) := by
  simpa [S.centralizer_centralizer] using
    isSOTClosed_centralizer_centralizer (H := H) (S := (S : Set (H →L[ℂ] H)))

/-- Any `VonNeumannAlgebra` can be viewed as a SOT-closed *-subalgebra. -/
noncomputable instance : CoeOut (VonNeumannAlgebra H) (VonNeumannAlgebraSOT H) where
  coe S := ⟨S.toStarSubalgebra, S.isSOTClosed⟩

/-- The double commutant theorem for SOT-closed *-subalgebras.

A SOT-closed *-subalgebra equals its double commutant.
-/
theorem isSOTClosed_iff_doubleCommutant (S : StarSubalgebra ℂ (H →L[ℂ] H)) :
    IsSOTClosed (H := H) (S : Set (H →L[ℂ] H)) ↔
      Set.centralizer (Set.centralizer (S : Set (H →L[ℂ] H))) = (S : Set (H →L[ℂ] H)) :=
  ⟨SOTClosedSubalgebra.doubleCommutant_eq_of_isSOTClosed S, fun hcc => by
    -- The reverse direction: A'' = A implies A is SOT-closed (easy half).
    simpa [hcc] using isSOTClosed_centralizer_centralizer (H := H) (S := (S : Set (H →L[ℂ] H)))⟩

/-- The two notions of SOT von Neumann algebra are carrier-equivalent. -/
theorem VonNeumannAlgebraSOT.coe_coe_eq (S : VonNeumannAlgebraSOT H) :
    ((S : VonNeumannAlgebra H) : Set (H →L[ℂ] H)) = (S.toStarSubalgebra : Set (H →L[ℂ] H)) := by
  classical
  let sset : Set (H →L[ℂ] H) := (S.toStarSubalgebra : Set (H →L[ℂ] H))
  have hsstar : star sset = sset := by simp [sset]
  have hcommstar : star (Set.centralizer sset) = Set.centralizer sset := by
    simp [Set.star_centralizer, hsstar]
  have hcc := (isSOTClosed_iff_doubleCommutant S.toStarSubalgebra).1 S.sot_closed'
  simp [StarSubalgebra.coe_centralizer, hcommstar, hcc, sset]

/-- Round-trip: `VonNeumannAlgebra → SOT → VonNeumannAlgebra` gives carrier equality. -/
theorem VonNeumannAlgebra.coe_coe_eq_sot (S : VonNeumannAlgebra H) :
    ((S : VonNeumannAlgebraSOT H) : VonNeumannAlgebra H) = S := by
  have h : ((S : VonNeumannAlgebraSOT H) : VonNeumannAlgebra H).toStarSubalgebra.carrier =
           S.toStarSubalgebra.carrier := by
    have := VonNeumannAlgebraSOT.coe_coe_eq (S : VonNeumannAlgebraSOT H)
    simp only [VonNeumannAlgebra.coe_toStarSubalgebra] at this
    exact this
  ext x
  exact Set.ext_iff.1 h x

end SOTClosed

namespace GNS
namespace Construction

open WeakOperatorTopology

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable {A : Type*} [NonUnitalCStarAlgebra A]
variable (ω : State ℂ A)

/-- The (concrete) von Neumann algebra generated by a set of operators: the double commutant.

This definition does *not* require any topology: it is purely algebraic.
In classical functional analysis, by the von Neumann double commutant theorem, this coincides
with the weak operator closure of the unital *-algebra generated by the set.
-/
noncomputable def vonNeumannAlgebraGenerated (S : Set (H →L[ℂ] H)) : VonNeumannAlgebra H where
  -- We take the commutant of the commutant (as `StarSubalgebra.centralizer`).
  -- Unfolding shows the underlying set is `(S ∪ star S).centralizer.centralizer`.
  toStarSubalgebra := StarSubalgebra.centralizer ℂ (StarSubalgebra.centralizer ℂ S : Set (H →L[ℂ] H))
  centralizer_centralizer' := by
    -- A commutant is fixed by the double-commutant operation.
    simp

@[simp]
theorem coe_vonNeumannAlgebraGenerated (S : Set (H →L[ℂ] H)) :
    (vonNeumannAlgebraGenerated (H := H) S : Set (H →L[ℂ] H)) =
      (S ∪ star S).centralizer.centralizer := by
  -- This is exactly `StarSubalgebra.coe_centralizer_centralizer` specialized to `A = H →L[ℂ] H`.
  simpa [vonNeumannAlgebraGenerated] using
    (StarSubalgebra.coe_centralizer_centralizer (R := ℂ) (A := H →L[ℂ] H) (s := S))

/-- The generating set is contained in its double commutant. -/
theorem subset_vonNeumannAlgebraGenerated (S : Set (H →L[ℂ] H)) :
    S ⊆ (vonNeumannAlgebraGenerated (H := H) S : Set (H →L[ℂ] H)) := by
  intro x hx
  -- Work in the explicit set `(S ∪ star S)''`.
  have : x ∈ (S ∪ star S).centralizer.centralizer := by
    intro y hy
    -- `hy x` gives `x * y = y * x`, so flip sides.
    exact (hy x (Or.inl hx)).symm
  simpa [coe_vonNeumannAlgebraGenerated (H := H) (S := S)] using this

/-- The concrete von Neumann algebra on the GNS Hilbert space generated by the GNS operators
`πω(a) : Hω →L[ℂ] Hω`.

By definition this is the double commutant of the range of `πω`.
-/
noncomputable def gnsVonNeumannAlgebra : VonNeumannAlgebra (Hω (ω := ω)) :=
  vonNeumannAlgebraGenerated (H := Hω (ω := ω)) (Set.range fun a : A => (πω ω a))

/-- The GNS operators lie in the von Neumann algebra generated by the GNS representation. -/
theorem gnsVonNeumannAlgebra_contains_πω (a : A) :
    (πω ω a) ∈ (gnsVonNeumannAlgebra (ω := ω) : Set (Hω (ω := ω) →L[ℂ] Hω (ω := ω))) :=
  subset_vonNeumannAlgebraGenerated (H := Hω (ω := ω))
    (S := Set.range fun a : A => (πω ω a)) ⟨a, rfl⟩

end Construction
end GNS
