module

public import QuantumSystem.Algebra.VonNeumannAlgebra.Factor

/-!
# Central projections in a von Neumann algebra

A **central projection** of `N` is a projection lying in the centre `N ∩ N'`. This file records
the basic facts, in particular that in a *factor* the only central projections are the trivial
ones `0` and `1` — the projection-level expression of the triviality of the centre, and the seed
of "central support `= 1`" used in the comparison theory.

## Main definitions

* `VonNeumannAlgebra.IsCentralProjection N e` — `e` is a projection in `N ∩ N'`.

## Main results

* `VonNeumannAlgebra.IsFactor.central_projection_eq` — in a factor every central projection is
  `0` or `1`.
* `VonNeumannAlgebra.isStarProjection_mem_commutant_iff` — a star projection lies in the commutant
  `N'` exactly when its range is invariant under every element of `N` (the projection–reducing
  subspace bridge used to build central supports).
-/

@[expose] public section

namespace VonNeumannAlgebra

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- A **central projection** of `N`: a star projection lying in both `N` and its commutant
(equivalently, in the centre `N ∩ N'`). -/
def IsCentralProjection (N : VonNeumannAlgebra H) (e : H →L[ℂ] H) : Prop :=
  IsStarProjection e ∧ e ∈ N ∧ e ∈ N.commutant

/-- `0` is a central projection. -/
theorem isCentralProjection_zero (N : VonNeumannAlgebra H) : IsCentralProjection N 0 :=
  ⟨IsStarProjection.zero _, zero_mem _, zero_mem _⟩

/-- `1` is a central projection. -/
theorem isCentralProjection_one (N : VonNeumannAlgebra H) : IsCentralProjection N 1 :=
  ⟨IsStarProjection.one _, one_mem _, one_mem _⟩

/-- In a factor, every central projection is trivial: it is `0` or `1`. This is the
projection-level form of the triviality of the centre. -/
theorem IsFactor.central_projection_eq [Nontrivial H] {N : VonNeumannAlgebra H}
    (hN : IsFactor N) {e : H →L[ℂ] H} (he : IsCentralProjection N e) :
    e = 0 ∨ e = 1 := by
  obtain ⟨c, hc⟩ := hN e he.2.1 he.2.2
  have hidem : e * e = e := he.1.isIdempotentElem
  rw [hc] at hidem
  have hcc : (c * c) • (1 : H →L[ℂ] H) = c • 1 := by
    rw [← hidem, smul_mul_smul_comm, mul_one]
  have hc2 : c * c = c := smul_left_injective ℂ one_ne_zero hcc
  have h0 : c * (c - 1) = 0 := by rw [mul_sub, mul_one, hc2, sub_self]
  rcases mul_eq_zero.mp h0 with h | h
  · exact Or.inl (by rw [hc, h, zero_smul])
  · exact Or.inr (by rw [hc, sub_eq_zero.mp h, one_smul])

/-- A star projection lies in the commutant `N'` exactly when its range is invariant under every
element of `N`. This is the bridge between reducing subspaces and (eventually central)
projections: it follows from the double-commutant characterisation
`VonNeumannAlgebra.IsStarProjection.mem_iff` together with `commutant_commutant`. -/
theorem isStarProjection_mem_commutant_iff {N : VonNeumannAlgebra H} {e : H →L[ℂ] H}
    (he : IsStarProjection e) :
    e ∈ N.commutant ↔ ∀ y ∈ N, (e.range) ∈ Module.End.invtSubmodule (y : Module.End ℂ H) := by
  rw [IsStarProjection.mem_iff he N.commutant, commutant_commutant]

/-- **Central support (factor case).** In a factor, a nonzero operator `q` meets the
"`N`-orbit" of any nonzero `e ∈ N`: there is `a ∈ N` with `q a e ≠ 0`. The statement needs no
projection hypothesis on `e` or `q`, only `e ∈ N`, `e ≠ 0` and `q ≠ 0`. The proof takes the
orthogonal projection `P` onto the closed `N`-invariant subspace generated by `e H`; `P` reduces
both `N` and `N'`, so it is central, hence `0` or `1`; since `P` acts as the identity on `e H`
(so `P ≠ 0`, as `e ≠ 0`), `P = 1`, so the generated subspace is the whole space and `q` cannot
annihilate it. This is the geometric input of the comparison theorem. -/
theorem IsFactor.exists_mul_ne [Nontrivial H] {N : VonNeumannAlgebra H} (hN : IsFactor N)
    {e q : H →L[ℂ] H} (heN : e ∈ N) (he0 : e ≠ 0) (hq0 : q ≠ 0) : ∃ a ∈ N, q * a * e ≠ 0 := by
  by_contra hcon
  have hcon' : ∀ a ∈ N, q * a * e = 0 := fun a haN => by
    by_contra h; exact hcon ⟨a, haN, h⟩
  set S : Set H := {y | ∃ a ∈ N, ∃ x, (a : H →L[ℂ] H) (e x) = y} with hS
  set M : Submodule ℂ H := (Submodule.span ℂ S).topologicalClosure with hM
  set P : H →L[ℂ] H := M.starProjection with hP
  have hPproj : IsStarProjection P := isStarProjection_starProjection
  have hSsub : S ⊆ M := Submodule.subset_span.trans (Submodule.le_topologicalClosure _)
  have hSmem : ∀ (a : H →L[ℂ] H), a ∈ N → ∀ x, (a : H →L[ℂ] H) (e x) ∈ M :=
    fun a haN x => hSsub ⟨a, haN, x, rfl⟩
  have hinv : ∀ (y : H →L[ℂ] H), (∀ s ∈ S, y s ∈ M) →
      P.range ∈ Module.End.invtSubmodule (y : Module.End ℂ H) := by
    intro y hyS
    have hcomapclosed : IsClosed ((M.comap (y : H →ₗ[ℂ] H)) : Set H) := by
      rw [Submodule.comap_coe]
      exact ((Submodule.span ℂ S).isClosed_topologicalClosure).preimage y.continuous
    have hle : M ≤ M.comap (y : H →ₗ[ℂ] H) := by
      apply Submodule.topologicalClosure_minimal (Submodule.span ℂ S) _ hcomapclosed
      rw [Submodule.span_le]
      intro s hs
      simp only [Submodule.comap_coe, Set.mem_preimage, SetLike.mem_coe]
      exact hyS s hs
    rw [hP, Submodule.range_starProjection]; exact hle
  have hPcomm : P ∈ N.commutant := by
    rw [isStarProjection_mem_commutant_iff hPproj]
    intro y hyN
    refine hinv y ?_
    rintro s ⟨a, haN, x, rfl⟩
    rw [show y ((a : H →L[ℂ] H) (e x)) = (y * a) (e x) from rfl]
    exact hSmem (y * a) (mul_mem hyN haN) x
  have hPN : P ∈ N := by
    rw [IsStarProjection.mem_iff hPproj N]
    intro y hyN'
    refine hinv y ?_
    rintro s ⟨a, haN, x, rfl⟩
    have hay : a * y = y * a := mem_commutant_iff.mp hyN' a haN
    have hey : e * y = y * e := mem_commutant_iff.mp hyN' e heN
    have heq : y ((a : H →L[ℂ] H) (e x)) = (a : H →L[ℂ] H) (e (y x)) := by
      rw [show y ((a : H →L[ℂ] H) (e x)) = (y * a) (e x) from rfl, ← hay]
      rw [show (a * y) (e x) = (a : H →L[ℂ] H) (y (e x)) from rfl]
      rw [show y (e x) = (y * e) x from rfl, ← hey]; rfl
    rw [heq]; exact hSmem a haN (y x)
  have hPcentral : IsCentralProjection N P := ⟨hPproj, hPN, hPcomm⟩
  have hP1 : P = 1 := by
    rcases hN.central_projection_eq hPcentral with h0 | h1
    · exact absurd (by
        ext x
        have hpx : P (e x) = e x := by
          rw [hP, Submodule.starProjection_eq_self_iff]; exact hSmem 1 (one_mem _) x
        rw [h0] at hpx; simpa using hpx.symm : e = 0) he0
    · exact h1
  have hMtop : M = ⊤ := by
    have hMr : M = P.range := (Submodule.range_starProjection M).symm
    rw [hMr, hP1]; exact Submodule.eq_top_iff'.2 fun y => ⟨y, rfl⟩
  have hqM : M ≤ LinearMap.ker (q : H →ₗ[ℂ] H) := by
    apply Submodule.topologicalClosure_minimal (Submodule.span ℂ S) _ q.isClosed_ker
    rw [Submodule.span_le]
    rintro s ⟨a, haN, x, rfl⟩
    simp only [SetLike.mem_coe, LinearMap.mem_ker, ContinuousLinearMap.coe_coe]
    rw [show q ((a : H →L[ℂ] H) (e x)) = (q * a * e) x from rfl, hcon' a haN]; rfl
  apply hq0
  ext x
  have hx : x ∈ LinearMap.ker (q : H →ₗ[ℂ] H) := hqM (hMtop ▸ Submodule.mem_top)
  simpa using hx

end VonNeumannAlgebra
