module

public import QuantumSystem.Algebra.VonNeumannAlgebra.SpatialDecomposition
public import QuantumSystem.Algebra.VonNeumannAlgebra.TensorFactor
public import QuantumSystem.Algebra.Star.DoubleCommutant.SOTClosedSubAlgebra
public import QuantumSystem.ForMathlib.Analysis.VonNeumannAlgebra.Commutant
public import Mathlib.Algebra.Star.Subalgebra

/-!
# The structure theorem for type I factors

This file proves the spatial structure theorem for a type I factor `N ⊆ B(H)` with minimal
projection `e`: there is a linear isometric equivalence `U : H ≃ₗᵢ ℓ²(F) ⊗̂ (eH)` under which `N`
becomes exactly the tensor factor `B(ℓ²(F)) ⊗̄ 1` and `N'` becomes the right factor `1 ⊗̄ B(eH)`.
The ingredients — the covering orthogonal family `F` (`OrthEquivFam`), the matrix units
`e_{pq} = v_p v_q⋆`, and the spatial isomorphism `multiplicityEquiv` — are built in
`QuantumSystem.Algebra.VonNeumannAlgebra.SpatialDecomposition`. The proof here has two halves.

**Generation half.** The system of matrix units generates `N` as a von Neumann algebra:

> `VonNeumannAlgebra.generated S = N`,   where `S = { e_{pq} | p q : F }`.

This is the von-Neumann-algebraic (double-commutant) reformulation of the strong-operator
reconstruction `a = Σ_{pq} c_{pq}(a) e_{pq}`. The reformulation avoids any strong/weak-operator
infinite-sum API (which Mathlib lacks) by working through the commutant: the inclusion `S'' ⊆ N`
is monotonicity, and the content `N ⊆ S''` is the statement that every operator commuting with all
matrix units commutes with all of `N`. The proof of that content
(`commutes_of_mem_centralizer`) is genuinely analytic: it inserts the resolution of the identity
`Σ_r p_r = 1` (here `p_r = e_{rr} = v_r v_r⋆`) as a `HasSum`, and uses that each `↑p · a · ↑r` is
a *scalar* multiple of the matrix unit `e_{pr}` (multiplicity one, `exists_matrixEntry`), hence
commutes with `b`. The sum over the possibly-infinite index set `F` is handled throughout by
`HasSum`/`HasSum.mapL`/`HasSum.unique`; no operator-level infinite series is formed.

**Identification half.** The identification glues the generation theorem `N = ⟨matrix units⟩''`
to the tensor commutation theorem (`QuantumSystem.Algebra.VonNeumannAlgebra.TensorFactor`) through
the spatial isomorphism `U = multiplicityEquiv ∘ lpTensorEquiv`. The key computation is that `U`
carries the matrix unit `e_{pq}` to the amplified rank-one operator `|δ_p⟩⟨δ_q| ⊗̂ 1`, where
`δ_p = lp.single 2 p 1` is the `p`-th standard basis vector of `ℓ²(F)`.

## Main results

* `VonNeumannAlgebra.OrthEquivFam.hasSum_resolutionOfIdentity` — the resolution of the identity
  `HasSum (fun i : F => (↑i) y) y`, the analytic core.
* `VonNeumannAlgebra.OrthEquivFam.commutes_of_mem_centralizer` — an operator commuting with every
  matrix unit commutes with every element of `N`.
* `VonNeumannAlgebra.OrthEquivFam.generated_matrixUnits_eq` — **the matrix units generate `N`**:
  `generated S = N`.
* `VonNeumannAlgebra.OrthEquivFam.mem_sotClosure_adjoin` — the literal SOT-reconstruction corollary:
  every `a ∈ N` lies in the SOT-closure of the `*`-subalgebra generated by the matrix units.
* `VonNeumannAlgebra.OrthEquivFam.coe_multiplicityEquiv_apply` — the explicit `i`-th coordinate of
  `U y`: `(multiplicityEquiv y) i = v_i⋆ y`.
* `VonNeumannAlgebra.OrthEquivFam.hasSum_tmul_spatialEquiv` — the resulting expansion
  `U y = ∑ᵢ δᵢ ⊗̂ (v_i⋆ y)`.
* `VonNeumannAlgebra.OrthEquivFam.conjStarAlgEquiv_matrixUnit` — `U e_{pq} U⋆ = |δ_p⟩⟨δ_q| ⊗̂ 1`.
* `VonNeumannAlgebra.OrthEquivFam.conj_spatialEquiv_eq_vnTensorLeft` — the identification
  `U N U⋆ = B(ℓ²(F)) ⊗̄ 1`, with commutant companion `conj_spatialEquiv_commutant_eq_vnTensorRight`.
* `VonNeumannAlgebra.IsFactor.exists_spatial_tensor_decomposition` — the existence headline.
* `VonNeumannAlgebra.IsFactor.exists_split_tensor_decomposition` — the split tensor decomposition:
  for an inclusion `A ≤ B` of von Neumann algebras with intermediate type I factor `A ≤ N ≤ B` —
  a *split inclusion* in the sense of Doplicher–Longo (see
  `VonNeumannAlgebra.IsSplitInclusion`) — the same `U` sends `A` into `B(ℓ²(F)) ⊗̄ 1` and the
  commutant `B′` into `1 ⊗̄ B(eH)`.

## References

* [Yngvason] J. Yngvason, *Localization and Entanglement in Relativistic Quantum Physics*, in
  *The Message of Quantum Science*, Lecture Notes in Physics 899, Springer 2015, pp. 325–348;
  arXiv:1401.2652. Its §5.1 ("Causal Independence and Split Property") displays the two equations
  cited below as `(38)`, `𝒜₁ ⊂ 𝒩 ⊂ 𝒜₂′`, and `(39)`, `𝒜₁ ⊂ ℬ(ℋ₁) ⊗ 𝟏` and `𝒜₂ ⊂ 𝟏 ⊗ ℬ(ℋ₂)`.
* [DL84] S. Doplicher, R. Longo, *Standard and split inclusions of von Neumann algebras*,
  Invent. Math. 75 (1984) 493–536.
* [dB74] D. Buchholz, *Product states for local algebras*, Comm. Math. Phys. 36 (1974) 287–304.

## Notation

`⊗̄` in the prose above is documentation shorthand for the von Neumann (spatial) tensor product of
algebras; that convention is stated in full in `QuantumSystem.Algebra.VonNeumannAlgebra.TensorFactor`,
where the algebras it names (`HilbertTensor.vnTensorLeft` / `vnTensorRight`) are defined.
-/

@[expose] public section

open scoped TensorProduct

namespace VonNeumannAlgebra

open StrongOperatorTopology HilbertTensor

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable {N : VonNeumannAlgebra H} {e : H →L[ℂ] H} {F : Set (H →L[ℂ] H)}

/-! ### The matrix units generate the factor -/

/-- The set of matrix units is contained in `N`. -/
lemma OrthEquivFam.matrixUnit_subset (hF : OrthEquivFam N e F) :
    Set.range (fun pq : F × F => hF.matrixUnit pq.1 pq.2) ⊆ (N : Set (H →L[ℂ] H)) := by
  rintro x ⟨pq, rfl⟩
  exact hF.matrixUnit_mem pq.1 pq.2

/-- **Resolution of the identity.** For a covering orthogonal family, the projections `↑i` sum to
the identity in the strong operator sense: `HasSum (fun i : F => (↑i) y) y` for every `y`. This is
the analytic heart of the generation theorem; it is the Hilbert-sum reconstruction of `y` from its
coordinates, with the `i`-th coordinate recognised as the orthogonal projection `(↑i) y` by
`coe_hilbertSumEquiv_apply`. -/
theorem OrthEquivFam.hasSum_resolutionOfIdentity (hF : OrthEquivFam N e F)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤) (y : H) :
    HasSum (fun i : F => (i : H →L[ℂ] H) y) y := by
  have hdecomp : HasSum
      (fun i : F => ((hF.hilbertSumEquiv htop y i :
          LinearMap.range ((i : H →L[ℂ] H) : H →ₗ[ℂ] H)) : H)) y := by
    have h := (hF.isHilbertSum htop).hasSum_linearIsometryEquiv_symm (hF.hilbertSumEquiv htop y)
    have hy : (hF.isHilbertSum htop).linearIsometryEquiv.symm (hF.hilbertSumEquiv htop y) = y :=
      (hF.hilbertSumEquiv htop).symm_apply_apply y
    rwa [hy] at h
  simpa only [hF.coe_hilbertSumEquiv_apply htop y] using hdecomp

/-- **The content of the generation theorem.** Any operator `b` commuting with every matrix unit
commutes with every `a ∈ N`. Equivalently `Set.centralizer S ⊆ Set.centralizer N`, which is the
nontrivial inclusion `N ⊆ S''`.

The proof tests `a * b = b * a` against arbitrary inner products. Inserting the resolution of the
identity `Σ_r p_r = 1` between and around `a`, the commutator reduces to the family of operators
`↑p · a · ↑r`, each of which equals a *scalar* multiple of the matrix unit `e_{pr}`
(`exists_matrixEntry`) and therefore commutes with `b`. -/
theorem OrthEquivFam.commutes_of_mem_centralizer (hF : OrthEquivFam N e F)
    (he : IsMinimalProjection N e)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    {a : H →L[ℂ] H} (ha : a ∈ N) {b : H →L[ℂ] H}
    (hb : b ∈ Set.centralizer (Set.range (fun pq : F × F => hF.matrixUnit pq.1 pq.2))) :
    a * b = b * a := by
  have hbcomm : ∀ p q : F, hF.matrixUnit p q * b = b * hF.matrixUnit p q :=
    fun p q => (Set.mem_centralizer_iff.mp hb) _ ⟨(p, q), rfl⟩
  -- `↑p · a · ↑r` is a scalar multiple of `e_{pr}`, hence commutes with `b`.
  have hcomm_T : ∀ p r : F, ((p : H →L[ℂ] H) * a * (r : H →L[ℂ] H)) * b
      = b * ((p : H →L[ℂ] H) * a * (r : H →L[ℂ] H)) := by
    intro p r
    obtain ⟨c, hc⟩ := hF.exists_matrixEntry he p r ha
    have hT : (p : H →L[ℂ] H) * a * (r : H →L[ℂ] H) = c • hF.matrixUnit p r := by
      rw [← hF.pisom_range p, ← hF.pisom_range r]
      calc hF.pisom p * star (hF.pisom p) * a * (hF.pisom r * star (hF.pisom r))
          = hF.pisom p * (star (hF.pisom p) * a * hF.pisom r) * star (hF.pisom r) := by
            simp only [mul_assoc]
        _ = hF.pisom p * (c • e) * star (hF.pisom r) := by rw [hc]
        _ = c • (hF.pisom p * e * star (hF.pisom r)) := by rw [mul_smul_comm, smul_mul_assoc]
        _ = c • (hF.pisom p * star (hF.pisom r)) := by rw [hF.pisom_mul_source p]
        _ = c • hF.matrixUnit p r := rfl
    rw [hT, smul_mul_assoc, hbcomm p r, mul_smul_comm]
  -- Test `a * b = b * a` against inner products.
  apply ContinuousLinearMap.ext
  intro y
  apply ext_inner_left ℂ
  intro x
  -- For each `r`, the `r`-summands agree (insert `Σ_p p_p` to the left of `a`).
  have step : ∀ r : F, inner ℂ x ((a * (r : H →L[ℂ] H) * b) y)
      = inner ℂ x ((b * a * (r : H →L[ℂ] H)) y) := by
    intro r
    have hLp : HasSum
        (fun p : F => inner ℂ x (((p : H →L[ℂ] H) * a * (r : H →L[ℂ] H) * b) y))
        (inner ℂ x ((a * (r : H →L[ℂ] H) * b) y)) := by
      have h := (hF.hasSum_resolutionOfIdentity htop ((a * (r : H →L[ℂ] H) * b) y)).mapL (innerSL ℂ x)
      simpa only [innerSL_apply_apply, ContinuousLinearMap.mul_apply] using h
    have hRp : HasSum
        (fun p : F => inner ℂ x ((b * (p : H →L[ℂ] H) * a * (r : H →L[ℂ] H)) y))
        (inner ℂ x ((b * a * (r : H →L[ℂ] H)) y)) := by
      have h := (((hF.hasSum_resolutionOfIdentity htop ((a * (r : H →L[ℂ] H)) y)).mapL b).mapL (innerSL ℂ x))
      simpa only [innerSL_apply_apply, ContinuousLinearMap.mul_apply] using h
    have hfun : (fun p : F => inner ℂ x (((p : H →L[ℂ] H) * a * (r : H →L[ℂ] H) * b) y))
        = (fun p : F => inner ℂ x ((b * (p : H →L[ℂ] H) * a * (r : H →L[ℂ] H)) y)) := by
      funext p
      have hkey : (p : H →L[ℂ] H) * a * (r : H →L[ℂ] H) * b
          = b * (p : H →L[ℂ] H) * a * (r : H →L[ℂ] H) := by
        rw [hcomm_T p r, ← mul_assoc, ← mul_assoc]
      rw [hkey]
    rw [hfun] at hLp
    exact hLp.unique hRp
  have hL : HasSum (fun r : F => inner ℂ x ((a * (r : H →L[ℂ] H) * b) y))
      (inner ℂ x ((a * b) y)) := by
    have h := ((hF.hasSum_resolutionOfIdentity htop (b y)).mapL a).mapL (innerSL ℂ x)
    simpa only [innerSL_apply_apply, ContinuousLinearMap.mul_apply] using h
  have hR : HasSum (fun r : F => inner ℂ x ((b * a * (r : H →L[ℂ] H)) y))
      (inner ℂ x ((b * a) y)) := by
    have h := ((hF.hasSum_resolutionOfIdentity htop y).mapL (b * a)).mapL (innerSL ℂ x)
    simpa only [innerSL_apply_apply, ContinuousLinearMap.mul_apply] using h
  rw [funext step] at hL
  exact hL.unique hR

/-- The centralizer of the matrix units is contained in the commutant of `N`. -/
lemma OrthEquivFam.centralizer_subset_commutant (hF : OrthEquivFam N e F)
    (he : IsMinimalProjection N e)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤) :
    Set.centralizer (Set.range (fun pq : F × F => hF.matrixUnit pq.1 pq.2))
      ⊆ Set.centralizer (N : Set (H →L[ℂ] H)) := by
  intro b hb
  rw [Set.mem_centralizer_iff]
  intro a ha
  exact hF.commutes_of_mem_centralizer he htop ha hb

/-- **Matrix units generate the type I factor.** The von Neumann algebra generated by the system of
matrix units `e_{pq} = v_p v_q⋆` is `N`. This is the von-Neumann-algebraic form of the structure
theorem `N ≅ B(ℓ²(F)) ⊗̄ 1`. -/
theorem OrthEquivFam.generated_matrixUnits_eq (hF : OrthEquivFam N e F)
    (he : IsMinimalProjection N e)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤) :
    VonNeumannAlgebra.generated (Set.range (fun pq : F × F => hF.matrixUnit pq.1 pq.2)) = N := by
  set S := Set.range (fun pq : F × F => hF.matrixUnit pq.1 pq.2) with hSdef
  apply le_antisymm
  · exact VonNeumannAlgebra.generated_le hF.matrixUnit_subset
  · intro a ha
    rw [← SetLike.mem_coe]
    change a ∈ ((VonNeumannAlgebra.commutantSet S).commutant : Set (H →L[ℂ] H))
    rw [VonNeumannAlgebra.coe_commutant, VonNeumannAlgebra.coe_commutantSet]
    have hsub : (S ∪ star S).centralizer ⊆ (N : Set (H →L[ℂ] H)).centralizer :=
      (Set.centralizer_subset Set.subset_union_left).trans (hF.centralizer_subset_commutant he htop)
    have h2 : ((N : Set (H →L[ℂ] H)).centralizer).centralizer
        ⊆ ((S ∪ star S).centralizer).centralizer := Set.centralizer_subset hsub
    exact h2 (Set.subset_centralizer_centralizer (SetLike.mem_coe.mpr ha))

/-- **SOT reconstruction (corollary).** Every `a ∈ N` lies in the strong-operator closure of the
`*`-subalgebra generated by the matrix units. This is the literal `a = Σ_{pq} c_{pq}(a) e_{pq}`
content of the structure theorem, in closure form, obtained from the generation theorem and the SOT
double commutant theorem. -/
theorem OrthEquivFam.mem_sotClosure_adjoin (hF : OrthEquivFam N e F)
    (he : IsMinimalProjection N e)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    {a : H →L[ℂ] H} (ha : a ∈ N) :
    (⟨a⟩ : ContinuousLinearMapSOT H) ∈ closure (Set.toSOT
      (StarAlgebra.adjoin ℂ (Set.range (fun pq : F × F => hF.matrixUnit pq.1 pq.2)) :
        Set (H →L[ℂ] H))) := by
  set S := Set.range (fun pq : F × F => hF.matrixUnit pq.1 pq.2) with hSdef
  apply SOTClosedSubalgebra.mem_sotClosure_of_mem_doubleCommutant (StarAlgebra.adjoin ℂ S) a
  have hunion : S ∪ star S ⊆ (StarAlgebra.adjoin ℂ S : Set (H →L[ℂ] H)) := by
    refine Set.union_subset (StarAlgebra.subset_adjoin ℂ S) ?_
    intro y hy
    rw [Set.mem_star] at hy
    have hya : star y ∈ (StarAlgebra.adjoin ℂ S : Set (H →L[ℂ] H)) :=
      StarAlgebra.subset_adjoin ℂ S hy
    have := star_mem (s := StarAlgebra.adjoin ℂ S) hya
    rwa [star_star] at this
  have hgen : (VonNeumannAlgebra.generated S : Set (H →L[ℂ] H))
      = Set.centralizer (Set.centralizer (S ∪ star S)) := by
    change ((VonNeumannAlgebra.commutantSet S).commutant : Set (H →L[ℂ] H)) = _
    rw [VonNeumannAlgebra.coe_commutant, VonNeumannAlgebra.coe_commutantSet]
  have hmono : Set.centralizer (Set.centralizer (S ∪ star S))
      ⊆ Set.centralizer (Set.centralizer (StarAlgebra.adjoin ℂ S : Set (H →L[ℂ] H))) :=
    Set.centralizer_subset (Set.centralizer_subset hunion)
  apply hmono
  have hmem : a ∈ (VonNeumannAlgebra.generated S : Set (H →L[ℂ] H)) := by
    rw [hF.generated_matrixUnits_eq he htop]; exact SetLike.mem_coe.mpr ha
  rwa [hgen] at hmem

/-! ### Spatial identification with the tensor factor `B(ℓ²(F)) ⊗̄ 1` -/

/-- The `i`-th standard basis vector `δ_i = lp.single 2 i 1` of `ℓ²(F) = lp (fun _ : F => ℂ) 2`.
This is a thin wrapper whose only purpose is to pin the index family `fun _ : F => ℂ`, so that the
basis vectors are unambiguous in scalar positions (such as inner products). -/
noncomputable def lpDelta [DecidableEq F] (i : F) : lp (fun _ : F => ℂ) 2 :=
  lp.single (E := fun _ : F => ℂ) 2 i (1 : ℂ)

/-- `δ i` abbreviates the standard basis vector `lpDelta i` of `ℓ²(F)`, matching the `δ_i` of the
informal text. (A Dirac bra-ket `|x⟩⟨y|` notation for the rank-one operator is deliberately not
introduced here: a leading `|` token collides with the set-builder `{y | … }` used in the `htop`
hypotheses throughout this file.) -/
local notation "δ" => lpDelta

omit [CompleteSpace H] in
/-- `δ_i` unfolds to the `ℓ²` standard basis vector `lp.single 2 i 1`. -/
lemma lpDelta_apply [DecidableEq F] (i : F) :
    lpDelta i = lp.single (E := fun _ : F => ℂ) 2 i (1 : ℂ) := rfl

omit [CompleteSpace H] in
/-- The basis vectors `δ_i` are unit vectors. -/
lemma lpDelta_norm [DecidableEq F] (i : F) : ‖lpDelta i‖ = 1 := by
  rw [lpDelta_apply, lp.norm_single (by norm_num), norm_one]

omit [CompleteSpace H] in
/-- The standard basis vectors `δ_i` span a dense subspace of `ℓ²(F)`. -/
lemma dense_span_lpDelta [DecidableEq F] :
    Dense (Submodule.span ℂ (Set.range (lpDelta : F → lp (fun _ : F => ℂ) 2)) :
      Set (lp (fun _ : F => ℂ) 2)) := by
  intro g
  have hsum : HasSum (fun i : F => lp.single (E := fun _ : F => ℂ) 2 i (g i)) g :=
    lp.hasSum_single (by norm_num) g
  refine mem_closure_of_tendsto hsum (Filter.Eventually.of_forall (fun s => ?_))
  refine Submodule.sum_mem _ (fun i _ => ?_)
  rw [show lp.single (E := fun _ : F => ℂ) 2 i (g i) = (g i) • lpDelta i by
    rw [lpDelta_apply, ← lp.single_smul, smul_eq_mul, mul_one]]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

/-- **Explicit multiplicity coordinate.** Under the spatial decomposition the `i`-th coordinate of
`y` in `ℓ²(F; eH)` is `v_i⋆ y`, where `v_i` is the equivalence partial isometry `e ≅ i`. -/
theorem OrthEquivFam.coe_multiplicityEquiv_apply (hF : OrthEquivFam N e F)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    (y : H) (i : F) :
    ((hF.multiplicityEquiv htop y i : LinearMap.range (e : H →ₗ[ℂ] H)) : H)
      = star (hF.pisom i) y := by
  have hop : star (hF.pisom i) * (i : H →L[ℂ] H) = star (hF.pisom i) := by
    rw [← hF.pisom_range i, ← mul_assoc, hF.pisom_source i, hF.e_mul_star_pisom i]
  have h1 : ((hF.multiplicityEquiv htop y i : LinearMap.range (e : H →ₗ[ℂ] H)) : H)
      = star (hF.pisom i)
          ((hF.hilbertSumEquiv htop y i : LinearMap.range ((i : H →L[ℂ] H) : H →ₗ[ℂ] H)) : H) :=
    (hF.pisom_isPI i).coe_sourceRangeEquiv_symm (hF.pisom_source i) (hF.pisom_range i) _
  rw [h1, hF.coe_hilbertSumEquiv_apply htop y i, ← ContinuousLinearMap.mul_apply, hop]

/-- **The spatial isomorphism.** A covering orthogonal family of `e`-equivalent projections gives a
linear isometric equivalence `U : H ≃ₗᵢ ℓ²(F) ⊗̂ (eH)` of `H` with the completed Hilbert tensor
product, identifying `H` with `ℓ²(F) ⊗̂ (eH)` via `multiplicityEquiv` and the tensor bridge. This is
the isomorphism implementing the type I structure theorem `N ≅ B(ℓ²(F)) ⊗̄ 1`. -/
noncomputable def OrthEquivFam.spatialEquiv (hF : OrthEquivFam N e F)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    [CompleteSpace (LinearMap.range (e : H →ₗ[ℂ] H))] [DecidableEq F] :
    H ≃ₗᵢ[ℂ] HilbertTensor (lp (fun _ : F => ℂ) 2) (LinearMap.range (e : H →ₗ[ℂ] H)) :=
  (hF.multiplicityEquiv htop).trans (lpTensorEquiv (ι := F) (K := LinearMap.range (e : H →ₗ[ℂ] H)))

/-- **Spatial expansion of `U`.** The spatial isomorphism `U = multiplicityEquiv ∘ lpTensorEquiv`
expands a vector as `U y = ∑ᵢ δᵢ ⊗̂ (i-th multiplicity coordinate of y)`. -/
theorem OrthEquivFam.hasSum_tmul_spatialEquiv (hF : OrthEquivFam N e F)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    [CompleteSpace (LinearMap.range (e : H →ₗ[ℂ] H))] [DecidableEq F] (y : H) :
    HasSum (fun i : F => tmul (δ i) (hF.multiplicityEquiv htop y i))
      (hF.spatialEquiv htop y) := by
  have h := (lp.hasSum_single (E := fun _ : F => LinearMap.range (e : H →ₗ[ℂ] H)) (p := 2)
      (by norm_num) (hF.multiplicityEquiv htop y)).mapL
      (lpTensorEquiv (ι := F)
        (K := LinearMap.range (e : H →ₗ[ℂ] H))).toLinearIsometry.toContinuousLinearMap
  simpa only [OrthEquivFam.spatialEquiv, lpDelta, LinearIsometryEquiv.coe_toLinearIsometry,
    LinearIsometry.coe_toContinuousLinearMap, lpTensorEquiv_single,
    LinearIsometryEquiv.trans_apply] using h

attribute [local irreducible] OrthEquivFam.spatialEquiv OrthEquivFam.multiplicityEquiv

/-- The `p`-th coordinate of `U (e_{pq} y)` collapses to the single term `δ_p ⊗̂ (v_q⋆ y)`: every
other coordinate vanishes because `v_i⋆ e_{pq} = 0` for `i ≠ p`. -/
lemma OrthEquivFam.spatialEquiv_matrixUnit_apply (hF : OrthEquivFam N e F)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    [CompleteSpace (LinearMap.range (e : H →ₗ[ℂ] H))] [DecidableEq F] (p q : F) (y : H) :
    hF.spatialEquiv htop (hF.matrixUnit p q y)
      = tmul (δ p) (hF.multiplicityEquiv htop (hF.matrixUnit p q y) p) := by
  refine (hF.hasSum_tmul_spatialEquiv htop (hF.matrixUnit p q y)).unique ?_
  refine hasSum_single p (fun i hi => ?_)
  have hcoe : ((hF.multiplicityEquiv htop (hF.matrixUnit p q y) i :
      LinearMap.range (e : H →ₗ[ℂ] H)) : H) = 0 := by
    rw [hF.coe_multiplicityEquiv_apply htop]
    have h0 : star (hF.pisom i) * hF.matrixUnit p q = 0 := by
      rw [OrthEquivFam.matrixUnit_def, ← mul_assoc,
        hF.star_pisom_mul_pisom_of_ne hi, zero_mul]
    rw [← ContinuousLinearMap.mul_apply, h0, ContinuousLinearMap.zero_apply]
  rw [show hF.multiplicityEquiv htop (hF.matrixUnit p q y) i = 0 from
    Subtype.ext (by rw [hcoe]; rfl), ← tmulRightL_apply, map_zero]

/-- The surviving coordinates agree: `v_p⋆ (e_{pq} y) = v_q⋆ y`. -/
lemma OrthEquivFam.multiplicityEquiv_matrixUnit_coord (hF : OrthEquivFam N e F)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    (p q : F) (y : H) :
    hF.multiplicityEquiv htop (hF.matrixUnit p q y) p = hF.multiplicityEquiv htop y q := by
  apply Subtype.ext
  rw [hF.coe_multiplicityEquiv_apply htop, hF.coe_multiplicityEquiv_apply htop]
  have hpp : star (hF.pisom p) * hF.matrixUnit p q = star (hF.pisom q) := by
    rw [OrthEquivFam.matrixUnit_def, ← mul_assoc, hF.pisom_source p, hF.e_mul_star_pisom q]
  rw [← ContinuousLinearMap.mul_apply, hpp]

/-- The amplified rank-one operator on `U y` collapses to the single term `δ_p ⊗̂ (v_q⋆ y)`: the
rank-one operator picks out the `q`-th coordinate. -/
lemma OrthEquivFam.amplifyLeft_rankOne_spatialEquiv (hF : OrthEquivFam N e F)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    [CompleteSpace (LinearMap.range (e : H →ₗ[ℂ] H))] [DecidableEq F] (p q : F) (y : H) :
    amplifyLeft (InnerProductSpace.rankOne ℂ (δ p) (δ q)) (hF.spatialEquiv htop y)
      = tmul (δ p) (hF.multiplicityEquiv htop y q) := by
  have key : ∀ i : F, amplifyLeft (InnerProductSpace.rankOne ℂ (δ p) (δ q))
      (tmul (δ i) (hF.multiplicityEquiv htop y i))
      = (inner ℂ (δ q) (δ i) : ℂ) • tmul (δ p) (hF.multiplicityEquiv htop y i) :=
    fun i => by rw [amplifyLeft_tmul, InnerProductSpace.rankOne_apply, tmul_smul_left]
  have hqq : (inner ℂ (δ q) (δ q) : ℂ) = 1 := by
    rw [lpDelta_apply, lp.inner_single_left, lp.coeFn_single, Pi.single_eq_same,
      RCLike.inner_apply, map_one, mul_one]
  have hz : ∀ i : F, i ≠ q → amplifyLeft (InnerProductSpace.rankOne ℂ (δ p) (δ q))
      (tmul (δ i) (hF.multiplicityEquiv htop y i)) = 0 := by
    intro i hi
    have hzero : (inner ℂ (δ q) (δ i) : ℂ) = 0 := by
      rw [lpDelta_apply, lpDelta_apply, lp.inner_single_left, lp.coeFn_single,
        Pi.single_eq_of_ne (Ne.symm hi), inner_zero_right]
    rw [key i, hzero, zero_smul]
  have hval : amplifyLeft (InnerProductSpace.rankOne ℂ (δ p) (δ q))
      (tmul (δ q) (hF.multiplicityEquiv htop y q))
      = tmul (δ p) (hF.multiplicityEquiv htop y q) := by
    rw [key q, hqq, one_smul]
  exact (((hF.hasSum_tmul_spatialEquiv htop y).mapL
    (amplifyLeft (InnerProductSpace.rankOne ℂ (δ p) (δ q)))).unique
    (hasSum_single q hz)).trans hval

/-- **Intertwining relation.** The spatial isomorphism intertwines the matrix unit `e_{pq}` with
the amplified rank-one operator: `U (e_{pq} y) = (|δ_p⟩⟨δ_q| ⊗̂ 1) (U y)`. -/
lemma OrthEquivFam.spatialEquiv_intertwine (hF : OrthEquivFam N e F)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    [CompleteSpace (LinearMap.range (e : H →ₗ[ℂ] H))] [DecidableEq F] (p q : F) (y : H) :
    hF.spatialEquiv htop (hF.matrixUnit p q y)
      = amplifyLeft (InnerProductSpace.rankOne ℂ (δ p) (δ q)) (hF.spatialEquiv htop y) :=
  (hF.spatialEquiv_matrixUnit_apply htop p q y).trans
    ((congrArg (tmul (δ p)) (hF.multiplicityEquiv_matrixUnit_coord htop p q y)).trans
      (hF.amplifyLeft_rankOne_spatialEquiv htop p q y).symm)

/-- **Matrix unit identifies with an amplified rank-one operator.** Under the spatial isomorphism
`U`, the matrix unit `e_{pq}` is carried to the amplification of the rank-one operator
`|δ_p⟩⟨δ_q|` on `ℓ²(F)`: `U e_{pq} U⋆ = |δ_p⟩⟨δ_q| ⊗̂ 1`. This is the algebraic heart of the
identification `N ≅ B(ℓ²(F)) ⊗̄ 1`. -/
theorem OrthEquivFam.conjStarAlgEquiv_matrixUnit (hF : OrthEquivFam N e F)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    [CompleteSpace (LinearMap.range (e : H →ₗ[ℂ] H))] [DecidableEq F] (p q : F) :
    (hF.spatialEquiv htop).conjStarAlgEquiv (hF.matrixUnit p q)
      = amplifyLeft (InnerProductSpace.rankOne ℂ (δ p) (δ q)) := by
  refine ContinuousLinearMap.ext fun w => ?_
  rw [LinearIsometryEquiv.conjStarAlgEquiv_apply_apply]
  exact (hF.spatialEquiv_intertwine htop p q ((hF.spatialEquiv htop).symm w)).trans
    (congrArg (amplifyLeft (InnerProductSpace.rankOne ℂ (δ p) (δ q)))
      (LinearIsometryEquiv.apply_symm_apply (hF.spatialEquiv htop) w))

omit [CompleteSpace H] in
/-- **The amplified basis rank-one operators generate `B(ℓ²(F)) ⊗̄ 1`.** The von Neumann algebra
generated by `{|δ_p⟩⟨δ_q| ⊗̂ 1 : p q : F}` is the tensor factor `vnTensorLeft = B(ℓ²(F)) ⊗̄ 1`. The
proof computes the commutant: an operator commuting with all the amplified rank-one operators lies
in `1 ⊗̄ B(eH)` (the dense slice lemma, using that `{δ_p}` spans densely), and conversely
`1 ⊗̄ B(eH)` commutes with them; so the commutant is `vnTensorRight`, whose commutant is
`vnTensorLeft`. -/
lemma generated_amplifyLeft_rankOne_eq [Nonempty F] [DecidableEq F]
    [CompleteSpace (LinearMap.range (e : H →ₗ[ℂ] H))] :
    VonNeumannAlgebra.generated (Set.range (fun pq : F × F =>
        amplifyLeft (H₂ := LinearMap.range (e : H →ₗ[ℂ] H))
          (InnerProductSpace.rankOne ℂ (δ pq.1) (δ pq.2))))
      = vnTensorLeft := by
  set T := Set.range (fun pq : F × F => amplifyLeft (H₂ := LinearMap.range (e : H →ₗ[ℂ] H))
    (InnerProductSpace.rankOne ℂ (δ pq.1) (δ pq.2))) with hTdef
  have hcomm : VonNeumannAlgebra.commutantSet T = vnTensorRight := by
    refine le_antisymm (fun x hx => ?_) ?_
    · refine mem_vnTensorRight_of_commutes_dense (δ (Classical.arbitrary F))
        (lpDelta_norm _) (Set.range lpDelta) dense_span_lpDelta x (fun f hf => ?_)
      obtain ⟨p, rfl⟩ := hf
      have hg : amplifyLeft (H₂ := LinearMap.range (e : H →ₗ[ℂ] H))
          (InnerProductSpace.rankOne ℂ (δ p) (δ (Classical.arbitrary F))) ∈ T :=
        ⟨(p, Classical.arbitrary F), rfl⟩
      have hcx := (VonNeumannAlgebra.mem_commutantSet_iff.mp hx _ hg).1
      exact hcx.symm
    · refine VonNeumannAlgebra.generated_le ?_
      rintro g ⟨B, rfl⟩
      rw [SetLike.mem_coe, VonNeumannAlgebra.mem_commutantSet_iff]
      rintro h ⟨pq, rfl⟩
      refine ⟨amplifyLeft_comp_amplifyRight
        (InnerProductSpace.rankOne ℂ (δ pq.1) (δ pq.2)) B, ?_⟩
      rw [amplifyLeft_star]
      exact amplifyLeft_comp_amplifyRight
        (star (InnerProductSpace.rankOne ℂ (δ pq.1) (δ pq.2))) B
  haveI : Nontrivial (lp (fun _ : F => ℂ) 2) :=
    ⟨lpDelta (Classical.arbitrary F), 0, by
      rw [← norm_ne_zero_iff, lpDelta_norm]; norm_num⟩
  exact (congrArg VonNeumannAlgebra.commutant hcomm).trans
    (vnTensorRight_commutant (H₁ := lp (fun _ : F => ℂ) 2)
      (H₂ := LinearMap.range (e : H →ₗ[ℂ] H)))

/-- **Type I factor structure theorem (explicit identification).** Under the spatial isomorphism
`U : H ≃ₗᵢ ℓ²(F) ⊗̂ (eH)`, the type I factor `N` is carried exactly onto the tensor factor
`B(ℓ²(F)) ⊗̄ 1`: `U N U⋆ = B(ℓ²(F)) ⊗̄ 1`. This glues the matrix-unit generation theorem
`N = ⟨e_{pq}⟩''` to the identification `U e_{pq} U⋆ = |δ_p⟩⟨δ_q| ⊗̂ 1` through the fact that the
spatial conjugation commutes with the generated-algebra construction. -/
theorem OrthEquivFam.conj_spatialEquiv_eq_vnTensorLeft (hF : OrthEquivFam N e F)
    (he : IsMinimalProjection N e)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    [Nonempty F] [DecidableEq F] [CompleteSpace (LinearMap.range (e : H →ₗ[ℂ] H))] :
    VonNeumannAlgebra.conj (hF.spatialEquiv htop) N = vnTensorLeft := by
  have himg : ⇑(hF.spatialEquiv htop).conjStarAlgEquiv ''
      (Set.range (fun pq : F × F => hF.matrixUnit pq.1 pq.2))
      = Set.range (fun pq : F × F =>
        amplifyLeft (H₂ := LinearMap.range (e : H →ₗ[ℂ] H))
          (InnerProductSpace.rankOne ℂ (δ pq.1) (δ pq.2))) := by
    rw [← Set.range_comp]
    exact congrArg Set.range (funext fun pq => hF.conjStarAlgEquiv_matrixUnit htop pq.1 pq.2)
  calc VonNeumannAlgebra.conj (hF.spatialEquiv htop) N
      = VonNeumannAlgebra.conj (hF.spatialEquiv htop)
          (VonNeumannAlgebra.generated (Set.range (fun pq : F × F => hF.matrixUnit pq.1 pq.2))) :=
        congrArg (VonNeumannAlgebra.conj (hF.spatialEquiv htop))
          (hF.generated_matrixUnits_eq he htop).symm
    _ = VonNeumannAlgebra.generated (⇑(hF.spatialEquiv htop).conjStarAlgEquiv ''
          Set.range (fun pq : F × F => hF.matrixUnit pq.1 pq.2)) :=
        VonNeumannAlgebra.conj_generated _ _
    _ = VonNeumannAlgebra.generated (Set.range (fun pq : F × F =>
          amplifyLeft (H₂ := LinearMap.range (e : H →ₗ[ℂ] H))
            (InnerProductSpace.rankOne ℂ (δ pq.1) (δ pq.2)))) :=
        congrArg VonNeumannAlgebra.generated himg
    _ = vnTensorLeft := generated_amplifyLeft_rankOne_eq

/-- **Type I factor structure theorem (commutant).** The same spatial isomorphism carries the
commutant `N'` onto `1 ⊗̄ B(eH)`: `U N' U⋆ = 1 ⊗̄ B(eH)`. This is the companion of
`conj_spatialEquiv_eq_vnTensorLeft`, obtained from it because conjugation commutes with taking
commutants and `(B(ℓ²(F)) ⊗̄ 1)' = 1 ⊗̄ B(eH)`. -/
theorem OrthEquivFam.conj_spatialEquiv_commutant_eq_vnTensorRight (hF : OrthEquivFam N e F)
    (he : IsMinimalProjection N e)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    [Nonempty F] [DecidableEq F] [CompleteSpace (LinearMap.range (e : H →ₗ[ℂ] H))] :
    VonNeumannAlgebra.conj (hF.spatialEquiv htop) N′ = vnTensorRight := by
  haveI : Nontrivial (lp (fun _ : F => ℂ) 2) :=
    ⟨lpDelta (Classical.arbitrary F), 0, by
      rw [← norm_ne_zero_iff, lpDelta_norm]; norm_num⟩
  rw [← VonNeumannAlgebra.conj_commutant, hF.conj_spatialEquiv_eq_vnTensorLeft he htop,
    vnTensorLeft_commutant]

/-- **Left factor absorption.** Any von Neumann subalgebra `A ≤ N` of the type I factor `N`
is carried by the spatial isomorphism into the left tensor factor: `U A U⋆ ≤ B(ℓ²(F)) ⊗̄ 1`. This
is monotonicity of spatial conjugation composed with `U N U⋆ = vnTensorLeft`. -/
lemma OrthEquivFam.conj_spatialEquiv_le_vnTensorLeft (hF : OrthEquivFam N e F)
    (he : IsMinimalProjection N e)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    [Nonempty F] [DecidableEq F] [CompleteSpace (LinearMap.range (e : H →ₗ[ℂ] H))]
    {A : VonNeumannAlgebra H} (h₁ : A ≤ N) :
    VonNeumannAlgebra.conj (hF.spatialEquiv htop) A ≤ vnTensorLeft :=
  (VonNeumannAlgebra.conj_mono _ h₁).trans_eq (hF.conj_spatialEquiv_eq_vnTensorLeft he htop)

/-- **Right factor absorption.** For any von Neumann algebra `B` containing `N`, the commutant
`B′` is carried by the spatial isomorphism into the right tensor factor: `U B′ U⋆ ≤ 1 ⊗̄ B(eH)`.
Taking commutants in `N ≤ B` gives `B′ ≤ N′`, and monotonicity composed with
`U N′ U⋆ = vnTensorRight` finishes. -/
lemma OrthEquivFam.conj_spatialEquiv_le_vnTensorRight (hF : OrthEquivFam N e F)
    (he : IsMinimalProjection N e)
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤)
    [Nonempty F] [DecidableEq F] [CompleteSpace (LinearMap.range (e : H →ₗ[ℂ] H))]
    {B : VonNeumannAlgebra H} (h₂ : N ≤ B) :
    VonNeumannAlgebra.conj (hF.spatialEquiv htop) B′ ≤ vnTensorRight :=
  (VonNeumannAlgebra.conj_mono _ (VonNeumannAlgebra.commutant_le h₂)).trans_eq
    (hF.conj_spatialEquiv_commutant_eq_vnTensorRight he htop)

omit [CompleteSpace H] in
/-- A covering orthogonal family of a nonzero Hilbert space is nonempty: its ranges span a dense
subspace, which would be `{0}` were the family empty. -/
lemma OrthEquivFam.nonempty_of_top [Nontrivial H] {F : Set (H →L[ℂ] H)}
    (htop : (Submodule.span ℂ {y | ∃ f ∈ F, ∃ x, f x = y}).topologicalClosure = ⊤) :
    Nonempty F := by
  rw [← not_isEmpty_iff]
  intro hempty
  have hset : {y : H | ∃ f ∈ F, ∃ x, f x = y} = (∅ : Set H) := by
    ext y
    simp only [Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
    rintro ⟨f, hf, x, rfl⟩
    exact hempty.false ⟨f, hf⟩
  obtain ⟨z, hz⟩ := exists_ne (0 : H)
  have hmem : z ∈ (⊤ : Submodule ℂ H) := Submodule.mem_top
  rw [← htop, hset, Submodule.span_empty, ← SetLike.mem_coe,
    Submodule.topologicalClosure_coe, Submodule.bot_coe, closure_singleton,
    Set.mem_singleton_iff] at hmem
  exact hz hmem

/-- **Type I factor structure theorem (existence form).** A type I factor `N ⊆ B(H)` with minimal
projection `e` (acting on a nonzero Hilbert space) is, up to a spatial isomorphism
`U : H ≃ₗᵢ ℓ²(F) ⊗̂ (eH)`, exactly the tensor factor `B(ℓ²(F)) ⊗̄ 1`, with commutant `1 ⊗̄ B(eH)`:
conjugation by `U` carries `N` onto `vnTensorLeft` and `N'` onto `vnTensorRight`. This is
[Yngvason] §5.1 (38)→(39) in its model-independent von-Neumann-algebraic form (see the module
doc's reference list). -/
theorem IsFactor.exists_spatial_tensor_decomposition {N : VonNeumannAlgebra H}
    (hN : IsFactor N) {e : H →L[ℂ] H} (he : IsMinimalProjection N e) :
    ∃ (F : Set (H →L[ℂ] H))
      (U : H ≃ₗᵢ[ℂ] lp (fun _ : F => ℂ) 2 ⊗̂ LinearMap.range (e : H →ₗ[ℂ] H)),
      VonNeumannAlgebra.conj U N = vnTensorLeft ∧
      VonNeumannAlgebra.conj U N′ = vnTensorRight := by
  haveI := he.nontrivial
  obtain ⟨F, hF, htop⟩ := hN.exists_orthEquivFam_top he
  haveI : CompleteSpace (LinearMap.range (e : H →ₗ[ℂ] H)) := he.1.completeSpace_range
  haveI : DecidableEq F := Classical.decEq _
  haveI : Nonempty F := OrthEquivFam.nonempty_of_top htop
  exact ⟨F, hF.spatialEquiv htop, hF.conj_spatialEquiv_eq_vnTensorLeft he htop,
    hF.conj_spatialEquiv_commutant_eq_vnTensorRight he htop⟩

/-- **Split tensor decomposition ([Yngvason] §5.1 (38)→(39); see the module doc's reference
list).** Suppose an inclusion `A ≤ B` of von
Neumann algebras admits an intermediate factor `N ⊆ B(H)` with minimal projection `e` — that is,
`A ≤ N ≤ B` with `N` type I. The existence of such an `N` is precisely what makes `A ≤ B` a
*split inclusion* in the sense of Doplicher–Longo (*Standard and split inclusions of von Neumann
algebras*, Invent. Math. 75, 1984); the named form of that definition, `IsSplitInclusion`, and its
consequences live in `QuantumSystem.Algebra.VonNeumannAlgebra.SplitInclusion`. In AQFT the split
inclusions of interest are `𝓡(O₁) ≤ 𝓡(O₂)` for properly contained regions — the *split property*
of a local net (Buchholz, *Product states for local algebras*, Comm. Math. Phys. 36, 1974).

The conclusion: there is a spatial isomorphism `U : H ≃ₗᵢ ℓ²(F) ⊗̂ (eH)` simultaneously
tensor-splitting the inclusion — `A` lands in the left factor `B(ℓ²(F)) ⊗̄ 1` and the commutant
`B′` lands in the right factor `1 ⊗̄ B(eH)`, with `N` and its commutant identified exactly. The
commuting-pair form of this statement — `A₁ ≤ N ≤ A₂′` for a pair `(A₁, A₂)` — is recovered by
instantiating `B := A₂′`. -/
theorem IsFactor.exists_split_tensor_decomposition {N : VonNeumannAlgebra H}
    (hN : IsFactor N) {e : H →L[ℂ] H} (he : IsMinimalProjection N e)
    {A B : VonNeumannAlgebra H} (h₁ : A ≤ N) (h₂ : N ≤ B) :
    ∃ (F : Set (H →L[ℂ] H))
      (U : H ≃ₗᵢ[ℂ] lp (fun _ : F => ℂ) 2 ⊗̂ LinearMap.range (e : H →ₗ[ℂ] H)),
      Nonempty F ∧
      VonNeumannAlgebra.conj U N = vnTensorLeft ∧
      VonNeumannAlgebra.conj U N′ = vnTensorRight ∧
      VonNeumannAlgebra.conj U A ≤ vnTensorLeft ∧
      VonNeumannAlgebra.conj U B′ ≤ vnTensorRight := by
  haveI := he.nontrivial
  obtain ⟨F, hF, htop⟩ := hN.exists_orthEquivFam_top he
  haveI : CompleteSpace (LinearMap.range (e : H →ₗ[ℂ] H)) := he.1.completeSpace_range
  haveI : DecidableEq F := Classical.decEq _
  haveI : Nonempty F := OrthEquivFam.nonempty_of_top htop
  exact ⟨F, hF.spatialEquiv htop, ‹Nonempty F›, hF.conj_spatialEquiv_eq_vnTensorLeft he htop,
    hF.conj_spatialEquiv_commutant_eq_vnTensorRight he htop,
    hF.conj_spatialEquiv_le_vnTensorLeft he htop h₁,
    hF.conj_spatialEquiv_le_vnTensorRight he htop h₂⟩

end VonNeumannAlgebra
