module

public import QuantumSystem.ForMathlib.Analysis.InnerProductSpace.TensorProductCompletion
public import QuantumSystem.ForMathlib.Analysis.VonNeumannAlgebra.Commutant
public import Mathlib.Analysis.InnerProductSpace.Adjoint

/-!
# The tensor von Neumann factors `B(H₁) ⊗̄ 1` and `1 ⊗̄ B(H₂)`

Using the operator amplifications `amplifyLeft : B(H₁) → B(H₁ ⊗̂ H₂)` and
`amplifyRight : B(H₂) → B(H₁ ⊗̂ H₂)` (from `TensorProductCompletion`), this file defines the two
von Neumann factors on the completed Hilbert tensor product:

* `HilbertTensor.vnTensorLeft  = B(H₁) ⊗̄ 1` — the von Neumann algebra generated by the image of
  `amplifyLeft`,
* `HilbertTensor.vnTensorRight = 1 ⊗̄ B(H₂)` — the von Neumann algebra generated by the image of
  `amplifyRight`.

These are the objects in the split-property tensor decomposition `A₁ ⊆ B(H₁)⊗̄1`,
`A₂ ⊆ 1⊗̄B(H₂)` (paper eq. (39)). The file culminates in the **tensor commutation theorem**
`vnTensorLeft.commutant = vnTensorRight` (von Neumann's commutation theorem for a full factor on
the first leg): the commutant of `B(H₁)⊗̄1` is exactly `1⊗̄B(H₂)`.

## Main definitions

* `HilbertTensor.vnTensorLeft`, `HilbertTensor.vnTensorRight`.
* `HilbertTensor.tmulRightL f` — the inclusion `H₂ → H₁ ⊗̂ H₂`, `z ↦ f ⊗ z`.

## Main results

* `HilbertTensor.amplifyLeft_mem_vnTensorLeft` / `amplifyRight_mem_vnTensorRight` — the
  amplified operators lie in the corresponding factor.
* `HilbertTensor.amplifyLeft_comp_amplifyRight` — the two amplifications commute.
* `HilbertTensor.mem_vnTensorRight_of_commutes` — the slice lemma: an operator commuting with all
  `A ⊗̂ 1` is of the form `1 ⊗̂ S`.
* `HilbertTensor.vnTensorLeft_commutant` — the tensor commutation theorem
  `(B(H₁)⊗̄1)' = 1⊗̄B(H₂)`.
-/

@[expose] public section

open scoped TensorProduct

namespace HilbertTensor

variable {H₁ H₂ : Type*}
  [NormedAddCommGroup H₁] [InnerProductSpace ℂ H₁]
  [NormedAddCommGroup H₂] [InnerProductSpace ℂ H₂]

/-- The von Neumann factor `B(H₁) ⊗̄ 1` acting on `HilbertTensor H₁ H₂`: the von Neumann algebra
generated by the image of the left amplification `A ↦ A ⊗̂ 1`. -/
noncomputable def vnTensorLeft : VonNeumannAlgebra (HilbertTensor H₁ H₂) :=
  VonNeumannAlgebra.generated (Set.range (amplifyLeft (H₂ := H₂)))

/-- The von Neumann factor `1 ⊗̄ B(H₂)` acting on `HilbertTensor H₁ H₂`: the von Neumann algebra
generated by the image of the right amplification `B ↦ 1 ⊗̂ B`. -/
noncomputable def vnTensorRight : VonNeumannAlgebra (HilbertTensor H₁ H₂) :=
  VonNeumannAlgebra.generated (Set.range (amplifyRight (H₁ := H₁)))

/-- Every left amplification `A ⊗̂ 1` lies in the factor `B(H₁) ⊗̄ 1`. -/
theorem amplifyLeft_mem_vnTensorLeft (A : H₁ →L[ℂ] H₁) :
    amplifyLeft (H₂ := H₂) A ∈ vnTensorLeft :=
  VonNeumannAlgebra.mem_generated_of_mem ⟨A, rfl⟩

/-- Every right amplification `1 ⊗̂ B` lies in the factor `1 ⊗̄ B(H₂)`. -/
theorem amplifyRight_mem_vnTensorRight (B : H₂ →L[ℂ] H₂) :
    amplifyRight (H₁ := H₁) B ∈ vnTensorRight :=
  VonNeumannAlgebra.mem_generated_of_mem ⟨B, rfl⟩

/-- The commutant of `B(H₁) ⊗̄ 1` is the commutant of the range of `amplifyLeft` (bicommutant
collapse). This reduces the tensor commutation theorem `vnTensorLeft.commutant = vnTensorRight`
to the identity `(range amplifyLeft)' = 1 ⊗̄ B(H₂)`. -/
theorem vnTensorLeft_commutant_eq_commutantSet :
    (vnTensorLeft (H₁ := H₁) (H₂ := H₂)).commutant
      = VonNeumannAlgebra.commutantSet (Set.range (amplifyLeft (H₂ := H₂))) :=
  VonNeumannAlgebra.commutant_generated _

/-- The commutant of `1 ⊗̄ B(H₂)` is the commutant of the range of `amplifyRight`. -/
theorem vnTensorRight_commutant_eq_commutantSet :
    (vnTensorRight (H₁ := H₁) (H₂ := H₂)).commutant
      = VonNeumannAlgebra.commutantSet (Set.range (amplifyRight (H₁ := H₁))) :=
  VonNeumannAlgebra.commutant_generated _

/-! ### The tensor commutation theorem

The commutant of `B(H₁) ⊗̄ 1` is exactly `1 ⊗̄ B(H₂)` — von Neumann's commutation theorem for the
special case of a full factor on the first leg. The hard inclusion
`(B(H₁)⊗̄1)' ⊆ 1⊗̄B(H₂)` is the slice argument: an operator `T` commuting with every `A ⊗̂ 1`
must be of the form `1 ⊗̂ S`, where `S = ι_e* ∘ T ∘ ι_e` for a fixed unit vector `e ∈ H₁` and
`ι_e : H₂ → H₁ ⊗̂ H₂`, `y ↦ e ⊗ y`. The reduction to a pure-tensor computation uses the rank-one
operators `|f⟩⟨e|` on `H₁`. -/

/-- The bounded inclusion `H₂ → H₁ ⊗̂ H₂`, `z ↦ f ⊗ z`, for a fixed `f ∈ H₁`. Its operator norm
is `‖f‖` (`‖tmulRightL f z‖ = ‖f‖ * ‖z‖`), so it is an isometry exactly when `‖f‖ = 1`. -/
noncomputable def tmulRightL (f : H₁) : H₂ →L[ℂ] HilbertTensor H₁ H₂ :=
  UniformSpace.Completion.toComplL.comp
    (LinearMap.mkContinuous (TensorProduct.mk ℂ H₁ H₂ f) ‖f‖ fun z => by
      rw [TensorProduct.mk_apply, TensorProduct.norm_tmul])

@[simp] theorem tmulRightL_apply (f : H₁) (z : H₂) : tmulRightL f z = tmul f z := rfl

/-- The left and right amplifications commute: `(A ⊗̂ 1)(1 ⊗̂ B) = A ⊗̂ B = (1 ⊗̂ B)(A ⊗̂ 1)`. -/
theorem amplifyLeft_comp_amplifyRight (A : H₁ →L[ℂ] H₁) (B : H₂ →L[ℂ] H₂) :
    (amplifyLeft (H₂ := H₂) A).comp (amplifyRight (H₁ := H₁) B)
      = (amplifyRight B).comp (amplifyLeft A) := by
  refine ContinuousLinearMap.ext fun w => ?_
  refine UniformSpace.Completion.induction_on w
    (isClosed_eq (by fun_prop) (by fun_prop)) (fun a => ?_)
  induction a using TensorProduct.induction_on with
  | zero => simp only [UniformSpace.Completion.coe_zero, map_zero]
  | tmul f y =>
      change amplifyLeft A (amplifyRight B (tmul f y)) = amplifyRight B (amplifyLeft A (tmul f y))
      rw [amplifyRight_tmul, amplifyLeft_tmul, amplifyLeft_tmul, amplifyRight_tmul]
  | add p q hp hq => rw [UniformSpace.Completion.coe_add, map_add, map_add, hp, hq]

section CompleteRight

variable [CompleteSpace H₂]

/-- The adjoint of the inclusion `ι_e` acts on pure tensors as the `e`-slice
`g ⊗ z ↦ ⟪e, g⟫ • z`. -/
theorem adjoint_tmulRightL_tmul (e g : H₁) (z : H₂) :
    ContinuousLinearMap.adjoint (tmulRightL (H₂ := H₂) e) (tmul g z) = (inner ℂ e g) • z := by
  refine ext_inner_right ℂ fun y => ?_
  rw [ContinuousLinearMap.adjoint_inner_left, tmulRightL_apply, inner_tmul, inner_smul_left,
    inner_conj_symm]

/-- The amplification of a rank-one operator `|f⟩⟨e|` factors through the `e`-slice and the
inclusion `ι_f`: `(|f⟩⟨e|) ⊗̂ 1 = ι_f ∘ ι_e*`. This is the algebraic heart of the slice
argument. -/
theorem amplifyLeft_rankOne_eq (e f : H₁) :
    amplifyLeft (H₂ := H₂) (InnerProductSpace.rankOne ℂ f e)
      = (tmulRightL f).comp (ContinuousLinearMap.adjoint (tmulRightL e)) := by
  refine ContinuousLinearMap.ext fun w => ?_
  refine UniformSpace.Completion.induction_on w
    (isClosed_eq (by fun_prop) (by fun_prop)) (fun a => ?_)
  induction a using TensorProduct.induction_on with
  | zero => simp only [UniformSpace.Completion.coe_zero, map_zero]
  | tmul g z =>
      change amplifyLeft _ (tmul g z)
        = (tmulRightL f).comp (ContinuousLinearMap.adjoint (tmulRightL e)) (tmul g z)
      rw [amplifyLeft_tmul, ContinuousLinearMap.comp_apply, adjoint_tmulRightL_tmul,
        tmulRightL_apply, InnerProductSpace.rankOne_apply,
        tmul_smul_left, smul_tmul_right]
  | add p q hp hq => rw [UniformSpace.Completion.coe_add, map_add, map_add, hp, hq]

/-- **Slice lemma (dense form).** If `T` commutes with the rank-one amplifications
`(|f⟩⟨e|) ⊗̂ 1` for `f` ranging over a set `D` whose span is dense in `H₁` (and a fixed unit vector
`e ∈ H₁`), then `T = 1 ⊗̂ S` for `S = ι_e* ∘ T ∘ ι_e`, hence `T ∈ 1 ⊗̄ B(H₂)`. The relation
`T (f ⊗̂ y) = f ⊗̂ (S y)` is first established for `f ∈ D` and then extended to all `f` by density,
working at the level of the bounded inclusions `ι_y : f ↦ f ⊗̂ y`. -/
theorem mem_vnTensorRight_of_commutes_dense (e : H₁) (he : ‖e‖ = 1) (D : Set H₁)
    (hD : Dense (Submodule.span ℂ D : Set H₁))
    (T : HilbertTensor H₁ H₂ →L[ℂ] HilbertTensor H₁ H₂)
    (hT : ∀ f ∈ D, T.comp (amplifyLeft (InnerProductSpace.rankOne ℂ f e))
      = (amplifyLeft (InnerProductSpace.rankOne ℂ f e)).comp T) :
    T ∈ vnTensorRight := by
  set S := (ContinuousLinearMap.adjoint (tmulRightL e)).comp (T.comp (tmulRightL e)) with hS
  have hee : inner ℂ e e = (1 : ℂ) := by rw [inner_self_eq_norm_sq_to_K, he]; norm_num
  have key : ∀ f ∈ D, ∀ y : H₂, T (tmul f y) = tmul f (S y) := by
    intro f hf y
    have e1 : amplifyLeft (H₂ := H₂) (InnerProductSpace.rankOne ℂ f e) (tmul e y) = tmul f y := by
      rw [amplifyLeft_tmul, InnerProductSpace.rankOne_apply, hee, one_smul]
    calc T (tmul f y)
        = T (amplifyLeft (InnerProductSpace.rankOne ℂ f e) (tmul e y)) := by rw [e1]
      _ = amplifyLeft (InnerProductSpace.rankOne ℂ f e) (T (tmul e y)) := by
            rw [← ContinuousLinearMap.comp_apply, hT f hf, ContinuousLinearMap.comp_apply]
      _ = (tmulRightL f).comp (ContinuousLinearMap.adjoint (tmulRightL e)) (T (tmul e y)) := by
            rw [amplifyLeft_rankOne_eq]
      _ = tmul f (S y) := by
            rw [ContinuousLinearMap.comp_apply, tmulRightL_apply, hS]
            simp only [ContinuousLinearMap.comp_apply, tmulRightL_apply]
  have key_all : ∀ (f : H₁) (y : H₂), T (tmul f y) = tmul f (S y) := by
    intro f y
    have hcl : T.comp (tmulLeftL y) = (amplifyRight S).comp (tmulLeftL y) := by
      refine ContinuousLinearMap.ext_on hD (fun g hg => ?_)
      rw [ContinuousLinearMap.comp_apply, ContinuousLinearMap.comp_apply, tmulLeftL_apply,
        amplifyRight_tmul, key g hg y]
    have h := congrArg (fun L : H₁ →L[ℂ] HilbertTensor H₁ H₂ => L f) hcl
    simpa only [ContinuousLinearMap.comp_apply, tmulLeftL_apply, amplifyRight_tmul] using h
  have hTS : T = amplifyRight S := by
    refine ContinuousLinearMap.ext fun w => ?_
    refine UniformSpace.Completion.induction_on w
      (isClosed_eq T.continuous (amplifyRight S).continuous) (fun a => ?_)
    induction a using TensorProduct.induction_on with
    | zero => simp only [UniformSpace.Completion.coe_zero, map_zero]
    | tmul f y =>
        change T (tmul f y) = amplifyRight S (tmul f y)
        rw [key_all, amplifyRight_tmul]
    | add p q hp hq => rw [UniformSpace.Completion.coe_add, map_add, map_add, hp, hq]
  rw [hTS]
  exact amplifyRight_mem_vnTensorRight S

/-- **Slice lemma (hard inclusion of the commutation theorem).** If `T` commutes with every left
amplification `A ⊗̂ 1`, then `T = 1 ⊗̂ S` for `S = ι_e* ∘ T ∘ ι_e` (any unit vector `e ∈ H₁`),
hence `T ∈ 1 ⊗̄ B(H₂)`. -/
theorem mem_vnTensorRight_of_commutes (e : H₁) (he : ‖e‖ = 1)
    (T : HilbertTensor H₁ H₂ →L[ℂ] HilbertTensor H₁ H₂)
    (hT : ∀ A : H₁ →L[ℂ] H₁, T.comp (amplifyLeft A) = (amplifyLeft A).comp T) :
    T ∈ vnTensorRight :=
  mem_vnTensorRight_of_commutes_dense e he Set.univ
    (by rw [Submodule.span_univ, Submodule.top_coe]; exact dense_univ) T
    (fun f _ => hT (InnerProductSpace.rankOne ℂ f e))

end CompleteRight

/-- **Tensor commutation theorem.** The commutant of the von Neumann factor `B(H₁) ⊗̄ 1` is exactly
`1 ⊗̄ B(H₂)`. This is von Neumann's commutation theorem `(M ⊗ 1)' = M' ⊗ B(H₂)` for `M = B(H₁)`
(whose commutant `M'` is `ℂ`), and it is the analytic core of the split-property tensor
decomposition: combined with `vnTensorLeft_commutant_eq_commutantSet` and a unit vector in `H₁`,
it identifies `A₁ ⊆ B(H₁)⊗̄1` with `A₂ ⊆ 1⊗̄B(H₂)` for commuting `A₁, A₂`. -/
theorem vnTensorLeft_commutant [CompleteSpace H₁] [CompleteSpace H₂] [Nontrivial H₁] :
    (vnTensorLeft (H₁ := H₁) (H₂ := H₂)).commutant = vnTensorRight := by
  rw [vnTensorLeft_commutant_eq_commutantSet]
  refine le_antisymm ?_ ?_
  · -- hard inclusion: every `T` commuting with `B(H₁)⊗̄1` lies in `1⊗̄B(H₂)`
    obtain ⟨x, hx⟩ := exists_ne (0 : H₁)
    have he : ‖(‖x‖⁻¹ : ℂ) • x‖ = 1 := by
      rw [norm_smul, norm_inv, Complex.norm_real, norm_norm,
        inv_mul_cancel₀ (norm_ne_zero_iff.mpr hx)]
    intro T hT
    refine mem_vnTensorRight_of_commutes _ he T fun A => ?_
    have hc := (VonNeumannAlgebra.mem_commutantSet_iff.mp hT (amplifyLeft A) ⟨A, rfl⟩).1
    rw [← ContinuousLinearMap.mul_def, ← ContinuousLinearMap.mul_def]
    exact hc.symm
  · -- easy inclusion: `1⊗̄B(H₂)` commutes with `B(H₁)⊗̄1`
    change VonNeumannAlgebra.generated (Set.range (amplifyRight (H₁ := H₁)))
      ≤ VonNeumannAlgebra.commutantSet (Set.range (amplifyLeft (H₂ := H₂)))
    refine VonNeumannAlgebra.generated_le ?_
    rintro g ⟨B, rfl⟩
    rw [SetLike.mem_coe, VonNeumannAlgebra.mem_commutantSet_iff]
    rintro h ⟨A, rfl⟩
    refine ⟨?_, ?_⟩
    · rw [ContinuousLinearMap.mul_def, ContinuousLinearMap.mul_def]
      exact amplifyLeft_comp_amplifyRight A B
    · rw [amplifyLeft_star, ContinuousLinearMap.mul_def, ContinuousLinearMap.mul_def]
      exact amplifyLeft_comp_amplifyRight (star A) B

end HilbertTensor
