module

public import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap
public import QuantumSystem.Algebra.QuasiLocalAlgebra.LocalEmbed

/-!
# Quasi-local algebra (Phase 5'c)

Following Naaijkens 2012 §1.3 / Bratteli–Robinson Vol. 2 §2.7.2, the
quasi-local algebra of an infinite quantum lattice system is the norm closure of
the `*`-algebra generated by all finite-region local subalgebras.  In this file
that algebraic core is represented by the supremum of the local subalgebras in
the complete lattice of `StarSubalgebra`s:

`𝔄_alg := ⨆ Λ : Finset L, 𝔄(Λ)`, with `quasiLocal L := closure 𝔄_alg`.

In our basis-indexed model the local subalgebras
`localSubalgebra Λ : StarSubalgebra ℂ (globalHilbert L →L[ℂ] globalHilbert L)`
are realised as the ranges of `localEmbedHom Λ`; their `iSup` (in the
`CompleteLattice` of `StarSubalgebra ℂ _`) is the algebraic quasi-local core
`quasiLocalSubalg L`, and its topological closure is
`quasiLocal L`.

Here `localSubalgebra Λ` / `𝔄(Λ)` is the *represented* layer of the three
local-algebra layers documented in `QuantumSystem.Algebra.LocalNetLike`.

## Main definitions

* `LocalNetLike.quasiLocalSubalg L` — the unital `*`-subalgebra
  `⨆ Λ : Finset L, localSubalgebra Λ`.
* `LocalNetLike.quasiLocal L` — the norm closure of `quasiLocalSubalg L`,
  i.e. the quasi-local algebra of the lattice system.

## References

* Naaijkens, *Anyons in Infinite Quantum Systems*, 2012, §1.3.
* Bratteli, Robinson, *Operator Algebras and Quantum Statistical Mechanics II*,
  §2.7.2.
-/

@[expose] public section

namespace LocalNetLike

variable (L : Type*) [DecidableEq L] [LocalNetLike L]
    [hL : ∀ s : L, Nonempty (LocalNetLike.localIdx (L := L) s)]

/-- Algebraic core generated by local subalgebras:
`⨆ Λ : Finset L, localSubalgebra Λ`.
This is the `*`-subalgebra of `globalHilbert L →L[ℂ] globalHilbert L` generated by
all local operators.  Its norm closure is the quasi-local algebra `quasiLocal L`. -/
noncomputable def quasiLocalSubalg :
    StarSubalgebra ℂ (globalHilbert L →L[ℂ] globalHilbert L) :=
  ⨆ Λ : Finset L, localSubalgebra Λ

/-- The **quasi-local algebra** of the lattice system: the norm closure of
the algebraic local core generated by all local subalgebras. -/
noncomputable def quasiLocal :
    StarSubalgebra ℂ (globalHilbert L →L[ℂ] globalHilbert L) :=
  (quasiLocalSubalg L).topologicalClosure

/-- Each local subalgebra is contained in the algebraic quasi-local core. -/
theorem localSubalgebra_le_quasiLocalSubalg (Λ : Finset L) :
    localSubalgebra Λ ≤ quasiLocalSubalg L :=
  le_iSup (fun Λ : Finset L => localSubalgebra Λ) Λ

/-- Each local subalgebra is contained in the quasi-local algebra. -/
theorem localSubalgebra_le_quasiLocal (Λ : Finset L) :
    localSubalgebra Λ ≤ quasiLocal L :=
  (localSubalgebra_le_quasiLocalSubalg L Λ).trans
    (StarSubalgebra.le_topologicalClosure _)

/-- The algebraic quasi-local core is contained in the quasi-local
algebra. -/
theorem quasiLocalSubalg_le_quasiLocal :
    quasiLocalSubalg L ≤ quasiLocal L :=
  StarSubalgebra.le_topologicalClosure _

/-- The quasi-local algebra is closed in the operator-norm topology. -/
theorem isClosed_quasiLocal :
    IsClosed (↑(quasiLocal L) : Set (globalHilbert L →L[ℂ] globalHilbert L)) :=
  StarSubalgebra.isClosed_topologicalClosure _

/-- The quasi-local algebra `quasiLocal L` is a closed subset of
`B(globalHilbert L)`. -/
instance instIsClosed_quasiLocal :
    IsClosed (SetLike.coe (quasiLocal L)) :=
  isClosed_quasiLocal L

/-- The **quasi-local algebra is a unital C⋆-algebra**.  This instance is
derived from the closed-subalgebra `CStarAlgebra` instance
`StarSubalgebra.cstarAlgebra` and the closedness of `quasiLocal L`. -/
noncomputable instance instCStarAlgebra_quasiLocal :
    CStarAlgebra ↥(quasiLocal L) :=
  inferInstance

end LocalNetLike
