#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""Render check for an extraction note.

Every math span in `docs/math/<slug>.md` must render **on its own**, and that is
the part that bites: **a note cannot define macros for itself.** Measured through
`@vscode/markdown-it-katex`, the plugin VS Code's own Markdown preview uses,
`\\newcommand`, `\\gdef` and `\\global\\def` all fail to reach the next math
span — the plugin renders each span with fresh options, so nothing is carried.
(Bare KaTeX behaves slightly better: `\\gdef` survives when the caller passes a
shared `macros` object. No markdown previewer does.)

So a note whose prose says `$\\A_\\U$` throws `Undefined control sequence` on
every occurrence, however carefully the preamble was written, and the reader sees
a wall of ParseErrors instead of the mathematics. This script is what stops that
reaching the tracked note.

    uv run .claude/skills/math-extract/scripts/check_render.py docs/math/<slug>.md

Exit 0 clean, 1 on findings, 2 on a usage error.

What counts as a math span: `$...$` inline and `$$`-delimited blocks, **outside
fenced code**. Fenced code is deliberately exempt — it is the sanctioned place
for a verbatim quote that carries its source's private macros, because the bytes
survive untouched and no renderer tries to typeset them.

The allowlist in `references/katex-commands.txt` was generated by probing a real
KaTeX build, one command at a time, and keeping only what actually rendered; it
contains no guesses. Regenerate it against a newer KaTeX with the recipe in
`references/note-format.md`.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

SKILL = Path(__file__).resolve().parent.parent
ALLOWLIST = SKILL / "references" / "katex-commands.txt"
RENDER_JS = SKILL / "scripts" / "render_check.js"

FIX_ORDER = """Fix by preference order:
  1. In the note's OWN prose, write plain KaTeX (\\mathcal{A}, \\mathrm{Tr},
     \\operatorname{supp}) — a source's private macro has no business there.
  2. Put a verbatim quote that carries source macros in a fenced code block, or
     a short inlined fragment in `backticks`; the bytes stay exact and nothing
     tries to typeset them.
  3. Brace any multi-token argument: \\widetilde{\\mathcal U}, \\Delta_{\\mathcal U}.
  4. There is no step 4. A macro preamble does not work in the pipeline VS Code
     uses, whatever the definition form."""


def real_render(note: Path) -> tuple[str, int]:
    """Parse every span with a real KaTeX build, when one is available.

    This is the stronger half of the check. The allowlist below catches unknown
    command *names*; only a parser catches an unbraced argument such as
    `\\widetilde\\mathcal U`, an unbalanced delimiter, or a bad environment.

    Returns (report, findings). findings < 0 means the check could not run.
    """
    if not (shutil.which("node") and RENDER_JS.is_file()):
        return ("real render: skipped (no node)", -1)
    if not (SKILL / "node_modules" / "@vscode" / "markdown-it-katex").is_dir():
        return (
            "real render: skipped — enable it with\n"
            f"    (cd {SKILL} && npm install --no-save markdown-it @vscode/markdown-it-katex)\n"
            "  node_modules/ is already gitignored, so nothing is added to the tree.",
            -1,
        )
    proc = subprocess.run(
        ["node", str(RENDER_JS), str(note)], capture_output=True, text=True
    )
    body = (proc.stdout + proc.stderr).strip()
    return (body, 0 if proc.returncode == 0 else 1)

# `\foo`, or a single non-letter control symbol such as `\<`, `\{`, `\|`.
COMMAND_RE = re.compile(r"\\[A-Za-z]+|\\[^A-Za-z\s]")
# A definition in the note's own macro preamble.
DEF_RE = re.compile(r"\\(?:gdef|gdef\s*|global\s*\\def|def|newcommand|renewcommand|providecommand)\s*\{?(\\[A-Za-z]+|\\[^A-Za-z\s])\}?")
LOCAL_DEF_RE = re.compile(r"\\(?:newcommand|renewcommand|providecommand)\s*\{?(\\[A-Za-z]+|\\[^A-Za-z\s])\}?")
GLOBAL_DEF_RE = re.compile(r"(?:\\gdef|\\global\s*\\def)\s*\{?(\\[A-Za-z]+|\\[^A-Za-z\s])\}?")


def math_spans(text: str) -> list[tuple[int, str, str]]:
    """Yield (line_number, kind, tex) for every span a renderer will typeset."""
    spans: list[tuple[int, str, str]] = []
    in_fence = False
    in_block = False
    block_start = 0
    block_buf: list[str] = []

    for lineno, raw in enumerate(text.split("\n"), 1):
        stripped = raw.lstrip("> ").rstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if stripped == "$$":
            if in_block:
                spans.append((block_start, "block", "\n".join(block_buf)))
                block_buf = []
            else:
                block_start = lineno
            in_block = not in_block
            continue
        if in_block:
            block_buf.append(raw)
            continue
        # HTML comments never render.
        line = re.sub(r"<!--.*?-->", "", raw)
        for m in re.finditer(r"(?<!\\)\$([^$\n]+?)(?<!\\)\$", line):
            spans.append((lineno, "inline", m.group(1)))
    return spans


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    note = Path(sys.argv[1])
    if not note.is_file():
        print(f"not a file: {note}")
        return 2
    if not ALLOWLIST.is_file():
        print(f"missing allowlist: {ALLOWLIST}")
        return 2

    supported = {c for c in ALLOWLIST.read_text().split("\n") if c}
    text = note.read_text()
    spans = math_spans(text)

    # Macros the note defines for itself, split by whether they actually carry.
    globals_: set[str] = set()
    locals_: dict[str, int] = {}
    for lineno, _kind, tex in spans:
        for m in GLOBAL_DEF_RE.finditer(tex):
            globals_.add(m.group(1))
        for m in LOCAL_DEF_RE.finditer(tex):
            locals_.setdefault(m.group(1), lineno)

    findings: list[str] = []

    for name, lineno in sorted({**locals_, **{g: 0 for g in globals_}}.items()):
        findings.append(
            f"{note}:{lineno or '?'}: `{name}` is defined inside the note. "
            f"No definition form carries: measured through @vscode/markdown-it-katex, "
            f"neither \\newcommand nor \\gdef nor \\global\\def survives to the next "
            f"math span, because the plugin renders each span with fresh options"
        )

    undefined: dict[str, list[int]] = {}
    for lineno, _kind, tex in spans:
        body = GLOBAL_DEF_RE.sub("", LOCAL_DEF_RE.sub("", tex))
        for m in COMMAND_RE.finditer(body):
            name = m.group(0)
            if name in supported:
                continue
            undefined.setdefault(name, []).append(lineno)

    for name, lines in sorted(undefined.items()):
        where = ", ".join(str(n) for n in lines[:6])
        more = f" (+{len(lines) - 6} more)" if len(lines) > 6 else ""
        findings.append(
            f"{note}: `{name}` is not a KaTeX command and is not \\gdef'd in this note "
            f"— used at line(s) {where}{more}"
        )

    print(f"{len(spans)} math spans; {len(globals_) + len(locals_)} in-note macro "
          f"definitions (none of which carry); {len(undefined)} undefined commands")

    report, rc = real_render(note)
    print(report)

    # The pipeline is authoritative when it ran: it decides what a math span is,
    # and this scanner's idea of that is an approximation. Its findings are
    # reported only as a hint in that case, and are the whole verdict otherwise.
    if rc >= 0:
        if findings:
            print("\n(scanner hints, superseded by the pipeline above:)")
            for f in findings:
                print("  " + f)
        if rc == 0:
            print("\nrender check: clean")
            return 0
        print()
        print(FIX_ORDER)
        return 1

    if not findings:
        print("render check: scanner clean; the pipeline did not run, so brace, "
              "delimiter and span-boundary errors remain unchecked")
        return 0
    print()
    for f in findings:
        print(f)
    print()
    print(FIX_ORDER)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
