#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""Render check for an extraction note.

Every math span in `docs/math/<slug>.md` must render **on its own**, and that is
the part that bites: **no macro definition survives from one math span to the
next.** Measured through `@vscode/markdown-it-katex`, the plugin VS Code's own
Markdown preview uses: `\\newcommand`, `\\gdef` and `\\global\\def` all fail to
reach the NEXT span — the plugin renders each span with fresh options, so
nothing is carried forward.

`\\gdef` works fine *within the span that defines it*, though — nothing has to
survive anywhere for that. So the convention this checker enforces is: a
verbatim quote needing a source's own macro carries a local, self-contained
`\\gdef` of exactly that macro, defined and used inside the same `$...$` pair,
e.g. `$\\gdef\\lok#1{{\\mathcal #1}}\\lok{B}$`. That renders exactly as the
source intended, in every renderer, with no persistence required. A `\\gdef`
sitting in a span with nothing else to use it (the old document-level preamble,
reborn one span at a time) is exactly as broken as before, and is flagged the
same way.

    uv run .claude/skills/math-extract/scripts/check_render.py docs/math/<slug>.md

Exit 0 clean, 1 on findings, 2 on a usage error.

What counts as a math span: `$...$` inline and `$$`-delimited blocks, **outside
fenced code**. Fenced code is exempt — it is the fallback for a macro that
cannot be `\\gdef`'d at all, because the bytes survive untouched there and no
renderer tries to typeset them.

The allowlist in `references/katex-commands.txt` was generated by probing a real
KaTeX build, one command at a time, and keeping only what actually rendered; it
contains no guesses. Regenerate it against a newer KaTeX with the recipe in
`references/note-format.md`.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

SKILL = Path(__file__).resolve().parent.parent
ALLOWLIST = SKILL / "references" / "katex-commands.txt"
RENDER_JS = SKILL / "scripts" / "render_check.js"

FIX_ORDER = """Fix by preference order:
  1. In the note's OWN prose, write plain KaTeX (\\mathcal{A}, \\mathrm{Tr},
     \\operatorname{supp}) — a source's private macro has no business there.
  2. In a verbatim quote, give the macro a LOCAL \\gdef inside the same $...$ it
     is used in: `$\\gdef\\lok#1{{\\mathcal #1}}\\lok{B}$`. This renders as the
     source intended, with no cross-span persistence required, so it is the
     default fix, not a fallback. Audit the body against the source's own
     preamble (or mark it "reconstructed" when that preamble is unrecoverable)
     in the note's opening-comment macro catalogue.
  3. Brace any multi-token argument: \\widetilde{\\mathcal U}, \\Delta_{\\mathcal U}.
  4. Fence a quote (or backtick a fragment) only when a macro cannot be
     \\gdef'd at all (a \\newenvironment, a catcode change) — this shows raw
     source LaTeX instead of the intended notation, so it is the last resort.
  5. There is still no document-level macro preamble: no definition form
     survives from one math span to the next in the renderers this note has
     to work in, whatever the definition form."""


def real_render(note: Path) -> tuple[str, int]:
    """Parse every span with a real KaTeX build, when one is available.

    This is the stronger half of the check. The allowlist below catches unknown
    command *names*; only a parser catches an unbraced argument such as
    `\\widetilde\\mathcal U`, an unbalanced delimiter, or a bad environment.

    Returns (report, findings). findings < 0 means the check could not run.
    """
    if not (shutil.which("node") and RENDER_JS.is_file()):
        return ("real render: skipped (no node)", -1)
    if not (SKILL / "node_modules" / "@vscode" / "markdown-it-katex").is_dir():
        return (
            "real render: skipped — enable it with\n"
            f"    (cd {SKILL} && npm install --no-save markdown-it @vscode/markdown-it-katex)\n"
            "  node_modules/ is already gitignored, so nothing is added to the tree.",
            -1,
        )
    proc = subprocess.run(
        ["node", str(RENDER_JS), str(note)], capture_output=True, text=True
    )
    body = (proc.stdout + proc.stderr).strip()
    return (body, 0 if proc.returncode == 0 else 1)

# `\foo`, or a single non-letter control symbol such as `\<`, `\{`, `\|`.
COMMAND_RE = re.compile(r"\\[A-Za-z]+|\\[^A-Za-z\s]")
# The head of a macro definition: name, then zero or more #N parameters, then
# the opening brace of its body. The body itself is matched separately by
# counting braces, since it is frequently nested (`\gdef\BH{{\cal B}({\cal H})}`)
# and a single non-recursive regex cannot balance that in general.
DEF_HEAD_RE = re.compile(
    r"\\(?:gdef|global\s*\\def|def|(?:new|renew|provide)command)"
    r"\s*\{?(\\[A-Za-z]+|\\[^A-Za-z\s])\}?((?:#\d+)*)\s*\{"
)


def strip_defs(tex: str) -> tuple[str, set[str], bool]:
    """Remove every `\\NAME(#n)*{body}` definition from `tex`.

    Returns (remaining_text, names_defined, is_local_form). A definition is
    "local form" (\\newcommand/\\renewcommand/\\providecommand) if ANY match is
    of that form -- those are the ones that never carry, full stop, and are
    flagged regardless of where they appear.
    """
    names: set[str] = set()
    local_form = False
    out = []
    i = 0
    n = len(tex)
    while i < n:
        m = DEF_HEAD_RE.match(tex, i)
        if not m:
            out.append(tex[i])
            i += 1
            continue
        names.add(m.group(1))
        if re.match(r"\\(?:new|renew|provide)command", m.group(0)):
            local_form = True
        depth = 0
        k = m.end() - 1  # position of the opening '{' just matched
        while True:
            if tex[k] == "{":
                depth += 1
            elif tex[k] == "}":
                depth -= 1
                if depth == 0:
                    k += 1
                    break
            k += 1
        i = k
    return "".join(out), names, local_form


def math_spans(text: str) -> list[tuple[int, str, str]]:
    """Yield (line_number, kind, tex) for every span a renderer will typeset."""
    spans: list[tuple[int, str, str]] = []
    in_fence = False
    in_block = False
    block_start = 0
    block_buf: list[str] = []

    for lineno, raw in enumerate(text.split("\n"), 1):
        stripped = raw.lstrip("> ").rstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if stripped == "$$":
            if in_block:
                spans.append((block_start, "block", "\n".join(block_buf)))
                block_buf = []
            else:
                block_start = lineno
            in_block = not in_block
            continue
        if in_block:
            block_buf.append(raw)
            continue
        # HTML comments never render.
        line = re.sub(r"<!--.*?-->", "", raw)
        for m in re.finditer(r"(?<!\\)\$([^$\n]+?)(?<!\\)\$", line):
            spans.append((lineno, "inline", m.group(1)))
    return spans


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    note = Path(sys.argv[1])
    if not note.is_file():
        print(f"not a file: {note}")
        return 2
    if not ALLOWLIST.is_file():
        print(f"missing allowlist: {ALLOWLIST}")
        return 2

    supported = {c for c in ALLOWLIST.read_text().split("\n") if c}
    text = note.read_text()
    spans = math_spans(text)

    findings: list[str] = []
    local_form_lines: dict[str, int] = {}
    empty_def_only_lines: list[int] = []
    undefined: dict[str, list[int]] = {}
    self_contained = 0

    for lineno, _kind, tex in spans:
        remaining, names, local_form = strip_defs(tex)
        if names:
            self_contained += 1
        if local_form:
            for n in names:
                local_form_lines.setdefault(n, lineno)
        # A span whose ENTIRE content was definitions, with nothing left to use
        # them, is the old preamble anti-pattern reborn one span at a time.
        if names and not remaining.strip():
            empty_def_only_lines.append(lineno)
        for m in COMMAND_RE.finditer(remaining):
            name = m.group(0)
            if name in supported or name in names:
                continue
            undefined.setdefault(name, []).append(lineno)

    for name, lineno in sorted(local_form_lines.items()):
        findings.append(
            f"{note}:{lineno}: `{name}` is defined with \\newcommand/\\renewcommand/"
            f"\\providecommand, which never carries even within its own span — use "
            f"\\gdef instead (it works when defined and used inside the same $...$)"
        )
    for lineno in empty_def_only_lines:
        findings.append(
            f"{note}:{lineno}: this span is only macro definitions, with nothing in "
            f"the same span to use them — that is the old document-level-preamble "
            f"pattern, one span at a time, and it does not carry to the NEXT span "
            f"either. Move the definition into the span that actually uses the macro"
        )

    for name, lines in sorted(undefined.items()):
        where = ", ".join(str(n) for n in lines[:6])
        more = f" (+{len(lines) - 6} more)" if len(lines) > 6 else ""
        findings.append(
            f"{note}: `{name}` is not a KaTeX command and has no local \\gdef in the "
            f"same span — used at line(s) {where}{more}"
        )

    print(f"{len(spans)} math spans; {self_contained} carry a local macro "
          f"definition; {len(undefined)} undefined commands")

    report, rc = real_render(note)
    print(report)

    # The pipeline is authoritative when it ran: it decides what a math span is,
    # and this scanner's idea of that is an approximation. Its findings are
    # reported only as a hint in that case, and are the whole verdict otherwise.
    if rc >= 0:
        if findings:
            print("\n(scanner hints, superseded by the pipeline above:)")
            for f in findings:
                print("  " + f)
        if rc == 0:
            print("\nrender check: clean")
            return 0
        print()
        print(FIX_ORDER)
        return 1

    if not findings:
        print("render check: scanner clean; the pipeline did not run, so brace, "
              "delimiter and span-boundary errors remain unchecked")
        return 0
    print()
    for f in findings:
        print(f)
    print()
    print(FIX_ORDER)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
