module

public import QuantumSystem.Algebra.QuasiLocalAlgebra.QuasiLocal
public import QuantumSystem.Algebra.QuasiLocalAlgebra.ConeSubalgebra

/-!
# Haag duality and net additivity (the geometric hypotheses)

The Doplicher–Haag–Roberts structure theory of superselection sectors does not
hold for an arbitrary local net: it needs two geometric inputs about the net,
which are *not* provable in general and are supplied as explicit hypotheses
(discharged model-by-model elsewhere):

* **Haag duality** `HaagDuality L Ω`: for every cone `Λ`, the commutant of the
  algebra localised in the spacelike complement `Λᶜ` equals the algebra
  localised in `Λ`, i.e. `𝔄(Λᶜ)' = 𝔄(Λ)`.  This is the input that lets an
  operator intertwining two localised endomorphisms *land* inside the
  quasi-local algebra (the centralizer argument).
* **Net additivity** `NetAdditive L Ω`: the quasi-local algebra is generated
  (densely) by the single-site algebras `𝔄({x})` — the lattice/spin-system form
  of the additivity axiom.

References: Naaijkens, *Anyons in Infinite Quantum Systems* (2012), §1.3–1.4;
Buchholz–Fredenhagen, *Locality and the Structure of Particle States*, CMP 84
(1982); Doplicher–Haag–Roberts (1971).
-/

@[expose] public section

open scoped LocalNetLike

namespace LocalNetLike

variable (L : Type*) [DecidableEq L] [LocalNetLike L]
  (Ω : (s : L) → LocalNetLike.localIdx (L := L) s)

/-- **Haag duality**: for every cone `Λ`, the commutant (centralizer) in
`𝓑(globalHilbert L Ω)` of the spacelike-complement algebra
`complementConeSubalg L Ω Λ` equals the cone-localised algebra
`localConeSubalg L Ω Λ` (`𝔄(Λᶜ)' = 𝔄(Λ)`). -/
def HaagDuality : Prop :=
  ∀ Λ : Cone L,
    Set.centralizer
        (((complementConeSubalg L Ω Λ) :
          Set (globalHilbert L Ω →L[ℂ] globalHilbert L Ω)))
      = (((localConeSubalg L Ω Λ) :
          Set (globalHilbert L Ω →L[ℂ] globalHilbert L Ω)))

/-- **Net additivity** (single-site generation): the unital `*`-subalgebra of
`quasiLocal L Ω` generated by the single-site local algebras `𝔄({x})` is dense.
Every quasi-local element is a norm limit of polynomials in single-site
operators (Naaijkens 2012, §1.3). -/
def NetAdditive : Prop :=
  Dense (X := ↥(quasiLocal L Ω))
    (↑(StarAlgebra.adjoin ℂ
        {a : ↥(quasiLocal L Ω) | ∃ x : L, a.val ∈ localSubalgebra (Ω := Ω) {x}}) :
      Set ↥(quasiLocal L Ω))

end LocalNetLike
