/-
Copyright (c) 2026 Keisuke Suzuki. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Keisuke Suzuki
-/
module

public import Mathlib.Analysis.Complex.LocallyUniformLimit
public import QuantumSystem.Analysis.SpectralTheory.UnboundedIntegral
public import QuantumSystem.Analysis.UnboundedOperator.AnalyticContinuation
public import QuantumSystem.Analysis.UnboundedOperator.Power
public import QuantumSystem.ForMathlib.Analysis.Complex.Strip
public import QuantumSystem.ForMathlib.Analysis.Complex.WeakHolomorphic

/-!
# Interpolation between the imaginary powers of two positive operators

Let `A` on `H₁` and `B` on `H₂` be positive injective self-adjoint operators and let `V`, `V'` be
bounded operators with `B^{1/2} V ⊇ V' A^{1/2}`. Then `t ↦ B^{-it} V A^{it}` extends to a family
`F z` of bounded operators on the strip `0 ≤ im z ≤ 1/2`, holomorphic in the operator norm in the
interior, weakly continuous up to the boundary, with the three lines bound
`‖F z‖ ≤ ‖V‖^{1 - 2 im z} ‖V'‖^{2 im z}` and `F (t + i/2) = B^{-it} V' A^{it}`
(`IsSelfAdjoint.exists_stripContinuation`); here `A^{it}` is the unitary group generated by
`log A` (`IsSelfAdjoint.logPMap`). This is the analytic core of Borchers' Theorem A
(`QuantumSystem.Analysis.StandardSubspace.Borchers`), where `A`, `B` are modular operators
and `V' = J₂ V J₁`.

## Proof

The imaginary powers are cut off to the spectral windows `[1/(n+1), n+1]`: with `1_n` the indicator
of the window, the operators `F_n(z) = ∫ 1_n λ^{-iz} dE_B ∘ V ∘ ∫ 1_n λ^{iz} dE_A` are bounded and
entire in `z`, bounded by `‖V‖` on `im z = 0` and, by the intertwining, equal to
`∫ 1_n λ^{-it} dE_B ∘ V' ∘ ∫ 1_n λ^{it} dE_A` on `im z = 1/2`; the three lines theorem bounds them
by `‖V‖^{1 - 2 im z} ‖V'‖^{2 im z}` on the strip. The windows are compatible,
`F_n = E_B(window n) F_m E_A(window n)` for `n ≤ m`, so on the range of a window
`‖F_m x - F_n x‖² = ‖F_m x‖² - ‖F_n x‖²`, and the uniform bound makes `F_n` converge strongly. Its
matrix coefficients between window vectors are eventually those of a fixed `F_n`, hence entire, and
the general ones are uniform limits of these on the strip; norm holomorphy follows from weak
holomorphy and the bound (`Complex.differentiableOn_continuousLinearMap_of_inner`).

## Main results

* `IsSelfAdjoint.exists_stripContinuation` — the interpolation theorem.

## TODO

* `*`-strong continuity up to the boundary.
* Interpolation for a general exponent: `B^α V ⊇ V' A^α` continues `t ↦ B^{-it} V A^{it}` to
  `0 ≤ im z ≤ α` (Heinz–Kato type inequalities).
-/

@[expose] public section

open Set Filter Topology MeasureTheory Complex Metric
open scoped InnerProductSpace ComplexConjugate LinearPMap

namespace MeasureTheory.ProjectionValuedMeasure

/-! ### Spectral windows -/

/-- The spectral window `[1/(n+1), n+1] ⊆ (0, ∞)`. -/
private def window (n : ℕ) : Set ℝ := Icc ((n + 1 : ℝ)⁻¹) (n + 1)

/-- The windows are measurable. -/
private lemma measurableSet_window (n : ℕ) : MeasurableSet (window n) := measurableSet_Icc

/-- The windows lie in `(0, ∞)`. -/
private lemma pos_of_mem_window {n : ℕ} {t : ℝ} (ht : t ∈ window n) : 0 < t :=
  lt_of_lt_of_le (inv_pos.mpr (by positivity)) ht.1

/-- The windows increase. -/
private lemma window_mono {n m : ℕ} (h : n ≤ m) : window n ⊆ window m := by
  have h' : (n + 1 : ℝ) ≤ m + 1 := by exact_mod_cast Nat.succ_le_succ h
  exact Icc_subset_Icc (inv_anti₀ (by positivity) h') h'

/-- On the window `n`, `|log λ| ≤ log (n + 1)`. -/
private lemma abs_log_le_of_mem_window {n : ℕ} {t : ℝ} (ht : t ∈ window n) :
    |Real.log t| ≤ Real.log (n + 1) := by
  rw [abs_le]
  constructor
  · have := Real.log_le_log (inv_pos.mpr (by positivity)) ht.1
    rw [Real.log_inv] at this
    linarith
  · exact Real.log_le_log (pos_of_mem_window ht) ht.2

/-- Every `λ > 0` lies in all windows from some index on. -/
private lemma eventually_mem_window {t : ℝ} (ht : 0 < t) : ∀ᶠ n : ℕ in atTop, t ∈ window n := by
  obtain ⟨N, hN⟩ := exists_nat_gt (max t t⁻¹)
  filter_upwards [eventually_ge_atTop N] with n hn
  have hn' : (N : ℝ) ≤ n := by exact_mod_cast hn
  constructor
  · rw [inv_le_comm₀ (by positivity) ht]
    linarith [le_max_right t t⁻¹]
  · linarith [le_max_left t t⁻¹]

/-- The cut-off power `λ ↦ 1_{[1/(n+1), n+1]}(λ) λ^w`, with `λ^w = e^{w log λ}`. -/
private noncomputable def cutPow (n : ℕ) (w : ℂ) : ℝ → ℂ :=
  (window n).indicator fun t => cexp (w * Real.log t)

/-- The cut-off powers are measurable. -/
private lemma measurable_cutPow (n : ℕ) (w : ℂ) : Measurable (cutPow n w) :=
  (by fun_prop : Measurable fun t : ℝ => cexp (w * Real.log t)).indicator (measurableSet_window n)

/-- `|1_n(λ) λ^w| ≤ (n + 1)^{|re w|}`. -/
private lemma norm_cutPow_le (n : ℕ) (w : ℂ) (t : ℝ) :
    ‖cutPow n w t‖ ≤ Real.exp (|w.re| * Real.log (n + 1)) := by
  by_cases ht : t ∈ window n
  · rw [cutPow, indicator_of_mem ht, norm_exp, re_mul_ofReal]
    refine Real.exp_le_exp.mpr ((le_abs_self _).trans ?_)
    rw [abs_mul]
    exact mul_le_mul_of_nonneg_left (abs_log_le_of_mem_window ht) (abs_nonneg _)
  · rw [cutPow, indicator_of_notMem ht, norm_zero]
    positivity

/-- The cut-off powers are bounded by `1` for imaginary `w`. -/
private lemma norm_cutPow_le_of_re_eq_zero (n : ℕ) {w : ℂ} (hw : w.re = 0) (t : ℝ) : ‖cutPow n w t‖ ≤ 1 :=
  (norm_cutPow_le n w t).trans (by simp [hw])

/-- The cut-off powers are bounded by `n + 1` for `|re w| ≤ 1`. -/
private lemma norm_cutPow_le_of_abs_re_le_one (n : ℕ) {w : ℂ} (hw : |w.re| ≤ 1) (t : ℝ) :
    ‖cutPow n w t‖ ≤ n + 1 := by
  refine (norm_cutPow_le n w t).trans ?_
  calc Real.exp (|w.re| * Real.log (n + 1)) ≤ Real.exp (1 * Real.log (n + 1)) :=
        Real.exp_le_exp.mpr (mul_le_mul_of_nonneg_right hw (Real.log_nonneg (by linarith)))
    _ = n + 1 := by rw [one_mul, Real.exp_log (by positivity)]

/-- Cutting off a cut-off power to a smaller window. -/
private lemma indicator_one_mul_cutPow {n m : ℕ} (h : n ≤ m) (w : ℂ) :
    (window n).indicator 1 * cutPow m w = cutPow n w := by
  funext t
  by_cases ht : t ∈ window n
  · simp [cutPow, ht, window_mono h ht]
  · simp [cutPow, ht]

/-- Cutting off a cut-off power to a smaller window, on the right. -/
private lemma cutPow_mul_indicator_one {n m : ℕ} (h : n ≤ m) (w : ℂ) :
    cutPow m w * (window n).indicator 1 = cutPow n w := by
  rw [mul_comm, indicator_one_mul_cutPow h]

/-- The cut-off powers converge to `1_{(0, ∞)} λ^w`. -/
private lemma tendsto_cutPow (w : ℂ) (t : ℝ) :
    Tendsto (fun n => cutPow n w t) atTop (𝓝 ((Ioi 0).indicator (fun t => cexp (w * Real.log t)) t)) := by
  by_cases ht : 0 < t
  · rw [indicator_of_mem (show t ∈ Ioi 0 from ht)]
    refine tendsto_const_nhds.congr' ?_
    filter_upwards [eventually_mem_window ht] with n hn
    rw [cutPow, indicator_of_mem hn]
  · rw [indicator_of_notMem (show t ∉ Ioi 0 from ht)]
    exact tendsto_const_nhds.congr' (Eventually.of_forall fun n =>
      (indicator_of_notMem (fun h => ht (pos_of_mem_window h)) _).symm)

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  (E : ProjectionValuedMeasure ℝ H)

/-- `z ↦ ∫ 1_{[1/(n+1), n+1]}(λ) λ^{cz} dE(λ)` is entire in the operator norm. -/
private lemma differentiable_integral_cutPow (n : ℕ) (c : ℂ) :
    Differentiable ℂ fun z => E.integral (cutPow n (c * z)) := by
  intro z₀
  set R := ‖z₀‖ + 1 with hRdef
  have hz₀ : z₀ ∈ ball (0 : ℂ) R := mem_ball_zero_iff.mpr (by rw [hRdef]; linarith)
  set M := Real.exp (‖c‖ * R * Real.log (n + 1))
  have hU : IsOpen (ball (0 : ℂ) R) := isOpen_ball
  have hb : ∀ z ∈ ball (0 : ℂ) R, ∀ t, ‖cutPow n (c * z) t‖ ≤ M := fun z hz t => by
    refine (norm_cutPow_le n _ t).trans (Real.exp_le_exp.mpr
      (mul_le_mul_of_nonneg_right ?_ (Real.log_nonneg (by linarith))))
    rw [mem_ball_zero_iff] at hz
    calc |(c * z).re| ≤ ‖c * z‖ := abs_re_le_norm _
      _ = ‖c‖ * ‖z‖ := norm_mul _ _
      _ ≤ ‖c‖ * R := mul_le_mul_of_nonneg_left hz.le (norm_nonneg _)
  have hd : DifferentiableOn ℂ (fun z => E.integral (cutPow n (c * z))) (ball 0 R) := by
    refine Complex.differentiableOn_continuousLinearMap_of_inner hU fun ξ η => ?_
    · have hv : DifferentiableOn ℂ (fun z => E.integralApply (cutPow n (c * z)) ξ) (ball 0 R) :=
        E.differentiableOn_integralApply hU (fun z _ => measurable_cutPow n _)
          (F' := fun z => (window n).indicator fun t => cexp (c * z * Real.log t) * (c * Real.log t))
          (fun z _ => (by fun_prop : Measurable fun t : ℝ =>
            cexp (c * z * Real.log t) * (c * Real.log t)).indicator (measurableSet_window n))
          (fun t z _ => ?_) (memLp_const M) (Eventually.of_forall fun t z hz => hb z hz t)
      · refine ((innerSL ℂ η).differentiable.comp_differentiableOn hv).congr fun z hz => ?_
        simp [E.integral_apply (measurable_cutPow n _) ⟨M, hb z hz⟩]
      · by_cases ht : t ∈ window n
        · simp only [cutPow, indicator_of_mem ht]
          simpa [mul_assoc] using
            (((hasDerivAt_id z).const_mul c).mul_const (Real.log t : ℂ)).cexp
        · simp only [cutPow, indicator_of_notMem ht]
          exact hasDerivAt_const _ _
  exact (hd z₀ hz₀).differentiableAt (hU.mem_nhds hz₀)

/-- The unitary cut-off powers converge strongly: `∫ 1_n λ^w dE → ∫ λ^w dE` for `re w = 0`. -/
private lemma tendsto_integral_cutPow (hE : E (Iic 0) = 0) {w : ℂ} (hw : w.re = 0) (y : H) :
    Tendsto (fun n => E.integral (cutPow n w) y) atTop
      (𝓝 (E.integral (fun t => cexp (w * Real.log t)) y)) := by
  have hm : Measurable fun t : ℝ => cexp (w * Real.log t) := by fun_prop
  have hb : ∀ t : ℝ, ‖cexp (w * Real.log t)‖ ≤ 1 := fun t => by
    rw [norm_exp, re_mul_ofReal, hw, zero_mul, Real.exp_zero]
  have hbi : ∀ t : ℝ, ‖(Ioi 0).indicator (fun t => cexp (w * Real.log t)) t‖ ≤ 1 := fun t => by
    by_cases ht : t ∈ Ioi (0 : ℝ)
    · rw [indicator_of_mem ht]
      exact hb t
    · rw [indicator_of_notMem ht, norm_zero]
      exact zero_le_one
  have h := E.tendsto_integral_apply (fun n => measurable_cutPow n w)
    (hm.indicator measurableSet_Ioi) (fun n t => norm_cutPow_le_of_re_eq_zero n hw t) hbi
    (tendsto_cutPow w) y
  rwa [E.integral_indicator_Ioi hE hm ⟨1, hb⟩] at h

/-- The spectral projections of the windows converge strongly to `1`. -/
private lemma tendsto_apply_window (hE : E (Iic 0) = 0) (y : H) :
    Tendsto (fun n => E (window n) y) atTop (𝓝 y) := by
  have h := E.tendsto_integral_cutPow hE (w := 0) rfl y
  simp only [zero_mul, Complex.exp_zero, integral_one, one_apply_eq_self] at h
  refine h.congr fun n => ?_
  rw [← E.integral_indicator_one (measurableSet_window n)]
  congr 2
  funext t
  by_cases ht : t ∈ window n <;> simp [cutPow, ht]

/-- `∫ 1_m λ^w dE ∘ E(window n) = ∫ 1_n λ^w dE` for `n ≤ m`. -/
private lemma integral_cutPow_comp_apply {n m : ℕ} (h : n ≤ m) (w : ℂ) :
    E.integral (cutPow m w) ∘L E (window n) = E.integral (cutPow n w) := by
  rw [← E.integral_indicator_one (measurableSet_window n), ← ContinuousLinearMap.mul_def,
    ← E.integral_mul (measurable_cutPow m w) ⟨_, norm_cutPow_le m w⟩
      (measurable_one.indicator (measurableSet_window n))
      ⟨1, fun t => by by_cases ht : t ∈ window n <;> simp [ht]⟩, cutPow_mul_indicator_one h]

/-- `E(window n) ∘ ∫ 1_m λ^w dE = ∫ 1_n λ^w dE` for `n ≤ m`. -/
private lemma apply_comp_integral_cutPow {n m : ℕ} (h : n ≤ m) (w : ℂ) :
    E (window n) ∘L E.integral (cutPow m w) = E.integral (cutPow n w) := by
  rw [← E.integral_indicator_one (measurableSet_window n), ← ContinuousLinearMap.mul_def,
    ← E.integral_mul (measurable_one.indicator (measurableSet_window n))
      ⟨1, fun t => by by_cases ht : t ∈ window n <;> simp [ht]⟩ (measurable_cutPow m w)
      ⟨_, norm_cutPow_le m w⟩, indicator_one_mul_cutPow h]

/-! ### The interpolation theorem -/

section Interpolation

variable {H₁ H₂ : Type*} [NormedAddCommGroup H₁] [InnerProductSpace ℂ H₁] [CompleteSpace H₁]
  [NormedAddCommGroup H₂] [InnerProductSpace ℂ H₂] [CompleteSpace H₂]
  (E₁ : ProjectionValuedMeasure ℝ H₁) (E₂ : ProjectionValuedMeasure ℝ H₂)

/-- The family `B^{-iz} V A^{iz}` with `A`, `B` cut off to the spectral window `n`; it is entire
in `z`. -/
private noncomputable def windowConj (V : H₁ →L[ℂ] H₂) (n : ℕ) (z : ℂ) : H₁ →L[ℂ] H₂ :=
  E₂.integral (cutPow n (-I * z)) ∘L V ∘L E₁.integral (cutPow n (I * z))

private lemma differentiable_windowConj (V : H₁ →L[ℂ] H₂) (n : ℕ) :
    Differentiable ℂ (windowConj E₁ E₂ V n) :=
  (E₂.differentiable_integral_cutPow n (-I)).clm_comp
    ((differentiable_const V).clm_comp (E₁.differentiable_integral_cutPow n I))

/-- `‖∫ 1_n λ^{±iz} dE‖ ≤ n + 1` on the strip `|im z| ≤ 1`. -/
private lemma norm_integral_cutPow_le (E : ProjectionValuedMeasure ℝ H₁) (n : ℕ) {w : ℂ}
    (hw : |w.re| ≤ 1) : ‖E.integral (cutPow n w)‖ ≤ n + 1 :=
  E.norm_integral_le (measurable_cutPow n w) ⟨_, norm_cutPow_le n w⟩
    (norm_cutPow_le_of_abs_re_le_one n hw) (by positivity)

private lemma norm_integral_cutPow_le_one (E : ProjectionValuedMeasure ℝ H₁) (n : ℕ) {w : ℂ}
    (hw : w.re = 0) : ‖E.integral (cutPow n w)‖ ≤ 1 :=
  E.norm_integral_le (measurable_cutPow n w) ⟨_, norm_cutPow_le n w⟩
    (norm_cutPow_le_of_re_eq_zero n hw) zero_le_one

private lemma norm_windowConj_le (V : H₁ →L[ℂ] H₂) (n : ℕ) {z : ℂ}
    (hz : z ∈ im ⁻¹' Icc 0 (1 / 2)) : ‖windowConj E₁ E₂ V n z‖ ≤ (n + 1) * (‖V‖ * (n + 1)) := by
  have h₁ : |(-I * z).re| ≤ 1 := by
    simp only [neg_mul, neg_re, mul_re, I_re, I_im, zero_mul, one_mul, zero_sub, neg_neg]
    rw [abs_le]
    constructor <;> linarith [hz.1, hz.2]
  have h₂ : |(I * z).re| ≤ 1 := by
    simp only [mul_re, I_re, I_im, zero_mul, one_mul, zero_sub]
    rw [abs_le]
    constructor <;> linarith [hz.1, hz.2]
  refine (ContinuousLinearMap.opNorm_comp_le _ _).trans ?_
  refine mul_le_mul (norm_integral_cutPow_le E₂ n h₁) ((ContinuousLinearMap.opNorm_comp_le _ _).trans
    (mul_le_mul_of_nonneg_left (norm_integral_cutPow_le E₁ n h₂) (norm_nonneg _)))
    (by positivity) (by positivity)

private lemma norm_windowConj_ofReal_le (V : H₁ →L[ℂ] H₂) (n : ℕ) (t : ℝ) :
    ‖windowConj E₁ E₂ V n t‖ ≤ ‖V‖ := by
  refine (ContinuousLinearMap.opNorm_comp_le _ _).trans ?_
  calc _ ≤ 1 * (‖V‖ * 1) := mul_le_mul (norm_integral_cutPow_le_one E₂ n (by simp))
          ((ContinuousLinearMap.opNorm_comp_le _ _).trans (mul_le_mul_of_nonneg_left
            (norm_integral_cutPow_le_one E₁ n (by simp)) (norm_nonneg _)))
          (by positivity) zero_le_one
    _ = ‖V‖ := by ring

/-- `B^{-iz} V A^{iz}` restricted to a window is the restriction of the one on a larger window. -/
private lemma windowConj_eq_comp (V : H₁ →L[ℂ] H₂) {n m : ℕ} (h : n ≤ m) (z : ℂ) :
    windowConj E₁ E₂ V n z = E₂ (window n) ∘L windowConj E₁ E₂ V m z ∘L E₁ (window n) := by
  simp only [windowConj, ← ContinuousLinearMap.comp_assoc, E₂.apply_comp_integral_cutPow h]
  simp only [ContinuousLinearMap.comp_assoc, E₁.integral_cutPow_comp_apply h]

/-- `√λ = λ^{1/2}` on `(0, ∞)`. -/
private lemma ofReal_sqrt_eq {t : ℝ} (ht : 0 < t) :
    ((Real.sqrt t : ℝ) : ℂ) = cexp (1 / 2 * Real.log t) := by
  rw [Real.sqrt_eq_rpow, Real.rpow_def_of_pos ht, ofReal_exp]
  push_cast
  ring_nf

/-- **The upper boundary line**: the intertwining `B^{1/2} V ⊇ V' A^{1/2}` turns
`B^{-i(t + i/2)} V A^{i(t + i/2)}` into `B^{-it} V' A^{it}` (on each window). -/
private lemma windowConj_add_half {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ (E₁.integralPMap fun t => (Real.sqrt t : ℂ)).graph →
      (V x, V' u) ∈ (E₂.integralPMap fun t => (Real.sqrt t : ℂ)).graph) (n : ℕ) (t : ℝ) :
    windowConj E₁ E₂ V n (t + I / 2) = windowConj E₁ E₂ V' n t := by
  have hsq : Measurable fun t : ℝ => (Real.sqrt t : ℂ) :=
    Complex.measurable_ofReal.comp Real.continuous_sqrt.measurable
  have hI : I * I = -1 := I_mul_I
  -- the two function identities on the window
  have hf₁ : (fun s : ℝ => (Real.sqrt s : ℂ)) * cutPow n (I * (t + I / 2)) = cutPow n (I * t) := by
    funext s
    by_cases hs : s ∈ window n
    · simp only [Pi.mul_apply, cutPow, indicator_of_mem hs, ofReal_sqrt_eq (pos_of_mem_window hs),
        ← Complex.exp_add]
      congr 1
      linear_combination ((Real.log s : ℂ) / 2) * hI
    · simp [cutPow, hs]
  have hf₂ : cutPow n (-I * (t + I / 2)) =
      cutPow n (-I * t) * fun s : ℝ => (Real.sqrt s : ℂ) := by
    funext s
    by_cases hs : s ∈ window n
    · simp only [Pi.mul_apply, cutPow, indicator_of_mem hs, ofReal_sqrt_eq (pos_of_mem_window hs),
        ← Complex.exp_add]
      congr 1
      linear_combination (-(Real.log s : ℂ) / 2) * hI
    · simp [cutPow, hs]
  ext x
  simp only [windowConj, ContinuousLinearMap.comp_apply]
  set a := E₁.integral (cutPow n (I * (t + I / 2))) x
  have hb₁ : ∃ C, ∀ s, ‖cutPow n (I * (t + I / 2)) s‖ ≤ C := ⟨_, norm_cutPow_le n _⟩
  have hb₂ : ∃ C, ∀ s, ‖cutPow n (-I * t) s‖ ≤ C := ⟨_, norm_cutPow_le n _⟩
  -- `(a, A^{it} x) ∈ graph A^{1/2}` on the window
  have hgraph : (a, E₁.integral (cutPow n (I * t)) x) ∈
      (E₁.integralPMap fun t => (Real.sqrt t : ℂ)).graph := by
    have hmem : MemLp ((fun s : ℝ => (Real.sqrt s : ℂ)) * cutPow n (I * (t + I / 2))) 2
        (E₁.measure x) := by
      rw [hf₁]
      exact E₁.memLp_measure_of_bound (measurable_cutPow n _) (norm_cutPow_le n _) x
    refine E₁.mem_graph_integralPMap.mpr ⟨(E₁.memLp_measure_integral_apply_iff hsq
      (measurable_cutPow n _) hb₁ x).mpr hmem, ?_⟩
    rw [E₁.integralApply_integral_apply hsq (measurable_cutPow n _) hb₁ hmem, hf₁,
      E₁.integral_apply (measurable_cutPow n _) ⟨_, norm_cutPow_le n _⟩]
  obtain ⟨hmem₂, hval₂⟩ := E₂.mem_graph_integralPMap.mp (hVV' _ _ hgraph)
  rw [hf₂, E₂.integral_apply ((measurable_cutPow n _).mul hsq) ⟨_, fun s => by
      rw [← hf₂]
      exact norm_cutPow_le n _ s⟩,
    ← E₂.integral_integralApply hsq (measurable_cutPow n _) hb₂ hmem₂, hval₂]

/-- **Three lines**: on the closed strip, `‖B^{-iz} V A^{iz}‖ ≤ max ‖V‖ ‖V'‖` on each window. -/
private lemma norm_windowConj_le_max {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ (E₁.integralPMap fun t => (Real.sqrt t : ℂ)).graph →
      (V x, V' u) ∈ (E₂.integralPMap fun t => (Real.sqrt t : ℂ)).graph) (n : ℕ) {z : ℂ}
    (hz : z ∈ im ⁻¹' Icc 0 (1 / 2)) : ‖windowConj E₁ E₂ V n z‖ ≤ max ‖V‖ ‖V'‖ := by
  refine Complex.norm_le_of_im_mem_Icc
    (differentiable_windowConj E₁ E₂ V n).diffContOnCl
    ⟨(n + 1) * (‖V‖ * (n + 1)), ?_⟩ (fun w hw => ?_) (fun w hw => ?_) hz
  · rintro _ ⟨w, hw, rfl⟩
    exact norm_windowConj_le E₁ E₂ V n hw
  · have hw' : w = (w.re : ℂ) := Complex.ext (by simp) (by simp [hw])
    rw [hw']
    exact (norm_windowConj_ofReal_le E₁ E₂ V n _).trans (le_max_left _ _)
  · have hw' : w = (w.re : ℂ) + I / 2 := Complex.ext (by simp) (by simp [hw])
    rw [hw', windowConj_add_half E₁ E₂ hVV']
    exact (norm_windowConj_ofReal_le E₁ E₂ V' n _).trans (le_max_right _ _)

/-- **Three lines**: `‖B^{-iz} V A^{iz}‖ ≤ ‖V‖^{1 - 2 im z} ‖V'‖^{2 im z}` on each window. -/
private lemma norm_windowConj_le_interp {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ (E₁.integralPMap fun t => (Real.sqrt t : ℂ)).graph →
      (V x, V' u) ∈ (E₂.integralPMap fun t => (Real.sqrt t : ℂ)).graph) (n : ℕ) {z : ℂ}
    (hz : z ∈ im ⁻¹' Icc 0 (1 / 2)) :
    ‖windowConj E₁ E₂ V n z‖ ≤ ‖V‖ ^ (1 - 2 * z.im) * ‖V'‖ ^ (2 * z.im) := by
  have h := Complex.HadamardThreeLines.norm_le_interp_of_im_mem_Icc (f := windowConj E₁ E₂ V n)
    (a := 0) (b := 1 / 2) (Ma := ‖V‖) (Mb := ‖V'‖) (by norm_num)
    (differentiable_windowConj E₁ E₂ V n).diffContOnCl
    ⟨(n + 1) * (‖V‖ * (n + 1)), by
      rintro _ ⟨w, hw, rfl⟩
      exact norm_windowConj_le E₁ E₂ V n hw⟩ (fun w hw => ?_) (fun w hw => ?_) hz
  · have e₁ : (1 / 2 - z.im) / (1 / 2 - 0) = 1 - 2 * z.im := by ring
    have e₂ : (z.im - 0) / (1 / 2 - 0) = 2 * z.im := by ring
    rwa [e₁, e₂] at h
  · have hw' : w = (w.re : ℂ) := Complex.ext (by simp) (by simp [hw])
    rw [hw']
    exact norm_windowConj_ofReal_le E₁ E₂ V n _
  · have hw' : w = (w.re : ℂ) + I / 2 := Complex.ext (by simp) (by simp [hw])
    rw [hw', windowConj_add_half E₁ E₂ hVV']
    exact norm_windowConj_ofReal_le E₁ E₂ V' n _

/-- On the range of a window projection, the cut-off families form a Cauchy sequence: they are
the spectral cut-offs `E₂(window n) a_m` of one another, so `‖a_m - a_n‖² = ‖a_m‖² - ‖a_n‖²` and
`‖a_n‖²` increases to a finite limit. -/
private lemma cauchySeq_windowConj_apply_window {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ (E₁.integralPMap fun t => (Real.sqrt t : ℂ)).graph →
      (V x, V' u) ∈ (E₂.integralPMap fun t => (Real.sqrt t : ℂ)).graph) {z : ℂ}
    (hz : z ∈ im ⁻¹' Icc 0 (1 / 2)) (N : ℕ) (x : H₁) :
    CauchySeq fun n => windowConj E₁ E₂ V n z (E₁ (window N) x) := by
  set a := fun n => windowConj E₁ E₂ V n z (E₁ (window N) x)
  have hcons : ∀ n m, N ≤ n → n ≤ m → a n = E₂ (window n) (a m) := fun n m hn hnm => by
    simp only [a]
    rw [windowConj_eq_comp E₁ E₂ V hnm z]
    simp only [ContinuousLinearMap.comp_apply]
    rw [E₁.apply_apply_of_subset (measurableSet_window N) (measurableSet_window n)
      (window_mono hn)]
  have hpyth : ∀ n m, N ≤ n → n ≤ m → ‖a m - a n‖ ^ 2 = ‖a m‖ ^ 2 - ‖a n‖ ^ 2 :=
    fun n m hn hnm => by
      rw [hcons n m hn hnm]
      exact E₂.norm_sub_apply_sq (measurableSet_window n) _
  have hbound : ∀ n, ‖a n‖ ≤ max ‖V‖ ‖V'‖ * ‖E₁ (window N) x‖ := fun n =>
    (ContinuousLinearMap.le_opNorm _ _).trans (mul_le_mul_of_nonneg_right
      (norm_windowConj_le_max E₁ E₂ hVV' n hz) (norm_nonneg _))
  set s : ℕ → ℝ := fun k => ‖a (k + N)‖ ^ 2
  have hmono : Monotone s := fun k k' hkk' => by
    have := hpyth (k + N) (k' + N) (by omega) (by omega)
    simp only [s]
    nlinarith [sq_nonneg ‖a (k' + N) - a (k + N)‖]
  have hbdd : BddAbove (range s) := ⟨(max ‖V‖ ‖V'‖ * ‖E₁ (window N) x‖) ^ 2, by
    rintro _ ⟨k, rfl⟩
    exact pow_le_pow_left₀ (norm_nonneg _) (hbound _) 2⟩
  have hL := tendsto_atTop_ciSup hmono hbdd
  refine (cauchySeq_shift N).mp (Metric.cauchySeq_iff'.mpr fun ε hε => ?_)
  obtain ⟨K, hK⟩ := Metric.tendsto_atTop.mp hL (ε ^ 2) (by positivity)
  refine ⟨K, fun k hk => ?_⟩
  have h1 := hpyth (K + N) (k + N) (by omega) (by omega)
  have h2 : s k ≤ ⨆ i, s i := le_ciSup hbdd k
  have h3 := hK K le_rfl
  rw [Real.dist_eq, abs_lt] at h3
  rw [dist_eq_norm]
  have h4 : ‖a (k + N) - a (K + N)‖ ^ 2 < ε ^ 2 := by
    rw [h1]
    simp only [s] at h2 h3
    linarith
  exact lt_of_pow_lt_pow_left₀ 2 hε.le h4

/-- The cut-off families converge strongly on the closed strip. -/
private lemma cauchySeq_windowConj_apply (hE₁ : E₁ (Iic 0) = 0) {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ (E₁.integralPMap fun t => (Real.sqrt t : ℂ)).graph →
      (V x, V' u) ∈ (E₂.integralPMap fun t => (Real.sqrt t : ℂ)).graph) {z : ℂ}
    (hz : z ∈ im ⁻¹' Icc 0 (1 / 2)) (x : H₁) :
    CauchySeq fun n => windowConj E₁ E₂ V n z x := by
  set C := max ‖V‖ ‖V'‖
  have hC : 0 ≤ C := (norm_nonneg _).trans (le_max_left _ _)
  have hb : ∀ n v, ‖windowConj E₁ E₂ V n z v‖ ≤ C * ‖v‖ := fun n v =>
    (ContinuousLinearMap.le_opNorm _ _).trans (mul_le_mul_of_nonneg_right
      (norm_windowConj_le_max E₁ E₂ hVV' n hz) (norm_nonneg _))
  refine Metric.cauchySeq_iff.mpr fun ε hε => ?_
  have hδ : 0 < ε / (3 * (C + 1)) := by positivity
  obtain ⟨N, hN⟩ := Metric.tendsto_atTop.mp (E₁.tendsto_apply_window hE₁ x) _ hδ
  obtain ⟨K, hK⟩ := Metric.cauchySeq_iff.mp
    (cauchySeq_windowConj_apply_window E₁ E₂ hVV' hz N x) (ε / 3) (by positivity)
  refine ⟨K, fun m hm n hn => ?_⟩
  set x' := E₁ (window N) x
  have hxN : ‖x - x'‖ < ε / (3 * (C + 1)) := by
    rw [← dist_eq_norm, dist_comm]
    exact hN N le_rfl
  have hCδ : C * (ε / (3 * (C + 1))) ≤ ε / 3 := by
    rw [mul_div_assoc', div_le_div_iff₀ (by positivity) (by positivity)]
    nlinarith
  have hsplit : windowConj E₁ E₂ V m z x - windowConj E₁ E₂ V n z x =
      windowConj E₁ E₂ V m z (x - x') +
        (windowConj E₁ E₂ V m z x' - windowConj E₁ E₂ V n z x') +
          windowConj E₁ E₂ V n z (x' - x) := by
    simp only [map_sub]
    abel
  rw [dist_eq_norm, hsplit]
  refine (norm_add₃_le).trans_lt ?_
  have h₁ : ‖windowConj E₁ E₂ V m z (x - x')‖ ≤ ε / 3 :=
    (hb m _).trans ((mul_le_mul_of_nonneg_left hxN.le hC).trans hCδ)
  have h₃ : ‖windowConj E₁ E₂ V n z (x' - x)‖ ≤ ε / 3 :=
    (hb n _).trans ((mul_le_mul_of_nonneg_left (by rw [norm_sub_rev]; exact hxN.le) hC).trans hCδ)
  have h₂ := hK m hm n hn
  rw [dist_eq_norm] at h₂
  linarith

/-- `T_n u_n → T u` if `T_n → T` strongly, `‖T_n‖ ≤ C` and `u_n → u`. -/
private lemma tendsto_apply_apply {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E]
    [NormedAddCommGroup F] [NormedSpace ℂ F] {T : ℕ → E →L[ℂ] F} {T₀ : E →L[ℂ] F} {u : ℕ → E}
    {u₀ : E} {C : ℝ} (hT : ∀ v, Tendsto (fun n => T n v) atTop (𝓝 (T₀ v)))
    (hC : ∀ n, ‖T n‖ ≤ C) (hu : Tendsto u atTop (𝓝 u₀)) :
    Tendsto (fun n => T n (u n)) atTop (𝓝 (T₀ u₀)) := by
  have h1 : Tendsto (fun n => T n (u n - u₀)) atTop (𝓝 0) := by
    refine squeeze_zero_norm (fun n => (ContinuousLinearMap.le_opNorm _ _).trans
      (mul_le_mul_of_nonneg_right (hC n) (norm_nonneg _))) ?_
    simpa using (tendsto_iff_norm_sub_tendsto_zero.mp hu).const_mul C
  have := h1.add (hT u₀)
  simp only [map_sub, sub_add_cancel, zero_add] at this
  exact this

/-- The limit of the cut-off families on the real line. -/
private lemma tendsto_windowConj_ofReal (hE₁ : E₁ (Iic 0) = 0) (hE₂ : E₂ (Iic 0) = 0)
    (V : H₁ →L[ℂ] H₂) (t : ℝ) (x : H₁) :
    Tendsto (fun n => windowConj E₁ E₂ V n t x) atTop
      (𝓝 ((E₂.integral (fun s => cexp (↑(-t) * Real.log s * I)) ∘L V ∘L
        E₁.integral (fun s => cexp (t * Real.log s * I))) x)) := by
  have e₁ : (fun s : ℝ => cexp (I * t * Real.log s)) = fun s => cexp (t * Real.log s * I) := by
    funext s
    ring_nf
  have e₂ : (fun s : ℝ => cexp (-I * t * Real.log s)) = fun s => cexp (↑(-t) * Real.log s * I) := by
    funext s
    push_cast
    ring_nf
  simp only [windowConj, ContinuousLinearMap.comp_apply]
  rw [← e₁, ← e₂]
  have hre₁ : (I * (t : ℂ)).re = 0 := by simp
  have hre₂ : (-I * (t : ℂ)).re = 0 := by simp
  exact tendsto_apply_apply (T := fun n => E₂.integral (cutPow n (-I * t)))
    (fun v => E₂.tendsto_integral_cutPow hE₂ hre₂ v)
    (fun n => norm_integral_cutPow_le_one E₂ n hre₂)
    (V.continuous.tendsto _ |>.comp (E₁.tendsto_integral_cutPow hE₁ hre₁ x))

/-- The interpolation theorem in terms of the projection-valued measures `E₁`, `E₂` on `(0, ∞)`
of `A` and `B`, with `A^{it} = ∫ e^{it log λ} dE₁(λ)`. -/
private lemma exists_stripContinuation_pvm (hE₁ : E₁ (Iic 0) = 0) (hE₂ : E₂ (Iic 0) = 0)
    {V V' : H₁ →L[ℂ] H₂}
    (hVV' : ∀ x u, (x, u) ∈ (E₁.integralPMap fun t => (Real.sqrt t : ℂ)).graph →
      (V x, V' u) ∈ (E₂.integralPMap fun t => (Real.sqrt t : ℂ)).graph) :
    ∃ F : ℂ → H₁ →L[ℂ] H₂, DifferentiableOn ℂ F (im ⁻¹' Ioo 0 (1 / 2)) ∧
      (∀ x y, DiffContOnCl ℂ (fun z => ⟪y, F z x⟫_ℂ) (im ⁻¹' Ioo 0 (1 / 2))) ∧
      (∀ z ∈ im ⁻¹' Icc 0 (1 / 2), ‖F z‖ ≤ ‖V‖ ^ (1 - 2 * z.im) * ‖V'‖ ^ (2 * z.im)) ∧
      (∀ t : ℝ, F t = E₂.integral (fun s => cexp (↑(-t) * Real.log s * I)) ∘L V ∘L
        E₁.integral (fun s => cexp (t * Real.log s * I))) ∧
      ∀ t : ℝ, F (t + I / 2) = E₂.integral (fun s => cexp (↑(-t) * Real.log s * I)) ∘L V' ∘L
        E₁.integral (fun s => cexp (t * Real.log s * I)) := by
  classical
  set S := im ⁻¹' Icc (0 : ℝ) (1 / 2) with hS
  set C := max ‖V‖ ‖V'‖
  have hC : 0 ≤ C := (norm_nonneg _).trans (le_max_left _ _)
  have hU : IsOpen (im ⁻¹' Ioo (0 : ℝ) (1 / 2)) := isOpen_Ioo.preimage continuous_im
  have hUS : im ⁻¹' Ioo (0 : ℝ) (1 / 2) ⊆ S := preimage_mono Ioo_subset_Icc_self
  have hcl : closure (im ⁻¹' Ioo (0 : ℝ) (1 / 2)) = S := closure_preimage_im_Ioo (by norm_num)
  have hconv : ∀ z ∈ S, Tendsto (fun n x => windowConj E₁ E₂ V n z x) atTop
      (𝓝 fun x => limUnder atTop fun n => windowConj E₁ E₂ V n z x) := fun z hz =>
    tendsto_pi_nhds.mpr fun x => (cauchySeq_windowConj_apply E₁ E₂ hE₁ hVV' hz x).tendsto_limUnder
  let F : ℂ → H₁ →L[ℂ] H₂ := fun z =>
    if hz : z ∈ S then continuousLinearMapOfTendsto _ (hconv z hz) else 0
  have hF : ∀ z ∈ S, ∀ x, Tendsto (fun n => windowConj E₁ E₂ V n z x) atTop (𝓝 (F z x)) :=
    fun z hz x => by
      simp only [F, hz, ↓reduceDIte]
      exact tendsto_pi_nhds.mp (hconv z hz) x
  have hFb : ∀ z ∈ S, ‖F z‖ ≤ C := fun z hz => ContinuousLinearMap.opNorm_le_bound _ hC fun x =>
    le_of_tendsto (hF z hz x).norm (Eventually.of_forall fun n => (ContinuousLinearMap.le_opNorm _ _).trans
      (mul_le_mul_of_nonneg_right (norm_windowConj_le_max E₁ E₂ hVV' n hz) (norm_nonneg _)))
  -- weak holomorphy and continuity, by uniform approximation on the windows
  have hweak : ∀ x y, DiffContOnCl ℂ (fun z => ⟪y, F z x⟫_ℂ) (im ⁻¹' Ioo 0 (1 / 2)) := by
    intro x y
    set f : ℕ → ℂ → ℂ := fun N z =>
      ⟪E₂ (window N) y, windowConj E₁ E₂ V N z (E₁ (window N) x)⟫_ℂ
    have hfd : ∀ N, Differentiable ℂ (f N) := fun N =>
      (innerSL ℂ (E₂ (window N) y)).differentiable.comp
        ((differentiable_windowConj E₁ E₂ V N).clm_apply (differentiable_const _))
    have hfeq : ∀ N, ∀ z ∈ S, ⟪E₂ (window N) y, F z (E₁ (window N) x)⟫_ℂ = f N z := by
      intro N z hz
      refine tendsto_nhds_unique (tendsto_const_nhds.inner (hF z hz _))
        (tendsto_const_nhds.congr' ?_)
      filter_upwards [eventually_ge_atTop N] with n hn
      simp only [f]
      rw [windowConj_eq_comp E₁ E₂ V hn z]
      simp only [ContinuousLinearMap.comp_apply]
      rw [E₁.apply_apply_self (measurableSet_window N), ← E₂.inner_apply_left,
        E₂.apply_apply_self (measurableSet_window N)]
    have hb : Tendsto (fun N => C * (‖y - E₂ (window N) y‖ * ‖x‖ +
        ‖y‖ * ‖x - E₁ (window N) x‖)) atTop (𝓝 0) := by
      have hy := tendsto_iff_norm_sub_tendsto_zero.mp (E₂.tendsto_apply_window hE₂ y)
      have hx := tendsto_iff_norm_sub_tendsto_zero.mp (E₁.tendsto_apply_window hE₁ x)
      simp only [norm_sub_rev _ y, norm_sub_rev _ x] at hy hx
      simpa using ((hy.mul_const ‖x‖).add (hx.const_mul ‖y‖)).const_mul C
    have huni : TendstoUniformlyOn f (fun z => ⟪y, F z x⟫_ℂ) atTop S := by
      refine Metric.tendstoUniformlyOn_iff.mpr fun ε hε => ?_
      filter_upwards [(Metric.tendsto_atTop.mp hb) ε hε |> fun ⟨N, hN⟩ =>
        eventually_atTop.mpr ⟨N, hN⟩] with N hN z hz
      rw [Real.dist_eq, sub_zero, abs_of_nonneg (by positivity)] at hN
      rw [← hfeq N z hz, dist_eq_norm]
      have hsplit : ⟪y, F z x⟫_ℂ - ⟪E₂ (window N) y, F z (E₁ (window N) x)⟫_ℂ =
          ⟪y - E₂ (window N) y, F z x⟫_ℂ + ⟪E₂ (window N) y, F z (x - E₁ (window N) x)⟫_ℂ := by
        rw [inner_sub_left, map_sub, inner_sub_right]
        ring
      rw [hsplit]
      refine (norm_add_le _ _).trans_lt (lt_of_le_of_lt ?_ hN)
      have hFz : ∀ v, ‖F z v‖ ≤ C * ‖v‖ := fun v =>
        (ContinuousLinearMap.le_opNorm _ _).trans (mul_le_mul_of_nonneg_right (hFb z hz) (norm_nonneg _))
      calc _ ≤ ‖y - E₂ (window N) y‖ * (C * ‖x‖) +
            ‖E₂ (window N) y‖ * (C * ‖x - E₁ (window N) x‖) :=
          add_le_add ((norm_inner_le_norm _ _).trans
              (mul_le_mul_of_nonneg_left (hFz _) (norm_nonneg _)))
            ((norm_inner_le_norm _ _).trans (mul_le_mul_of_nonneg_left (hFz _) (norm_nonneg _)))
        _ ≤ ‖y - E₂ (window N) y‖ * (C * ‖x‖) + ‖y‖ * (C * ‖x - E₁ (window N) x‖) := by
          gcongr
          exact E₂.norm_apply_le _ _
        _ = _ := by ring
    refine ⟨(huni.mono hUS).tendstoLocallyUniformlyOn.differentiableOn
      (Eventually.of_forall fun N => (hfd N).differentiableOn) hU, ?_⟩
    rw [hcl]
    exact huni.continuousOn (Frequently.of_forall fun N => (hfd N).continuous.continuousOn)
  have hFi : ∀ z ∈ S, ‖F z‖ ≤ ‖V‖ ^ (1 - 2 * z.im) * ‖V'‖ ^ (2 * z.im) := fun z hz =>
    ContinuousLinearMap.opNorm_le_bound _ (by positivity) fun x =>
      le_of_tendsto (hF z hz x).norm (Eventually.of_forall fun n =>
        (ContinuousLinearMap.le_opNorm _ _).trans (mul_le_mul_of_nonneg_right
          (norm_windowConj_le_interp E₁ E₂ hVV' n hz) (norm_nonneg _)))
  refine ⟨F, Complex.differentiableOn_continuousLinearMap_of_inner hU
    (fun x y => (hweak x y).differentiableOn), hweak, hFi, fun t => ?_, fun t => ?_⟩
  · have ht : (t : ℂ) ∈ S := by simp [hS]
    ext x
    exact tendsto_nhds_unique (hF _ ht x) (tendsto_windowConj_ofReal E₁ E₂ hE₁ hE₂ V t x)
  · have ht : (t : ℂ) + I / 2 ∈ S := by simp [hS]
    ext x
    refine tendsto_nhds_unique (hF _ ht x) ?_
    simp only [windowConj_add_half E₁ E₂ hVV']
    exact tendsto_windowConj_ofReal E₁ E₂ hE₁ hE₂ V' t x

end Interpolation

end MeasureTheory.ProjectionValuedMeasure

namespace IsSelfAdjoint

variable {H₁ H₂ : Type*} [NormedAddCommGroup H₁] [InnerProductSpace ℂ H₁] [CompleteSpace H₁]
  [NormedAddCommGroup H₂] [InnerProductSpace ℂ H₂] [CompleteSpace H₂]
  {A : H₁ →ₗ.[ℂ] H₁} {B : H₂ →ₗ.[ℂ] H₂}

/-- **Interpolation between the imaginary powers of two positive operators.** Let `A` on `H₁` and
`B` on `H₂` be positive injective self-adjoint operators and `V`, `V'` bounded operators with
`B^{1/2} V ⊇ V' A^{1/2}`. Then `t ↦ B^{-it} V A^{it}` extends to a family `F z` of bounded operators
on the strip `0 ≤ im z ≤ 1/2`, holomorphic in the operator norm in the interior and weakly
continuous up to the boundary, with `‖F z‖ ≤ ‖V‖^{1 - 2 im z} ‖V'‖^{2 im z}` and
`F (t + i/2) = B^{-it} V' A^{it}`. Here `A^{it}` is the unitary group generated by `log A`. -/
theorem exists_stripContinuation (hA : IsSelfAdjoint A) (hB : IsSelfAdjoint B)
    (hApos : A.IsPositive) (hAinj : A.ker = ⊥) (hBpos : B.IsPositive) (hBinj : B.ker = ⊥)
    {V V' : H₁ →L[ℂ] H₂} (hVV' : ∀ x u, (x, u) ∈ hA.sqrt.graph → (V x, V' u) ∈ hB.sqrt.graph) :
    ∃ F : ℂ → H₁ →L[ℂ] H₂, DifferentiableOn ℂ F (im ⁻¹' Ioo 0 (1 / 2)) ∧
      (∀ x y, DiffContOnCl ℂ (fun z => ⟪y, F z x⟫_ℂ) (im ⁻¹' Ioo 0 (1 / 2))) ∧
      (∀ z ∈ im ⁻¹' Icc 0 (1 / 2), ‖F z‖ ≤ ‖V‖ ^ (1 - 2 * z.im) * ‖V'‖ ^ (2 * z.im)) ∧
      (∀ t : ℝ, F t = (hB.isSelfAdjoint_logPMap.unitaryGroup (-t) : H₂ →L[ℂ] H₂) ∘L V ∘L
        (hA.isSelfAdjoint_logPMap.unitaryGroup t : H₁ →L[ℂ] H₁)) ∧
      ∀ t : ℝ, F (t + I / 2) = (hB.isSelfAdjoint_logPMap.unitaryGroup (-t) : H₂ →L[ℂ] H₂) ∘L V' ∘L
        (hA.isSelfAdjoint_logPMap.unitaryGroup t : H₁ →L[ℂ] H₁) := by
  have hE₁ : hA.pvm (Iic 0) = 0 :=
    (hA.pvm.apply_eq_zero_iff measurableSet_Iic).mpr (hA.measure_pvm_Iic_zero hApos hAinj)
  have hE₂ : hB.pvm (Iic 0) = 0 :=
    (hB.pvm.apply_eq_zero_iff measurableSet_Iic).mpr (hB.measure_pvm_Iic_zero hBpos hBinj)
  obtain ⟨F, hFd, hFw, hFb, hF0, hF1⟩ :=
    hA.pvm.exists_stripContinuation_pvm hB.pvm hE₁ hE₂ (V := V) (V' := V') hVV'
  refine ⟨F, hFd, hFw, hFb, fun t => ?_, fun t => ?_⟩
  · rw [hF0, coe_unitaryGroup_logPMap_apply, coe_unitaryGroup_logPMap_apply]
  · rw [hF1, coe_unitaryGroup_logPMap_apply, coe_unitaryGroup_logPMap_apply]

end IsSelfAdjoint
